### ISSUE TITLE
Change countdown to start connecting local daemon from 5 sec to 10 sec

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-gui#1004]
After reading many posts like [this one on reddit](https://www.reddit.com/r/Monero/comments/7idaet/did_i_do_something_wrong_when_connecting_to/), I think many people don't see in time the popup window who warn "Starting Monero daemon in 5 seconds" after creating the wallet . This cause the GUI to often start syncing a local daemon without the user noticing. This can cause issues to first time or not expert users.

My proposal is to change the countdown from 5 to 10 seconds. This should give time enough to see the popup

**Comment by aekrylov** [comment]
Why not disable the countdown completely,leaving only a prompt to start a local daemon? IMO that's rather annoying, and changing number of seconds won't do if the user is AFK (otherwise, the popup most likely will be senn immediately)
