### ISSUE TITLE
Save multiple daemons under settings.

### ISSUE THREAD

**Issue by guzzijones** [monero-project/monero-gui#1008]
When I am at home I want to use my local daemon.  When I am at work I want to use the public daemon.  I take my laptop back and forth a lot.  Remebering the daemon ip address and port numbers for multiple daemons is difficult and I end up just leaving it on the public daemon.  This is a request to save multiple daemons and give us a drop down under Settings | Daemon Address to pick historical daemons we have entered. Also would be great if on startup it prompted which daemon you wanted to use.

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by Raginglikeaboss** [comment]
First time I thought about this.  I would absolutely use this feature if it was implemented.
