### ISSUE TITLE
Left Panel: Seed & Keys hotkey not setup

### ISSUE THREAD

**Issue by Timo614** [monero-project/monero-gui#1011]
The Seeds & Keys hotkey is not setup currently so users cannot `ctrl+y` to switch to that tab.

https://github.com/monero-project/monero-gui/blob/master/main.qml#L106

The behavior should mimic the clicking of the leftPanel button where the password dialog is presented.

**Comment by Timo614** [comment]
I'll quickly take care of this one this morning.

**Comment by mmbyday** [comment]
+resolved
by #1489

**Comment by erciccione** [comment]
+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
