### ISSUE TITLE
Misc Tabbing Related Hotkey Bugs

### ISSUE THREAD

**Issue by Timo614** [monero-project/monero-gui#1012]
The hotkeys are a bit bugged with how they are currently setup.

1. On Mac OS X if I click the `alt` key while I'm on the "Advanced" tab I'm sent to the previous tab I was on but no other tabs have this behavior (guessing since the hotkeys logic sets the leftPanel to the current main state but the advanced tab has no content / mainstate by itself so it reverts to the last tab)
2. The `ctrl+tab` or `alt+tab` behavior seems random "Send" -> "Receive" -> "Prove/check"(under advanced) -> "History" -> "Address book"(under send) -> "Sign/verify"(under advanced) -> "Settings"
3. The "alt+shift+backspace" logic doesn't appear to do anything on a mac (perhaps since it's the delete key on macs?)

**Comment by erciccione** [comment]
+resolved
