### ISSUE TITLE
Memory Leak for Mac (maybe windows)

### ISSUE THREAD

**Issue by adamrabbit** [monero-project/monero-gui#1019]
monero-wallet-gui for Mac uses the full amount of available memory within 48 hours. Attached is a picture after about 24 hours:

Process Name | Memory | Compressed Memory | Threads | Ports |
monero-wallet-gui | 59.46 GB | 57.98 GB | 16 | 277 |  
monerod | 139.4 MB | 42.5 MB | 15 | 36

![memory](https://user-images.githubusercontent.com/6310271/33937687-b42120a8-e047-11e7-92b5-ab2e02650d77.jpg)

It's a clean install last week:

- GUI version: v0.11.1.0
- Embedded Monero version: v0.11.1.0-2-gc328163
- OS X 10.13
- block chain has been synced for days (fresh install last week)

This is my first issue - If info is missing please let me know and I'll update it.

**Comment by medusadigital** [comment]
+bug

**Comment by erciccione** [comment]
Closing since it's related to an old version. Please reopen if leak stil exists.

+resolved
