### ISSUE TITLE
Bug with payment ID

### ISSUE THREAD

**Issue by CoinHodler** [monero-project/monero-gui#1022]
When jumping between wallets on Mac OS GUI a small bug.
If you randomly generate payment ID, and the payment ID field fills. Then proceed to close that wallet and open up a new wallet (without exiting the program), the same payment ID field is still filled in new wallet but with the previous payment ID.
The field doesn't clear when opening new wallet unless you manually clear it. It's a like cache that doesn't clear.

When jumping between wallets, need the payment ID field to be empty and not carry over payment ID field.

**Comment by dEBRUYNE-1** [comment]
This wouldn't cause any issues for what it's worth, but it should still generate a new one. 

+bug

**Comment by skftn** [comment]
Since #952, receive page does not include a payment ID anymore.

**Comment by skftn** [comment]
+resolved
