### ISSUE TITLE
Memory leak in QCocoaMenuDelegate

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1032]
GUI version: v0.11.1.0
Embedded Monero version: v0.11.1.0-2-gc328163

Steps:
Launch Monero GUI.

What happened:
Memory leak in QCocoaMenuDelegate.

https://www.dropbox.com/s/c2orrbv5vionwnh/Monero%20leaks.trace.zip?dl=0

Expected result:
No leaks.

Notes:
Unzip and open file with Apple Instruments (part of Xcode tools).

**Comment by skftn** [comment]
Thanks for your submission(s).

Please collect all memory leaks you have submitted into one big issue. This is better for visibility. I also believe most of the issues you submitted are out of scope, as they're QT related. Tagging this as wontfix.

**Comment by skftn** [comment]
+wontfix
