### ISSUE TITLE
This process has no code signature

### ISSUE THREAD

**Issue by akseeker** [monero-project/monero-gui#1048]
I run Little Snitch on my Mac, and when I run the Monero GUI,  it warns me numerous times "The process has no code signature. The executable can be maliciously modified without being detected." for many, many IP addresses.

Is this normal?

I see a lot of outgoing traffic, too, and I'm curious: why is Monero so chatty through a process that has no code signature and is susceptible to being modified? Isn't that a fairly large security risk?

Sorry if this is an inappropriate  question for this forum. I would appreciate if you could point me to a (not overly technical) FAQ with this info.

**Comment by Tech-CF** [comment]
Yes, this is normal. I just allow until quit. Little Snitch will not allow permanent rules for apps running in a sandbox on macOS.

**Comment by skftn** [comment]
+resolved
