### ISSUE TITLE
Build native GUI clients

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1049]
The current situation with the QT ports is convenient, I can understand, but performance is slooooowwww...

I propose native GUI clients using a modern, fast and cross platform language. I suggest the use of [Swift](https://swift.org/about/#swiftorg-and-open-source).

The result is a modern looking and responsive client with feature parity that runs on Linux, macOS and [Windows](https://github.com/apple/swift/blob/master/docs/Windows.md).

**Comment by gboelter** [comment]
You are right, we really should have a 'modern looking and responsive client'. The current client looks and runs like Software during the time of Windows 3.11!

But believe me, that's not the fault of Qt. If have written many applications in Qt and they all are very fast.

**Comment by alexeyneu** [comment]
As you know qt use  pthreads under windows. It's not about performance for sure

**Comment by rex4539** [comment]
I personally use a Mac and performance feels slow.

**Comment by gboelter** [comment]
What I mean is, Qt is not an excuse for slow performance in this case. Take a look at Karbo Wallet - https://karbo.io/ - it's Qt-based too but it's nicely designed and very fast compared with Monero.

And BTW, when I see all the issues here, I can't believe the developers are really good ...

**Comment by Jaqueeee** [comment]
The GUI is slow when the daemon and wallet are syncing because they are using lots of CPU and disk I/o when validating the blockchain. It’s not related to Qt. Are you experiencing a slow GUI after everything is synced?

**Comment by alexeyneu** [comment]
it is related to qt . i can answer about windows case ,it's really low-grade stuff overall ,both qt itself and this gui code. i didnt test remote procedure calls impact on performance but what i could say for sure : if just pipeline monero-wallet-cli in winapi and bundle it with pipelined monerod you'll have a fast app. I already have monerod dealt with in this style and engine holds heavy loads without wait rings and others.

**Comment by fluffypony** [comment]
@alexeyneu great stuff - looking forward to your pull request!

**Comment by medusadigital** [comment]
the monero-gui project barely has recources to do anything and ofc no capacity to build a new client. 

closing issue here.

**Comment by medusadigital** [comment]
+wontfix

**Comment by stoffu** [comment]
> Is this moron(stoffu) part of a crew?

I'm a researcher at Monero Research Lab.
