### ISSUE TITLE
Inconsistent terminology: "wallet"

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-gui#1058]
The GUI refers to "ReadOnly wallet" and "view only wallet". Shouldn't it use only one and shouldn't it be consistent with the CLI? I'm thinking "view-only wallet" (see the localizable strings in translations/monero-core.ts)

This issue is related to https://github.com/monero-project/monero/issues/3048

**Comment by mmbyday** [comment]
+resolved
We couldn’t find any code matching '"ReadOnly wallet"' in monero-project/monero-gui

**Comment by erciccione** [comment]
+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by erciccione** [comment]
@dEBRUYNE-1 sometimes the buildbot just catch up veeery solowly
