### ISSUE TITLE
error in translation of the graphical wallet interface rus

### ISSUE THREAD

**Issue by kukuruk** [monero-project/monero-gui#1060]
Instead of the letter K, the first letter must be a Russian letter У

<a target="_blank" href="https://d.radikal.ru/d41/1801/b6/bf2c8d119e9f.jpg"><img src="https://d.radikal.ru/d41/1801/b6/bf2c8d119e9ft.jpg" /></a>

**Comment by erciccione** [comment]
Hi, this was fixed by #947 . You can see it already if you self compile the binaries, or in the next release. (thanks @ordtrogen for spotting it)
