### ISSUE TITLE
Utilize Monero URI

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1063]
GUI version: v0.11.1.0
Embedded Monero version: v0.11.1.0-2-gc328163

Reproducibility: always

Steps:
Click on monero URI eg. `monero:496Rqtzb7SvcMNDWYnULtPaeK2UsdjiQGZjSpW6hXhuXU16xSh8UY1qSaGuwT3moLt7ekqXHDtZj7KpTDoy63tBkNEWKwpt`

What happened:
Address is not recognized.

[https://www.dropbox.com/s/7ju9fyiee48s71c/MoneroURI.mp4?dl=0](url)

Expected result:
Address is recognized.

Notes:
Bitcoin and Dash for example recognize it.

**Comment by skftn** [comment]
+feature

**Comment by skftn** [comment]
Tagging this as feature request. I do wonder about the security implications, as this requires a mime-handler.

**Comment by skftn** [comment]
+duplicate
