### ISSUE TITLE
GUI displays unexpected path to wallet log file

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-gui#1068]
Why does it point to 
/usr/bin/monero-wallet-gui.log

(see screenshot)

System:

OS: Manjaro Linux i686
Model: Compaq Mini 110c-1000 03A81000000000001000
Kernel: 4.9.74-2-MANJARO
Packages: 976
Shell: bash 4.4.12
CPU: Intel Atom N270 (2) @ 1.600GHz
GPU: Intel Integrated Graphics
GPU: Intel Integrated Graphics
Memory: 298MiB / 995MiB

Daemon installed from https://aur.archlinux.org/monero.git
I typically keep it running continuously 

Recently installed GUI to begin testing:

GUI installed from https://aur.archlinux.org/monero-wallet-qt.git

First time I ran it, decided to create a wallet on testnet
When I start GUI now, it displays this:

![skarmbild_2018-01-09_23-01-43](https://user-images.githubusercontent.com/15184875/34745818-14039f1e-f592-11e7-8ffc-524c24163cc3.png)

**Comment by ordtrogen** [comment]
Maybe worth mentioning these errors displayed on console on startup:

![skarmbild_2018-01-09_23-13-07](https://user-images.githubusercontent.com/15184875/34746022-dd70f6d0-f592-11e7-918e-a6b86c211d33.png)

**Comment by medusadigital** [comment]
that looks like a potential bug to me.

however, please check permissioning on the file here too: https://monero.stackexchange.com/questions/2866/where-are-the-monero-core-configuration-parameters-stored

**Comment by ordtrogen** [comment]
I found the config file but its location is different from what the SE question mentions. I have it

~/.config/monero-project/monero-core.conf

Are you suggesting that the properties mentioned in the console output (daemonLogPath et al) should be mentioned in the .conf file?

**Comment by mmbyday** [comment]
+resolved 
by #1800

**Comment by dEBRUYNE-1** [comment]
+resolved
