### ISSUE TITLE
No way in GUI to switch from testnet to mainnet?

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-gui#1069]
First wallet I created was on testnet. Now I can't find any way in GUI to switch to mainnet. Have looked through all settings. When I start GUI, displays testnet even before I have entered the password for the most recently opened wallet

![skarmbild_2018-01-09_23-35-39](https://user-images.githubusercontent.com/15184875/34746826-e3398e3a-f595-11e7-9ef9-42a5a8024561.png)

**Comment by stoffu** [comment]
You need to go back to the wizard window by either closing the current wallet or cancelling the password dialog. There's a check box "Testnet" in the wizard window.

**Comment by ordtrogen** [comment]
Ok thanks.

Now the problem is that the wizard step with testnet checkbox is skipped, i.e when I get to it, it is displayed briefly but then wizard automatically moves to the next step and doesn't give me time to unselect testnet

(I'll try to make a screen recording)

**Comment by skftn** [comment]
What I do:

- Settings -> Manage Wallet -> Close wallet
- Choose language dialog -> English
- Open a wallet from file (disable checkbox 'testnet' here)

And you're good to go.

**Comment by ordtrogen** [comment]
Here's a video showing what happens, and as I recorded it, I realized what the problem is

https://youtu.be/PxrBcFfXVxM

At the page in the Wizard where the button "Create a new wallet" is displayed, there is a check box which allows you to select (or unselect) "Testnet", but because it is outside the screen (10" in my case), you can't see the check box. When you click the "Create a new wallet" button, the window content is shifted upward slightly and you get to see the check box for a brief second before the Wizard moves to the next step.

Maybe I should change the issue title to something like "Testnet checkbox not visible on smaller screens"?

**Comment by skftn** [comment]
Ah, thanks for the video. I can see how it hides the checkbox. 

Can I ask what kind of device/laptop you have?

**Comment by ordtrogen** [comment]
Details are in first part of issue
Brand is Compaq or HP (can't check, am at work now)
Or did you refer to sth else?

Den 11 jan. 2018 23:22 skrev "Sander Ferdinand" <notifications@github.com>:

**Comment by ordtrogen** [comment]
Sorry, wrong thread ...
see #1066

**Comment by skftn** [comment]
I'm closing this thread in favor of #1066 for now. Lets continue there!

**Comment by skftn** [comment]
+resolved
