### ISSUE TITLE
abuseat.org

### ISSUE THREAD

**Issue by agsware** [monero-project/monero-gui#1073]
i have download and running
monero-gui-win-x64-v0.11.1.0.zip
but i have been banned from abuseat.org this is the message:

This IP is infected with, or is NATting for a machine infected with the "monerominer" malware.
This was detected by a TCP connection from "xxx.xxx.xxx.xxx" on port "1706" going to IP address "104.155.224.46" (the sinkhole) on port "8888".
The botnet command and control domain for this connection was "myxmr.pw".
This detection corresponds to a connection at Thu Jan 11 11:24:03 2018 UTC (this timestamp is believed accurate to within one second). 
.....

why this?

**Comment by wagdi8** [comment]
I have the same problem

**Comment by xmrdsc** [comment]
See https://www.abuseat.org/ **I'M LISTED, WHAT DO I DO?**

This issue tracker is for bugs related to the GUI.

+invalid
