### ISSUE TITLE
Monero GUI wallet - I can't see my founds

### ISSUE THREAD

**Issue by STokenman** [monero-project/monero-gui#1079]
Hi 

Thanks for willing to help,
I made a transaction using Shapeshift a few days ago,
While I was waiting for confirmation, I saw in my wallet the purchase waiting for approved, but after few minutes my wallet didn't respond so I refreshed it, and since then I lost touch with it :(
Mean that I have never seen it again in the wallet or the pending transactions,
When I'm checking the blockchain, I can use my privet view key to see the transaction but my GUI wallet somehow just can't recognize it...
Hope you could help me to understand what should I do
Thanks In advance

**Comment by leonklingele** [comment]
Have you tried this: https://monero.stackexchange.com/a/6641 ?

**Comment by STokenman** [comment]
Hi 
Thanks for your reply,
I walked all the steps of your instructions, but unfortunately it didn't work for me

**Comment by leonklingele** [comment]
__Make sure to back up your old wallet before proceeding__. You could try restoring the wallet from your seed.

**Comment by STokenman** [comment]
Tried but didn't work yet for me, 
Just to make sure, If I can see the transaction at the public blockchain using my privet view key, and I'm using a paper wallet, my founds are safe?

**Comment by leonklingele** [comment]
Correct, if you still have your private spend key.

**Comment by STokenman** [comment]
Thanks :)

**Comment by skftn** [comment]
Sorry to hear you are experiencing problems. Best to ask in another place:

- Via Reddit using [this thread](https://www.reddit.com/r/Monero/comments/7hhgjx/monero_gui_01110_helium_hydra_megathread_download/?sort=new)
- On [stackexchange](https://monero.stackexchange.com)

The community will pick your questions up.

**Comment by skftn** [comment]
+wontfix
