### ISSUE TITLE
Wallet "invalid password" after changing initial block height

### ISSUE THREAD

**Issue by Neozaru** [monero-project/monero-gui#1081]
**OS :** Archlinux x86_64
**Kernel :** 4.13.8-1-ARCH
**Branch** : master (3b069ec04908f76b8244a96124ce9619c0b0300d)

Summary : Error message "Could open wallet, invalid password" after changing wallet initial block height and closing/reopening.

Steps to reproduce :
- Create new wallet with name "neozaru5".
- Set password "barbarbar".
- Choose to connect to a remote node.
- Wait for connect and quick sync.
- Go Settings > Change creation block to "1" (should freeze some seconds before going back to wallet view)
- Close the window (should freeze some seconds before actually closing)
- Open again, and enter the password for your wallet
--> You get "wrong password" error message

EDIT : I didn't investigate technically speaking but entering no password seems to do the trick. So I assume that when *wallet creation height* is edited, a new wallet file is created, but not encrypted again (which would make sense since the GUI doesn't ask for any password before changing this parameter). 
EEDIT : Finally investigated.

Wallet files after create, after changing height, and after closing the GUI :
[debugNeozaruAfterClosing.zip](https://github.com/monero-project/monero-gui/files/1635279/debugNeozaruAfterClosing.zip)

Full console log : https://pastebin.com/2dkDYQF6

**Comment by skftn** [comment]
Assuming resolved, as there was a PR. If not, please re-open.

**Comment by skftn** [comment]
+resolved
