### ISSUE TITLE
Create explicit warnings and information when connecting to remote node

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-gui#1085]
Do some kind of checking to see if the IP isn't 127.0.0.1 and warn about risks.

**Comment by SamsungGalaxyPlayer** [comment]
@Gingeropolous do you have a specific warning message in mind?

**Comment by Gingeropolous** [comment]
"WARNING: Using a remote node means you are trusting someone elses copy of the blockchain. To have a fully trustless interaction with the monero network, you must synchronize your own node. It is highly recommended to run your own node."

something like that. I'm sure @moneromooo has some ideas as well :)

**Comment by skftn** [comment]
+enhancement

**Comment by dEBRUYNE-1** [comment]
The GUI now contains explicit warnings about remote node usage.

**Comment by dEBRUYNE-1** [comment]
+resolved
