### ISSUE TITLE
Monero-gui Windows Compile Failed

### ISSUE THREAD

**Issue by QuillLittlefeather** [monero-project/monero-gui#1095]
I followed the directions to the letter under windows section of compile guide but it will not compile.

here is the compile output ---> https://pastebin.com/8UZSCz7B

The last error was 

> [100%] Linking CXX executable ../../bin/monero-wallet-rpc.exe
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE18unwind_extra_blockE                                                                                                                                                                                    b[__ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcN                                                                                                                                                                                    St7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_1                                                                                                                                                                                    2regex_traitsIcNS_16cpp_regex_traitsIcEEEEE18unwind_extra_blockEb]+0x1a): undefi                                                                                                                                                                                    ned reference to `boost::re_detail_106200::put_mem_block(void*)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE12append_stateENS0_19syntax_element_typeEj[_                                                                                                                                                                                    _ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_re                                                                                                                                                                                    gex_traitsIcEEEEE12append_stateENS0_19syntax_element_typeEj]+0x80): undefined re                                                                                                                                                                                    ference to `boost::re_detail_106200::raw_storage::resize(unsigned int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620011raise_errorINS_20regex_traits_wr                                                                                                                                                                                    apperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constant                                                                                                                                                                                    s10error_typeE[__ZN5boost16re_detail_10620011raise_errorINS_20regex_traits_wrapp                                                                                                                                                                                    erINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10                                                                                                                                                                                    error_typeE]+0xa4): undefined reference to `boost::re_detail_106200::raise_runti                                                                                                                                                                                    me_error(std::runtime_error const&)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620011raise_errorINS_20regex_traits_wr                                                                                                                                                                                    apperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constant                                                                                                                                                                                    s10error_typeE[__ZN5boost16re_detail_10620011raise_errorINS_20regex_traits_wrapp                                                                                                                                                                                    erINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10                                                                                                                                                                                    error_typeE]+0xc9): undefined reference to `boost::re_detail_106200::get_default                                                                                                                                                                                    _error_string(boost::regex_constants::error_type)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12extend_stackEv[__ZN                                                                                                                                                                                    5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__c                                                                                                                                                                                    xx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex                                                                                                                                                                                    _traitsIcNS_16cpp_regex_traitsIcEEEEE12extend_stackEv]+0x1b): undefined referenc                                                                                                                                                                                    e to `boost::re_detail_106200::get_mem_block()'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE14append_literalEc[__ZN5boost16re_detail_106                                                                                                                                                                                    20019basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE14appen                                                                                                                                                                                    d_literalEc]+0xac): undefined reference to `boost::re_detail_106200::raw_storage                                                                                                                                                                                    ::resize(unsigned int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE12insert_stateEiNS0_19syntax_element_typeEj[                                                                                                                                                                                    __ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_r                                                                                                                                                                                    egex_traitsIcEEEEE12insert_stateEiNS0_19syntax_element_typeEj]+0x69): undefined                                                                                                                                                                                     reference to `boost::re_detail_106200::raw_storage::insert(unsigned int, unsigne                                                                                                                                                                                    d int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE10append_setERKNS0_14basic_char_setIcS5_EEPN                                                                                                                                                                                    4mpl_5bool_ILb0EEE[__ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex                                                                                                                                                                                    _traitsIcNS_16cpp_regex_traitsIcEEEEE10append_setERKNS0_14basic_char_setIcS5_EEP                                                                                                                                                                                    N4mpl_5bool_ILb0EEE]+0x17b): undefined reference to `boost::re_detail_106200::ra                                                                                                                                                                                    w_storage::resize(unsigned int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE10append_setERKNS0_14basic_char_setIcS5_EEPN                                                                                                                                                                                    4mpl_5bool_ILb0EEE[__ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex                                                                                                                                                                                    _traitsIcNS_16cpp_regex_traitsIcEEEEE10append_setERKNS0_14basic_char_setIcS5_EEP                                                                                                                                                                                    N4mpl_5bool_ILb0EEE]+0x5da): undefined reference to `boost::re_detail_106200::ra                                                                                                                                                                                    w_storage::resize(unsigned int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE10append_setERKNS0_14basic_char_setIcS5_EEPN                                                                                                                                                                                    4mpl_5bool_ILb0EEE[__ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex                                                                                                                                                                                    _traitsIcNS_16cpp_regex_traitsIcEEEEE10append_setERKNS0_14basic_char_setIcS5_EEP                                                                                                                                                                                    N4mpl_5bool_ILb0EEE]+0x9d8): undefined reference to `boost::re_detail_106200::ra                                                                                                                                                                                    w_storage::resize(unsigned int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZNK5boost16re_detail_10620031cpp_regex_traits_implementation                                                                                                                                                                                    IcE18lookup_collatenameB5cxx11EPKcS4_[__ZNK5boost16re_detail_10620031cpp_regex_t                                                                                                                                                                                    raits_implementationIcE18lookup_collatenameB5cxx11EPKcS4_]+0xcc): undefined refe                                                                                                                                                                                    rence to `boost::re_detail_106200::lookup_default_collate_name(std::__cxx11::bas                                                                                                                                                                                    ic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620031cpp_regex_traits_implementationI                                                                                                                                                                                    cE4initEv[__ZN5boost16re_detail_10620031cpp_regex_traits_implementationIcE4initE                                                                                                                                                                                    v]+0xca): undefined reference to `boost::re_detail_106200::get_default_error_str                                                                                                                                                                                    ing(boost::regex_constants::error_type)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620031cpp_regex_traits_implementationI                                                                                                                                                                                    cE4initEv[__ZN5boost16re_detail_10620031cpp_regex_traits_implementationIcE4initE                                                                                                                                                                                    v]+0x1b0): undefined reference to `boost::re_detail_106200::raise_runtime_error(                                                                                                                                                                                    std::runtime_error const&)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost12object_cacheINS_16re_detail_10620021cpp_regex_trai                                                                                                                                                                                    ts_baseIcEENS1_31cpp_regex_traits_implementationIcEEE6do_getERKS3_j[__ZN5boost12                                                                                                                                                                                    object_cacheINS_16re_detail_10620021cpp_regex_traits_baseIcEENS1_31cpp_regex_tra                                                                                                                                                                                    its_implementationIcEEE6do_getERKS3_j]+0x1c0): undefined reference to `boost::re                                                                                                                                                                                    _detail_106200::cpp_regex_traits_char_layer<char>::init()'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620018basic_regex_parserIcNS_12regex_t                                                                                                                                                                                    raitsIcNS_16cpp_regex_traitsIcEEEEE4failENS_15regex_constants10error_typeEi[__ZN                                                                                                                                                                                    5boost16re_detail_10620018basic_regex_parserIcNS_12regex_traitsIcNS_16cpp_regex_                                                                                                                                                                                    traitsIcEEEEE4failENS_15regex_constants10error_typeEi]+0xd7): undefined referenc                                                                                                                                                                                    e to `boost::re_detail_106200::get_default_error_string(boost::regex_constants::                                                                                                                                                                                    error_type)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620019basic_regex_creatorIcNS_12regex_                                                                                                                                                                                    traitsIcNS_16cpp_regex_traitsIcEEEEE8finalizeEPKcS8_[__ZN5boost16re_detail_10620                                                                                                                                                                                    019basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8finalize                                                                                                                                                                                    EPKcS8_]+0x7d): undefined reference to `boost::re_detail_106200::raw_storage::re                                                                                                                                                                                    size(unsigned int)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[__ZN5boo                                                                                                                                                                                    st16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx11                                                                                                                                                                                    12basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_tra                                                                                                                                                                                    itsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0xb): undefined reference to `boo                                                                                                                                                                                    st::re_detail_106200::get_mem_block()'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[__ZN5boo                                                                                                                                                                                    st16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx11                                                                                                                                                                                    12basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_tra                                                                                                                                                                                    itsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0xe4): undefined reference to `bo                                                                                                                                                                                    ost::re_detail_106200::verify_options(unsigned int, boost::regex_constants::_mat                                                                                                                                                                                    ch_flags)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[__ZN5boo                                                                                                                                                                                    st16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx11                                                                                                                                                                                    12basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_tra                                                                                                                                                                                    itsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0x118): undefined reference to `b                                                                                                                                                                                    oost::re_detail_106200::put_mem_block(void*)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[__ZN5boo                                                                                                                                                                                    st16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx11                                                                                                                                                                                    12basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_tra                                                                                                                                                                                    itsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0x1cc): undefined reference to `b                                                                                                                                                                                    oost::re_detail_106200::put_mem_block(void*)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[__ZN5boos                                                                                                                                                                                    t16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx111                                                                                                                                                                                    2basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_trai                                                                                                                                                                                    tsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0xb): undefined reference to `boost                                                                                                                                                                                    ::re_detail_106200::get_mem_block()'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[__ZN5boos                                                                                                                                                                                    t16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx111                                                                                                                                                                                    2basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_trai                                                                                                                                                                                    tsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x122): undefined reference to `boo                                                                                                                                                                                    st::re_detail_106200::verify_options(unsigned int, boost::regex_constants::_matc                                                                                                                                                                                    h_flags)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[__ZN5boos                                                                                                                                                                                    t16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx111                                                                                                                                                                                    2basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_trai                                                                                                                                                                                    tsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x161): undefined reference to `boo                                                                                                                                                                                    st::re_detail_106200::put_mem_block(void*)'
CMakeFiles/wallet_rpc_server.dir/objects.a(wallet_rpc_server.cpp.obj):wallet_rpc                                                                                                                                                                                    _server.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__norm                                                                                                                                                                                    al_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_                                                                                                                                                                                    matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[__ZN5boos                                                                                                                                                                                    t16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx111                                                                                                                                                                                    2basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_trai                                                                                                                                                                                    tsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x293): undefined reference to `boo                                                                                                                                                                                    st::re_detail_106200::put_mem_block(void*)'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:129: bin/mo                                                                                                                                                                                    nero-wallet-rpc.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:2184: src/wallet/CMakeFiles/wallet_rpc_server                                                                                                                                                                                    .dir/all] Error 2
make: *** [Makefile:139: all] Error 2

not sure how to fix this as im not sure what the issue is the output tells me nothing.

**Comment by cryptobender69** [comment]
Any solution for this yet?

**Comment by glv2** [comment]
Maybe the compilation is trying to use the wrong boost version. Could you check if the solution in https://github.com/monero-project/monero-gui/issues/1086#issuecomment-359252241 (and following comments) solves the problem?

**Comment by skftn** [comment]
No response, assuming resolved. If not, please re-open.

**Comment by skftn** [comment]
+resolved
