### ISSUE TITLE
Pop-Up File Dialog for picking a wallet opens behind GUI 

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#1096]
File Dialog for picking s wallet opens behind GUI. Depending on location of the main window, it can be hidden completely.

--> All popups of this kind are affected (also when signing a trx for example)

![seed_restore_behind](https://user-images.githubusercontent.com/17108301/35472070-b8290fd2-0368-11e8-9dee-35500066a721.png)

**Comment by medusadigital** [comment]
+Bug

**Comment by pwag42** [comment]
I think this is part of a bigger issue where the monero gui renders in front of _everything_ and can't be minimized.

**Comment by Sheastesx** [comment]
+duplicate

**Comment by skftn** [comment]
Related to window manager.

**Comment by skftn** [comment]
+wontfix
