### ISSUE TITLE
Pop-Up Payment Tracking Info in recive tab opens behind GUI 

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#1097]
Pop-Up Payment Tracking Info in recive tab opens behind GUI. Depending on location of the GUI, it can be completely hidden and the gui needs to be restarted with force.

--> All popups of this kind are affected (also when signing a trx for example)

![payment_tracker_hidden](https://user-images.githubusercontent.com/17108301/35472503-9f2c5b80-0370-11e8-8c8e-d00f52ad3452.png)

**Comment by medusadigital** [comment]
+Bug

**Comment by skftn** [comment]
Related to your window manager ;)

**Comment by skftn** [comment]
+wontfix
