### ISSUE TITLE
Memory leak in TSMInputSource

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1112]
GUI version: v0.11.1.0-190-g75bc37e
Embedded Monero version: v0.10.3.1-1575-ged67e5c

Steps:
Launch Monero GUI.

What happened:
Memory leak in TSMInputSource

https://www.dropbox.com/s/icdw0bicbo3mzts/Monero%20leaks%202.trace.zip?dl=0

Expected result:
No leaks.

Notes:
Unzip and open file with Apple Instruments (part of Xcode tools).

**Comment by skftn** [comment]
Thanks for your submission(s).

Please collect all memory leaks you have submitted into one big issue. This is better for visibility. I also believe most of the issues you submitted are out of scope, as they're QT related. Tagging this as wontfix.

**Comment by skftn** [comment]
+wontfix
