### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [monero-project/monero-gui#1119]
Hello, I would like to collaborate on the project and translate into Spanish, what files can I translate?

**Comment by erciccione** [comment]
Hi again. Somebody is already working on updating the spanish localization of the GUI ( #1109 )
You could work on the CLI wallet (as explained in the issue you opened in the 'monero' repo) or on the website. Let me know what you'd like to contribute to and i'll help you to get it done :)

**Comment by selsta** [comment]
Seeing that there is a Spanish translation, I’ll close this.

+resolved
