### ISSUE TITLE
Esperanto seed option not used in GUI

### ISSUE THREAD

**Issue by ProkhorZ** [monero-project/monero-gui#1131]
In languages.xml, the wallet_language parameter for Esperanto is still set to English, although there is a mnemonic seed word list in Esperanto now. I assume this parameter refers to the mnemonic seed language, since it's localized for other languages like Russian and Japanese that have localized seeds but not a localized CLI and daemon.

`        <language display_name="Esperanto" locale="eo" wallet_language="English" flag="/lang/flags/esperanto.png" qs="none"/>
`
in https://github.com/monero-project/monero-gui/blob/master/lang/languages.xml

I don't feel comfortable changing this myself in an important file. I'm not sure if anything else needs to be changed in order to enable selecting Esperanto. But I would like to see Moneristoj actually use the word list I compiled.

**Comment by glv2** [comment]
There is no other line to change to use the Esperanto word list when the Esperanto locale is used.

So you just have to make a pull request changing the line
```<language display_name="Esperanto" locale="eo" wallet_language="English" flag="/lang/flags/esperanto.png" qs="none"/>```
to
```<language display_name="Esperanto" locale="eo" wallet_language="Esperanto" flag="/lang/flags/esperanto.png" qs="none"/>```
and new wallet generation will use the right word list.

**Comment by ProkhorZ** [comment]
Thanks, that's surprisingly easy! 

Complication: I accidentally made another commit in my forked master branch. I'll make a pull request for this issue after sorting that out.

**Comment by ProkhorZ** [comment]
PR #1154 merged.
