### ISSUE TITLE
macOS High Sierra build error: ld: library not found for -lwallet_merged

### ISSUE THREAD

**Issue by bref2013** [monero-project/monero-gui#1139]
-F/usr/local/Cellar/qt/5.10.1/lib -L/Users/lee/Downloads/monero-gui-master/monero/lib -lwallet_merged -lepee -lunbound -leasylogging -lreadline -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/boost/lib -lboost_serialization -lboost_thread-mt -lboost_system -lboost_date_time -lboost_filesystem -lboost_regex -lboost_chrono -lboost_program_options -lssl -lcrypto -ldl -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework QtWidgets -framework OpenGL -framework AGL 
ld: library not found for -lwallet_merged
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [release/bin/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui] Error 1

macOS High Sierra 10.13.3 (17D47)
with brew install all the boost, openssl and so on.
there is one time generate app, but cannot the GUI wallet cannot link to daemon.

Is there any advice why can't compile the gui wallet?
thanks a lot ahead

**Comment by pazos** [comment]
I found an error building for Ubuntu, where libreadline is missing. I don't know if this could help but you can try `brew install readline` and report if that works for you.

**Comment by einsteinsfool** [comment]
Well, I had this error but I also had another one with "-lepee". Fixed that by adding more RAM to my VM. 1 GB -> 3 GB. Probably not the case if you're not using VM.

**Comment by BigslimVdub** [comment]
I had this issue with AEON rebase gui using ver1.2 but it was fixed with v1.3 for high Sierra.

**Comment by skftn** [comment]
I believe this was resolved in monero-project/monero#3296. Could you verify?

**Comment by dEBRUYNE-1** [comment]
Given the inactivity of this issue, I am going to close it. 

+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
