### ISSUE TITLE
Wonky behaviour when switching wallets

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#1157]
Switching wallets is somewhat borked. I switched from testwallet 3 to testwallet 1, but it would display testwallet 3 as Wallet name and have no balance. After restarting the GUI it showed the correct balance and Wallet name. I should also note that this bug was hard to reproduce and was quite inconsistent.

**Comment by skftn** [comment]
Possibly related: #1194

**Comment by skftn** [comment]
Closing this, in favor of issue 1194, which `ui-dark-theme` has a 'fix' for. Please re-open or create a new issue when it occurs (+reproducible steps)

**Comment by skftn** [comment]
+resolved
