### ISSUE TITLE
Open a wallet from file displays Settings page in the background

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#1159]
Open a wallet from file -> It will display the settings page of the GUI in the background.

**Comment by skftn** [comment]
+bug

**Comment by xmrdsc** [comment]
@mmbyday mentioned:
> Whatever page, such as the setting page, was open previously, will show in the background. 

### Quick solution:

Programmatically switch to the transfer page before closing a wallet (and call [completeTransition()](http://doc.qt.io/qt-5/qml-qtquick-controls-stackview.html#completeTransition-method) to prevent stacktransition).

### Better solution:

Find a way to properly construct and deconstruct QML components by utilizing `Component.onCompleted {` so a cleanup of text contents would happen automatically.

Just thinking out loud :-)

**Comment by mmbyday** [comment]
I made a small, simple change. That'll fix this for now. #1837 ,

**Comment by dEBRUYNE-1** [comment]
Looks good. I'll close this issue when the PR gets merged.

**Comment by dEBRUYNE-1** [comment]
+resolved
