### ISSUE TITLE
Switching pages does not reset the state of the page

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#1160]
If you scroll down on the Settings page and then switch to, for instance, the Send page it will start at the bottom. It should start at the top.

**Comment by skftn** [comment]
+enhancement

**Comment by skftn** [comment]
+easy

**Comment by leonklingele** [comment]
Only the scroll position should be reset, it's quite useful that form fields are not touched.

**Comment by dEBRUYNE-1** [comment]
@leonklingele - Agree.
