### ISSUE TITLE
Can not minimize gui to tray

### ISSUE THREAD

**Issue by BigslimVdub** [monero-project/monero-gui#1163]
Using AEON rebase v1.3 on high Sierra I can not minimize( _ function)  to tray. Maximize works fine. Close (x) works fine. 

Running released tar.zip not made with cMake. Tagging @stoffu 

Monero gui 11.0 helium hydra works fine to minimize to tray on same system.

**Comment by stoffu** [comment]
Ah, sorry for not being clear, but if the issue only exists in my Aeon port but not in the original Monero GUI, then probably it's not appropriate to open an issue here. I've enabled the issue feature just now.

**Comment by BigslimVdub** [comment]
Issue moved to aeon gui
