### ISSUE TITLE
List disk space among the system requirements before installing

### ISSUE THREAD

**Issue by Bomper** [monero-project/monero-gui#1164]
First time user on Linux. Ran out of disk space several times, as the wallet keeps download the blockchain.

1. Is there an open-source thin wallet alternative for Linux?
2. Before installing, the user should be warned that they need ample space for the blockchain. On a laptop, 40GB+ is no joke. Ideally the space required would be estimated based on the current state of the blockchain.

**Comment by pazos** [comment]
@Bomper:

1. You can use the GUI with a [remote node](https://getmonero.org/resources/user-guides/remote_node_gui.html)

**Comment by Bomper** [comment]
@pazos: interesting, didn't realize that. I guess a wizard would be helpful for new users, asking if they'd like to search for a node, vs. run their own daemon.

**Comment by skftn** [comment]
A diskspace warning is already present during the wallet setup warnings, so I wonder how you did not receive one.

See also: https://github.com/monero-project/monero-gui/blob/master/main.qml#L1122

As for the wizard(s) themselves, they'll be improved at a later stage.

**Comment by skftn** [comment]
+resolved
