### ISSUE TITLE
Display block heights in the GUI

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1168]
Related: 
#766 GUI says "Synchronizing" when it hasn't connected yet

When the highest block height is higher than the last block that was scanned for all addresses in the wallet, there could be another line under the progress bar:

{lastBlockScannedForAllAddresses}/{highestKnownBlock}

(There is a third block height, the highest downloaded block, but I suggest not including that in the GUI. NEO's Neon wallet does that and it looks super confusing. Users mostly watch the progress just to see if they received their funds.)

If the wallet is all synced and scanned, I propose displaying just the latest block height next to/under the "Connected" text box.

**Comment by skftn** [comment]
+enhancement

**Comment by skftn** [comment]
#891

**Comment by leafcutterant** [comment]
I believe this is fixed now, so closing.
