### ISSUE TITLE
Display fee (before sending)

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1169]
I see no good reason not to show the user the final transaction fee amount in XMR. It could have a place somewhere on the Send tab, maybe under the Amount value in a smaller font size.

**Comment by SamsungGalaxyPlayer** [comment]
The fee is shown in the confirmation dialog. However, it could be shown somewhere on the send screen itself.

**Comment by leafcutterant** [comment]
Closed in favor of #1198.
