### ISSUE TITLE
Allow running a node without creating/opening a wallet

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1170]
After opening and choosing a language, there should be a fourth option to just sync the blocks and act as a full node without having any wallets open.

What do you think?

**Comment by skftn** [comment]
Perhaps 2 seperate launch icons in Windows could do the trick as well (one for `monerod.exe`, one for `monero-wallet-gui.exe`)

**Comment by leafcutterant** [comment]
Not sure what you mean.

If you mean that those who only want to run a full node, without a wallet open, should simply run `monerod`, then I oppose as I think there is value in enabling a "no-wallet" mode for users who are deterred by the sight of command line windows.

Speaking of that, it could be like Bitcoin Core started with the  `--no-wallet` parameter, where wallet-related content is simply not displayed on the UI.

**Comment by skftn** [comment]
I hear what you're saying. However, I believe that users will not be deterred by a command prompt, as those that have a 'full-node' requirement (and ofc, everyone should) will:

- Take peace with leaving the GUI on
- Will find out how to run it without the GUI (headless server).

**Comment by skftn** [comment]
+wontfix
