### ISSUE TITLE
Standard log location (Linux & Android)

### ISSUE THREAD

**Issue by pazos** [monero-project/monero-gui#1181]
For monero-wallet-gui the logfile is in the same folder as the binary. This is great when running the GUI from its folder (ie: static build) but a bad choice If I want to run the GUI from /usr/bin, /usr/local/bin, where the user running the binary doesn't have permissions to write at those folders.

Using a standard location, like $HOME/.monero/monero-wallet-gui.log as a fallback would be great.

**Comment by pazos** [comment]
About android I'm not sure if the log should be saved in AppDataLocation (/data/data/monero..) or somewhere in external storage, like DocumentsLocation  /storage/emulated/0/Documents..)

The latter requires request for permission WRITE_EXTERNAL_STORAGE.

The former doesn't require permissions and it is compatible with IOS.

**Comment by skftn** [comment]
+feature

**Comment by pazos** [comment]
It seems that changing Wallet::getWalletLogPath() in src/libwalletqt/Wallet.cpp don't make any difference and the log is still created in the same dir as the binary.

@skftn: any hint on this?

**Comment by skftn** [comment]
No clue, unfortunately. Perhaps try in #monero-dev or the GUI channel on Freenode.
