### ISSUE TITLE
Display transaction size (kB) and fee rate (XMR/kB) on Send tab

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1198]
This is useful information. If it's not possible to include in the ~~fees~~ **Send** tab, at least the confirmation widow could contain them.

**Comment by skftn** [comment]
Could #1169 be closed in favor of this issue/feature-request?

**Comment by leafcutterant** [comment]
Sure. I closed it.

Do you think it's possible to add the fee to the list of metrics to display?

**Comment by skftn** [comment]
It's a good idea, but technically possibly complicated to implement. 

We could have Javascript create dummy transactions while the user is filling in the 'Send' form - will have to check the viability of that approach.

**Comment by selsta** [comment]
The fee is now displayed.
