### ISSUE TITLE
History page - search by address

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#1208]
Would be nice if the GUI could filter the transaction history table by receiving/recipient address.

**Comment by skftn** [comment]
+enhancement

**Comment by skftn** [comment]
For reference:

https://github.com/monero-project/monero-gui/blob/b4353a31ac9cfabd348eb14b4f334918b2abc135/src/model/TransactionHistorySortFilterModel.cpp#L217

This feature might not be worth it, as recipient addresses are only stored in the wallet cache.
