### ISSUE TITLE
Dark theme: Can't scroll History if mouse is over the transactions

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1209]
Scrolling when the mouse cursor is over the transactions in History doesn't work. If you move the cursor to the left or right gutter, scrolling then works.

Mac OS
GUI version: v0.11.1.0-450-gb32b308

**Comment by skftn** [comment]
Interesting, scrolls fine on Linux. How many items do you reckon you have in that table?

Ill test on OSX at a later date.

**Comment by tficharmers** [comment]
29 items.

Ah interesting. It doesn't scroll if I use an Apple magic mouse, but I just plugged in a cheap Microsoft mouse and it does scroll the transactions using the scroll wheel on that.

**Comment by skftn** [comment]
Can reproduce on macbook pro trackpad.

**Comment by skftn** [comment]
+bug

**Comment by peanutsformonkeys** [comment]
Encountered the same issue when testing Aeon's pre-release 0.1.7.2. Scrolling with the mouse-wheel works, but two-finger swiping on the built-in trackpad doesn't work anymore. One has to click with the trackpad and then drag, which is a pain if you have hundreds of transactions to move through.

**Comment by Axam** [comment]
Hold left mouse button to scroll as workaround. Mouse wheel and touchpad didn't work for me.

**Comment by selsta** [comment]
+resolved
