### ISSUE TITLE
Dark theme: black text on black background for unlock wallet

### ISSUE THREAD

**Issue by qubenix** [monero-project/monero-gui#1212]
Debian Stretch. I'm sure it has something to do with fonts, but not sure what. I included the term in the screenshot for added info.

![image](https://user-images.githubusercontent.com/15707061/38153008-cb17ce4a-3427-11e8-8694-9cc25bb18a9d.png)

**Comment by skftn** [comment]
Thanks for the console output, helps in this case.

Fixed in #1217

**Comment by skftn** [comment]
Thanks for console output.

#1217 will fix this

**Comment by skftn** [comment]
+resolved
