### ISSUE TITLE
Dark theme: shared ringdb page black check on black background

### ISSUE THREAD

**Issue by qubenix** [monero-project/monero-gui#1213]
Debian Stretch. Can't tell what boxes are checked here. In the screenshot `Relative` is unchecked and the other two are checked.

![image](https://user-images.githubusercontent.com/15707061/38153119-4ca53696-3428-11e8-844c-28ea45f20191.png)

**Comment by skftn** [comment]
+bug

**Comment by erciccione** [comment]
Hey folks, can somebody fix this please? so we can start working on monero-ecosystem/monero-GUI-guide#10

**Comment by SamsungGalaxyPlayer** [comment]
pinging @erciccione to let them know this is done

**Comment by erciccione** [comment]
thanks @SamsungGalaxyPlayer :)
