### ISSUE TITLE
Dark theme: wizard, bootstrap node bold text

### ISSUE THREAD

**Issue by qubenix** [monero-project/monero-gui#1214]
When setting up a wallet in the wizard the host and port of the bootstrap node is bold, but the remote node text is not. Maybe it's intentional?

![image](https://user-images.githubusercontent.com/15707061/38153269-03424718-3429-11e8-9de0-a4c916f407b7.png)

**Comment by skftn** [comment]
Will probably not fix, as these wizards will also be restyled soon(tm).

**Comment by qubenix** [comment]
Sounds good.
