### ISSUE TITLE
Dark theme: "start node" is option when node is already started

### ISSUE THREAD

**Issue by qubenix** [monero-project/monero-gui#1215]
Debian Stretch. If I start a local node from the settings page the button changes to `Stop Local Node`, but if I leave the settings page and then return, `Start Local Node` is again the option instead of `Stop Local Node`. Even though the node is still running.

If I want to stop the node, I have to click `Start Local Node` which actually restarts the node, and then I can click `Stop Local Node` to shutdown properly.

**Comment by skftn** [comment]
+bug

**Comment by xiphon** [comment]
#1728

**Comment by dEBRUYNE-1** [comment]
+resolved
