### ISSUE TITLE
Add "Remember language" option

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1225]
There is no point in showing the language selector every time a new wallet is opened. Once a user chooses a language, they will probably stick with it (and even in the rare cases when multiple people use the same OS account on the same machine, they will be probably of the same language).

My suggestion:
* Add a `☑ Remember language` tick box to the language selector screen. If a language is selected after ticking this, Monero from there on will skip the language selector and go to the New/Restore/Open screen whenever a new wallet should be opened,
* Add a `Change language ` button to the bottom left corner of the New/Restore/Open screen in case someone changes their mind or a new user with a different language accesses the application. Display the flag icon of the present language next to the button so that it's obvious it leads to the language selector even if the new user doesn't speak the presently selected language.

**Comment by leafcutterant** [comment]
I think a 'Change language' option in the 'Advanced' tab won't do any harm, so yes, sure.

The new designs look cool!

**Comment by mmbyday** [comment]
+resolved
by wizard redesign.

**Comment by dEBRUYNE-1** [comment]
+resolved
