### ISSUE TITLE
Display wallet name somewhere in the GUI

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1237]
Ease of use feature.

**Comment by dEBRUYNE-1** [comment]
It's displayed on the `Settings` page under `Debug info`. As such, I am going to mark this issue as 'invalid'.

+invalid

**Comment by leafcutterant** [comment]
I mean the name of the wallet file actually in use, to be able to discern which wallet is opened at the moment.

I see nothing like that under Debug. There is GUI version, Embedded version, Wallet creation height, Wallet log path and Daemon log path,

**Comment by pazos** [comment]
@leafcutterant: it was merged in master last week. You'll need to update your gui you see the change (or wait until 0.12 release)
![captura de pantalla de 2018-04-01 22-45-05](https://user-images.githubusercontent.com/975883/38177235-5d5ec0e2-35fe-11e8-95d2-7a337ed8fd0a.png)

**Comment by leafcutterant** [comment]
I was unaware of this, thanks! Closing.
