### ISSUE TITLE
Can't launch v0.12.0.0 on Ubuntu

### ISSUE THREAD

**Issue by 1337tester** [monero-project/monero-gui#1242]
GUI_VERSION = "v0.12.0.0"
Ubunutu - 17.10

When opening monero-wallet-gui, this **error occurs** (and the GUI is ofc not launched)
"
_QQmlApplicationEngine failed to load component
qrc:///main.qml:1043 Type StandardDialog unavailable
qrc:///components/StandardDialog.qml:30 module "QtQuick.Controls" version 2.0 is not installed
Error: no root objects_
"
Could be that this #1240 is causing it, after some [research](https://stackoverflow.com/questions/22389605/module-qtquick-controls-is-not-installed-error-on-ubuntu-14-04) (aka quick duckduckgo search) - the issue can be that Ubuntu has also a older version of QT(5.0.2) which is first found when the program is launched - and it fails (even when the correct version is present in the system)

Don't know a easy way to fix this, probably there is a workaround, but I assume we don't really want people to remove some parts of ubuntu for installing a monero-gui build

**Comment by pazos** [comment]
From [reddit/r/monero](https://www.reddit.com/r/Monero/comments/892vlr/lithium_luna_gui_released/dwordse/)

`sudo apt qml-module-qtquick-controls2`

For ubuntu 16.04 - 17.10

**Comment by skftn** [comment]
QT 5.7.0 is a minimum requirement

**Comment by 1337tester** [comment]
thanks alot, worked, the command is btw:

sudo apt install qml-module-qtquick-controls2

can be closed

**Comment by lowrenhart** [comment]
For Ubuntu 16.04LTS, this doesn't work:

> sudo apt qml-module-qtquick-controls2

As @skftn commented, the version must be higher, but that one is not available. You have to manually install it.

**Comment by 1337tester** [comment]
can be closed

**Comment by skftn** [comment]
+resolved
