### ISSUE TITLE
Dark theme: LeftPanel MenuButton symbol displayed in awkward positions

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero-gui#1249]
After the merge of dark theme, the character symbols that show up when pressing Ctrl (or Command on mac) are positioned in the center of the whole column:

![screen shot 2018-04-03 at 19 51 31](https://user-images.githubusercontent.com/26077532/38249508-d7fdbff4-3786-11e8-924e-533c8a2f5fe9.jpg)

Before the dark theme, these symbols were shown on top of the small circles on the left of the menu texts.

**Comment by skftn** [comment]
+bug
