### ISSUE TITLE
Dark theme: Settings > Log level dropdown is transparent on Mac OS

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1250]
The log level dropdown probably shouldn't have a translucent background. See attached image.

Mac OS 10.13.2
GUI version: v0.12.0.0

![screen shot 2018-04-03 at 18 05 09](https://user-images.githubusercontent.com/23356013/38264142-09c5a6d6-376a-11e8-8615-a20e0e9ab9cd.PNG)

**Comment by skftn** [comment]
+bug
