### ISSUE TITLE
Can't run Linux x64 binaries on Arch Linux x64

### ISSUE THREAD

**Issue by MaxXor** [monero-project/monero-gui#1253]
Trying to run `monero-wallet-gui` fails with:
> ./monero-wallet-gui: error while loading shared libraries: **libpcsclite.so.1**: cannot open shared object file: No such file or directory

GUI v0.11.1.0 was working fine, seems like some dependency is messed up.

I'm using the binaries from here: https://github.com/monero-project/monero-gui/tree/v0.12.0.0

**Comment by stevesbrain** [comment]
Does it change if you install pcsclite?

**Comment by MaxXor** [comment]
Yes, then it is starting. Why this new dependency on "PC/SC Architecture smartcard middleware library"?

**Comment by stevesbrain** [comment]
@MaxXor My expectation would be possible use with the Ledger Nano S when it comes about, but I don't know if this is why or not. Glad to hear that resolves it :) P.S. you can always build from [the AUR package](https://aur.archlinux.org/packages/monero-gui-bin/) if that helps :)

**Comment by MaxXor** [comment]
Ah, that seems to be the reason for the new dependency.

**Comment by skftn** [comment]
+resolved

**Comment by tummybos** [comment]
@stevesbrain Hi i am having this issue as well. How do i install the pcsclite you talked about

**Comment by stevesbrain** [comment]
@tummybos Should just be a case of `pacman -S pcsclite` - let us know if you have issues beyond that :)
