### ISSUE TITLE
GUI glitch in Shared RingDB

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1254]
GUI version: v0.12.0.0
macOS 10.13.4 (17E199)

Reproducibility: always

Steps:
1. Launch GUI.
2. Advanced -> Shared RingDB

What happened:
Text "Relative" is drawn beyond bounds and produces glitch depending on window size.

https://www.dropbox.com/s/fgk7ns0o7w9djiu/Monero%20GUI%20glitch.mp4?dl=0

Expected result:
No glitch.

**Comment by skftn** [comment]
+bug
