### ISSUE TITLE
GUI glitch in progress bars

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1256]
GUI version: v0.12.0.0
macOS 10.13.4 (17E199)

Reproducibility: always

Steps:
Check the progress bars on the lower left.

What happened:
The color inside the bars is not fully drawn until the very right, implying there is still progress, although the wallet and daemon are both 100% synced.

![screen shot 2018-04-04 at 13 10 00](https://user-images.githubusercontent.com/227442/38302067-1fc8e574-380a-11e8-87ab-9a614fba4227.png)

Expected result:
No glitch.

**Comment by tficharmers** [comment]
Perhaps make the bar go green when 100% filled too?

**Comment by skftn** [comment]
+enhancement
