### ISSUE TITLE
Dark theme: Settings: If using a remote node, the 'Log level' section is redundant and shouldn't be visible

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1257]
If using a remote node, the 'Log level' section is redundant and shouldn't be visible.

**Comment by tficharmers** [comment]
+bug

**Comment by skftn** [comment]
+enhancement

**Comment by skftn** [comment]
Log Level section actually implies to the GUI log, not the daemon log.

The daemon log is under Settings->Manage Daemon->Show Status, which is already hidden when using a remote node.

**Comment by skftn** [comment]
+invalid

**Comment by tficharmers** [comment]
> Argument could be made to communicate this more clearly to the user.

Agreed. I'll look into that.
