### ISSUE TITLE
Couldn't start mining

### ISSUE THREAD

**Issue by MaxXor** [monero-project/monero-gui#1274]
In latest GUI release the solo mining option does no longer work and only shows:
> Couldn't start mining

Also the mining status on the bottom is out of view and scrolling is required to view it. I had fixed this a while ago, but seems it's back again... https://github.com/monero-project/monero-gui/pull/844

**Comment by dEBRUYNE-1** [comment]
Are you running `monerod` with `--restricted-rpc`?

**Comment by MaxXor** [comment]
Does the GUI run `monerod` by default with `--restricted-rpc` ? I didn't change any setting.

**Comment by SamsungGalaxyPlayer** [comment]
It does not run with `--restricted-rpc` by default.

Is it possible you are connected to a bootstrapped node since your local node is not fully synced yet?

**Comment by MaxXor** [comment]
It's fully synced and mining worked fine in v0.11.

**Comment by MaxXor** [comment]
Seems to be working again after fork.

**Comment by skftn** [comment]
+resolved
