### ISSUE TITLE
Embed GUI guide

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-gui#1275]
The guide for the GUI wallet developed by the community is ready and can be found at this address:
https://github.com/erciccione/monero-GUI-guide

This guide was created on @dEBRUYNE-1 's proposal, with the goal of giving the community a costantly updated guide easily available with the GUI executable files.

How can we integrate it in the binaries? It is available in two formats at the moment: Markdown and PDF (The PDF can be downloaded from the [release section](https://github.com/erciccione/monero-GUI-guide/releases)). The latter will be created along with every major release or point release.
Should we also link to it from this repository?

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by erciccione** [comment]
The new PDF of the guide is ready to be embedded with the binaries and can be found here: https://github.com/monero-ecosystem/monero-GUI-guide/releases/tag/1.1

Pinging @fluffypony

**Comment by dEBRUYNE-1** [comment]
@erciccione - Perhaps this should be closed in favor of #1602? The GUI guide is also embedded in the release binaries.

**Comment by erciccione** [comment]
@dEBRUYNE-1 I would prefer to close #1602 and keep this open. At the moment the guide is manually included in the binaries, but would be better to have it integrated in the GUI. We discussed this option, but never really decided how to make it happen.

**Comment by dEBRUYNE-1** [comment]
All right. Closing #1602 in favor of this then.

**Comment by erciccione** [comment]
Done :)
