### ISSUE TITLE
GUI will not start over RDP connection [v0.12.0.0]

### ISSUE THREAD

**Issue by LesterCovax** [monero-project/monero-gui#1277]
`monero-wallet-gui.exe` in v0.12.0.0 will not start while RDP'ing via Remmina from Ubuntu to a Win10 box.  This issue does not occur in v0.11.1.0.

`start-low-graphics-mode.bat`, however, does start correctly with v0.12.0.0.  I suspect that it's a QT-based regression error, and related to [OpenGL rendering of QT over RDP](https://forum.qt.io/topic/79580/opening-qt-from-remote-desktop-connection/12).

**Comment by medusadigital** [comment]
issue seems to be that we have nuked ANGLE support by accident while upgrading to qt 5.10 on windows build environment.

it may also be possible that ANGLE ist still enabled, but needs some dll's.

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by LesterCovax** [comment]
@medusadigital Thanks for the info. TIL.

[Here's more information](https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL) on the differences between OpenGL and ANGLE for others that are interested.  One of the key advantages listed for ANGLE is RDP support.

**Comment by dEBRUYNE-1** [comment]
This particular issue is resolved in GUI v0.12.2.0: 

https://www.reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/

**Comment by dEBRUYNE-1** [comment]
+resolved
