### ISSUE TITLE
Is there a white theme before?

### ISSUE THREAD

**Issue by fionasit** [monero-project/monero-gui#1280]
My eye is not good in black on white mode, previous it is white on black mode, is there any option in gui to turn it back to white background and black text mode?

**Comment by dEBRUYNE-1** [comment]
There will be a light theme as well (using a similar design) in the future. Example screenshot:

https://i.imgur.com/ywyBtTY.png

**Comment by maddinthegreat** [comment]
**Please, please! Don't like that grufty theme**

**Comment by xmrdsc** [comment]
#2060
