### ISSUE TITLE
GUI glitch when waiting for block

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1282]
GUI version: v0.12.0.0
macOS 10.13.5 (17F35e)

Reproducibility: always

Steps:
Receive a transaction and wait for block.

What happened:
GUI glitch. Text falls out of bounds.

![screen shot 2018-04-06 at 18 30 59](https://user-images.githubusercontent.com/227442/38430164-25eec8f4-39c9-11e8-92da-c89738445203.png)

Expected result:
No glitch.

**Comment by xiphon** [comment]
https://github.com/monero-project/monero-gui/pull/1727

**Comment by dEBRUYNE-1** [comment]
+resolved
