### ISSUE TITLE
GUI glitch when resizing window to small size

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1283]
GUI version: v0.12.0.0
macOS 10.13.5 (17F35e)

Reproducibility: always

Steps:
Resize window to small size.

What happened:
GUI glitch.

https://www.dropbox.com/s/jqkhimvj25l5hy8/Monero%20GUI%20glitch%202.mp4?dl=0

Expected result:
No glitch.

**Comment by skftn** [comment]
It tries to switch to 'mobile mode' which is currently being worked on.

**Comment by dEBRUYNE-1** [comment]
Probably fixed by #1491.

**Comment by dEBRUYNE-1** [comment]
Can you check if this is still an issue in GUI v0.14.1.0?

**Comment by rex4539** [comment]
Unfortunately not. I'm not running `monerod` anymore. I use Cake Wallet instead.

**Comment by dEBRUYNE-1** [comment]
@rex4539 - Would you have some time to quickly test it though?

**Comment by rex4539** [comment]
Unfortunately not.

**Comment by xmrdsc** [comment]
This is still unfixed. Reproduce: make the window smaller. It jumps to 'mobile' mode.

**Comment by selsta** [comment]
Mobile view got removed.

+resolved
