### ISSUE TITLE
Monero GUI 0.12.0.0 GUI blurred white typeface

### ISSUE THREAD

**Issue by allegro101** [monero-project/monero-gui#1284]
Win 7 64 bit GUI works fine so far but white typeface against black background is blurred. Previous white background/black type was crystal clear. Is there an advanced setting which would make the type clearer?

![guinotclear](https://user-images.githubusercontent.com/24720449/38435843-ef712a24-39a0-11e8-812a-3627da153890.JPG)

**Comment by allegro101** [comment]
Launching GUI by start-low-graphics-mode,bat batch file I notice no difference. Type still blurred.

**Comment by pazos** [comment]
@allegro101: has your screen a resolution higher than 1920x1080?, which one?

**Comment by dEBRUYNE-1** [comment]
This particular issue is supposedly resolved in GUI v0.12.2.0: 

https://www.reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/

Could you give it a try?

**Comment by allegro101** [comment]
Tried GUI v0.12.2.0 issue still present as shown before.

**Comment by dEBRUYNE-1** [comment]
@allegro101 - Even with the `start-low-graphics-mode.bat` batch file?

**Comment by allegro101** [comment]
@dEBRUYNE-1  - Yes even starting GUI with the start-low-graphics-mode.bat batch file:

![moneroscreenshot](https://user-images.githubusercontent.com/24720449/42326217-856e1f6a-8036-11e8-911b-55e989dd582a.PNG)

Slightly better perhaps this is as good as it gets? I preferred the older white background BTW.

**Comment by dEBRUYNE-1** [comment]
That looks slightly better indeed. 

>this is as good as it gets?

Probably :-P

>I preferred the older white background BTW.

There will, most likely, be a white theme in v0.13.

**Comment by allegro101** [comment]
White theme option would be welcome as easier on the eyes. I also appreciate the separate command prompt window that GUI v0.12.2.0 launches by default.

**Comment by xmrdsc** [comment]
@allegro101 Is still an issue on the latest GUI version (0.14) for you?

**Comment by dEBRUYNE-1** [comment]
I am going to close this, as the author has not responded for several months.

**Comment by dEBRUYNE-1** [comment]
+resolved
