### ISSUE TITLE
GUI History Tabs Default Order...

### ISSUE THREAD

**Issue by juanpc2018** [monero-project/monero-gui#1285]
as a New user all those Tabs in History are very confusing....

Date from latest to oldest should be default...
Payment ID, Block Height, Amount, should be Hidden in Advanced mode.
like the Address inside Send...

very confusing for a New user.
if there is a mistake, you go crazy. LOL. Jajajajaja

Or the selected Tab should Magnify/Grow, & other Tabs font size should get a smaller & the Tab background darker, all white, very weird.

Also the Up & Down Arrows are confusing...
in Bitcoin is very easy to understand, because there is a point of reference, In & Out...

here Red Down Arrow does Not seem to Equal Sent. confusing.
should be replaced with a more intuitive less confusing icon, 
if you want to say Value Up or Value Down, should use a universal symbol (+) or (-).

but i think Sent & Received makes more sense.

or Arrows should be Backwards...
Red Up, Green Down.

from a Bitcoin user, this is very confusing.

Red Down is Redundant, like Water Wets.

**Comment by selsta** [comment]
Page was significantly redesigned, please open a new issue if you feel still have feedback.
