### ISSUE TITLE
GUI graphic overlay

### ISSUE THREAD

**Issue by ElectricSlacks** [monero-project/monero-gui#1288]
![monero bitchthing](https://user-images.githubusercontent.com/35742210/38453881-48b9546e-3a5d-11e8-9f2a-3627bf70e0f4.JPG)

Hello,
As you can see an opened ''Advanced' tab creates an overlay in the gui.
I am sure that this is easily fixed.
And its a small thing. no worries.

**Comment by pazos** [comment]
Also the flickable region should be dynamic based on the size of the menu.

I'm in for this issue

**Comment by jamescanningcooke** [comment]
Same prob

**Comment by skftn** [comment]
Fixed via #1289 #1290

+resolved
