### ISSUE TITLE
MacOS build require high performance graphics.

### ISSUE THREAD

**Issue by Axam** [monero-project/monero-gui#1301]
On Mac with 2 graphics cards GUI require high performance graphics.

Fix: include in Info.plist this option:
```
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
```

**Comment by skftn** [comment]
Nice one! Will test this later.

**Comment by skftn** [comment]
+enhancement

**Comment by skftn** [comment]
+easy

**Comment by pazos** [comment]
@Axam : could you check if https://build.getmonero.org/downloads/monero-wallet-gui-894b10e-osx-10.11.zip fix your problem? thanks
