### ISSUE TITLE
Misleading "not enough money" error message

### ISSUE THREAD

**Issue by mbg033** [monero-project/monero-gui#131]
Tested on public testnet, "transaction priority" = high, "privacy level" = max
![image](https://cloud.githubusercontent.com/assets/411612/20077359/1e118b88-a54d-11e6-8802-42524300d08b.png)

**Comment by medusadigital** [comment]
still unfixed, see : https://www.reddit.com/r/Monero/comments/65fv4c/problem_with_monero_gui_beta2_send/

**Comment by medusadigital** [comment]
+bug

probably resolved, i had no luck reproducing it.

this also comes from a time where the privacy slider went up to 100 afaik.

closing this here.

+resolved

**Comment by erciccione** [comment]
This appear to be solved. If it's not, please open a new issue

+resolved
