### ISSUE TITLE
Linux doesn't show Monero icon on Show Applications

### ISSUE THREAD

**Issue by cialu** [monero-project/monero-gui#1312]
Hi,
I have downloaded source of **monero-wallet-gui** (v0.12.0.0 - Lithium Luna) from here and installed it on **Linux Ubuntu 18.04** system with communitheme(the next Ubuntu theme in development). I compiled the code and moved the executable to `/opt` folder, then I made a `monero-gui.desktop` file in `/home/user/.local/share/applications/`.

This is the `monero-gui.desktop` file:

```
[Desktop Entry]
Name=Monero GUI wallet
Comment=Monero: the secure, private, untraceable cryptocurrency
Exec=/opt/monero/monero-wallet-gui
Icon=monero
Terminal=false
Type=Application
StartupNotify=true
```
                 
Everything went fine and all is working. The node connect itself to the network and the GUI wallet works like a charm. Just, one minor graphical issue.

The **monero-wallet-gui** application shows the correct icon on the dock when it's opened, but in 'Show Application' there's no Monero icon. I know that I specified `Icon=monero` and the default theme doesn't provide a Monero icon, so I also look into Monero folder to make a link to the right icon, but I found no icon file.

Here the monero-wallet-gui icon on the dock:
![monero-dock](https://user-images.githubusercontent.com/1382127/38720624-3f820afa-3ef7-11e8-98dd-0ecc438dd49f.png)

Here the wrong icon on 'Show Applications':
![screenshot from 2018-04-13 08-34-04](https://user-images.githubusercontent.com/1382127/38720639-4eb4e8d0-3ef7-11e8-8fb2-adc818c88554.png)

Is there a way to provide a Monero icon to link to?

~~Also I'm wondering, should I open an issue upstream to insert Monero (and crypto in general) icon in the default Ubuntu theme?~~ I also opened this [How about to insert Monero and Crypto icons in the theme?](https://github.com/snwh/suru-icon-theme/issues/41) on the next Ubuntu icons theme repository.

**Comment by pazos** [comment]
duplicate of #1165.

You'll need to copy the icon you want to /usr/share/pixmaps/monero.png

**Comment by cialu** [comment]
@pazos thanks. I have already placed an icon in the theme folder and it worked as your proposed solution. I also opened an issue upstream to insert the Monero icon directly in the standard Ubuntu icons theme.

**Comment by pazos** [comment]
@cialu: I'm glad it worked.

This issue is indeed related to #1165. This isn't about linux distros, because every linux distro out there is based on freedesktop and its [desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html).

So please close this issue, thanks :)

**Comment by cialu** [comment]
Ok, sure.
