### ISSUE TITLE
Transaction not appearing in |Monero GUI wallet 

### ISSUE THREAD

**Issue by tobyaj** [monero-project/monero-gui#1319]
Hi I'm wondering if anyone can help. Last week on the day of the monero update i sent a payment to changelly of litecoin to recieve monero at first the transaction failed because of the update( I think) and then a couple days later after being in contact with changelly customer service they said the payment had now been completed. However the payment hasn't appeared in my monero gui wallet, i'm using a remote node and I followed a guide changing the name of the file. to do full restart and resync but still nothing.I've followed another guide and confirmed i can see both the failed and completed transactions on the block chain but they're not in my wallet. I've signed into mymonero with the same key but the balance reads 0 on there too. I can pay 0.1XMR to import my transactions but i'm hesitant to pay as I'm unsure that will help. Any advice would be great, Changelly customer services can see the transaction so nothing else they can do. Cheers.

**Comment by skftn** [comment]
This issue tracker is specifically for technical issues with the GUI. Please re-post on /r/monero - where the community can answer your questions. Thanks!

**Comment by skftn** [comment]
+invalid
