### ISSUE TITLE
wallet created in v.012 cannot be opened with v.011

### ISSUE THREAD

**Issue by automag** [monero-project/monero-gui#1324]
When trying to open the wallet from v.012 with v.011 i get the message incorrect password.
v.011 finds the v.012 wallet.
How to fix this?

Also in v.012 there is no more public / private key display, but  a primary adress.
Please explain.

**Comment by skftn** [comment]
1. Pub/priv key can be viewed via a submenu under Settings. 
2. Wallets created in v12 cannot be opened in v11. You can restore it by seed, which you can retreive on the page from point 1

**Comment by skftn** [comment]
+resolved
