### ISSUE TITLE
Stuck at creating transaction

### ISSUE THREAD

**Issue by KonfuciousK** [monero-project/monero-gui#1327]
I've had issues with the newest release when using a remote node the transaction just stays stuck on creating. When running my own local node the synching is all over the place (from 500 blocks behind to 2 to 600 in 3 minutes) and the transaction takes about 15 minutes to get to confirmation screen, if at all. But it does go through fine if I confirm after that.

Is this a problem on my end?

Internet connection is fibre with <8ms pings, internet synched time etc.

**Comment by KonfuciousK** [comment]
Yeah I think it was a network or slow system problem. I've set up on a different PC altogether and no issues.  

It was a Dual Opteron originally but it's mining as well so probably what caused half the issues, just never had it happen on it before this version.

Thanks.

**Comment by dEBRUYNE-1** [comment]
I consider this particular issue resolved.

**Comment by dEBRUYNE-1** [comment]
+resolved
