### ISSUE TITLE
Transaction not appearing - I've followed all instructions!

### ISSUE THREAD

**Issue by rodoebri** [monero-project/monero-gui#1328]
Hi all.  I sent 8 Monero from my Binance account to my wallet about 12 hours ago.  It was the old wallet so since then I have upgraded to the new wallet, renamed my wallet so that it re-downloaded the wallet file and it is still not appearing.  I also tried verifying the transaction at https://xmr.llcoins.net/checktx.html and it is saying that my private key is invalid!

Here is the transaction provided by Binance:  https://moneroblocks.info/tx/38609776fddb5bf5fae9fefcc8999bd22e9707bcaa7be84c15f36f325415bfa5

The transaction appears to have gone through from Binance but at this point I am at a loss.  I am hoping it has not disappeared but am losing a bit of that hope. 

Any help would be appreciated!

**Comment by rodoebri** [comment]
P.S. I am using the GUI wallet monero-gui-win-x64-v0.12.0.0

**Comment by dEBRUYNE-1** [comment]
>and it is saying that my private key is invalid!

Are you sure you followed this guide correctly?

https://monero.stackexchange.com/questions/6137/how-do-i-as-a-recipient-verify-that-my-transaction-actually-arrived

**Comment by dEBRUYNE-1** [comment]
>I am using a local node and it says that both the wallet and daemon are up to date. 

Could you post the full output of `Show status` (on the `Settings` page of the GUI)?

**Comment by rodoebri** [comment]
Here you go:
Height: 1554457/1554457 (100.0%) on mainnet, not mining, net hash 549.96 MH/s, v7, up to date, 8(out)+2(in) connections, uptime 0d 0h 52m 58s

Height: 1554457/1554457 (100.0%) on mainnet, not mining, net hash 549.96 MH/s, v7, up to date, 8(out)+2(in) connections, uptime 0d 0h 55m 50s

Height: 1554457/1554457 (100.0%) on mainnet, not mining, net hash 549.96 MH/s, v7, up to date, 5(out)+0(in) connections, uptime 0d 5h 22m 17s

Height: 1554457/1554457 (100.0%) on mainnet, not mining, net hash 549.96 MH/s, v7, up to date, 5(out)+0(in) connections, uptime 0d 5h 22m 22s

Height: 1554457/1554457 (100.0%) on mainnet, not mining, net hash 549.96 MH/s, v7, up to date, 1(out)+1(in) connections, uptime 0d 7h 12m 0s

Height: 1554457/1554457 (100.0%) on mainnet, not mining, net hash 549.96 MH/s, v7, up to date, 1(out)+1(in) connections, uptime 0d 7h 12m 9s

**Comment by rodoebri** [comment]
Should I be worried?

**Comment by dEBRUYNE-1** [comment]
Your `Show status` output indicates that you're on the wrong (alternative) chain. Therefore, you should be able to resolve your issue with this guide:

https://monero.stackexchange.com/questions/7989/i-forgot-to-upgrade-from-cli-or-gui-v0-11-to-cli-or-gui-v0-12-and-as-a-result

Please note:

>As a general rule of thumb, for each day you synced after the fork height (1546000 or April 6) you have to pop 800 blocks. Thus, let's say you synced 10 days on the wrong (alternative) chain, you should use --pop-blocks 8000

Since we're 13 days after the scheduled network upgrade, you ought to use `--pop-blocks 10400`

P.S. I reckon aforementioned guide might be a bit convoluted. Therefore, if you need any assistance, feel free to shoot me a PM on Reddit:

https://www.reddit.com/user/dEBRUYNE_1/

**Comment by rodoebri** [comment]
Thanks!  Finally fixed it.  I had a few errors, realized Windows Firewall was still blocking a couple of Monero executables, but it's all in there.

Thank you again for your help!

**Comment by dEBRUYNE-1** [comment]
Good to hear and you're welcome :) 

+resolved
