### ISSUE TITLE
The '4' placeholder text in the 'Address' input could be misleading because subaddresses start with an '8'

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1332]
Quick fixes could be:

4.. / 8..
4.. or 8..
4.. 8..
Beginning with 4 or 8

**Comment by dEBRUYNE-1** [comment]
I'd prefer 4.. / 8..

+easy
+enhancement

**Comment by tficharmers** [comment]
This would also need to be changed on the 'Address book' tab/page.
