### ISSUE TITLE
GUI Wallet is not connected to daemon on Mac OS

### ISSUE THREAD

**Issue by guifalci** [monero-project/monero-gui#1334]
i upgraded Monero GUI wallet cannot connect to remote node.

![node](https://user-images.githubusercontent.com/34798255/39064468-e9e299f6-44ce-11e8-8815-adaa19726d80.jpeg)

if push connect botton nothing happens

**Comment by skftn** [comment]
FYI: I believe moneroworld DNS was having problems earlier (or still having problems).

**Comment by skftn** [comment]
+invalid
+wontfix

**Comment by guifalci** [comment]
today still have same problem with node!!

again my wallet not connected to daemon....wallet not show the right balance!!!

**Comment by skftn** [comment]
+wontfix

**Comment by skftn** [comment]
moneroworld is having issues.

**Comment by guifalci** [comment]
thank you…

how can have blockchain in my laptop I mean connected to local host?
if i connect to my local host show only the old balance….and not show the right balance after the fork.

please help me

**Comment by skftn** [comment]
Please re-post on [/r/monero](https://reddit.com/r/monero) - where the community can answer your question(s).

**Comment by dEBRUYNE-1** [comment]
@guifalci - Have you opened a thread on reddit where I could help you? If so, please post the link.
