### ISSUE TITLE
Wallet creation wizard: make the node page more consistent

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1338]
Right now it looks like this:

![0](https://user-images.githubusercontent.com/7106231/39084172-4dac6334-4571-11e8-9071-4d7093a0f2d0.png)

* Complement the first option's text: "Start a node automatically in the background **or use an already running local node** (recommended)", because if you already run the daemon, you don't want two instances of it to run. Even if that's impossible (it looks like it is), it can raise unneeded concern.

* Replace the tick boxes with radio buttons, so it's obvious that it's an either/or option.

**Comment by skftn** [comment]
+enhancement

**Comment by cryptochangements34** [comment]
Both #1387 and #1388 have been merged so I think this can be closed now

**Comment by mmbyday** [comment]
+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
