### ISSUE TITLE
cleanup folders. only have the executable in root folder and 1 or 2 subdirectories to make it easier for beginners

### ISSUE THREAD

**Issue by krtschmr** [monero-project/monero-gui#1363]
just introduced monero to 2 different friends who are not tech-savy. both had headaches with all the folders and files. one even asked me which file he needs to copy because he wants to delete all others.

suggestion:

having a folder structure where we only have the executable as a file in the root tree and all other files are in 1 (max 2) subfolder. 

    /monero-gui-v0.12.0.0
      - wallets (directory for our wallets)
      - monero (monerod, monerowalletcli, monerorpc and blockchainimport can be in there)
      - misc (all files that are now in root can go into )
      - monero-wallet-gui.exe

now it would be clear and easy for everybody to start with monero

**Comment by rbrunner7** [comment]
That "mess" of directories mostly comes from Qt and its deploy mechanism. Changing it would be probably dangerous and error-prone.

I don't think there is much to delete, most of those files are probably needed, and for the rest nearly impossible to prove conclusively that under no circumstances occuring while using the GUI wallet those files are needed. (Qt loads some files not already at startup, but dynamically when needed, as far as I know.)

IMHO the right way to make life easier for beginners is finally bringing the Windows installer into service that I built and that is waiting already for quite some time ...

**Comment by dEBRUYNE-1** [comment]
GUI v0.14.1.0 now contains a single executable and no other files (except for one DLL that is needed for the graphic fallback and a script that can be used as last resort (with respect to graphic fallback)). I am thus going to mark this as resolved.

**Comment by dEBRUYNE-1** [comment]
+resolved
