### ISSUE TITLE
Withdrew Monero XMR from Binance Exchange to my local Monero GUI wallet using wrong Payment ID

### ISSUE THREAD

**Issue by fintechlim** [monero-project/monero-gui#1371]
I used the Payment ID from Monero Wallet GUI that was generated from the wallet. Plugged that into the Binance Withdraw of XMR using the correct address. The transaction completed but no coins showed up in wallet. After emails with Binance they said I used the wrong payment ID but had the correct address and they gave me the correct Payment ID but the transaction already completed.

I can view the transaction and decoded it using the my private view key on MoneroExplorer and can see the transaction and correct amount of funds and showed "ouput match = true" please see attachment but 
[MoneroFoundLostTransaction.docx](https://github.com/monero-project/monero-gui/files/1975925/MoneroFoundLostTransaction.docx)
[MoneroFoundLostTransaction.docx](https://github.com/monero-project/monero-gui/files/1975929/MoneroFoundLostTransaction.docx)

But never showed up Monero GUI Wallet. I was told this would fix it but it didn't.

I have tried:
1) Created new wallet using same seed as old wallet using localhost sync
2) Created new wallet using same seed as old wallet using remote node.moneroworld.com  sync 
Nothing is working.

TX ID:   b2b2df0f1ae824a4d5eec82e212b7d5eb23a673eed2bb833afe38578546b5add
Wallet Payment Key Used (bad):   20197c09a0b58da9
My Public Send Address (good):  41ngmusSp7mbhWbdwWUEsj6bVSaaJQsh94LJdwVKUBRKD34ZYntaSDTAefzDAJo3jkPbk3b5r8QxLN2FVpRyRLsUDZ2Ycmr
Block Height: 1565673

Binance said I should have used this Payment ID: dee6dfa4a67f1b8e5b34f4b420506da32d2d1d4da0be47b4805fa5618c174f05

Amount: Completed        XMR    5.52529256         2018-05-03 13:48:52

Please Help!

**Comment by dEBRUYNE-1** [comment]
Could you post the full `Show status` output (on the `Settings` page of the GUI)? Also, what is the `Wallet creation height` (on the `Settings` page under `Debug info`)?

**Comment by dEBRUYNE-1** [comment]
@fintechlim - I first need to verify your full `Show status` output.

**Comment by fintechlim** [comment]
Here you go. I tried to send 0.5 XMR out to Kraken when I was in remote sync mode hung for a while then failed??? Kraken doesnt require a payment ID. Trying local mode now. Sincerely, Graham P. RiveraFinTech Limited 8(a)/SWaM/DBME13711 Solstice CloseMidlothian, VA 23113Tel: (804) 536-3200Fax: (804) 464-2439http://www.fintechlimited.com CONFIDENTIALITY NOTICE  The information in this email and any attachments may contain legally privileged, proprietary and confidential information that is intended for a particular recipient. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, retention or use of the contents of this e-mail information is prohibited. When addressed to FinTech Limited's clients or vendors, any information contained in this e-mail is subject to the terms and conditions in the governing contracts that are currently in place. If you have received this e-mail in error, please immediately notify us by telephone or by return e-mail, and delete the e-mail.

**Comment by fintechlim** [comment]
Cant do local mode funds disappeared???? Changing back to remote mode. Sincerely, Graham P. RiveraFinTech Limited 8(a)/SWaM/DBME13711 Solstice CloseMidlothian, VA 23113Tel: (804) 536-3200Fax: (804) 464-2439http://www.fintechlimited.com CONFIDENTIALITY NOTICE  The information in this email and any attachments may contain legally privileged, proprietary and confidential information that is intended for a particular recipient. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, retention or use of the contents of this e-mail information is prohibited. When addressed to FinTech Limited's clients or vendors, any information contained in this e-mail is subject to the terms and conditions in the governing contracts that are currently in place. If you have received this e-mail in error, please immediately notify us by telephone or by return e-mail, and delete the e-mail.

**Comment by dEBRUYNE-1** [comment]
>when I was in remote sync mode hung for a while then failed???

Have you tried using a different remote node?

>Cant do local mode funds disappeared????

Please ignore that for a bit and post the full `Show status` output whilst being in local mode.

**Comment by fintechlim** [comment]
Remote mode finally worked just slower, local mode does not. You can close the ticket and thanks for your help! Sincerely, Graham P. RiveraFinTech Limited 8(a)/SWaM/DBME13711 Solstice CloseMidlothian, VA 23113Tel: (804) 536-3200Fax: (804) 464-2439http://www.fintechlimited.com CONFIDENTIALITY NOTICE  The information in this email and any attachments may contain legally privileged, proprietary and confidential information that is intended for a particular recipient. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, retention or use of the contents of this e-mail information is prohibited. When addressed to FinTech Limited's clients or vendors, any information contained in this e-mail is subject to the terms and conditions in the governing contracts that are currently in place. If you have received this e-mail in error, please immediately notify us by telephone or by return e-mail, and delete the e-mail.

**Comment by dEBRUYNE-1** [comment]
+resolved
