### ISSUE TITLE
Unlock time is Visible when switch to wallet

### ISSUE THREAD

**Issue by burnssos** [monero-project/monero-gui#1403]
Windows x64 GUI Wallet 0.12.0

When staying in-app and you close one wallet and open another, if that wallet has recently received a transaction, it will show the balance unlock time prior wallet unlock to successful wallet password.

![monero wallet balance unlock time visible circled](https://user-images.githubusercontent.com/39074135/39959173-a034f446-55d3-11e8-9b60-f15bb371a2cc.png)

Does not appear to be a serious issue, however could raise concerns regarding privacy.

**Comment by dEBRUYNE-1** [comment]
I *think* this is similar to #1159
