### ISSUE TITLE
Documentation | Installation for ubuntu 18.04 x64

### ISSUE THREAD

**Issue by MrBob007** [monero-project/monero-gui#1405]
In order to build the monero-gui under Ubuntu 18.04, following UI dependencies are needed:

sudo apt install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-xmllistmodel qttools5-dev-tools qml-module-qtquick-dialogs qml-module-qt-labs-settings **qml-module-qtquick-controls2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel**

**Comment by pazos** [comment]
Thanks. The same dependencies are required for Ubuntu 17.10.

We should update instructions for debian distros since we require Qt5.7 and Ubuntu 16.04 & distros based on it (like linux mint 18.x) doesn't have that version.
