### ISSUE TITLE
some qml warnings

### ISSUE THREAD

**Issue by pazos** [monero-project/monero-gui#1407]
These are warnings that don't break the gui. They should be fixed in the long run, but seems easy. Pinging @skftn 

Self-explanatory:
qrc:///main.qml:1317: ReferenceError: mainFlickable is not defined
qrc:///components/InputDialog.qml:68: ReferenceError: bg is not defined
qrc:///components/TitleBar.qml:70:9: QML Image: Cannot anchor to an item that isn't a parent or sibling.

Other:
file:///opt/qt/5.10.1/gcc_64/qml/QtQuick/Controls/ApplicationWindow.qml:240:9: QML ContentItem: Binding loop detected for property "implicitWidth" **in components/DatePicker.qml**

qrc:///pages/Receive.qml:392: Error: Insufficient arguments (adding a new subaddress with o without a valid label)

**Comment by skftn** [comment]
Will fix them in https://github.com/skftn/monero-core/tree/redesign-settings

**Comment by erciccione** [comment]
+resolved
