### ISSUE TITLE
The "privacy level" slider doesn't convey meaningful information

### ISSUE THREAD

**Issue by antanst** [monero-project/monero-gui#142]
Seasoned Monero users that know what a mixin is, have no indication of what mixin value corresponds to a specific counter location.

New Monero users don't know what to choose there and there's no information provided to help them.

May I suggest that at least the applied mixin value is shown? This way a user can at least google "mixin" to find out what it's all about, and experienced users have sufficient information.

**Comment by dEBRUYNE-1** [comment]
FWIW, mixin is shown in the confirmation message.

**Comment by medusadigital** [comment]
is confirmation message good enough? personally i would prefer having it somewhere visible too, maybe even as changeable field, so the user can add their own mixing ? 

with ringCt, much higher mixing values will be possible before reaching the transaction size limit. 

or is the slider enough for "normal" users and we should close this?

**Comment by antanst** [comment]
Confirmation message isn't informative imho. The user doesn't know what changes when he moves the slider. A simple label below the slider that prints the active mixin should be enough I guess.

**Comment by medusadigital** [comment]
+enhancement

would prefer to not do this via Tiptext (also because this can be turned off, and maybe will be by default)

**Comment by leafcutterant** [comment]
Currently, the chosen "privacy level" is shown in parentheses.

![mixin](https://user-images.githubusercontent.com/7106231/37039839-b758797c-2158-11e8-9adf-dc0550368f34.png)

BUT I think it's very hard to notice that it changes with moving the slider. I suggest placing it after a semicolon and using a larger font size for the value, e.g.:

Privacy level (ringsize): ## 5

Also, the "Transaction cost" label on the far end of the slider is confusing. If I wouldn't know what it means, I' think the slider is a trade-off between privacy level and transaction cost. (This  would make people always use the lowest actual privacy level.)

**Comment by erciccione** [comment]
The slider has been removed. Closing this

+resolved
