### ISSUE TITLE
Monero GUI v0.12 behaves as "always on top" window in Xubuntu 16.04.4 in VirtualBox

### ISSUE THREAD

**Issue by bananajamma** [monero-project/monero-gui#1431]
## Information and Steps to Reproduce

On Xubuntu 16.04.4, when first opening the GUI v0.12 [build 201](https://build.getmonero.org/builders/monero-gui-ubuntu-amd64/builds/201), the file dialog is behind the Monero GUI, which behaves as "always on top", over any other GTK dialog, action menu, or application.

![monero-always-on-top](https://user-images.githubusercontent.com/37884555/40571187-6fdf7c46-6062-11e8-8b0b-7fdb9ca3c178.png)

The Monero GUI appears to be "frozen".

A work-around is to right-click the application on the xfce4-panel, and select "move" to gain access to the file dialog:

![monero-xubuntu-move-workaround](https://user-images.githubusercontent.com/37884555/40571186-6fd62db2-6062-11e8-84c6-acb3e0f4a08d.png)

## System Information

Running inside of VirtualBox 5.2.12:

```
bj@xubuntu$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```
```
bj@xubuntu$ dpkg -l "*ubuntu-desktop" |grep ii
ii  xubuntu-desktop 2.206        amd64        Xubuntu desktop system
```
```
bj@xubuntu$ xfce4-about --version
xfce4-about 4.12.1 (Xfce 4.12)

Copyright (c) 2008-2015
	The Xfce development team. All rights reserved.

Please report bugs to <http://bugzilla.xfce.org/>.
Translators list from 2015-03-15 16:44:46.
```

```
bj@xubuntu$ uname -a
Linux xubuntu 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dEBRUYNE-1** [comment]
Similar to #1096 and #1097 it seems.

**Comment by skftn** [comment]
Thanks for reporting. Please note Monero-gui uses QT, not Eectron, so you wont find it there ^^

Will look into this at a later stage, unless someone else does.

**Comment by bananajamma** [comment]
@skftn egg on my face.  I made an assumption based on the UI, I should have looked closer at the source code.  Thanks for pointing out the error in my assessment.  I'll look into some QT bugs and see if I come with anything similar as well.

**Comment by bananajamma** [comment]
Ubuntu 18.04 has a similar issue in GNOME.  However, the work-around doesn't work, the file open dialog appears to move with the application itself, so it's never able to retrieve focus.

![ubuntu-18 04-monero-bug](https://user-images.githubusercontent.com/37884555/40580637-86964fa6-6110-11e8-8016-af438dc40fce.png)

I also tried other qt applications in XFCE on 16.04.4, keepassx (qt4) and phototonic (qt5.5).  These did not have the z-order issue.

Please let me know if there are any test cases you'd like me to try.  Thanks.

**Comment by skftn** [comment]
Could you try a more recent build and verify? https://build.getmonero.org/builders/monero-gui-ubuntu-amd64/builds/441

**Comment by bananajamma** [comment]
I was able to resolve the issue in both 16.04.4 and 18.04 by disabling "3d acceleration" in my VirtualBox VM settings.  Edited the issue title to specify VirtualBox now, as I'm not sure if this is strictly related to the other bugs, or not.  It could be OpenGL related/video driver issues.

The bug is still reproducible with build 441 in VirtualBox on either version of [X]ubuntu when "3d acceleration" is enabled.

I'd like to add that I've noticed focus can still given to the application behind the Monero GUI, I could click through to the "browse", or "cancel" buttons if I know where they were behind the splash screen where you select a wallet file to open.

**Comment by pazos** [comment]
@bananajamma : mmmm interesting bug. Can you reproduce this without custom decorations?

Vbox->3daccel->settings->disable custom decorations. I wouldn't expect the window on top.

**Comment by bananajamma** [comment]
Sorry @pazos, I don't see that option anywhere in VirtualBox, or the OS Settings.  Can you clarify?

**Comment by pazos** [comment]
@bananajamma: thanks for the feedback.

If you are still interested in running the gui without disabling experimental HW accel on VBox you can force software render for the gui with `QT_OPENGL=software ./monero-wallet-gui` from an open terminal. This should fix your problem, since it forces the same behaviour for monero-wallet-gui as running it without HW accel.

**Comment by dEBRUYNE-1** [comment]
@bananajamma - Can you check if this still happens with GUI v0.14.1.0?

**Comment by dEBRUYNE-1** [comment]
@bananajamma - ping.

**Comment by SamsungGalaxyPlayer** [comment]
No updates from the user since July 2018, please close.

**Comment by dEBRUYNE-1** [comment]
+resolved
