### ISSUE TITLE
History page becomes unresponsive when too much txs

### ISSUE THREAD

**Issue by Lafudoci** [monero-project/monero-gui#1433]
I have a stagenet wallet with countless received txs. Clicking on history page freezes the whole GUI program.  I believe it's caused by displaying too much txs. The default behavior is that the history list shows all txs at opening. Maybe we could just show the last few txs and have "load more" or "next page"?

**Comment by skftn** [comment]
For my perception, could you estimate how many txs that wallet has?

You are correct, that page should be paginated.

+enhancement

**Comment by Lafudoci** [comment]
I guess there are about 7000 txs

**Comment by selsta** [comment]
#2025 

+resolved
