### ISSUE TITLE
Use radio buttons (like with daemon mode) for the export wallet feature

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1434]
Thinking about consistency.

![screen shot 2018-05-26 at 14 01 45](https://user-images.githubusercontent.com/23356013/40725085-6da36922-641a-11e8-92f2-27ea3e439227.PNG)

![screen shot 2018-05-30 at 15 04 53](https://user-images.githubusercontent.com/23356013/40725253-d7ed293a-641a-11e8-943d-20b4f0cf4732.PNG)

**Comment by erciccione** [comment]
+resolved
