### ISSUE TITLE
Ledger not detected on Windows v0.12.1 GUI

### ISSUE THREAD

**Issue by philkode** [monero-project/monero-gui#1435]
Just built v0.12.1 GUI from source on Windows and can't open an existing, known working ledger wallet file. The Ledger wallet file was created on v0.12.1 CLI on the same machine.

The error given by the GUI is:
`Couldn't open wallet: device not found: Ledger`

This is the same error that v0.12.0 CLI gave on Windows when it couldn't connect to the smartcard service at all. If it can interface with that then it gives a more detailed error message.

Update: the compilation-time error given is:
`Could NOT find PCSC (missing: PCSC_INCLUDE_DIR)`

**Comment by dEBRUYNE-1** [comment]
This is resolved with https://github.com/monero-project/monero/pull/3886

+resolved
