### ISSUE TITLE
Add explicit option for choosing Mainnet on Welcome to Monero! in gui wallet

### ISSUE THREAD

**Issue by hvr1** [monero-project/monero-gui#1436]
Enhancement: Add option for choosing Mainnet above Testnet and Stagenet. At the moment double clicking either will enable mainnet. However it would be more intuitive to have this as an explicit option.

![monero gui](https://user-images.githubusercontent.com/39798404/40780732-7efbb140-64ea-11e8-8070-7a7e5fc02ba1.PNG)

**Comment by skftn** [comment]
+enhancement

**Comment by baryluk** [comment]
Even better remove both all options, and require to use a command line flag or entry in the config file. This is not something normal user needs to know or accidentally select.

**Comment by mmbyday** [comment]
+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
