### ISSUE TITLE
[Minor design] History > Tab sizes and visual noise

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#144]
# Tab sizes
I think these could be sized better. The 'Amount' tab being too wide for example. I would say that if possible to size them to fit their content.

# Order toggles
I think these add visual noise to the feature. It would be nice to only have one arrow per tab that alternates up/down based on the state. Also to hide the arrow when the tab isn't active.

This might help with the minimised view as I noticed that the 'Amount' tab is off-screen.

Here's a quick mockup of my thoughts.
![screen shot 2016-11-10 at 15 33 20](https://cloud.githubusercontent.com/assets/23356013/20182861/27b2421c-a75b-11e6-93ce-4d1951c4679f.PNG)

**Comment by erciccione** [comment]
GUI has changed theme. This is not meaningful anymore

+resolved
