### ISSUE TITLE
[BUG] if we change transaction priority it will change back to default if we change the tab

### ISSUE THREAD

**Issue by krtschmr** [monero-project/monero-gui#1453]
- change priority
- go on receive tab
- go on send tab
- priority is back to default

**Comment by pazos** [comment]
hey, AFAIK this is the intended behaviour, not a bug. You fill the form and send a payment, next time you'll do that again. Almost all the form items are empty by default and the priority is, errrr, default too.

**Comment by krtschmr** [comment]
@pazos 

if i fill in an address, then change the tab, then go back, the address is still in. 

i just tested, literally *everything* is persistent, except the priority. doesn't make sense.

**Comment by cryptochangements34** [comment]
I agree this sounds more like a bug. It doesn't make much sense for the address, amount, payment id, etc to all be somewhat persistent while the priority always gets reset.

**Comment by pazos** [comment]
err, in that case we can do:

1. wipe all values on page changed.  **or**
2. keep all stuff as is and add a clean button to wipe all form data manually if the payment is not sent( ie: wipe all lineEdits and set combobox index to 0)

**Comment by krtschmr** [comment]
wipe it after a transaction was successfully send. unless it's send, keep whatever we did.

**Comment by erciccione** [comment]
+hacktoberfest
