### ISSUE TITLE
UI - when using bootstrap node, the status bar should show status of local daemon

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-gui#1462]
not the remote daemon.

**Comment by dEBRUYNE-1** [comment]
Isn't the point of the bootstrap node that the user is able to use the wallet before his local daemon is synced? If the status bar displays the status of the *local* daemon, the user might think his wallet is not ready to be used yet.

**Comment by Gingeropolous** [comment]
Well, then it should indicate that it is showing the remote node sync status (which is kinda silly, because a remote node has to be 100% to be usable).

how will the user know how close their own node is close to 100% sync then?

**Comment by Gingeropolous** [comment]
Obviously the solution is another progress bar.

**Comment by stoffu** [comment]
@Gingeropolous Currently the only way to know the status of the local daemon is by the `status` command in the daemon console.

**Comment by dEBRUYNE-1** [comment]
@stoffu - Simply pressing `Show status` (on the `Settings` page) will provide a status overview as well.

**Comment by qubenix** [comment]
#1216

**Comment by Realchacal** [comment]
This issue is included in #2304. I'd recommend closing this one.

**Comment by Gingeropolous** [comment]
yep, #2304 addresses this.
