### ISSUE TITLE
source contains PNG file with embedded non-free ICC profile

### ISSUE THREAD

**Issue by jonassmedegaard** [monero-project/monero-gui#1464]
The file <lang/flags/denmark.png> contains an embedded color calibartion profile which is copyright Adobe and lacks a free license.

Please simply strip the ICC profile: It is highly unlikely needed. More information e.g. at <https://github.com/monero-project/monero/issues/3944>

**Comment by erciccione** [comment]
Thanks. Fixed in #1466
