### ISSUE TITLE
error bild win 64

### ISSUE THREAD

**Issue by laricoins** [monero-project/monero-gui#1475]
hi.
pls say list  pkg to way bild application on win 64
--------------------------------------------
i'm use  MSYS2
1 step 
pacman -S mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium
2 step
pacman -S mingw-w64-x86_64-qt5
3 step
pacman -S git
4 step
git clone https://github.com/monero-project/monero-gui.git
5 step
cd monero-gui
./build.sh

and give error

pls list version pkg to succes bild from repo (example http://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/)
via
FROM 
pacman -S mingw-w64-x86_64-qt5 
TO 
```
wget -c http://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/mingw-w64-x86_64-qt5-5.8.0-2-any.pkg.tar.xz
pacman -U mingw-w64-x86_64-qt5-5.8.0-2-any.pkg.tar.xz
```

need all pkg list version  to good bild.

**pls 
type
```
cd /var/cache/pacman/pkg
ls
```
and post list file**

Thancks

**Comment by dEBRUYNE-1** [comment]
I am doing some housekeeping and closing all old build relates issues, as they are probably not relevant anymore.

**Comment by dEBRUYNE-1** [comment]
+resolved
