### ISSUE TITLE
wallet not use/known https connect to the node!?

### ISSUE THREAD

**Issue by minzak** [monero-project/monero-gui#1480]
I run my own monero node and it works wit my mobile wallet in usual http mode.

I use node as backend with nginx.
And i see that wallet not use or can't use https, when i use https on nginx.
It is something wrong in my wallet? Or wallet still weak?

![image](https://user-images.githubusercontent.com/12154217/42104267-9972604a-7bd4-11e8-8a86-371cf659cf3d.png)

**Comment by selsta** [comment]
By default the GUI will connect using SSL if the daemon has --rpc-ssl auto / enabled.
