### ISSUE TITLE
Need little correct form size or wrap or else.

### ISSUE THREAD

**Issue by bizlevel** [monero-project/monero-gui#1481]
using ..... what? 

![photo_2018-06-29_20-27-08](https://user-images.githubusercontent.com/12154217/42105939-e1de8d12-7bda-11e8-88b0-6522081db120.jpg)

**Comment by cryptochangements34** [comment]
That looks like monerujo, certainly not this wallet. You are likely looking for m2049r/xmrwallet

**Comment by bizlevel** [comment]
@cryptochangements34  Thanks.
