### ISSUE TITLE
Decimal place not working in Send Amount

### ISSUE THREAD

**Issue by ludachris9000** [monero-project/monero-gui#1483]
Unable to send a fraction of XMR via Send/ Amount. Decimal not operational.

macOS 10.13.5
GUI v0.12.2.0

**Comment by dEBRUYNE-1** [comment]
What does "Decimal not operational" mean here? Also, could you try a comma?

**Comment by ludachris9000** [comment]
Actually nothing other than numbers will enter into the "Amount" box.
example.  Send/ Amount .5 XMR will not input I can only input 5
