### ISSUE TITLE
(UI/UX) Hide Stagenet and testnet radio's on GUI launch in advanced options link

### ISSUE THREAD

**Issue by Electricsheep01** [monero-project/monero-gui#1493]
On the create a new wallet page when launching the GUI the stagenet and testnet radios should be hidden by default in an advanced options dropdown link (on the same page). 

I've noticed several people confused by these options being present. Hiding them would alleviate some confusion users have and slightly improve UI/UX of the GUI.

**Comment by dEBRUYNE-1** [comment]
See #1452.
