### ISSUE TITLE
Monero GUI won't launch (v0.12.2.0)

### ISSUE THREAD

**Issue by heslorb26** [monero-project/monero-gui#1499]
This release won't run at all for me. The process appears in taskmgr for a split second and immediately closes. Trying to run low graphics mode results in the same problem.

monero-wallet-gui.log is attached

[monero-wallet-gui.log](https://github.com/monero-project/monero-gui/files/2175720/monero-wallet-gui.log)

**Comment by skftn** [comment]
See #1500

**Comment by dEBRUYNE-1** [comment]
Please see:

https://reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/e21xnyd/

**Comment by heslorb26** [comment]
Installing to a clean folder fixed the issue, many thanks!
