### ISSUE TITLE
[Proposal] Change "Default" to "Automatic" for Transaction Priority

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#1509]
This change was initially proposed by smooth, in light of this discussion: 

https://www.reddit.com/r/Monero/comments/8yvts5/kudelski_security_completed_their_bulletproof/e2ex5be/

"Automatic" better conveys the expected behavior than "Default" and therefore it would be prudent to switch to this term.

**Comment by medusadigital** [comment]
good idea

**Comment by jonathancross** [comment]
Thanks for the clarification @stoffu 
Seems this can be closed though given "That said, the GUI is primarily intended for novice users who will never touch the CLI, so I think it's fine to replace the text." -- correct?

**Comment by dEBRUYNE-1** [comment]
Resolved with #1510.
