### ISSUE TITLE
[Bug] Suddenly returns to initial wizard when pressing ESC in History's detail window

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero-gui#1512]
https://streamable.com/68158

The first time I clicked on the "?" icon, I closed the window normally by clicking "OK". The second time I opened the tx details window, I pressed the Esc key, and somehow the window size shrunk a bit, and then after clicking "OK" I was back at the initial wizard screen.

**Comment by skftn** [comment]
+bug

**Comment by dEBRUYNE-1** [comment]
+resolved
