### ISSUE TITLE
[CriticalЕrror / Fraud] Transaction amount invalid

### ISSUE THREAD

**Issue by candro** [monero-project/monero-gui#1519]
Attention, in the latest version (0.12.2.0) Monero Gui for Windows has a critical error that allows an attacker to deceive you. Briefly, in the transaction history shows the amount of 20XMR, and in fact, 10XMR has arrived.

The balance is increased by 10, if you do a transaction check, then it also writes 10, but in the history the transaction has a value of 20.

**Comment by dEBRUYNE-1** [comment]
This issue is resolved in GUI v0.12.3.0, which should be out soon.

**Comment by dEBRUYNE-1** [comment]
+resolved
