### ISSUE TITLE
[PROPOSAL] Translations directory could be a git submodule

### ISSUE THREAD

**Issue by skftn** [monero-project/monero-gui#1520]
### what

Move `translations/` to it's own submodule.

### why

- Translation related issues/PRs will be detached from the monero-gui repo. This will create more breathing room for both parties.
- When it is its own repo, one may tailor it specifically for translations and provide documentation more effectively. Such a setup would be more comprehensible for GIT beginners, which translators often are **
- It could save luigi some merge work as @erciccione (or whoever would manage the repository), works independently.
- PRs will be merged faster**

** citation needed :-P

## cons

- For security, must ensure that only `*.ts` files will be modified during contributions. 
  - If necessary; an extra step could be taken that during the build process of `monero-gui` that removes any file that does not end with `(ts|md)`. 
- More moving parts in `monero-gui`. However, `monero` is already a submodule so adding one more should not be a problem.

All say aye' in favor.

```
< cryptochangement> I think that making translations a submodule is an excellent idea
```

**Comment by skftn** [comment]
I dont think anyone actually cares, closing :-P

**Comment by erciccione** [comment]
Sorry i didn't have time to write a proper answer, will do it today. (i think it's a good idea, but i have some dubts)
