### ISSUE TITLE
balance is zero  

### ISSUE THREAD

**Issue by whenswineflu** [monero-project/monero-gui#1526]
no log ?

**Comment by dEBRUYNE-1** [comment]
Use:

https://monero.stackexchange.com/questions/6640/i-am-missing-not-seeing-a-transaction-to-in-the-gui-zero-balance

**Comment by whenswineflu** [comment]
ahh I thought would be hearing from you yeah I tried that few times my issue been on going and did start at the fork I am new monero not crypto  so that did work and my funds show up as I was learning wallet got closer to sum  eg first time was 3 /56  I sync with remote node would go back to 0 so start over from mnemonic seed 25 word and my .bitmonero added up with new gui wallet names each time  balance got closer to the sum same wouldent let me send out  and remote node 0 out so del the .bitmonero folders   I started with gui 0.12.1.0  didnt have much luck when 0.12.2.0  came out started  and I got all my funds started having probs with hdd  old  and full hdd I didnt like was taking to long    bought new and sdd  and hdd  i,m running windows 10 insiders build ![screenshot 128](https://user-images.githubusercontent.com/25366386/43360954-ace2d02e-9277-11e8-92ae-db23c6bf06c6.png)

**Comment by whenswineflu** [comment]
yes right now nothing working Win32/CoinMiner  flag as trojan

**Comment by whenswineflu** [comment]
went back to 0.12.0 same no coins

**Comment by whenswineflu** [comment]
going to read the log see whats up

**Comment by stevesbrain** [comment]
So did you ever add an exception for 0.12.3 and run that, or not?

**Comment by whenswineflu** [comment]
yes  for proof date 6/16/2018 June ur right well went though troubleshooting steps and possibly resyncs wallets when I stated I used hdd took 4-5 days each time did that 3-4 times upgraded to ssd takes 30hrs I'm usually able to solve my own problem's im not new to crypto have good understanding now I new to monero that took time for me to learn then I hit forums  dEBRUYNE  was very helpful then one day in July finely gave up kind of embarrassing for me had to be done wasn't to worried about time  lol balance in that pic is about half the sum pic was before issue  had to take a break so I could regroup and be here now did a fresh resync 0.12.3 is at  1572437/1636509 trying log level 2 post log

**Comment by whenswineflu** [comment]
![screenshot 149](https://user-images.githubusercontent.com/25366386/44001797-3396f82c-9ded-11e8-8469-363d76daa248.png)
![screenshot 151](https://user-images.githubusercontent.com/25366386/44001803-44098198-9ded-11e8-8606-edeb0eb5130c.png)
![screenshot 150](https://user-images.githubusercontent.com/25366386/44001808-55343dbe-9ded-11e8-8e4d-05abc49de51a.png)

**Comment by whenswineflu** [comment]
<img width="960" alt="2018-06-16" src="https://user-images.githubusercontent.com/25366386/44001840-20c1d478-9dee-11e8-88e3-f66179045a20.png">

**Comment by whenswineflu** [comment]
the last pic is old  refence/proof

**Comment by whenswineflu** [comment]
whats best way I can post log ?

**Comment by whenswineflu** [comment]
![screenshot 152](https://user-images.githubusercontent.com/25366386/44002388-8833917a-9df6-11e8-8cb4-48d51ada368f.png)

**Comment by whenswineflu** [comment]
![screenshot 154](https://user-images.githubusercontent.com/25366386/44220115-911f8980-a132-11e8-8c87-1ebdf555e1c4.png)
  what should I do with p2p .bin  should remove or use my windows-insiders ability to run Subsystem for Linux

**Comment by dEBRUYNE-1** [comment]
@whenswineflu - Apologies for the late response. Did you perhaps manage to resolve your issue in the meantime?

**Comment by whenswineflu** [comment]
unfortunately no haven't given up lol was using cmdlets got some different moderod responses along few hello world tinkering thought had something  so went to visual studio not aloud wouldent let me was funny

**Comment by whenswineflu** [comment]
ok so I did each step 
 Exit the GUI, but keep the daemon running.
Browse to the directory your wallet files are located (Documents\Monero on Windows | ~/Monero on Linux and Mac OS X). 
Rename <wallet-name> (the file without extension) to <wallet-name>-old.
Restart the GUI. This will trigger a wallet refresh from scratch, which shouldn't take longer than 30 minutes. 
Once it states Connected (in the left bottom) you should see funds.

didnt work done it 2 different ways same thing ground zero opens back to  whats  Language and keys my guess renaming simple like that moves it thats not good   

starting  outside the box ideas lot of your command are mixed that is easy to do when covering different shells is fine i get it is cached .keys and like .NET stuff have to remove key when do that will say need a admin funny when user is the admin and even if  simply del hidden file some how saves it agents admin and user wish   after sync up this time around want do it right in powershell  this cmdlet in the ballpark 

  [ https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-6 ](url)

**Comment by dEBRUYNE-1** [comment]
@whenswineflu - Have you tried restoring from the 25 word mnemonic seed in conjunction with a remote node (instead of your own (local) node)? It could be that (part of) your blockchain is corrupted. Make sure to set a proper restore height:

https://monero.stackexchange.com/questions/7581/what-is-the-relevance-of-the-restore-height

In addition, you can use `node.moneroworld.com` with port `18089` as remote node.

**Comment by dEBRUYNE-1** [comment]
Author has not responded to my last question / suggestion. I therefore am going to close this issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
