### ISSUE TITLE
Can't connect to na.node.moneroworld.com as remote node when using Ledger

### ISSUE THREAD

**Issue by aaronjolson** [monero-project/monero-gui#1533]
I just downloaded the new 12.3 lithium luna version of the Monero Wallet GUI. I went through the wizard, selecting set up hardware wallet, everything appeared to be working. However I don't have room on my machine to download the entire chain. I usually just use a remote node. In this case, trying to use the default  na.node.moneroworld.com

 1. I go to settings 
 2. I select remote node
 3. click connect

Then the key scrolling across the screen of the Ledger freezes. The ledger device becomes completely unresponsive. The bottom section of the GUI says that the daemon is synchronized, the "wallet blocks remaining" says all 15******* remaining, all grey bar, it also doesn't move.

If I click around in the GUI, say from the settings tab, up to the send or receive tab, the network status changes to disconnected.

Any ideas on how to fix this? Is this a known issue? 
Any other info I could provide that would be helpful?

I am running on Windows 10.
If I close the Monero GUI the Ledger goes back to scrolling and behaving normally immediately. 

Someone suggested I try a different node.
I tried node.xmrbackb.one at port 18081,
When I try to connect to that one I get a bit different behavior

The wallet blocks remaining says waiting for daemon to sync. The daemon blocks remaining is stuck at 23411. The ledger screen does not freeze though, which is encouraging?

**Comment by dEBRUYNE-1** [comment]
What did you use as `Restore height` upon generating the Ledger Monero wallet?

**Comment by aaronjolson** [comment]
1580000, also I set the subaddress-lookahead to 3:200

**Comment by dEBRUYNE-1** [comment]
@aaronjolson - Could you try to redo the Ledger wallet creation process with the parameters of [this guide](https://monero.stackexchange.com/questions/9901/how-do-i-generate-a-ledger-monero-wallet-with-the-gui-monero-wallet-gui) and the `node.moneroworld.com` (port 18089) remote node?

**Comment by dEBRUYNE-1** [comment]
Author has not responded to my suggestion. I therefore am going to close this issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
