### ISSUE TITLE
Ledger Nano S Freeze

### ISSUE THREAD

**Issue by wojtasss** [monero-project/monero-gui#1536]
1. Close Monero Wallet GUI
2. Ledger Nano S is in locked state
3. Launch Monero Wallet GUI, without unlocking Ledger Nano S
4. Click continute
5. Ledger Nano S freeze in locked state, also Wallet GUI then is not syncing

Xubuntu 18.04
Monero Wallet GUI v0.12.3.0 (Qt 5.7.0)

**Comment by dEBRUYNE-1** [comment]
Did you close the Monero GUI wallet after or before exiting the Monero Ledger *App*?

**Comment by dEBRUYNE-1** [comment]
The user has not responded to my question. I therefore am going to close this issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
