### ISSUE TITLE
Button becomes unusable after clicking

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero-gui#1548]
https://streamable.com/qy8da

Switching to a different tab and coming back to the Send tab makes the button enabled again.

**Comment by stoffu** [comment]
Hmm, looks like this issue applies to everywhere using StandardButton: https://streamable.com/8mqx4

And the cause seems to be on my side, because I get the same issue even when I checkout v0.12.3.0 tags on both monero-gui and monero. FWIW the release binary works just fine for me. I remember the binaries I built some time ago not having this issue. I must have done something to my build environment, but I don't know what...

> QMake version 3.1
Using Qt version 5.11.1 in /usr/local/Cellar/qt/5.11.1/lib

**Comment by mmbyday** [comment]
+resolved
by #1791

**Comment by dEBRUYNE-1** [comment]
+resolved
