### ISSUE TITLE
Demon log issue

### ISSUE THREAD

**Issue by wojtasss** [monero-project/monero-gui#1549]
When I type any command and press enter, scroll is going to start of log and I need scroll down to see command result it is really annoying

Monero Wallet GUI v0.12.3.0

**Comment by dEBRUYNE-1** [comment]
Can you check whether this is still an issue with GUI v0.14.1.0?

**Comment by dEBRUYNE-1** [comment]
I am going to close this as (i) the author did not respond and (ii) this is fixed in GUI v0.14.1.0 as far as I know.

**Comment by dEBRUYNE-1** [comment]
+resolved
