### ISSUE TITLE
Add a white border to QR codes when you save them as images

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1557]
Currently, there is a white border in the GUI. But if you save the QR code as an image, the border isn't saved with it and is difficult to scan depending on where the QR code is saved and then viewed. As mentioned here:

https://www.reddit.com/r/Monero/comments/9e2r45/make_saving_qr_images_great_again/

**Comment by erciccione** [comment]
+hacktoberfest

**Comment by skftn** [comment]
+resolved
