### ISSUE TITLE
Discussion: integrating approved FFS proposals into the GUI

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#1560]
I would like to start a discussion to see if there is any interest in the community/developers on creating a tab in the GUI indicating the current proposals awaiting funding in the FFS.

I understand that this would necessarily imply an interaction of the software with an external entity (server where FFS is hosted). This interaction should be limited in the simple reading of a JSON file containing the current approved proposals. I admit I do not know to what degree this can be dangerous to the software (perhaps by injecting malicious code via this file?). If this is a deal breaker because it adds an attack vector, then it's completely understandable to not add it.

That being said, it seems to me that integrating the GUI wallet with the FFS would increase the visibility of these proposals and would likely induce more users of the Monero network to participate in community actions.

**Comment by skftn** [comment]
It's a good idea, like #1484, but connections should most definitely go through Kovri. Another option is to explicitly opt-in on such a feature in the settings, but I'm not sure how many people would bother to manual enable it.

**Comment by wqking** [comment]
Re-post my comment on Reddit here.  
I suggest it's split to two layers,
Layer 1, backend API. Some REST API to list/fund an FFS.
Layer 2, the front end. For official wallet, it's the funding tab, but other wallets/websites are free to integrate it using Layer 1.

**Comment by selsta** [comment]
FWIW Feather wallet does this. We decided a while ago that the official GUI should not integrate external things like CCS proposals. If someone has different opinions, please comment here and I can reopen the issue.
