### ISSUE TITLE
Clicking "Sweep Unmixable" on gui crashes program on windows

### ISSUE THREAD

**Issue by BigslimVdub** [monero-project/monero-gui#1567]
Windows 10
Monero GUI release v.0.12.3
Aeon GUI release v.012.5
Issue repeatable 4 times In a row. Open GUI, login to wallet, select "sweep unmixable" and GUI locks up. Click anywhere In the GUI and program crashes and windows exits the program.

**Comment by maogo** [comment]
Yes ,i have same issue.GUI  v.0.12.3

**Comment by dEBRUYNE-1** [comment]
Can you check whether this is still an issue with GUI v0.14.1.0?

**Comment by BigslimVdub** [comment]
I will when I get a chance.

**Comment by dEBRUYNE-1** [comment]
Thanks.

**Comment by BigslimVdub** [comment]
Ok so I check with 14.1 GUI release on Windows 10 and when selecting "sweep unmixable" the gui hangs up and then windows prompts the "gui not responding" error prompt but before I could click "close monero-gui", the GUI sent me to the screen "Error-no unmixable outputs to sweep" and gui function returned to normal. 

So at this point, I would say that it is working properly as performance has enhanced and selecting this does not totally crash the gui like before. I am testing this with the same wallet file from November and it is an unused wallet file with no tx history. Possibly someone with a more "used" wallet with actual tx's may have an issue of the gui locking up but I am not.
