### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [monero-project/monero-gui#1578]
i've downloaded Version '0.12.3.0' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by pazos** [comment]
@core-code: yes, both keys are missing on [our Info.plist](https://github.com/monero-project/monero-gui/blob/master/share/Info.plist). A few months ago, before using our own template instead of qmake generated one I proposed [adding versioning support](https://github.com/monero-project/monero-gui/pull/1313) based on github commits. You can give it a try or propose another way of pulling the version automatically.

Anyways, you can check the version from the running gui, so it shouldn't matter.

**Comment by core-code** [comment]
well i think there are several reasons it matter:
• users don't need to launch the app to check the installed version
• users don't need to update manually but can use third party updater apps like MacUpdater
• only the version information from the CFBundleVersion key can be used by the operating system which is helpful e.g. if you have multiple versions installed. hiding something in the app has no use to any outside consumers

**Comment by pazos** [comment]
> well i think there are several reasons it matters:
• users don't need to launch the app to check the installed version
• users don't need to update manually but can use third party updater apps like MacUpdater
• only the version information from the CFBundleVersion key can be used by the operating system which is helpful e.g. if you have multiple versions installed. hiding something in the app has no use to any outside consumers.

I agree with you.

 A manual version should be trivial to implement, but an automatic version tagger would be preferred.

BTW, nice software @core-code. I'm a fan of your UninstallPKG app.

**Comment by core-code** [comment]
> A manual version should be trivial to implement, but an automatic version tagger would be preferred.

you are right its quite easy to forget updating prior to a release unless you follow strict procedure

> I'm a fan of your UninstallPKG app.

thanks! dark-mode update coming soon ;)

**Comment by erciccione** [comment]
+hacktoberfest

**Comment by selsta** [comment]
#2773 should solve this.
