### ISSUE TITLE
Using the GUI 12.3 requires entire wallet resync each time closed\opened. Using NANO S

### ISSUE THREAD

**Issue by usmarine2141** [monero-project/monero-gui#1579]
Every time the GUI closes, and reopens have to resync the ENTIRE wallet blocks, not just what was missed. I have read there is a save button, but do not see a save button anywhere in the wallet GUI. 

NOTE: Created wallet using the GUI, by selecting the Ledger option.

**Comment by skftn** [comment]
possibly related #1565

**Comment by dEBRUYNE-1** [comment]
@usmarine2141 - Did you manage to resolve this issue? If not, have you looked at the `It's imperative that the closing process of your Ledger Monero wallet is done in this specific consecutive order:` part of this guide?

https://monero.stackexchange.com/questions/9901/how-do-i-generate-a-ledger-monero-wallet-with-the-gui-monero-wallet-gui

**Comment by usmarine2141** [comment]
Yes i thought i had closed this issue.

**Comment by dEBRUYNE-1** [comment]
All right, will close then.

**Comment by dEBRUYNE-1** [comment]
+resolved
