### ISSUE TITLE
Ringsize slider giving different values

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-gui#158]
See this video (11:29) https://youtu.be/-n5azwzhwiA?t=11m29s

At the start of the video the Medium setting gives a mixin of 8. Then at 12m11s (about 40 seconds later) I use the same Medium privacy setting yet the confirmation popup shows a mixin of 7.

**Comment by moneromooo-monero** [comment]
AFAICT, you just moved the slider just before. So.. it works ?

**Comment by medusadigital** [comment]
it works basically as designed, but it can "snap" everywhere. 

so its porssible to basically produce something like this: 

![sliderpixel](https://cloud.githubusercontent.com/assets/17108301/20246541/019303cc-a9b9-11e6-877f-5fe30497ea1f.png)


so weither we do some automatic snapping or we let it slide freely like now (and accept that there is 1 pixel, which is the border between 7 and 8). maybe this border can be moved into the middle, between 7 and 8?

**Comment by moneromooo-monero** [comment]
or in the middle :D

**Comment by medusadigital** [comment]
so what would be the prefered behaviour ? 

to me personally it seems good enough.

**Comment by dEBRUYNE-1** [comment]
Closing this in favor of #863.

+duplicate
