### ISSUE TITLE
"Sign Transaction" confirmation window (offline mode) too large in low graphics mode

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#1580]
From a [bitcointalk thread](https://bitcointalk.org/index.php?topic=583449.msg46412931#msg46412931):

> Scrolling window and start-low-graphics-mode solutions in GUI to accommodate low-resolution/limited-GPU devices (such as netbooks used as cold/offline machines) are very handy. Unfortunately though, the "Sign Transaction" confirmation window (offline mode) remains too large and does not scroll thereby making the "Yes" and "No" buttons inaccessible.

> Are you able to confirm or deny with the enter and escape button, respectively? 

> I did try to hit enter hoping that Yes is made active and highlighted by default but to no avail. I even tried the tab/enter combo hoping it'd cycle through the buttons and get lucky. No dice. I'm almost sure I have hit the Esc key a few times too as I just about tried any key that I thought would trigger something.

> Unfortunately though, the "Sign Transaction" confirmation window (offline mode) remains too large and does not scroll thereby making the "Yes" and "No" buttons inaccessible.

> What resolution do you have? I have 1024x600 and sign tx window fit to the screen (on linux).

**Comment by erciccione** [comment]
+hacktoberfest

**Comment by dEBRUYNE-1** [comment]
+resolved
