### ISSUE TITLE
[Minor design] UX improvements

### ISSUE THREAD

**Issue by Baltsar** [monero-project/monero-gui#162]
Great work guys the GUI looks clear and solid!

As a UI / UX Designer eyes I saw some minor improvements that could help the user even more and clear. I just throw it out here:

### Minor changes
- Make handle/slider control of privacy level meter. Right now there is no indication that you can change the level. Take Inspiration from my privacy screen I did: [Monero mobile wallet fictive](https://www.gustafgarnow.com/monerowallet/)

- Copy to clipboard icons doesn't give any feedback that its been copied, perhaps a small window with green checkmark or text that it confirms that its been copied.

- Close wallet is dangerously close to be act as normal button make it different as a icon (logout). I suggest there would be pop-up warning screen after you clicked close wallet to confirm that you really want to close the wallet.

### Suggestion/Idea

- [http://imgur.com/hilcN9J](http://imgur.com/hilcN9J) Make adresses appear on the Verify transaction window to eliminate the jump back and forth for the user. So user can copy paste adress directly at the same screen.

More suggestions and ideas to come whenever I get free time!

Regards 
Gustaf/ reddit: Baltsar777

**Comment by Jaqueeee** [comment]
Hi @Baltsar 
Thanks for your input. I'm happy to implement this when some of the other open issues are solved. 
Don't agree on the closing wallet button though. It's no big deal if you close the wallet since everything is saved and you can choose to open it again. 

Looking forward to more suggestions from you further on. I really like the work you did on the mobile GUI.

**Comment by taushet** [comment]
Your input from a ux and design perspective would be great!  Your mobile wallet mockup is beautiful :)

**Comment by maitscha** [comment]
Also see #145

**Comment by leafcutterant** [comment]
> Make handle/slider control of privacy level meter. Right now there is no indication that you can change the level. Take Inspiration from my privacy screen I did: Monero mobile wallet fictive

I think it's very important to have a handle-looking thing on the slider. I doesn't at all look like you can move the slider.

**Comment by xmrdsc** [comment]
GUI has a new theme now. Thanks.

+resolved
