### ISSUE TITLE
After update MacOS Mojave: Couldn't open wallet: Fail SCard API : (-2146435069)  

### ISSUE THREAD

**Issue by tiocoin** [monero-project/monero-gui#1635]
Has been impossible to open the wallet (Lithium Luna v0.12.3.0 with Ledger Nano S) right after update my MacOS to Mojave. 
Couldn't open wallet: Fail SCard API : (-2146435069) Invalid handle. Device=0, hCard=0, hContext=2

**Comment by dEBRUYNE-1** [comment]
Resolved here:

https://www.reddit.com/r/Monero/comments/9n77u1/somebody_else_with_issues_after_update_to_macos/

**Comment by dEBRUYNE-1** [comment]
+resolved
