### ISSUE TITLE
MSYS2 build error: "qmlcachegen.exe: Bad address"

### ISSUE THREAD

**Issue by Lafudoci** [monero-project/monero-gui#1636]
Built from last master `6ca3c`.
Win7 x64 MSYS2
QMake version 3.1
Using Qt version 5.11.2 in C:/msys64/mingw64/lib

I found the same issue occured at aeonix#15.
```
/C/msys64/mingw64/bin/qmlcachegen.exe --resource-file-mapping=C:/msys64/home/x99/monero-gui/qml.qrc=C:/msys64/home/x99/monero-gui/build/qml_qmlcache.qrc -o release/qmlcache_loader.cpp ../qml.qrc
make[1]: execvp: /C/msys64/mingw64/bin/qmlcachegen.exe: Bad address
make[1]: *** [Makefile.Release:1029: release/qmlcache_loader.cpp] Error 127
make[1]: Leaving directory '/home/x99/monero-gui/build'
make: *** [Makefile:36: release] Error 2
```
Full log: https://paste.fedoraproject.org/paste/xdqtNp14H~b2oFgYp0m~hw

**Comment by skftn** [comment]
Solved in IRC. Best to use 5.11.1. 5.11.2 is known to have problems.

+resolved

**Comment by skftn** [comment]
+open

**Comment by HarrisonHesslink** [comment]
Just run it again and it should work

**Comment by wrokvidLiac** [comment]
i did it and still same error!
even delete some qml_cache files and nothing
strace not working on mingw so i cant understand what is happening!

**Comment by Lafudoci** [comment]
@stoffu #1796 did sovlve my issue of  `qmlcachegen.exe: Bad address`. Thank you!

**Comment by naughtyfox** [comment]
I still get this error:
```make[1]: execvp: /C/msys64/mingw64/bin/qmlcachegen.exe: Bad address```

when i'm trying to invoke in manually i get another error:
```
$ LANG=C /C/msys64/mingw64/bin/qmlcachegen.exe --resource-file-mapping=C:/exa/monero-gui/qml.qrc=C:/exa/monero-gui/build/qml_qmlcache.qrc -o release/qmlcache_loader.cpp ../qml.qrc
Error generating loader stub: ▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒.
```
which means that invocation passes. I think this is the bug in mingw `make` utility
