### ISSUE TITLE
Report monero-gui version to stdout

### ISSUE THREAD

**Issue by skftn** [monero-project/monero-gui#1654]
Upon startup, the application could output the monero-gui version to stdout as `WARN`. People often post logs to debug problems and to be able to see their version would be beneficial.

In QML the variable is exposed as `Version.GUI_VERSION`:
https://github.com/monero-project/monero-gui/blob/a9fa808dd136f6e95b81badb76dfcee5c18d7a1f/pages/settings/SettingsInfo.qml#L275

Should probably output somewhere around here:

https://github.com/monero-project/monero-gui/blob/7adeb694c17511ffcb1d3d0c0038f5f8b8684a5f/main.cpp#L143-L145

**Comment by skftn** [comment]
+hacktoberfest

**Comment by pazos** [comment]
Somewhat related to #1578. We need to define a version in qmake and export that to qml. An automated version would be better than a manual one.

**Comment by skftn** [comment]
@pazos I thought perhaps it would be best to read the version file the same way QML does it; via the resource system. See PR. Let me know what you think.
