### ISSUE TITLE
monero-wallet-gui cannot be opened because of a problem. [Mac OS Mojave]

### ISSUE THREAD

**Issue by tiocoin** [monero-project/monero-gui#1658]
Monero wallet [GUI Beryllium Bullet v0.13.0.3](https://github.com/monero-project/monero-gui/releases)
Mac OS Mojave 
`Crashed Thread:        0
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    DYLD, [0x1] Library missing
Application Specific Information:
dyld: launch, loading dependent libraries
Dyld Error Message:
  Library not loaded: /usr/local/Cellar/openssl/1.0.2p/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/monero-wallet-gui.app/Contents/Frameworks/libssl.1.0.0.dylib
  Reason: image not found   `
![monero-error](https://user-images.githubusercontent.com/8238880/46989237-ec6bf900-d12e-11e8-8aa6-d8c37f6f5bbb.png)

**Comment by hoyanf** [comment]
Dynamic Library Error

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/openssl/1.0.2p/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/monero-wallet-gui.app/Contents/Frameworks/libssl.1.0.0.dylib
  Reason: image not found

**Comment by selsta** [comment]
Can someone test this out:

1. Install homebrew from https://brew.sh
2. Install `openssl` using `brew install openssl`

This would obviously be only a temporary fix until there are new binaries without this problem.

**Comment by Aquilae32** [comment]
Installing OpenSSL via Homebrew has allowed me to then open monero-wallet-gui.

**Comment by xyberpix** [comment]
Okay, so a workaround is good, but I really don't feel the urge to install HomeBrew. Dev's any idea on when a fix is likely at all? BTW, thank you for all the great work.

**Comment by binarymind** [comment]
openssl 1.0.2l -> 1.0.2p was indeed necessary for me

**Comment by dEBRUYNE-1** [comment]
@xyberpix - Stoffu is currently investigating the issue. Hopefully we can produce a new Mac OS X build soon that includes a fix.

**Comment by xyberpix** [comment]
@dEBRUYNE-1 Thanks man, appreciate the update.

**Comment by dEBRUYNE-1** [comment]
You're welcome.

**Comment by Makazar** [comment]
Trying to install HomeBrew ( by Restart-Utility-Terminal Pad) but it would not happen and getting the message: "Could not resolve host: raw.githubusercontent.com"

Any idea what I can do?

**Comment by selsta** [comment]
@Makazar

The normal Terminal, not the Terminal in the Restart Utility.

**Comment by Makazar** [comment]
@selsta 

Thanks. Have done but now it displays this message and would not let me type anything: "Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin
Password: "

**Comment by Makazar** [comment]
@selsta 

YES! Installation of Homebrew completed, then installed 'brew install openssl' and the wallet has just opened!
Thanks guys.

**Comment by tiocoin** [comment]
I confirm GUI Beryllium Bullet v0.13.0.3 is working fine now installing homebrew https://brew.sh and running:
`brew install openssl`
Open the wallet, done ✅

**Comment by erciccione** [comment]
+resolved

**Comment by selsta** [comment]
We resolved this on the build machine, v0.13.0.4 has this fixed and should be out in the next days.

**Comment by umma08** [comment]
> We resolved this on the build machine, v0.13.0.4 has this fixed and should be out in the next days.

any update on this? will this also fix the issue on older versions of osX? i am on 10.11.4. 

thanks in advance!

**Comment by dEBRUYNE-1** [comment]
>will this also fix the issue on older versions of osX? i am on 10.11.4.

Yes and GUI v0.13.0.4 should be out soon.

**Comment by Emzy** [comment]
Quick workaround: 
`
$ sudo -i 
root# mkdir /usr/local/Cellar/openssl/1.0.2p/lib/ 
root# ln -s /Applications/monero-wallet-gui.app/Contents/Frameworks/libcrypto.1.0.0.dylib /usr/local/Cellar/openssl/1.0.2p/lib/
`

**Comment by ProBowie** [comment]
I had both installed, but had to upgrade brew via: `brew upgrade`

**Comment by freddrums** [comment]
Hello Iam trying to figure out how to install openssl. I am the avg person who has no idea how to do this. I have founs openssl in homebrew. Now trying to get the openssl to run on my mac. My mac says i need an app to run it. which app? any help to get thru would be amazing.
thanks!
Fred

**Comment by Aquilae32** [comment]
It is sufficient to have installed openSSL with Brew (“brew install openssl” in a terminal, supposing you have Brew already installed). The Monero GUI is the app that will automatically find it when opening. If it doesn’t, maybe openSSL is not in the PATH (the default directories where the system looks for a program).

(From Brew)
openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

**Comment by selsta** [comment]
This is fixed in the v0.13.0.4 binaries, openSSL is not required.
https://www.reddit.com/r/Monero/comments/9ti2on/gui_v01304_beryllium_bullet_released/

**Comment by skftn** [comment]
Please re-open if the problem persists.

+resolved
