### ISSUE TITLE
Non-translatable strings

### ISSUE THREAD

**Issue by snaggen** [monero-project/monero-gui#1661]
I looked at the latest GUI and looked for untranslated strings using the Swedish translation that should be complete. I then found some un translated strings, that were not available in the monero-core_sv.ts file. That gave me the following non-translatable strings.

On the Send page:
Automatic (in the transaction priority dropdown).

On the Recieve page it lists adresses, I have an entry saying
`#0  Primary address <adress>`
Where the text "Primary address" is not translatable

On the History page: 
The entries in the sort dropdown is not translatable.
In each entry "Sent", "To", "Transaction ID" is not translatable.

On the Advanced -> Sign/Verify page, these strings are not translatable
"Message from file"
"Verify message"

**Comment by erciccione** [comment]
Thanks @snaggen , the absence of a code freeze make hard to have all strings synced for release. Will fix this asap

**Comment by erciccione** [comment]
#1664 should fix this

**Comment by erciccione** [comment]
+resolved
