### ISSUE TITLE
0.13.0.3 GUI  macOS 10.14 not working

### ISSUE THREAD

**Issue by geli-ans** [monero-project/monero-gui#1675]
macOS 10.14 can't open  0.13.0.3 GUI。
old version works well。

**Comment by dEBRUYNE-1** [comment]
Duplicate of #1658. A quick resolution can be found here:

https://monero.stackexchange.com/questions/10364/gui-v0-13-0-3-does-not-start-on-mac-os-x-monero-wallet-gui-cannot-be-opened-bec

**Comment by dEBRUYNE-1** [comment]
+duplicate
