### ISSUE TITLE
Gui crash on start

### ISSUE THREAD

**Issue by RomyToklio** [monero-project/monero-gui#1679]
Building GUI on windows with mingw64 ok without error but don t want to start. How can I see what could crash the app?
Using qt5-1.11.2 
Using Monero master

**Comment by skftn** [comment]
Try to use this specific package: `qt5-5.11.1-3`

1. Remove current qt5: `pacman -R mingw-w64-x86_64-qt5` (or whatever your qt5 package is called)
2. Install: `pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-qt5-5.11.1-3-any.pkg.tar.xz`
3. Recompile & try

**Comment by RomyToklio** [comment]
Thank you, worked !

**Comment by dEBRUYNE-1** [comment]
+resolved
