### ISSUE TITLE
transaction is veiled, but in a purse is empty

### ISSUE THREAD

**Issue by irq15** [monero-project/monero-gui#1686]
Have translated coins, transaction is successfully complete, but in a wallet 2 days is empty
TX ID
4744c3e48debe5f6ef6907e051f926c2c073d7d2e27a7f59720de68a1187a721

in what a problem how to receive the coins?

**Comment by xiphon** [comment]
> transaction is successfully complete

How did you check this?

**Comment by irq15** [comment]
MoneroExplorer.com
4744c3e48debe5f6ef6907e051f926c2c073d7d2e27a7f59720de68a1187a721
Timestamp [UCT]: 2018-10-18 14:02:25
Age [y:d:h:m:s]: 00:001:15:00:57
Block: 1685559
Tx version: 2 |
No of confirmations: 14

**Comment by skftn** [comment]
Download the latest GUI

**Comment by xiphon** [comment]
MoneroExplorer.com is on the wrong chain. Seems they didn't update the daemon yet. Check any other block explore that is in sync with the network.

**Comment by dEBRUYNE-1** [comment]
@irq15 - Did you manage to resolve your issue?

**Comment by dEBRUYNE-1** [comment]
Ping @irq15.
