### ISSUE TITLE
Entering bad password results in usability issues

### ISSUE THREAD

**Issue by sectioneight** [monero-project/monero-gui#1694]
When you launch the GUI, you're prompted for a password. If you get the password wrong, you get a big screen with an "OK" button at the bottom that you need to click.

In most software I'm used to, you can hit "Escape" or "Enter" to try again -- or at least the button is closer and more visible. Here's the current experience:

![password flow](https://user-images.githubusercontent.com/97087/47306964-a60d1300-d5e2-11e8-8b21-1de2a5421546.gif)

What do you guys think about making "escape" or "enter" put you back into the "enter password" flow?

I'm happy to code something up if you all would like this to be improved, otherwise I'll just work on typing my password more accurately :)

**Comment by xiphon** [comment]
https://github.com/monero-project/monero-gui/pull/1699

**Comment by sectioneight** [comment]
Closing as duplicate of #1699 -- thanks @xiphon
