### ISSUE TITLE
Couldn't open wallet: basic_string::_M_replace_aux

### ISSUE THREAD

**Issue by TreantBG** [monero-project/monero-gui#1698]
I try to login with my ledger nano s with Monero GUI and this happens after i authorize privet view keys on the ledger

**Comment by dEBRUYNE-1** [comment]
Please see:

https://monero.stackexchange.com/questions/6611/cant-load-wallet-in-cli-v0-13-0-2-or-gui-v0-13-0-3-error-stdbad-alloc-err

**Comment by dEBRUYNE-1** [comment]
+resolved
