### ISSUE TITLE
No incoming connections - check firewalls/routers allow port

### ISSUE THREAD

**Issue by blackparallax** [monero-project/monero-gui#1711]
OS: Windows 10
GUI version: Monero GUI v0.13.0.3

I have successfully synchronised daemon and wallet blocks are now syncing:
![2018-10-29 4](https://user-images.githubusercontent.com/14051589/47645155-df81e780-dbbb-11e8-888e-6f22c6a04292.png)

However, while wallet blocks sync I am having the below notification when running Monero GUI:
2018-10-29 10:31:29.394 [P2P3] WARN global src/p2p/net_node.inl:1338 [1;31mNo incoming connections - check firewalls/routers allow port 18080[0m

Screenshot: 
![2018-10-29 1](https://user-images.githubusercontent.com/14051589/47644938-4783fe00-dbbb-11e8-9461-2e10f0995722.png)

I am using Windows Defender and I have allowed the port as requested (18080) - and whitelisted Monero GUI.

Screenshot (Port):
![2018-10-29 2](https://user-images.githubusercontent.com/14051589/47644989-697d8080-dbbb-11e8-813d-539b934ba02d.png)

Screenshot (Whitelist):
![2018-10-29 3](https://user-images.githubusercontent.com/14051589/47645062-a0539680-dbbb-11e8-88cc-9aaf8eb0b178.png)

Thanks for any advice, which would be greatly appreciated.

**Comment by dEBRUYNE-1** [comment]
First note that the GUI (and the integrated daemon (monerod)) will still function properly without any incoming connections. Now, to open port 18080 properly, you have to forward / open it in your router too.

**Comment by blackparallax** [comment]
Thanks 👍 Are you able to assist with what I need to fill in here:

![2018-10-30](https://user-images.githubusercontent.com/14051589/47658981-b2473080-dbdf-11e8-9cb8-6ce8cd8139aa.png)

**Comment by skftn** [comment]
Open port 18080 to allow incoming P2P connections. `print_cn` will help you verify your incoming connections are working.

As for actually configuring your router to forward port 18080 to the machine on your local network; write down the router model you have and look up some resources via DuckDuckGo/Google.

From the screenshot you posted I can give some insight:

Service: other
External host: (leave empty if you can)
External port: 18080
Internal host: (the IP address of your machine on your local network; it will start with `192.168.1...`
Internal port: 18080

Protocol is probably UDP (?) but if you can, choose 'Both' from the dropdown menu.

**Comment by blackparallax** [comment]
> 
> 
> Opening port 18080 allows incoming P2P connections. Like @dEBRUYNE-1 mentioned; your daemon works fine without port forwarding. Personally I sometimes get this error - I ignore it.
> 
> As for actually configuring your router to forward port 18080 to the machine on your local network; try to find some guides and/or your router's manual concerning port forwarding. In addition: Windows can block these requests so make sure the Windows firewall allows such connections (TCP and UDP).
> 
> From the screenshot you posted I can give some insight:
> 
> Service: other
> External host: (leave empty if you can)
> External port: 18080
> Internal host: (the IP address of your machine on your local network; it will start with `192.168.1...`
> Internal port: 18080
> 
> Protocol should probably be UDP (?) but if you can, choose 'Both' from the dropdown menu. `print_cn` will help you verify your incoming connections are working.

I managed to enter the details you provided in my router.

**Comment by blackparallax** [comment]
Thanks so much for the help! It seems to be working.

**Comment by hajes** [comment]
source IP or 0.0.0.0
source port any (because no network socket connects with two same ports, source port 51456 destination port 1844)

same goes for Monero node
