### ISSUE TITLE
Wallet Blocks Syncronizing all blocks each time opening Monero GUI

### ISSUE THREAD

**Issue by blackparallax** [monero-project/monero-gui#1713]
Is it recommended to leave Monero GUI always open in the background?

Yesterday I finally got the Daemon and Wallet Blocks to fully sync, when I've gone into it today the Wallet Block sync has started all over again.

Monero GUI v0.13.0.3
Windows 10 64bit

![2018-10-30 1](https://user-images.githubusercontent.com/14051589/47696287-d5122d00-dc51-11e8-8f83-7ffc227c50b5.png)

**Comment by blackparallax** [comment]
No ledger device, just my pc.

**Comment by dEBRUYNE-1** [comment]
Can you perhaps run the GUI as administrator to check whether it makes a difference?

**Comment by blackparallax** [comment]
I am having difficulties logging in to my wallet every time. I always get this error. I know the password is correct because I copy and past it from a document:

<img width="485" alt="2018-10-31" src="https://user-images.githubusercontent.com/14051589/47727252-d110fa00-dca7-11e8-90b6-179f0a66be2e.png">

**Comment by blackparallax** [comment]
Hey I really appreciate all the support. I've decided to remove the software until stable and usable versions are available.

**Comment by blackparallax** [comment]
So I attempted to download v0.13.0.4, but after the file downloaded it says it's 0.13.0.3. Here's a screenshot of your website and the downloaded file. The screenshot isn't the best, but the downloaded file is named: monero-gui-win-x64-v0.13.0.3.zip but it should be 0.13.0.4.

![2018-11-02 5](https://user-images.githubusercontent.com/14051589/47902173-56292880-decd-11e8-84b7-de11cdd82bf3.png)

**Comment by mr-tron** [comment]
Issue is still actual in monero v0.13.0.4

**Comment by selsta** [comment]
@mr-tron Make sure to properly close your wallet.

**Comment by mr-tron** [comment]
Yes. Via `x` in the windows right corner. Operational system ubuntu 18.04
On exit i see errors in stdout 
```
2019-02-21 11:44:03.314	    7f22d8f96700	ERROR	wallet.wallet2	src/wallet/wallet2.cpp:2020	!r. THROW EXCEPTION: error::no_connection_to_daemon
2019-02-21 11:44:03.315	    7f22db7fe700	ERROR	WalletAPI	src/wallet/api/wallet.cpp:973	daemonBlockChainTargetHeight: Failed to connect to daemon
2019-02-21 11:44:03.315	    7f22db7fe700	ERROR	WalletAPI	src/wallet/api/wallet.cpp:954	daemonBlockChainHeight: Failed to connect to daemon
```
But exit code is 0.

**Comment by mr-tron** [comment]
It reproduces sometimes. Looks like problems when connected with forced wallet disconnecting.
