### ISSUE TITLE
mac build error

### ISSUE THREAD

**Issue by CokeBear** [monero-project/monero-gui#1716]
An exception occurs when I use ./get_libwallet_api.sh to build

![image](https://user-images.githubusercontent.com/6119459/47853070-88c51980-de18-11e8-9431-a1b0f11719b7.png)

**Comment by BigslimVdub** [comment]
https://github.com/monero-project/monero-gui/issues/1558

**Comment by CokeBear** [comment]
@ubien @BigslimVdub  Thanks for your help
