### ISSUE TITLE
v13.0.3 GUI does not allow transaction under 1 XMR

### ISSUE THREAD

**Issue by BigslimVdub** [monero-project/monero-gui#1718]
OSX 10.13.6
monero-gui-mac-x64-v0.13.0.3.tar.bz2

Trying to send a transaction, GUI does not unlock the send button unless over 1 xmr is entered. If a decimal is the first point, I can not send a transaction. 
It does not change with custom decorations on or off. 

<img width="636" alt="less than 1" src="https://user-images.githubusercontent.com/30030687/47891871-01c96e80-de23-11e8-95da-2834661687cc.png">

<img width="647" alt="more than 1" src="https://user-images.githubusercontent.com/30030687/47891876-068e2280-de23-11e8-8438-ccc11b27c029.png">

**Comment by dEBRUYNE-1** [comment]
Amounts below one can be denoted with `0.` 

Fwiw, I thought this was fixed. 

Paging @skftn.

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by skftn** [comment]
Putting in `.194` never worked. Older versions would eat up the period and you'd end up with `194`.
