### ISSUE TITLE
v0.13.0.4 file name or file incorrect

### ISSUE THREAD

**Issue by blackparallax** [monero-project/monero-gui#1720]
So I attempted to download v0.13.0.4, but after the file downloaded it says it's 0.13.0.3. Here's a screenshot of your website and the downloaded file. The screenshot isn't the best, but the downloaded file is named: monero-gui-win-x64-v0.13.0.3.zip but it should be 0.13.0.4.

   ![Screenshot](https://i.imgur.com/uBdPtq1.png)

**Comment by blackparallax** [comment]
![]()

**Comment by dEBRUYNE-1** [comment]
We're aware of this issue and it should be fixed soon. In the meantime, you can use the direct links from this thread:

https://www.reddit.com/r/Monero/comments/9qrcw7/gui_v01304_prerelease_test_binaries_buildbot/
