### ISSUE TITLE
GUI Calendar Incorrect dates

### ISSUE THREAD

**Issue by keatond** [monero-project/monero-gui#1723]
![calendar](https://user-images.githubusercontent.com/428041/47931593-a42a3600-dea5-11e8-8df8-3f766d12bbab.PNG)

Good Afternoon All,

Calendar within the history tab appears to be showing the dates of the month on the incorrect day.

**Comment by skftn** [comment]
+bug

**Comment by mmbyday** [comment]
A few observations to add...

Seems to affect Window operating system. Datepicker is correct on Linux.

Specifically, the off by one bug occurs on March 11, 2018.
![mar11](https://user-images.githubusercontent.com/40871101/49189675-2e8a7c00-f324-11e8-9fe5-672efc21f26b.PNG)

**Comment by mmbyday** [comment]
It appears this is a bug in qt 5.7.

Can confirm in qt 5.9.5 and as far as 5.11.1, this issue no longer exists. 

Perhaps we should bump up the minimum required qt version? At least this is another reason to do so, sooner than later.

![2](https://user-images.githubusercontent.com/40871101/49612869-cf97b900-f95a-11e8-9dcd-479c253aea37.gif)

**Comment by mmbyday** [comment]
https://github.com/monero-project/monero-gui/issues/1787

**Comment by xmrdsc** [comment]
#789

**Comment by selsta** [comment]
Qt 5.9 is required now.

+resolved
