### ISSUE TITLE
Error opening wallet in Windows GUI

### ISSUE THREAD

**Issue by G-Bigo** [monero-project/monero-gui#1738]
The Windows x64 GUI wallet contains a massive bug. It is impossible to re-open a wallet.

Situation: 
• Open program first time
• Choose language (German for me)
• Create a wallet
• Choose a password (in my case containing spaces)
• Start service
• Sync blockchain
  (Everything standard up to here)
• Close program
• Re-open program
• Enter password
• Wallet couldn't be opened: basic_string::_M_replace_aus

The same happens when trying to open the (definitely existing) wallet from a file.

When restarting the whole process and creating a new wallet the wallet specs show a possible reason:
The alleged location (on a windows system!) alway ends with something like (without quotation marks)
'/username/username'
I.e. the windows path contains slashes (instead of backslashes), which of course must evoke an error. Seems like some Linux code splashed over unaltered.

I don't know whether the slashes within the wallet file path actually are the reason for the described bug. Anyway, the procedure described above reproducible yields the wallet open error.

**Comment by G-Bigo** [comment]
I first run into this issue with version 0.13.0.3, then downloaded 0.13.0.4 to see whether it works. And no, nothing is fixed in v0.13.0.4 — exactly the 'Can't open wallet' error described above.

**Comment by dEBRUYNE-1** [comment]
@G-Bigo - You will, after upgrading to GUI v0.13.0.4, still have to remove the wallet cache once. Thereafter it should work properly though.

**Comment by dEBRUYNE-1** [comment]
Ping @G-Bigo - Did you manage to resolve your issue?

**Comment by G-Bigo** [comment]
Yepp, deleting old wallet, restoring (aka recreating) it with mnemonic phrase, re-synching wallet. No it works as expected. Thanks.

**Comment by erciccione** [comment]
+resolved
