### ISSUE TITLE
Monero GUI cannot open on Windows 64

### ISSUE THREAD

**Issue by geft** [monero-project/monero-gui#1742]
I'm using 0.13.0.4. Clicking on it does literally nothing. Rebooted, deleted old wallet data, etc. Nothing. Is there any log I can read?

Before this I was using pre-hardfork GUI. It worked fine.

**Comment by skftn** [comment]
Open `cmd.exe`, navigate to the folder containing `monero-wallet-gui` and execute it: `monero-wallet-gui.exe`.

There should be some output you can observe.

**Comment by dEBRUYNE-1** [comment]
@geft - Do you have an AV running that could have been quarantining necessary files (i.e. files required in order for the GUI to run properly)?

**Comment by geft** [comment]
@skftn 
Still nothing. It's like pressing enter. I'm using the Windows 10 Pro 1803 build 17134.407.

@dEBRUYNE-1 
I use Avira and Malwarebytes but disabling both doesn't seem to fix the problem. There was no alert either. Just want to add that the CLI works just fine, so it'd be weird if they just choose to quarantine GUI stuff.

**Comment by skftn** [comment]
@geft Can you confirm you have indeed `monero-wallet-gui.exe` there?

You're saying that when you try to run it from `cmd.exe`, there is no output? at all?

**Comment by geft** [comment]
Well I use PowerShell but yeah, there's no output. `monero-wallet-gui.exe` is there. I even have the shortcut on my taskbar. Like I said, I was using the GUI just fine pre-hardfork. Even verified the zip hash to ensure it's not corrupt.

**Comment by dEBRUYNE-1** [comment]
@geft - The AV could have quarantined some files upon extracting the `.zip` file. 

Could you perhaps try the following steps:

1. Create a new directory / folder.

2. Add the folder to the exception list in your AV. Put differently, you have to whitelist the folder in your AV.

3. Extract the `.zip` file to aforementioned folder.

4. Double click on `monero-wallet-gui.exe` to open the GUI. 

Does it work now?

**Comment by geft** [comment]
Hey, it works! Not sure what's stopping it, either Avira or Malwarebytes. I checked both and nothing was quarantined. Why would the Monero GUI trigger a false positive anyway?

Regardless, thanks for the help!
