### ISSUE TITLE
I downloaded the gui wallet but I can't get Daemon to run

### ISSUE THREAD

**Issue by freddrums** [monero-project/monero-gui#1748]
I have now been able to download the new Gui wallet but I can't get daemon to sync. Any ideas, I keep getting an error and it says to monerod manually? How do I do that? Also, it says to check my wallet and daemon log for errors.
any ideas how to get the daemon to connect?

thanks,
Fred

**Comment by dEBRUYNE-1** [comment]
Ping @freddrums - did you manage to resolve your issue?

**Comment by freddrums** [comment]
I have't had a chance to run it for a few hours, I'll try today and keep you posted, thanks for checking in! really appreciate it,
all the best!
Fred

**Comment by dEBRUYNE-1** [comment]
@freddrums - All right, hopefully you will be able to resolve your issue!

**Comment by freddrums** [comment]
thanks for checking in! really appreciate it. I let daemon run for a few days, I think it eventually did sync once. It seems like it syncs very slowly!! I think my computer is old and really slow. I'll try to sync it again and see if it can do it quicker. Definitely time for a nex MAc. mine is almost 6 yrs old.
Thnx much!!

**Comment by dEBRUYNE-1** [comment]
@freddrums - Thanks for your report. Note that the sync performs best when all other resource intensive processes (e.g. a browser) are closed.

P.S. Can this issue be closed?

**Comment by dEBRUYNE-1** [comment]
Author has not responded in ~2 weeks. I therefore am going to close this issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
