### ISSUE TITLE
Suggestion: updates/api debug

### ISSUE THREAD

**Issue by SBSeed** [monero-project/monero-gui#1761]
add auto-check for updates to Monero-GUI api

would it be possible to do downloads through Monero network/blockchain transactions?
news/info. on updates coming out for Monero-GUI within api?
scan/check for potential problems within api, or send issue/bug ticket system?

not sure about work involved in adding this kind of thing, probably a pain in the ass, but after it was implemented i would think it would be easier to keep track of bugs and stuff...

**Comment by dEBRUYNE-1** [comment]
Related to #2089.

**Comment by selsta** [comment]
GUI notifies now if a new version is available.

**Comment by selsta** [comment]
+resolved
