### ISSUE TITLE
[Clarification] Testnet, Mainnet, Stagenet

### ISSUE THREAD

**Issue by SBSeed** [monero-project/monero-gui#1776]
Clarification on usage:
Testnet - used for messing around with monero_wallet-GUI, test mining, cannot recieve/send Monero (XRM) mined because its only test functions?

Mainnet - actual wallet, meant for mining/sending/receiving Monero (XRM), using any of it to purchase/trade/etc.?

Stagenet - combination of mainnet/testnet used as a staging ground for 'live'/beta versions of the wallet?

is this summation accurate to the explanation on Monero Wallet creation?, or am i missing something...
any further details would also be appreciated in general and with functionality of each (if i am missing something).

**Comment by dEBRUYNE-1** [comment]
We already have clarifications in the guide:

https://github.com/monero-ecosystem/monero-GUI-guide/blob/master/monero-GUI-guide.md#create-a-wallet

**Comment by SBSeed** [comment]
thanks for the link.

**Comment by dEBRUYNE-1** [comment]
You're welcome.
