### ISSUE TITLE
[Feature request] Initial sync throttle

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-gui#1783]
Monerod can really hog up resources during the initial sync. 

The CLI has all the flags necessary to do a little throttling. Perhaps there could be a checkbox during the getting started walkthrough screens that has these options, and it would autopopulate the daemon flag thing in that settings area.

Fast Sync - this would add no flags.
Medium Sync - this would add --limit-rate 1000 to the daemon flags. 1 MB/s is probably enough to throttle everything downstream to some extent. 
Slow Sync - this would add --limit-rate 500 and --max-concurrency 1. This would throttle the bandwidth and the CPU usage.

These could all be combined with the bootstrap-daemon flag as well to provide immediate functionality.

**Comment by xmrdsc** [comment]
+feature

**Comment by selsta** [comment]
IMO quite a niche feature that adds unnecessary extra complexity. We already add the `--max-concurrency` flag so that the daemon only uses half of the threads available.

See here: https://github.com/monero-project/monero-gui/pull/1920

**Comment by Gingeropolous** [comment]
sure.
