### ISSUE TITLE
fatal error: 'sodium/crypto_verify_32.h' file not found

### ISSUE THREAD

**Issue by CokeBear** [monero-project/monero-gui#1801]
When I build .a for android . 
![image](https://user-images.githubusercontent.com/6119459/49852904-6adbd300-fe20-11e8-89e6-b891aef3e333.png)

**Comment by xmrdsc** [comment]
Have you tried linking against libsodium?

**Comment by dEBRUYNE-1** [comment]
I am going to close this, as the author has not responded for several months.

**Comment by dEBRUYNE-1** [comment]
+resolved
