### ISSUE TITLE
App crashes when trying to send

### ISSUE THREAD

**Issue by geft** [monero-project/monero-gui#1859]
1. Press send and see loading screen.
2. After a few minutes wondering why it's still loading, I check my Ledger to see that I have to verify the transaction. Note that I had to re-enter my Ledger password since it automatically locks itself. I verify on the Ledger.
3. After a few minutes the Ledger asks for another verification. I verify again.
4. App crashes.

I'm on Windows 64, 13.0.4. It sends just fine if I quickly verify the transaction, but there is no prompt on the GUI to do that so I have to stare at the Ledger.

**Comment by selsta** [comment]
Timeout is set to two minutes, if you take longer than that the app can crash.

**Comment by geft** [comment]
In that case I guess I'll close this.
