### ISSUE TITLE
[monerod crashing] last thread post

### ISSUE THREAD

**Issue by SBSeed** [monero-project/monero-gui#1877]
whatever, might as well create another thread for whatever good it will do...

monerod.exe connects to specific nodes/machines to download specific hashes (most of which seem to be on the monero project machines since they are the same 2-3 for the most part) one of the nodes/machines is DENYING connection i have shown this to be the case in the last thread via the pic i had from the log file end...

what i was asking is:
- is it possible to force a connection to a node/machine
- is it possible to bypass a connection or force download from a different source
- is it possible to use the blockchain.raw to patch an already in-progress download of the imdb blockchain/data files

any information would be nice (frankly at this point i am not expecting much)...
this will most likely be the last time i ask for help here, getting any coherency here has been so unproductive and mentally draining that my depression is almost to the depths.... unbearable.

**Comment by xmrdsc** [comment]
> monerod.exe connects to specific nodes/machines to download specific hashes (most of which seem to be on the monero project machines since they are the same 2-3 for the most part)

I assume you're talking about P2P nodes. It is true that upon startup, the client will first contact so called 'seed nodes'. These are monero project owned machines and indeed, not all of them are up. This should however not pose a problem in terms of blockchain syncing.

> is it possible to force a connection to a node/machine

Use monerod flag `--add-priority-node <ip>` to specify/force connection to a specific p2p node.

> is it possible to bypass a connection or force download from a different source

See above answer.

> is it possible to use the blockchain.raw to patch an already in-progress download of the imdb blockchain/data files

I don't know. This issue tracker is for GUI problems (development only). For these type of questions, best to head to [our stackexchange](https://monero.stackexchange.com). 

+resolved
