### ISSUE TITLE
[Feature Request] Ability to Export history to CSV

### ISSUE THREAD

**Issue by prettycode** [monero-project/monero-gui#1897]
It's tax time and I need to report on my mining reward income sent to my wallet. For that, I need to know all the XMR I've received and on what dates. Currently, I can visually see that information by going to the "History" section in Monero GUI, but once in this view, I cannot copy the data out and there's no feature to export it either. It would be fantastic if this view (the "History") had an "Export" button to provide a CSV of the history data.

**Comment by xmrdsc** [comment]
+feature

**Comment by prettycode** [comment]
Wow, so cool, way impressed! @xmrdsc

**Comment by xmrdsc** [comment]
:+1:
