### ISSUE TITLE
Address book - request for improvements

### ISSUE THREAD

**Issue by kayront** [monero-project/monero-gui#1900]
(breaking down #1864 as requested)

1. **See point nr 1 on the next section for an idea on how to improve the send tx workflow when we're selecting an address from the address book**.

2. (see below)

![](https://i.ibb.co/9pMv7C3/monero-improve.png)

That button is in the way. With the window maximized it's not in the way, but in the default size that's how it looks. How about getting rid of it altogether, showing only the first 5 or so characters of the address, then 5 more in the middle, then the last 5, and with the gained space (perhaps make the font a tad smaller too) just have the buttons to send/copy/delete instead?

3. In the address book window, the *description*, could probably be renamed to *Contact*. At the very least, keeping "Description" as it is already, there could be subscript to the tune of something like "A person, institution or a purpose which this address uniquely identifies", something to that extent.

**Comment by selsta** [comment]
1 and 2 are resolved. I think keeping it as `Description` is ok. Adding a new address looks like this now. 
<img width="1092" alt="Screenshot 2019-04-27 at 01 19 55" src="https://user-images.githubusercontent.com/7697454/56840902-9240b300-688a-11e9-8033-fab98a338059.png">

+resolved
