### ISSUE TITLE
Text alignment bug in the 'Change wallet' / 'Cancel' button with the password prompt

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1924]
The updated 'cancel' button in the password prompt overlay has some text rendering issues. I saw it in this build on macOS:

https://build.getmonero.org/builders/monero-gui-osx-10.11/builds/1344

![screen shot 2019-02-01 at 09 44 49](https://user-images.githubusercontent.com/23356013/52122983-b0e13600-261c-11e9-9313-a20bf06f1ee9.PNG)

![screen shot 2019-02-01 at 10 22 16](https://user-images.githubusercontent.com/23356013/52122997-b5a5ea00-261c-11e9-883f-6354fdcc5d7c.PNG)

When you select the button, on mousedown, the text slides back into a central/correct position in the button.

**Comment by tficharmers** [comment]
I have just noticed the same kind of issue in the 'Start daemon' button on the Settings page. Again, on mousedown, the text moves to the left to correctly align:

![screen shot 2019-02-01 at 12 31 44](https://user-images.githubusercontent.com/23356013/52123282-8643ad00-261d-11e9-9623-dbdef3566ea6.PNG)

**Comment by xmrdsc** [comment]
Thanks for reporting.

+bug

**Comment by rbrunner7** [comment]
Happens on Windows as well, latest Buildbot build from today

**Comment by xiphon** [comment]
Seems this is related to Qt version 5.7 installed on both the buildbots

**Comment by selsta** [comment]
We should fix that before v0.14.

**Comment by mmbyday** [comment]
Fixed nicely by https://github.com/monero-project/monero-gui/pull/1952

+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
