### ISSUE TITLE
Alignment and size of the transaction time text on the History page is broken

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#1926]
Alignment and size of the transaction time text on the History page is broken. I have seen this in macOS using this build:

https://build.getmonero.org/builders/monero-gui-osx-10.11/builds/1344

![screen shot 2019-02-01 at 09 48 32](https://user-images.githubusercontent.com/23356013/52123519-49c48100-261e-11e9-84b6-0322f30b6d15.PNG)

**Comment by selsta** [comment]
#1932 fixes the alignment, the smaller size is on purpose. I think this is enough for now, the history page is going to get rewritten anyway.

**Comment by xmrdsc** [comment]
+resolved
