### ISSUE TITLE
Transaction history doesn’t load sometimes.

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#1933]
![history](https://user-images.githubusercontent.com/7697454/52191491-334c3e80-2845-11e9-9e7f-0b0d4bd588e6.gif)
Refreshing the table through picking the current date fixes the issue.

**Comment by xmrdsc** [comment]
:+1:

**Comment by xmrdsc** [comment]
+bug

**Comment by rating89us** [comment]
I have the same bug on a Mac
