### ISSUE TITLE
Wallet in windows, but mining in Linux

### ISSUE THREAD

**Issue by vasilevskykv** [monero-project/monero-gui#1934]
Good evening. 
 I have PC with 2 operating systems Windows 10 and Linux Ubuntu 16.4. My Linux is without GUI.
I would like to create Monero cold GUI wallet in Windows 10 and mine in Linux.
Is it possible to do this way or the only way is to create wallet in Linux or to mine in Windows 10?
And if it is possible how to make visible my windows wallet for Linux?
I don't have enough memory in Linux to synchronize Monero Blockchain

**Comment by xmrdsc** [comment]
Hi @vasilevskykv 

This is unfortunately not a support forum :) I will redirect you to [/r/monerosupport/](https://old.reddit.com/r/monerosupport/). Best to ask there.

+invalid
