### ISSUE TITLE
Various dates in readme / files still show 2018

### ISSUE THREAD

**Issue by mmbyday** [monero-project/monero-gui#1988]
is @xmr-eric around? is this still worthwhile updating?

2018 fdd528b99e285f1b3a750502a0d8f069781d4bb2
2017 8429cec6c3aa550ca84a248baabe40b6570c92da

**Comment by selsta** [comment]
I usually prefer updating the year when updating the file for the first time in the new year.

**Comment by dEBRUYNE-1** [comment]
Due to selsta's comment, I am going to mark this as resolved. Or do you guys think this should be left open?

**Comment by dEBRUYNE-1** [comment]
+resolved
