### ISSUE TITLE
[Ledger] Changing restore height in settings doesn’t work.

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#1992]
I briefly looked into it but I don’t understand how all our restore height variables (appWindow, persistentSettings, wallet api) work together. Could be a monero API bug.

**Comment by selsta** [comment]
Confirmed as a monero bug.

**Comment by mmbyday** [comment]
Confirmed +bug. Changing from settings does not work. If you wait long enough, the GUI just resets to the original wallet creation height.
