### ISSUE TITLE
cannot stat '/mingw64/bin/libicudt62.dll': No such file or directory

### ISSUE THREAD

**Issue by fbmoose48** [monero-project/monero-gui#1998]
After the final 'make deploy' command this was returned:

cp: cannot stat '/mingw64/bin/libicudt62.dll': No such file or directory
make: *** [Makefile:441: deploy] Error 1
 and the monero-wallet-gui won't run. any ideas?

**Comment by dEBRUYNE-1** [comment]
Which version of the icu files are present in your MingW64 directory? The make deploy script is looking for version 62, but you may have a higher version present.

**Comment by fbmoose48** [comment]
My mysys64/mingw64/bin folder has libicu**61.dll files present. How would I go about updating them to libicu**62.dll?

**Comment by dEBRUYNE-1** [comment]
You need to update your MSYS2 environment. Alternatively, you could copy the libicu ** 61.dll files to the build directory of the GUI, as, if I recall correctly, that should work fine.

**Comment by dEBRUYNE-1** [comment]
I am doing some housekeeping and closing all old build relates issues, as they are probably not relevant anymore.

**Comment by dEBRUYNE-1** [comment]
+resolved
