### ISSUE TITLE
Gui becomes non-responsive when remote node disconnects during synchronization

### ISSUE THREAD

**Issue by Engelberg** [monero-project/monero-gui#2000]
I'm using Windows 64-bit gui build 0.14.0.0.

I'm synchronizing a view wallet from scratch from the .keys file, using a remote node that has a tendency to drop out intermittently but comes back within a minute.

When the connection to the remote node is temporarily lost, the gui freezes up.  Even after the remote node is operational again, the gui stays frozen and completely non-responsive..

**Comment by dEBRUYNE-1** [comment]
Can you check whether this is still an issue with GUI v0.14.1.0?

**Comment by dEBRUYNE-1** [comment]
I am going to close this as (i) the author did not respond and (ii) xiphon addressed a lot of potential freezing issues in GUI v0.14.1.0.

**Comment by dEBRUYNE-1** [comment]
+resolved
