### ISSUE TITLE
Feature request | textpopup

### ISSUE THREAD

**Issue by 2Epic1** [monero-project/monero-gui#2002]
Feature request 
Before clicking on a button, it would be nice to show what the buttons dose when I mouse on it.
Something like the attached picture.
![textpopup](https://user-images.githubusercontent.com/7520766/54084970-6d26ce00-4338-11e9-9705-433cc078c9b1.jpg)

BR

**Comment by rating89us** [comment]
Fixed in #3401 and #3490 @selsta
