### ISSUE TITLE
Titlebar: create Lock wallet button

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2005]
Currently you can't actively lock your wallet (put it in standby, waiting for a password). It is only done passively, when the wallet is inactive for a period of time.

A "Lock wallet" button should be implemented in title bar, together with "Close wallet" button.
When unlocked, icon should be:  ![image](https://user-images.githubusercontent.com/45968869/71278731-26d6b480-2337-11ea-9185-70211ca54ffa.png) When locked, icon should be: ![image](https://user-images.githubusercontent.com/45968869/71278813-55ed2600-2337-11ea-81f8-790e90be77c0.png)

![image](https://user-images.githubusercontent.com/45968869/69524981-74921400-0f67-11ea-8ec1-b6dbb696765f.png)

See also issues:
#2656 (Add "Lock wallet" function in Settings > Wallet)
#2605 (Separate interface and wallet icons in titlebar)

**Comment by xmrdsc** [comment]
+feature

**Comment by reemuru** [comment]
Resolved by #3859
