### ISSUE TITLE
Recently used destination addresses aren't displayed in History tab

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2008]
My friend sent me his address as a WhatsApp message, therefore I couldn't copy and paste it (I had to type it manually in address field of Send tab).

After 10 minutes, I wanted to send some XMR again to my friend, but I couldn't find his address anywhere on the GUI wallet. Unfortunately the History tab didn't display the destination address of my recent transaction (it displayed "Unkown Recipient"). So I had to type his address all over again.

So my suggestion is to display recently used destination addresses in the History Tab.

**Comment by rating89us** [comment]
hmmm I checked it now and it is appearing. But it was not appearing yesterday (transaction was not confirmed yet), it was displaying "Unknown" or something like this.

**Comment by dEBRUYNE-1** [comment]
That's expected as far as I know. Can I close this then?

**Comment by rating89us** [comment]
The problem is still there. Isn't there a way to display the destination address on the transaction details of an unconfirmed transaction?

**Comment by dEBRUYNE-1** [comment]
Maybe, but I am not sure whether it is worthwhile to actually implement it if the information is shown properly after the transaction is confirmed (which is typically within a few minutes). It may require a lot of work and we only have limited dev time available.

**Comment by rating89us** [comment]
Maybe we could just change this "Unknown" text to "Waiting confirmation". So the user will know that the typed address of his last transaction will appear as soon as a confirmation is made.

Alternatively, the address field in Send tab could save the last typed values in a list.
