### ISSUE TITLE
[Ledger] Account/Receive page load slow

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#2009]
Clicking on these pages has a delay, results in a bad experience.

Probably subaddress related.

**Comment by mmbyday** [comment]
Same experience here. I think it's the wallet communications with the ledger. Also creating a new account and creating a new address is an order of magnitude slower.  GUI becomes unresponsive :(

**Comment by xmrdsc** [comment]
This lag is most likely also present in CLI, best to open issue in monero. Re-open if it's accurately GUI related.

+invalid

**Comment by selsta** [comment]
It is a GUI issue though :P

**Comment by xmrdsc** [comment]
oki

+open

**Comment by selsta** [comment]
Will be solved by https://github.com/monero-project/monero/pull/7744 in the future.
