### ISSUE TITLE
v0.14.0.0 GUI in task manager runs betwin 50 and 100% CPU

### ISSUE THREAD

**Issue by xhums1** [monero-project/monero-gui#2013]
![Untitled](https://user-images.githubusercontent.com/9310833/54207536-3be20580-44d2-11e9-91d5-657f84fbbdb5.png)
runs at 50 - 100% CPU all the time, even after sync finished

**Comment by dEBRUYNE-1** [comment]
Could you run the GUI via the `start-low-graphics-mode.bat` batch file that is included.

**Comment by xhums1** [comment]
Yes, tried it. Same thing
![Untitled](https://user-images.githubusercontent.com/9310833/54227446-d6a10b00-44f7-11e9-9e8a-5578888cd2e2.png)

**Comment by mmbyday** [comment]
Just wondering, can you create a new blank wallet and see if the CPU is just as high? Trying to narrow down what the issue could be. Also, could try opening the wallet in simple mode.

**Comment by xhums1** [comment]
So I made a new wallet in simple mode and it is the same, immediately after I start it it goes to full cpu usage. 
![simple mode](https://user-images.githubusercontent.com/9310833/54263108-f243fa00-4567-11e9-9736-e9e4822a492f.png)

**Comment by xhums1** [comment]
what is upsetting for me is that it seams I'm the only one with this problem. I want to specify that the windows is clean (no programs other then windows update installed), the system also used the v0.13 of monero and it was working fine. Also this is a virtualbox windows

**Comment by xmrdsc** [comment]
Did you enable AMD-V or Intel VT in the bios? Is your VM using hardware virtualization? This should speed things up a bit. Even then - running inside a VM has a performance loss. What is your host CPU?

**Comment by xhums1** [comment]
Virtualization is not a problem. Again, v0.13.0.4 worked perfectly

**Comment by dEBRUYNE-1** [comment]
@xhums1 - Are you using the GUI in conjunction with a Ledger device? Also, would you be able to try it outside of a VM environment?

**Comment by dEBRUYNE-1** [comment]
@xhums1 - Also, could you try this:

>1. Click the Start button, right-click the Computer option in the Start menu, and select Properties.

>2. Click the Advanced System Settings link in the left column.

>3. In the System Properties window, click on the Advanced tab, then click the Environment Variables button near the bottom of that tab.

>4. In the Environment Variables window you can now add a new User Environment Variable. Name=MONERO_USE_CNV4_JIT / Value=1

**Comment by xhums1** [comment]
Did not try in host windows, only on guest windows on wirtualbox.
I did what you asked and it is the same. look
![Untitled](https://user-images.githubusercontent.com/9310833/54392716-4225dc80-46a0-11e9-955c-9ee44a59a9ba.png)

**Comment by dEBRUYNE-1** [comment]
Odd, it worked for someone else. Could you perhaps try on host Windows?

**Comment by xmrdsc** [comment]
Runs fine in VM here.

![https://i.imgur.com/BelnHne.png](https://i.imgur.com/BelnHne.png)

**Comment by xmrdsc** [comment]
@xhums1 Does your wallet contain a lot of transactions?

**Comment by xhums1** [comment]
no, only 16

**Comment by xhums1** [comment]
Did you update windows to the latest version? patch and all, windows update. I thing the last cumulative update screwed things up

**Comment by xhums1** [comment]
Don't get me wrong, it is not that bad, because I only need it when I do a transaction or generate an address, so it is not pain, but just wondering what did go wrong.
If I try again the v0.13.0.4 will this screw things up? Just to see if it uses high cpu like v0.14 . Don't want to make a big mistake

**Comment by dEBRUYNE-1** [comment]
@xhums1 - Can you check whether this is still an issue with GUI v0.14.1.0?

**Comment by dEBRUYNE-1** [comment]
I am going to close this as (i) the author did not respond and (ii) xiphon addressed a lot of potential freezing issues in GUI v0.14.1.0.

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by xhums1** [comment]
Yes, I know what was the problem.
At virtualbox - guest settings - display - I had VBoxVGA (this is no longer supported) and that is why monero gui always used full CPU. I changed it now to VBoxSVGA and it is working perfectly
![Untitled](https://user-images.githubusercontent.com/9310833/65067979-3ed51b80-d977-11e9-86dc-68d5316d736e.png)

**Comment by xiphon** [comment]
@xhums1 

Did you try low graphic mode? Might resolve the issue as well.

**Comment by xhums1** [comment]
Tried that and did not work. The only solution was to set the Graphics Controller to VBoxSVGA
