### ISSUE TITLE
Unable to switch wallet modes

### ISSUE THREAD

**Issue by Electricsheep01** [monero-project/monero-gui#2018]
When setting up a wallet in simple mode I am unable to then switch to other wallet modes. This should be an option so if people decide they do want to run a full node they can.

**Comment by Electricsheep01** [comment]
To add to this, when closing my wallet it seems I am unable to change wallet mode at all once I have selected one.

**Comment by selsta** [comment]
Thanks for reporting! I think this is a duplicate of #1957 though.

**Comment by xmrdsc** [comment]
+duplicate
