### ISSUE TITLE
Creating a new wallet using a hardware device has a buggy label for the restore option

### ISSUE THREAD

**Issue by weiglt** [monero-project/monero-gui#2020]
I cannot say how it's meant to look like but it's obviously broken in some way.

![mon-gui-hw-wallet-bug](https://user-images.githubusercontent.com/3670192/54460821-f3914480-476a-11e9-8e32-e52913b39c87.png)

**Comment by selsta** [comment]
This is a Qt 5.7 issue. Until it is fixed you can access the restore height text box by inserting your cursor inside the `Wallet location` text box and pressing tab once.

**Comment by dEBRUYNE-1** [comment]
#2021

**Comment by lacksfish** [comment]
Ran into the same issue, https://github.com/monero-project/monero-gui/pull/2021 should fix that

**Comment by selsta** [comment]
+resolved
