### ISSUE TITLE
GUI freezes loading large transaction history

### ISSUE THREAD

**Issue by woodser** [monero-project/monero-gui#2031]
Steps to reproduce:

1. Open a wallet with a large transaction history.  Here is a stagenet seed with such a history: `nagged giddy virtual bias spying arsenic fowls hexagon oars frying lava dialect copy gasp utensils muffin tattoo ritual exotic inmate kisses either sprig sunken sprig`
2. Click the History tab in the wallet.
3. The GUI freezes.

**Comment by selsta** [comment]
Thanks for reporting, this is a known issue. #2025 should improve this.

**Comment by dEBRUYNE-1** [comment]
As far as I know, this is resolved with the `History` page redesign (which is included in GUI v0.14.1.0). Feel free to open a new issue if it still occurs in GUI v0.14.1.0.

**Comment by woodser** [comment]
This issue is resolved in GUI v0.14.1.0.  Thanks.
