### ISSUE TITLE
GUI crashes moving from [Create a New Wallet] to [Open a Wallet from File] +label:bug

### ISSUE THREAD

**Issue by MoneroChan** [monero-project/monero-gui#2032]
Hi, it seems some data lingers around after using the [back to menu] button, 
on the [create a new wallet] screen, causing GUI to crash.
(Not sure if this will corrupt anything?)

Procedure to Replicate Crash on GUI V0.14.0.0: 

1. Start GUI 
2. Click 'Create New Wallet' 
3. Click 'BACK to Menu' button (before finishing the wallet creation)
4. Select 'Open wallet from file'  
5. Browse file system and open wallet
6. Enter password
7. GUI Crashes with " Error: Couldn't open wallet: Please Restart GUI "

Problem only occurs once you've "created a wallet" , and then click the back to menu button 
(e.g if you accidentally click create new wallet, but don't complete the wallet creation process) . Then when you try to load a wallet after it crashes.

Looks like the 'back to menu' button doesn't seem to reset the GUI state to accept a new wallet, something stored in cache/memory wasn't cleared perhaps? I'm not sure.

Hope this helps.

**Comment by dEBRUYNE-1** [comment]
Are you using the release binary or a self-compiled one?

**Comment by xmrdsc** [comment]
I followed your steps, and could not reproduce. However, `Error: Couldn't open wallet: Please Restart GUI` is a bug we've had for a while that occurs after closing and opening multiple wallets in a row. The pragmatic solution for now is to... restart the GUI.

Could you verify you are experiencing this problem after following your own steps, right after starting the GUI? My guess is you will not see the error message.

**Comment by xmrdsc** [comment]
Possible related issue: #1194

**Comment by MoneroChan** [comment]
Hi,  I'm using the release version. 

The following may also be necessary to replicate bug:
- Custom wallet directory (not the default directory) 
- Custom blockchain directory, (not default directory)
- Advanced mode 

To replicate make sure you click the 'BACK to Menu [<] ' button before you complete the wallet creation, and also use a custom wallet/blockchain save directory)

I replicated this error every time successfully. Happens every time without fail.

i'm just worried it might be a security issue since something is "lingering" when it shouldn't be under some circumstances. otherwise i'm not fussed.

Possible Solution : 
- Force the "BACK to Menu" button to completely clear entire wallet / path / GUI cache in memory.
