### ISSUE TITLE
Compiling the Monero GUI from source: On OS X: brew install boost --c++11 error

### ISSUE THREAD

**Issue by akseeker** [monero-project/monero-gui#2034]
Newb here, trying to follow the OS X compile steps.

When I copy/paste "brew install boost --c++11" I get "Install formula.", a list of options, and "Error: invalid option: --c++11"

Is there a step missing?

Thanks!

macOS High Sierra, version 10.13.6 (17G5019), Xcode Version 9.0 (9A235)

**Comment by selsta** [comment]
`brew install boost` should be enough.

**Comment by akseeker** [comment]
Thanks, that appears to be working.

Curious, why was the --c++11 used?

**Comment by selsta** [comment]
It has been like this since the beginning, see here: https://github.com/monero-project/monero-gui/commit/5b1ab69d70a29c4ddf66d5f107f621ed3340d066

I’ve updated the README in #2035.

**Comment by xmrdsc** [comment]
+resolved

**Comment by akseeker** [comment]
thanks, were the instructions on https://github.com/monero-project/monero-gui going to be changed too? (they read the same as of this email…)

Thanks

On Mar 26, 2019, at 03:28 AM, selsta <notifications@github.com> wrote:

It has been like this since the beginning, see here: 5b1ab69
I’ve updated the README in #2035.

**Comment by selsta** [comment]
Yes, the instructions will change once #2035 is merged.
