### ISSUE TITLE
[UX] Add a desktop icon for the GUI

### ISSUE THREAD

**Issue by Electricsheep01** [monero-project/monero-gui#2039]
Currently no desktop icon gets created for the GUI when downloading the Windows-64 bit version. This would make the GUI much easier to open and close which currently I have to launch it from the .exe file in the download folder.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by selsta** [comment]
Did you try the GUI installer?

**Comment by Electricsheep01** [comment]
>Did you try the GUI installer?

@selsta Oh yep that got the desktop icon though why is there an installer and the other GUI download? Shouldn’t we just have the installer and that’s it? Seems unnecessary to have the other also. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by selsta** [comment]
Let’s continue the discussion in #2038.

+invalid
