### ISSUE TITLE
balance 0 after updating monero

### ISSUE THREAD

**Issue by dradlidr** [monero-project/monero-gui#2042]
Wallet update field on monero-gui v.0.14.0.0 I do not see the coins that I had before the update. Tell me how to fix this?

**Comment by dEBRUYNE-1** [comment]
Did you create a transaction with GUI v0.13.0.4 while it was outdated?

**Comment by dradlidr** [comment]
Yes, now I do not see the transactions and coins that I had before the update

**Comment by dradlidr** [comment]
I lost the coins that I had v0.13.0.4, the transactions that were missing, they were made before hard forks

**Comment by dradlidr** [comment]
after I updated my wallet to v0.14.0.0, I don’t see old monens and transactions

**Comment by dEBRUYNE-1** [comment]
Can you try this guide? 

https://monero.stackexchange.com/questions/7993/i-forgot-to-upgrade-from-cli-or-gui-v0-13-to-cli-or-gui-v0-14-and-created-pe

**Comment by dradlidr** [comment]
I already did it, it did not help

**Comment by selsta** [comment]
Did you make sure the correct account is selected?

**Comment by dradlidr** [comment]
yes correct. I have one account

**Comment by dradlidr** [comment]
Maybe coins can be seen in the old wallet in v0.13.0.4 it does not sync

**Comment by dEBRUYNE-1** [comment]
Do you see any unauthorized outgoing transactions on the history page?

**Comment by dradlidr** [comment]
No transactions at all. which I did before hard forks. their wallet does not see them

**Comment by dradlidr** [comment]
wallet sees transactions that were after hard forks

**Comment by dEBRUYNE-1** [comment]
Is your balance correct?

**Comment by dradlidr** [comment]
decidedly. Coins appeared after recovering a purse from a mnemonic phrase. on a new computer. thank you for your response

**Comment by dEBRUYNE-1** [comment]
All right, good to hear you managed to resolve your issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
