### ISSUE TITLE
Mac Client Generated a Broken Wallet? Money lost?

### ISSUE THREAD

**Issue by bbstm** [monero-project/monero-gui#2047]
Hello,

I downloaded the Monero GUI for Mac OS X and generated a wallet, all the keys were generated successfully and I generated a QRCode of my wallet to do the transfer, from another wallet I tried to do a transfer but the  money never arrived. It was very strange, so I downloaded Guarda Wallet and tried, all transactions to this wallet (Monero Gui) can't be completed, they do a check and say the transaction failed before being processed.

Unfortunately the first wallet software did not applied this check, so it "sent" the money anyway. I used this javascript tool (https://xmr.llcoins.net/checktx.html) developed by luigi1111 to check the transaction and the result was weird, see below please:

> This address doesn't own output 0 with pubkey: [EDITED01] for amount: Confidential
> RingCT amount for output 1 with pubkey: [EDITED02] decoded incorrectly! It will not be spendable.

Also, neither [EDITED01] or [EDITED02] correspond to the public view key, public spend key or my wallet address.

Any guidance?

Thanks.

**Comment by selsta** [comment]
What was the first wallet software that you used?

**Comment by bbstm** [comment]
Not sure, it was from a transaction made online with a person from localbitcoins. BTW, he sent me the receipt.

**Comment by selsta** [comment]
Is it possible that you share your wallet address that you sent the other person?

**Comment by selsta** [comment]
That’s a valid XMR address. It doesn’t make sense that Guarda Wallet has problems sending to this address.

**Comment by dEBRUYNE-1** [comment]
Can you try these steps to verify the transaction?

1. Go to the `Settings` page of the GUI and press on `Show seed & keys`. Subsequently, copy the *private / secret* view key. 

2. Go to [this](https://xmrchain.net) blockexplorer.

3. Enter your transaction ID / hash.

4. Now search the page for `Decode outputs`. 

5. Enter your private view key. In addition, enter your address in the second box.

6. Press on decode outputs.

7. If it shows "output true" it proves you correctly received your XMR.

**Comment by bbstm** [comment]
> That’s a valid XMR address. It doesn’t make sense that Guarda Wallet has problems sending to this address, probably a problem on Guarda’s side.

Humm... but what happened with the real transaction that failed with the seller from localbitcoins?

thanks.

**Comment by bbstm** [comment]
> Can you try these steps to verify the transaction?
> 
>     1. Go to the `Settings` page of the GUI and press on `Show seed & keys`. Subsequently, copy the _private / secret_ view key.
> 
>     2. Go to [this](https://xmrchain.net) blockexplorer.
> 
>     3. Enter your transaction ID / hash.
> 
>     4. Now search the page for `Decode outputs`.
> 
>     5. Enter your private view key. In addition, enter your address in the second box.
> 
>     6. Press on decode outputs.
> 
>     7. If it shows "output true" it proves you correctly received your XMR.

I did, the output edited is below:

> Tx hash: [HashID]
> Tx public key: [TXPubID]
> Payment id (decrypted): 0000000000000000 (value incorrect if you are not the recipient of the tx)
> Block: 1800392
> Timestamp [UCT]: 2019-03-28 06:12:25
> Age [y:d:h:m:s]: 00:004:11:41:32
> Fee: 0.000034280000
> Tx size: 1.7215 kB
> Checking which outputs belong to the given address and viewkey
> address: 4526FVbLuNCA3rmwNebsMoVUNNQy35NjpfGuh46DxcTa2NpsaREpZWtKH1HWk1nqEahHgRhfrFE9FYv1tfmgXrKs16NRQkg
> viewkey: ****************************************************************
> Outputs (2)
> output public key
> amount
> output match?
> 00: c94[EDITED]79d7
> ?
> false
> 01: 635[edited]ea6a
> XX.YY0000000
> true 
> Sum XMR from matched outputs (i.e., incoming XMR): XX.YY0000000000 
> 

If I understood it properly it was transferred, but my balance still appears as zero. :(

Thanks.

**Comment by dEBRUYNE-1** [comment]
Upon installing the GUI wallet, which mode did you choose?

**Comment by bbstm** [comment]
> Upon installing the GUI wallet, which mode did you choose?

I guess full / advanced mode. I have the GUI interface and also the command-line.

Thanks.

**Comment by dEBRUYNE-1** [comment]
@bbstm - Can you perform these steps?

**[1]** Go to the `Settings` page of the GUI.

**[2]** Go to the `Log` tab.

**[3]** Type `status` into the `command + enter (e.g. 'help' or 'status')` box.

**[4]** Post the output here.

**Comment by bbstm** [comment]
> @bbstm - Can you perform these steps?
> 
> **[1]** Go to the `Settings` page of the GUI.
> 
> **[2]** Go to the `Log` tab.
> 
> **[3]** Type `status` into the `command + enter (e.g. 'help' or 'status')` box.
> 
> **[4]** Post the output here.

Sure sir.

>>> status
[4/2/19 7:08 PM] Height: 1381623/1804569 (76.6%) on mainnet, not mining, net hash 140.41 MH/s, v5, up to date, 8(out)+0(in) connections, uptime 1d 9h 0m 44s

Does it explain why the money doesnt show up?

Thanks.

**Comment by selsta** [comment]
Your blockchain is still syncing up with the network. Once it is at 100%, your funds should show up.

I’ll close this as this doesn’t seem to be a bug. Please comment if you still have problems once your blockchain is fully synced up.

+invalid

**Comment by bbstm** [comment]
> Your blockchain is still syncing up with the network. Once it is at 100%, your funds should show up.
> 
> I’ll close this as this doesn’t seem to be a bug. Please comment if you still have problems once your blockchain is fully synced up.
> 
> +invalid

Hummm.. I think it synced but still no money in balance.

> 
> >>> status
> [4/3/19 7:19 AM] Height: 1399343/1399343 (100.0%) on mainnet, not mining, net hash 273.78 MH/s, v5 (next fork in 0.9 days), up to date, 0(out)+0(in) connections, uptime 0d 2h 34m 50s
> >>> sync_info
> [4/3/19 7:19 AM] Height: 1399343, target: 1399343 (100%)
> Downloading at 0 kB/s
> 0 peers
> 0 spans, 0 MB

One thing that called my attention is that sometimes Height appear with 1399343 and sometimes 1804569 . Why?

Thanks.

**Comment by dEBRUYNE-1** [comment]
It may be accidentally reporting that you are fully synced. Perhaps it would be worthwhile to switch to `Simple mode (bootstrap mode)`? This is done as follows:

1. Go to the `Settings` page of the GUI wallet.

2. Press `Close wallet`

3. Choose `Simple mode (bootstrap mode)`

4. Reopen your wallet via the `Open a wallet from file` option.
