### ISSUE TITLE
Can't drag wallet window during password prompt

### ISSUE THREAD

**Issue by Thunderosa** [monero-project/monero-gui#2063]
The wallet keeps getting better, good job. I noticed on Windows 10 using v0.14.0.0 that whenever the password prompt is up the wallet window can't be moved.  I noticed it during a screen resolution change. I was able to key in the password and then move the window, but it occurred to me that there might be edge cases where that wouldn't be the case.

**Comment by xmrdsc** [comment]
I actually noticed this last night. Will be fixed in #2060

https://github.com/monero-project/monero-gui/blob/5dbcd714eae8bfd6e900adde6910789e5cce6613/components/PasswordDialog.qml#L65

Thanks!

**Comment by mmbyday** [comment]
Also happens on InputDialog.qml when setting a new restore height or jumping to a page on the transactions. Fix sent to #2060 :)
