### ISSUE TITLE
Starting local node screen is flickering.

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#2074]
https://streamable.com/fjuh9

Qt 5.12.1, macOS. Not related to the white theme PR. Does this happen on other platforms too?

Edit: Seems to be a Qt 5.12.1 bug.

**Comment by dEBRUYNE-1** [comment]
Does this happen with QT 5.9.x as well?

**Comment by selsta** [comment]
Not sure. I was unable to setup Qt 5.9.x on my Mac.

**Comment by mmbyday** [comment]
Sorry @selsta. It's just you, and 5.12.1 🤣 Haven't seen this before.

**Comment by xmrdsc** [comment]
@selsta Is this still happening to you? Did you update MacOS or Qt in the meantime?

**Comment by selsta** [comment]
It does not happen anymore? Maybe because I updated to macOS 10.14.5.
