### ISSUE TITLE
Hardware wallet creation screeen is distorted on macos

### ISSUE THREAD

**Issue by KushGoyal** [monero-project/monero-gui#2075]
Restore height field is hidden and the title is messed up. PFA the screenshot.

<img width="896" alt="Screenshot 2019-04-15 at 7 16 07 PM" src="https://user-images.githubusercontent.com/4709156/56137832-4309a100-5fb3-11e9-9a35-bcc402524922.png">

**Comment by selsta** [comment]
Thanks for reporting, this is already fixed in master.

+invalid

**Comment by dEBRUYNE-1** [comment]
+resolved
