### ISSUE TITLE
Building for fedora

### ISSUE THREAD

**Issue by absolutez3** [monero-project/monero-gui#2077]
These are all the packages needed to build on Fedora. Could you add to README?

sudo dnf install make automake cmake gcc-c++ boost-devel miniupnpc-devel graphviz doxygen unbound-devel libunwind-devel pkgconfig openssl-devel libcurl-devel hidapi-devel libusb-devel

**Comment by xmrdsc** [comment]
Thanks.

**Comment by dEBRUYNE-1** [comment]
+resolved
