### ISSUE TITLE
Check if updates are available

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#2089]
GUI has functionality to check if a newer version of the GUI is available, via DNS. I believe this was disabled some time ago. We should get this functionality working. 

This also has overlap with a yet-to-be-made issue about redesigning all popups/modals.

**Comment by Electricsheep01** [comment]
Wasn’t this deemed a security risk? Big + on UX but

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erciccione** [comment]
> Wasn’t this deemed a security risk? Big + on UX but

Yes, but AFAIK the CLI check for updates, it just doesn't install them. I think something like that could be done for the GUI as well.

**Comment by xmrdsc** [comment]
Update mechanism leverages DNS to fetch latest version but not auto-download.

**Comment by GBKS** [comment]
Here's a design for this modal, just in case you'd like to have one. Would it be possible to add a link to a summary of what's new in the update?

![monero-new-version-gbks-190525](https://user-images.githubusercontent.com/695901/58366052-fb890580-7ecc-11e9-8db5-e756218143d4.png)

**Comment by selsta** [comment]
@GBKS Can you upload the modal to Zeplin? Looks good.

> We should get this functionality working.

Working again.

+resolved

**Comment by GBKS** [comment]
Sorry, I don't believe I ever uploaded this to Zeplin. I recently moved my design files to Figma, which should allow you to directly inspect the designs from there. If you still want to work with this design, here's the [link to Figma](https://www.figma.com/file/DplJ2DDQfIKiuRvolHX2hN/Monero-GUI?node-id=0%3A41).

**Comment by selsta** [comment]
Does Figma show the exact measurements like Zeplin does?

**Comment by GBKS** [comment]
Yep, works almost the same way. You can click, hover and command-hover things to see all kinds of spacing. There's also a code panel on the right to see font sizes and other values. But I'm sure there are some small details that are different, let me know if anything is a big issue for you.

**Comment by selsta** [comment]
I had to signup to see all the details, nice, looks like a good Zeplin alternative. I wonder if we should add the link to the README.

**Comment by GBKS** [comment]
We can definitely do that. I published this Figma file as a community file that I can regularly push updates to and people can freely duplicate. If you want to add a link, here's the one to the [public file](https://www.figma.com/c/file/775423808468574409). I'm also planning to update my Github repo where I had the Sketch files to point to Figma. Just seems a little better suited for open-source design collaboration.

**Comment by selsta** [comment]
@GBKS I opened #2726 for it :)
