### ISSUE TITLE
GUI Will Not Quit Upon Exit, Daemon Does (Latest Master on OS X)

### ISSUE THREAD

**Issue by breadsax** [monero-project/monero-gui#2108]
I compiled from Master just now on Mac OS X High Sierra and the build went well. When I exit the GUI from any method it prompts to stop the daemon as expected, the daemon stops normally, but the GUI remains running. It will close only with a Force Quit.

**Comment by xmrdsc** [comment]
What Qt version are you using?

**Comment by xmrdsc** [comment]
Possible duplicate of #2033

**Comment by breadsax** [comment]
brew install qt5. Does seem to be a duplicate issue across OSs. Mac OS X is also native host and not on a VM

**Comment by selsta** [comment]
`brew install qt5` installs Qt 5.12.2.

+duplicate
