### ISSUE TITLE
[Trezor] - Showing passphrase does not reset

### ISSUE THREAD

**Issue by vir-satoshi** [monero-project/monero-gui#2109]
If I uncheck the showing passphrase in Monero wallet for Trezor, the modal does not reset himself after the modal was used. So when next time the modal ask you to type the passphrase, it is unchecked...

![image](https://user-images.githubusercontent.com/37402655/56656521-049c7200-6696-11e9-8aa9-b5c33f289171.png)

This is a security flaw, unintentionally you can reveal your passphrase to someone by not be aware of this feature. 

My proposal is to reset the show passphrase button every time the modal shows up. 
@ph4r05

**Comment by selsta** [comment]
Same behaviour with normal password input. I’ll fix it.

**Comment by selsta** [comment]
#2111

**Comment by ph4r05** [comment]
@vir-satoshi good catch! The proposal makes sense. @selsta thanks for the fix!
