### ISSUE TITLE
[Trezor] - Entering passphrase hint in wallet

### ISSUE THREAD

**Issue by vir-satoshi** [monero-project/monero-gui#2110]
During the process of entering the passphrase in the Monero wallet, the T2 (Trezor T) device asks "Where to enter your passphrase?" question on the T2 display. During that process, the Monero wallet has only the "Opening wallet" dialog loading. 

![image](https://user-images.githubusercontent.com/37402655/56658140-2566c680-669a-11e9-8a41-66ec3bf7f8d4.png)

It would be really user-friendly if during this process the wallet could show a message to complete an action on the Trezor device, letting know the user to check the device display. 

I have attached a Trezor wallet solution for reference.

![image](https://user-images.githubusercontent.com/37402655/56658470-f7ce4d00-669a-11e9-8749-5166b6137b91.png)
@ph4r05

**Comment by selsta** [comment]
@ph4r05 

+enhancement

**Comment by ph4r05** [comment]
This should be already implemented with the current monero.git master and monero-gui.git master. All PRs are merged, pls rebuild and try again.

**Comment by dEBRUYNE-1** [comment]
@vir-satoshi - Can you perform it works properly with monero master & monero-gui master?

**Comment by selsta** [comment]
I can confirm that this is working.

<img width="1026" alt="Screenshot 2019-04-30 at 13 25 21" src="https://user-images.githubusercontent.com/7697454/56958737-70298800-6b4b-11e9-854a-dba3be176de6.png">

+invalid
