### ISSUE TITLE
Use qt5 from brew for OSX

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero-gui#212]
Currently brew qt5 formula contains qt5 `5.7.0`. Can be installed with `brew install qt5`.
It's keg-only so bins are not in `PATH` by default. Can be linked with `brew link qt5 --force` but it seems a bit dirty. There is a hint in formula info:

```
Qt 5 conflicts Qt 4
Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

LDFLAGS:  -L/usr/local/opt/qt5/lib
CPPFLAGS: -I/usr/local/opt/qt5/include
PKG_CONFIG_PATH: /usr/local/opt/qt5/lib/pkgconfig
```

I believe it's way better to follow this instructions instead of installing Qt5 using official installer from qt.io.

**Comment by sammy007** [comment]
Also, I added brew formula to my tap https://github.com/sammy007/homebrew-cryptonight

```
brew install monero-core --HEAD
brew linkapps monero-core
```

Feel free to add to readme.

**Comment by Jaqueeee** [comment]
agree. Haven't tested myself but if qt5 from homebrew works it's easier to use that.

**Comment by sammy007** [comment]
Also I found that `brew install boost --c++11` is not mandatory, you can use stock bottled boost `brew install boost` without compiling it.

**Comment by maitscha** [comment]
I can confirm that the `brew` Qt 5 build also works on my MacOS 10.11.6:

```
brew install qt5
brew link qt5 --force
```

**Comment by Jaqueeee** [comment]
Deployment is broken on current homebrew qt. https://github.com/Homebrew/homebrew-core/issues/3219

Until that issue is solved upstream we should stick to official qt binaries.

**Comment by sammy007** [comment]
Deployment? You don't need deployment if you compile it for yourself.

https://github.com/sammy007/homebrew-cryptonight#monero-core-qt-gui

**Comment by Jaqueeee** [comment]
I think some users would expect it to run on machines without Qt installed. Even when they compile themselves. We could have brew method in instructions + a note that official binaries are needed for deployment.

**Comment by sammy007** [comment]
They can expect everything, whole homebrew does not work this way.

**Comment by sammy007** [comment]
Just in case you don't completely understand my point, everything in homebrew is dynamically linked, it's like a gentoo, you can't redistribute binary bundles, only bottles, bottles requires all dependencies to be installed via brew also, can help to avoid compilation of formulas with common options. If someone want to do "deployments" (play coredev role) they must not use homebrew or perform extra steps to make that possible.

**Comment by Jaqueeee** [comment]
@sammy007 Got it! You're welcome to PR that readme update ofc.

**Comment by jonathancross** [comment]
Thanks @sammy007, this is great that we have a way to install monero-core via Homebrew.

> You're welcome to PR that readme update ofc.

@Jaqueeee I'm happy to help out with this.  Is the idea to just add the brew tap/ install commands to the monero-core README?

While we are on the subject, would it make sense to create a monero-specific a fork under `monero-project/...` ?
I suspect users would prefer to add a tap from `monero-project/brew-tap` so they can be sure it is the correct tap.

Thoughts?

**Comment by sammy007** [comment]
If only it still works, can't check ATM.

**Comment by Jaqueeee** [comment]
@jonathancross, yes, I think it would be best to add the brew taps to official repo before updating Readme. We need someone in the core team to help us with this. ping @fluffypony @luigi1111

**Comment by BigslimVdub** [comment]
Hello? 
Brew installing qt 5.11 now but doesn’t like compiling on high Sierra. Have you updated brew? 
I added all 5 variables as brew suggested post install but still no dice.

**Comment by selsta** [comment]
The instructions recommend using brew.

+resolved
