### ISSUE TITLE
[Trezor] - Proceed to device not shown after TX signature

### ISSUE THREAD

**Issue by ph4r05** [monero-project/monero-gui#2123]
After the spending transaction is signed with the Trezor, GUI prompts for a wallet password and freezes, as Trezor device expects user input (accept live refresh request). GUI does not show "Proceed to the device" splash from some reason.

After the user clicks the Trezor button process continues normally.
I will try to address this but if you happen to know why is it happening it might be useful. Thanks! :)

**Comment by ph4r05** [comment]
I think I found the reason - `transaction.commit()` is blocking call, this prevents the popup from showing.

**Comment by ph4r05** [comment]
@selsta @xmrdsc @xiphon do you think it would be beneficial to make an async wrapper for the PendingTransaction.commit() and commit in async way?

**Comment by selsta** [comment]
I know nothing about async, would there be any downsides? If not, it probably would be beneficial.

**Comment by xiphon** [comment]
> do you think it would be beneficial to make an async wrapper for the PendingTransaction.commit() and commit in async way?

Sure, async wrapper would definitely be beneficial.

**Comment by selsta** [comment]
Seems resolved.
