### ISSUE TITLE
Show a wallet's restore height more prominently

### ISSUE THREAD

**Issue by mmbyday** [monero-project/monero-gui#2126]
Specifically in the wizard > create new wallet screen
and in the keys page.

These are two opportunities for the user to backup this salient piece of data which will lead to a better experience when restoring their wallet. Not having proper restore height data can cause undue user frustration and leave a poor wallet impression.

+proposal

**Comment by xmrdsc** [comment]
+enhancement

**Comment by GBKS** [comment]
This has probably been already discussed, but is there no better name for "restore height"? Maybe something like "Wallet creation block number"?

**Comment by mmbyday** [comment]
Good point @GBKS Wallet creation block number is more descriptive and self-evident. Restore height is likely a legacy term from the beginning of time. There's other terms that could use clean up in the wallet. One that I can recall is secret key vs. private key. There's actually an issue on this one https://github.com/monero-project/monero-gui/issues/1064

**Comment by selsta** [comment]
CLI uses the term restore height. Not sure if we should aim to stay consistent with it.

**Comment by erciccione** [comment]
*restore height* is used everywhere (other wallets, guides, moneropedia, etc). Changing the term only in the GUI would cause a lot of confusion for the users. The term should stay consistent across all Monero projects.
 
So, if changed here, *restore height* should be changed everywhere. I don't see any strong reason to go trough this process.
