### ISSUE TITLE
monero-wallet-gui.app/Contents/MacOS/monerod (which was built for Mac OS X 10.12) crash

### ISSUE THREAD

**Issue by Afron-Lysias** [monero-project/monero-gui#2159]
`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
crashed on child side of fork pre-exec

Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Users/USER/*/monero-wallet-gui.app/Contents/MacOS/monerod (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
`

**Comment by xmrdsc** [comment]
> clock_gettime() was added in macOS 10.12.You need to build against an earlier SDK if you want to be backwards compatible.

**Comment by selsta** [comment]
+resolved with using a macOS 10.11 build.

**Comment by dEBRUYNE-1** [comment]
+resolved
