### ISSUE TITLE
OSX: Don't quit whole app

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero-gui#216]
It's way better to not quite whole application if "x" is clicked in window decoration, just hide window, let it remain running.

**Comment by Jaqueeee** [comment]
i think most people will get confused if 'X' doesn't quit the app. It would also add a security risk if wallet stays open when user thinks it's closed.

**Comment by sammy007** [comment]
Jst to make it clear, CMD+W has no effect and it's expected that "close" button will behave like Cmd+W. if you need to totally quit app you can use Cmd+Q to make user experience unobtrusive.

**Comment by Jaqueeee** [comment]
I see. Those shortcuts are mac specific and that behavior is not expected on other platforms. For now the GUI works the same on all platforms but we could add platform independent stuff later on.

**Comment by sammy007** [comment]
Yeah prolly with swapping decoration buttons because it's kinda looks not native.

**Comment by Jaqueeee** [comment]
#225 replaces black top bar with native bar. But the exit button still works the same AFAICT.

**Comment by SilverPin** [comment]
I just want to support this as another mac user. The x button on a mac usually closes the screen rather than the programme. We're a strange breed, but it is what we're used to.

**Comment by jonathancross** [comment]
> All existing wallets behave like this, Hive, Bitcoin-Qt and so forth.

FWIW: I just tested Electrum and see that clicking the red close button or using `⌘w` or `⌘q` all have the exact same effect -- completely close the application. Picasa too.  KeepassX will quit if the user clicks the close button, but `⌘w` will not hide or close the window.  They are all single-window apps like Monero.

GPG Keychain, Photoshop, act as described above.

Seems to me that this behavior is not all that consistent...

**Comment by rex4539** [comment]
Any updates on this?

Standard MacOS behavior when clicking the X button is to just close the main window.

Unless my understanding is totally off, implementing this is just connecting the action to `close()`

**Comment by selsta** [comment]
Apps that support multiple windows have this behaviour. monero-gui does not support multiple windows so it closes when clicking on X. This is inline with the e.g. native Notes.app.

We also use Qt instead of AppKit so implementing the requested feature is difficult.

+wontfix
