### ISSUE TITLE
Add lupdate to building process

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-gui#2160]
Would be great to include `lupdate` in the building process right before the language files are built. This would resolve the sync problems happening when something change in the code and consequently the referred string in the language files (`/translations`), causing the string getting ignored in the compiled wallet, even if correctly translated.

This was solved in past by resyncing all language files before tagging a release. Including the resync with lupdated every time the wallet is built is a better and cleaner solution.

The command that should run is:
```
lupdate -pro monero-wallet-gui.pro -ts translations/monero-core_*.ts -no-obsolete
```

*As discussed in the meeting of the Lcalization Workgroup (monero-ecosystem/monero-translations#51).*

**Comment by erciccione** [comment]
+enhancement

**Comment by selsta** [comment]
One thing to note is that it can get pretty annoying with merge conflicts if translation file changes are included with with every commit.

**Comment by erciccione** [comment]
I'm not sure of what you mean. There wouldn't be any conflict or commit, it would be just a refresh of the language files during the compilation process. No git involved

**Comment by mmbyday** [comment]
@erciccione Does that PR close this issue? :-)

**Comment by erciccione** [comment]
Left a comment in #2189 . Yes, that PR will resolve this issue.
