### ISSUE TITLE
visual studio buld

### ISSUE THREAD

**Issue by cchalifo999** [monero-project/monero-gui#2166]
Is there a way to bulid with visual studoio

**Comment by xmrdsc** [comment]
Maybe. https://devblogs.microsoft.com/cppblog/bring-your-existing-qt-projects-to-visual-studio/

**Comment by cchalifo999** [comment]
> 
> 
> Maybe. https://devblogs.microsoft.com/cppblog/bring-your-existing-qt-projects-to-visual-studio/

ty for your help

**Comment by xmrdsc** [comment]
Closing for now.

+resolved
