### ISSUE TITLE
String gets picked for translations, but there isn't anything to translate and results empty

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-gui#2172]
For some reason [line 91 in Transfers.qml](https://github.com/monero-project/monero-gui/blob/master/pages/Transfer.qml#L91) gets picked as translatable. The problem is that it's not a translatable string and it will be shown as empty to translators.

See on Pootle:
![pootle-empty-string](https://user-images.githubusercontent.com/28106476/58017803-661ef780-7b01-11e9-9043-c0e26c3583f9.png)

If checked manually with QTlinguist, it's labelled as *context comment*: 
![empty-string-linguist](https://user-images.githubusercontent.com/28106476/58017818-6fa85f80-7b01-11e9-9560-6e7c1898dfa3.png)

The problem is still there after pulling master and refreshing the language files. Moving the comment outside the function didn't help.

**Comment by selsta** [comment]
`// @TODO: ...` is used in various places, I don’t see any reason for it getting picked up as a context comment here :/

**Comment by selsta** [comment]
@erciccione Is this still happening?

**Comment by erciccione** [comment]
No, i forgot to close the issue :)
