### ISSUE TITLE
"dict-src.h" is missing

### ISSUE THREAD

**Issue by MrKrisWang** [monero-project/monero-gui#2181]
The sentence "#include 'dict-src.h' " occurs in  "zxcvbn.c",but i could not find this file throughout all folders.Is there any details i can notice?

**Comment by xiphon** [comment]
`dict-src.h` is auto-generated during `zxcvbn-c` build. 

https://github.com/monero-project/monero-gui/blob/master/src/zxcvbn-c/README.md
> The dict*.h and zxcvbn.dict files are generated by the dictgen program compiled from dict-generate.cpp (see makefile for details).

**Comment by MrKrisWang** [comment]
> 
> 
> `dict-src.h` is auto-generated during `zxcvbn-c` build.
> 
> https://github.com/monero-project/monero-gui/blob/master/src/zxcvbn-c/README.md
> 
> > The dict*.h and zxcvbn.dict files are generated by the dictgen program compiled from dict-generate.cpp (see makefile for details).

Thanks a lot for yours comment. I have read "readme.md" and after that, i run qmake makefile stored in "monero-gui-master\src\zxcvbn-c\" without changing any file. But i received errors like "Extra characters after test expression". The platform i use is Qt5.12.2 on Windows7 and compiler is MinGW 7.3.0. Could you give me some tip?

**Comment by xiphon** [comment]
You have to run `make`

**Comment by xmrdsc** [comment]
+resolved
