### ISSUE TITLE
[TREZOR] Feature request: Display address on device

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2184]
In Trezor's Bitcoin web wallet, I can click a button that displays the receiving address on Trezor's screen, confirming that it was actually created on my device. Also, I can display a QR code with the receiving address on Trezor's screen.

This function is missing on monero-gui.

@ph4r05

**Comment by ph4r05** [comment]
This is a good point! I will take a look at it.

**Comment by ph4r05** [comment]
PRs are laced. Once both are merged I can make GUI PR.
