### ISSUE TITLE
Support full screen mode in OSX

### ISSUE THREAD

**Issue by xhipster** [monero-project/monero-gui#2191]
I understand that this is a minor usability issue, but it seems that Monero GUI is the only blockchain application out of dozen in my system which do not support full-screen mode. Any chance to fix this?

<img width="762" alt="Screenshot 2019-06-01 at 16 38 55" src="https://user-images.githubusercontent.com/410789/58749898-ce6bc280-848b-11e9-8090-e06fe58792fb.png">

**Comment by selsta** [comment]
The next release will support full screen mode on macOS. You’ll have to disable “Custom decorations” inside settings though.

**Comment by selsta** [comment]
+resolved
