### ISSUE TITLE
windows gui 14.0.0 no balances

### ISSUE THREAD

**Issue by finehobby** [monero-project/monero-gui#2195]
After installing version 14.0.0 under windows I created a new wallet using with ledger nano. (previously 13.0.4 used without problems). You can't set the restore hight and no balances are displayed after the synchronization? I tried both: simple mode and bootstrap.
I ask for help

**Comment by dEBRUYNE-1** [comment]
Try this guide:

https://monero.stackexchange.com/questions/10598/how-do-i-restore-recreate-my-ledger-monero-wallet

**Comment by finehobby** [comment]
thank you for the link, but this is my problem, in the guid i read:
_Note: Use this work around if you cannot access the Restore height box:
There is a fix for the time being: You can access the restore height window by selecting the wallet location and pressing tab once._
what does it mean : "wallet location"? i dont find this place, where i can press the tab to put in the restore heigth?

**Comment by dEBRUYNE-1** [comment]
It is the wallet location box, see box (2) of this screenshot:

https://github.com/monero-ecosystem/monero-GUI-guide/raw/master/media/create_hardware_wallet.png

**Comment by finehobby** [comment]
yes this was the solution, it worked and i see balances, thank you for help.
Another question: everytime when I open the .exe i must do this procedure with create a new wallet from hardware? The old Version 13.0.4 started with asking pasword and then found the wallet. Now begins with language and Mode selection?

**Comment by dEBRUYNE-1** [comment]
@finehobby - No, it should open your Ledger Monero wallet automatically. Did you make sure to exit the wallet properly? That is:

>It's imperative that the closing process of your Ledger Monero wallet is done in this specific consecutive order:

>[1] Exit the GUI by clicking on the x (right top).

>[2] Exit the Ledger Monero app.

>[3] Unplug the Ledger device.

**Comment by finehobby** [comment]
Hello, but I really finished the wallet. That can't be it. It's curious, because with version 13.0.4 it works fine and after the start you are asked for the password and the balance is there. But with version 14.0.0 I have to recreate the wallet every time. Had also deleted everything from the PC in the meantime. But what is strange, when creating a new wallet, the old wallet name is always given. I don't know where it is stored on the PC?

Translated with www.DeepL.com/Translator

**Comment by dEBRUYNE-1** [comment]
>I don't know where it is stored on the PC?

On Windows the files should be stored in `Documents\Monero`, can you check if the wallet files of the *new* Ledger Monero wallet are actually stored there?

**Comment by dEBRUYNE-1** [comment]
I am going to close this, as the author has not responded for ~4 weeks.

**Comment by dEBRUYNE-1** [comment]
+resolved
