### ISSUE TITLE
Switch GUI node aggregator service to privacy aware hosting

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#2203]
https://autonode.xmr.pm is our node aggregator for Simple Mode inside the GUI. This centralised functionality will be replaced by xiphon soon. Till then, we have it hosted in The Netherlands, EU at a company called TransIP B.V (transip.nl).

I would like to switch hosting to https://ovo.sc/ for the following reasons:

### Benefits:

- Datacenter in Seychelles, Africa. Outside of EU jurisdiction.
- Unmanaged free speech hosting
- Payment methods are exclusively Bitcoin / Monero

### Downsides:

- Servers might not be as stable (as 'regular' hosters), however, I don't expect much downtime.
- Higher chance of being shutdown/raided due to the nature of unmanaged free speech hosting. But since the application I'm planning to host is not difficult to setup, I can quickly pivot to another hoster when necessary.

To conclude, I believe moving autonode.xmr.pm to a country that's not in the US/EU will harden privacy/decentralisation for any user using Simple Mode.

**Comment by selsta** [comment]
Are the servers in Romania or Seychelles?

**Comment by xmrdsc** [comment]
Seychelles

**Comment by SamsungGalaxyPlayer** [comment]
I have no strong opinion.

**Comment by selsta** [comment]
Closing as we don’t use a node aggregator currently.

+invalid
