### ISSUE TITLE
Create a new password dialog

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#2204]
There are 3 QML components for displaying a password dialog.

```bash
$ ls components | grep -i pass
NewPasswordDialog.qml
PassphraseDialog.qml
PasswordDialog.qml
```

Should be combined into one, modular QML component.

**Comment by Realchacal** [comment]
Not 100% sure if this belongs here:
![image](https://user-images.githubusercontent.com/46682965/59261898-87758e00-8c3e-11e9-8999-cb995a412fde.png)

Reasons:

A) Clicking on "Change wallet" doesn't change your wallet, it just takes you back to the window before, where you can do many things, FOR EXAMPLE changing your wallet.

B) The wording can be misinterpreted like this: When a user actually closes his wallet to open another wallet, he may think "Does I have to click 'change wallet' to confirm that I actually want to change my wallet?" (Of course not; He has to click "Continue" to change his wallet! How strange.)

**Comment by selsta** [comment]
+resolved
