### ISSUE TITLE
MoneroComponents.StandardDropdown should include labelText

### ISSUE THREAD

**Issue by cdiv1e12** [monero-project/monero-gui#2205]
QML API for the following 2 components: `lineEdit` and `lineEditMulti` both have a `labelText` property that functions as the label text, displayed above the aforementioned components.

`MoneroComponents.StandardDropdown` however, does not have a `labelText` property. If you want text above a `StandardDropdown`, it is necessary to include it within a `Layout.ColumnLayout` and use a `Text {}` field there.

Which results in PRs like this: https://github.com/monero-project/monero-gui/pull/2198

On-going effort for me is 'standardization' of our existing components in order to create an uniform API.

In addition, I believe our current dropdown component has some layout issues as observed here: https://github.com/monero-project/monero-gui/blob/68c7cf7276b8192ef800e3ab8fcc51815fb9c1cc/pages/settings/SettingsLayout.qml#L193

The layout of the language picker dropdown box is wrong.

Another example below.

https://github.com/monero-project/monero-gui/blob/68c7cf7276b8192ef800e3ab8fcc51815fb9c1cc/pages/Transfer.qml#L184-L220

Which, ideally, would be rewritten to:

```QML
         MoneroComponents.StandardDropdown { 
             Layout.fillWidth: true 
             labelText: qsTr("Transaction priority") + translationManager.emptyString
             id: priorityDropdown 
             Layout.topMargin: 5 
             currentIndex: 0 
         } 
```

**Comment by selsta** [comment]
> In addition, I believe our current dropdown component has some layout issues as observed here:

Can you make a screenshot of the layout issue?
