### ISSUE TITLE
Contradictory statements on daemon synchronization

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2207]
![monero1](https://user-images.githubusercontent.com/46682965/59201785-76277580-8b9b-11e9-99d2-701809b7ec25.jpg)

Edit: MAYBE the screenshot was a result of me not having pressed "Export View Key" on my Ledger Nano S. Not sure if I missed that. Edit2: This theory is WRONG.

**Comment by dEBRUYNE-1** [comment]
>Edit: MAYBE the screenshot was a result of me not having pressed "Export View Key" on my Ledger Nano S. Not sure if I missed that.

Can you try to reproduce this behavior?

**Comment by Realchacal** [comment]
1.) My theory that it has something to do with me not having pressed "Export View Key" is WRONG.
2.) I didn't manage to reproduce the behavior WITH MY STANDARD WALLET because everything happens too fast now since it's up to date.
3.) I DID manage to reproduce the behavior with creating a new hardware wallet. Directly after creating the hardware wallet everything was fine: It was working on the "Wallet blocks remaining: 12345" and no "Waiting on daemon synchronization to finish" was shown. Nice. But now I closed the GUI and opened it again: Then we have the situation shown in the screenshot.

**Comment by Realchacal** [comment]
I close this because I think this is just a small symptom of the real issue #2304. Also because I can't reproduce.
