### ISSUE TITLE
Wrong wording when setting new password for new wallet from hardware

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2211]
The marked text is wrong for new wallets **from hardware**:

![monero 5](https://user-images.githubusercontent.com/46682965/59260285-9eff4780-8c3b-11e9-90f9-1ea44d202179.JPG)

Proposed wording:
"If you forget it then the wallet will have to be restored from your 25 word mnemonic seed or your hardware wallet."

**Comment by dEBRUYNE-1** [comment]
Good suggestion, thanks!

**Comment by notmike-5** [comment]
#2236

**Comment by notmike-5** [comment]
#2236
