### ISSUE TITLE
Overlapping text in dialog with "Subaddress lookahead/ restore height"

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2212]
![Monero 6](https://user-images.githubusercontent.com/46682965/59263601-a6c1ea80-8c41-11e9-8618-ad65411b97e8.jpg)

Windows 10 reboot doesn't fix it.

**Comment by dEBRUYNE-1** [comment]
This has already been fixed in master.

**Comment by dEBRUYNE-1** [comment]
+resolved
