### ISSUE TITLE
Hook into URI scheme on, eg, Android, iOS

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero-gui#222]
I've no idea how that'd technically work, but:

- the GUI now shows a QR code for simple payment
- there are now RPC and wallet2 API for parsing a monero: URI

So there needs to be a way for the wallet to register itself as a handler for monero: URIs. When invoked, this should call the wallet2 API (tools::wallet2::parse_uri) to get back the constituents, then call the transfer function with those, and ensure a user prompt will be made.

**Comment by johnalanwoods** [comment]
This is trivial on iOS and macOS. Will investigate on Android.

**Comment by erciccione** [comment]
@moneromooo-monero is still also present in new GUI or can be closed?

**Comment by erciccione** [comment]
@moneromooo-monero This looks fixed in #2029. Please reopen if necessary.

+resolved
