### ISSUE TITLE
[WINDOWS] No success on building 0.14.1 tag

### ISSUE THREAD

**Issue by JochananCZ** [monero-project/monero-gui#2233]
I have tried to build it from the scratch. I have followed the manual on the mainpage up to the point of the building. I did a command

source ./build.sh release-static 

Which after some time just closed the MSYS2 console. When i reopened and try to process with another step (linking), it just fails.

I have redirected output to the textfile (see the attachment)
[build.log](https://github.com/monero-project/monero-gui/files/3318519/build.log)

**Comment by selsta** [comment]
I don't see any errors in your logs.

If you want a Windows build and don’t want to wait on the official release you can use the buildbot (`buildbot/monero-gui-win64`) from here: https://github.com/monero-project/monero-gui/pull/2218

**Comment by xiphon** [comment]
* Could you check whether the file `/home/User007/monero-gui/build/release/bin/monero-wallet-gui.exe` exists or not?
* Run `./build.sh release-static` (without `source`)

**Comment by JochananCZ** [comment]
> Could you check whether the file /home/User007/monero-gui/build/release/bin/monero-wallet-gui.exe exists or not?

Folder is empty
> Run ./build.sh release-static (without source)

At least have not crashed and gave me this errors
> E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwallet_merged
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llmdb
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lepee
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lunbound
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -leasylogging
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile.Release:453: release/bin/monero-wallet-gui.exe] Chyba 1
make[1]: Opouští se adresář „/home/User007/monero-gui/build“
make: *** [Makefile:38: release] Chyba 2

**Comment by xiphon** [comment]
It failed to build monero core. Please attach the complete log

**Comment by JochananCZ** [comment]
I was not able to obtain complete log (> output only non errors), but these are errors, that appeared on the build console:
[build.log](https://github.com/monero-project/monero-gui/files/3319511/build.log)
There is a problem with OpenSSL
> Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the

**Comment by xiphon** [comment]
> Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the

Did you install mingw-w64-x86_64-openssl package?

**Comment by JochananCZ** [comment]
Yes, i did. I even checked when I saw that error (when I tried to install it again, it told me, that it is already there)

**Comment by xiphon** [comment]
> > output only non errors

use ` > build.log 2>&1`

**Comment by JochananCZ** [comment]
[build.log](https://github.com/monero-project/monero-gui/files/3321170/build.log)

**Comment by TomBPotochek** [comment]
I was having the same problem. Then I tried using ./build as well and managed to finish without the mysys window closing. After cd-ing to build/ and doing a `make deploy` I was getting something like `cannot 'stat' over '/mingw64/bin/libicudt62.dll': No such file or directory` but was able to fix it by editing the 'windeploy_helper.sh' file and changing this line 
`ICU_FILES=(libicudt62.dll libicuin64.dll libicuio62.dll libicutu62.dll libicuuc62.dll)` 
to
`ICU_FILES=(libicudt64.dll libicuin64.dll libicuio64.dll libicutu64.dll libicuuc64.dll)`.
I'm not sure if this is your same issue as I could not find references to this in your logs though.

**Comment by selsta** [comment]
Please check if this is fixed with v0.15.0.0.

**Comment by selsta** [comment]
#2677

+invalid
