### ISSUE TITLE
v0.14.x.x High CPU Usage on Linux

### ISSUE THREAD

**Issue by EmbeddedAndroid** [monero-project/monero-gui#2238]
Every since upgrading from the v0.13.x.x  to the v0.14.x.x GUI release, I've noticed very high CPU utilization when running the GUI. On an Intel quad core i7, I'm seeing constant 80% CPU utilization on each of the four cores.

![Screenshot 2019-06-29 at 11 55 24 AM](https://user-images.githubusercontent.com/1061011/60388348-dc017180-9a64-11e9-8d42-a6d29bf4f994.png)

![Screenshot 2019-06-29 at 11 56 20 AM](https://user-images.githubusercontent.com/1061011/60388355-08b58900-9a65-11e9-9bd8-c00956e0d6e6.png)

I'm using a fully sync'd local daemon, configured as a remote node in the GUI. Installed using the prebuilt binaries, and the start-gui.sh script. 

Please let me know what information about the running process that would be helpful to have to debug!

**Comment by selsta** [comment]
Weird, normally CPU usage shoudn’t be noticeable. Is your wallet refreshing? Does this also happen while being inside the wizard? Does this happen with a fresh wallet?

**Comment by xmrdsc** [comment]
Currently you benchmark both `monero-wallet-gui` and `monerod` at the same time. This makes little sense, from a bug reporting perspective, as we now don't know if the reported CPU usage is due to the GUI or the local node :)

Please kill `monerod` and try again.

**Comment by xmrdsc** [comment]
In addition, please note `monerod` *could* be doing a database migration.

**Comment by EmbeddedAndroid** [comment]
Sorry if I wasnt clear but ```monerod``` is running on another machine and I'm using the GUI to connect to over a local network.

**Comment by xmrdsc** [comment]
Ok, thanks for clarification.

1. Is your wallet refreshing blocks?
2. Does this also happen inside the Wizard? (the main menu, wallet closed)
3. Are you using a virtual machine?
4. Do you have a graphics card + drivers installed? (GUI uses hardware acceleration via OpenGL)
    - If not, try launching the GUI like this: `QMLSCENE_DEVICE=softwarecontext ./monero-wallet-gui`
5. Please state your exact CPU model and Linux distribution version.

**Comment by EmbeddedAndroid** [comment]
Thanks for the help, it seems ```QMLSCENE_DEVICE=softwarecontext ./monero-wallet-gui``` was the trick here. 

I'm now seeing less than 2% CPU utilization on all four cores. 

I'll admit my setup is a bit unconventional, running a Chromebook, using crostini (kvm + oci runtime) providing a Debian vm/container and running the GUI from that. So there is no GPU available to the host that is running the GUI, makes sense why it was running up the CPU now.

If anyone is curious, here is the repo for running the GUI on a Chromebook with crostini: https://github.com/fnodes/monero-gui-crostini

I'm going to close this now, thanks again for the help!

**Comment by adrelanos** [comment]
This wasn't fixed. Please re-open.

I also have 100% CPU using monero GUI `v0.15.0.4` in a VirtualBox VM (Whonix-Workstation). It's just the first screen (language selection screen). No monero installed ever in that VM before.

`QMLSCENE_DEVICE=softwarecontext ./monero-wallet-gui` helps as a workaround but it's not a solution. Users shouldn't be required to figure that out the hard way. Should be the default or some other fix.

Also my CPU use is now down to 30% which still seems to much for just an idle language selection screen.

**Comment by adrelanos** [comment]
Thanks!

(Looks like a new ticket was created instead of re-opening the old one: https://github.com/monero-project/monero-gui/issues/2878 )
