### ISSUE TITLE
GUI  start delay

### ISSUE THREAD

**Issue by maogo** [monero-project/monero-gui#2239]
v0.14.1.0 Windows GUI, 64-bit

.exe  start delay almost 4-5 seconds，If it is generally existed, can add a loading page ?

My PC: Windows 10 , Ryzen 1800X ，16 GB RAM, SSD.

**Comment by selsta** [comment]
When is the 4-5 seconds delay happening?

**Comment by selsta** [comment]
It takes ~4.5 seconds on a 2014 MacBook Pro from double clicking the .app until the GUI is fully loaded.

Should be faster with your specs.

**Comment by maogo** [comment]
I just tested it again
clicking the gui.exe until the wallet form visible, around 6 seconds  !!!??

PC status:  cpu 10% left ,  RAM 50% left   ,disk 0-10%

**Comment by selsta** [comment]
Can you compare it to v0.14.0.0? Did it get slower?

**Comment by maogo** [comment]
@selsta  Sorry for late reply. 

v0.14.0.0 or earlier are also the same slow(wait 4-5 sec or more) for me ,  I always  thought that's a UX  

problem... So, what is the normal value that  startup on windows 10?

**Comment by selsta** [comment]
We are using Qt/QML, which is slow on startup compared to pure C++ programs. Not a lot we can do about this. https://blog.qt.io/blog/2019/01/11/qt-5-12-lts-road-faster-qml-application-startup/ has some suggestions.

**Comment by maogo** [comment]
Ok get it
