### ISSUE TITLE
[Trezor] Trezor not being detected on macOS

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2243]
Latest GUI (0.14.1 beta) is not detecting Trezor Model T (firmware v2.1.1) on macOS 10.14.3 (Mojave).
The device is working fine on online Trezor beta wallet.

@ph4r05

**Comment by selsta** [comment]
Can you try restarting your Mac? Also make sure that the you don’t use the Trezor web wallet at the same time (close your browser).

**Comment by rating89us** [comment]
It still not working after restart. Trezor web wallet isn't being used at the same time.
Error: "failed to generate wallet: Device connect failed"

**Comment by rating89us** [comment]
I discovered what was wrong. Trezor bridge was not installed.

**Comment by ph4r05** [comment]
@Selsta is the GUI binary compiled with libusb library? It should work also without Trezor bridge :/

**Comment by selsta** [comment]
@ph4r05 I don’t know but this is the first time I’m hearing about libusb so most likely not.

**Comment by ph4r05** [comment]
When I build it locally it works with libusb compiled in, but we would have to verify if released versions have the libusb compiled.

**Comment by dEBRUYNE-1** [comment]
@ph4r05 - Can you perhaps check with the beta v0.14.1.0 Mac OS binary?

https://github.com/monero-project/monero-gui/releases/tag/v0.14.1.0

**Comment by ph4r05** [comment]
@dEBRUYNE-1 how were the GUI binaries built pls? With the `build.sh`?

**Comment by ph4r05** [comment]
I've checked the binary and apparently it does not link `libusb`. 
There are no symbols related to the `libusb` / `webusb` transport in the statically linked monero-core.

-> Thus `WITH_DEVICE_TREZOR_WEBUSB` macro was not defined during the build 
-> `HAVE_TREZOR_LIBUSB` was not defined by the Cmake
-> CMake could not detect usable libusb, 1.0.18+ should be OK.

The resolve logic is handled by `cmake/FindLibUSB.cmake` and `cmake/CheckTrezor.cmake`.

Successful resolution should yield following lines from Cmake:

```
-- LibUSB Compilation test: TRUE
-- Trezor compatible LibUSB found at: /usr/local/Cellar/libusb/1.0.21/include/libusb-1.0
```

The monero-core build is handled by `get_libwallet_api.sh`, its Cmake output should indicate whether libusb is included or not.
