### ISSUE TITLE
When creating a wallet in Simple Mode with no internet, the GUI hangs after prompting for a password

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-gui#2252]
It's looking for remote nodes and after a while it says "No remote nodes found" (something akin to that), but during the search the user has no idea what is going on, simply that "Next" isn't functioning.

**Comment by selsta** [comment]
Works fine on my system. Can you post the exact steps to reproduce?

**Comment by xmrdsc** [comment]
context;
https://github.com/monero-project/monero-gui/blob/5f38dbb7dd3c25755427b103ae389ccc619b6c42/wizard/WizardController.qml#L566

**Comment by dginovker** [comment]
Looking closer, it seems this happens when internet is connected, but can't do anything meaningful because it's too slow or has other issues. In this case, you click "Next" and the GUI appears to do nothing. If the internet is fully unplugged, the GUI will immediately notify you.

**Comment by xmrdsc** [comment]
Made an issue.

**Comment by selsta** [comment]
We don't use this system for simple mode anymore, thus closing.
