### ISSUE TITLE
When testnet/stagenet is enabled and you're selecting Wallet Mode, you can't select Simple Mode or Simple Mode (Bootstrap) without first entering Advanced Mode > Advanced Options and changing your network

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-gui#2253]
This is rather unintuitive; while hiding away Testnet/Stagenet is good for UX, it could be more clear how to leave testnet/stagenet _when_ it's enabled

**Comment by selsta** [comment]
Thanks for your suggestion, I personally think that if someone is changing advanced features like the network mode, they’ll be able to change it back again.

**Comment by dginovker** [comment]
Fair enough.
