### ISSUE TITLE
Move HTTP calls to C++

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#2254]
Currently [calling this](https://github.com/monero-project/monero-gui/blob/5f38dbb7dd3c25755427b103ae389ccc619b6c42/wizard/WizardController.qml#L566) from Javascript, should probably be done in C++ through our networkmanager for greater control over timeouts, not freeze the UI and also the ability to setup proxies.

https://github.com/monero-project/monero-gui/issues/2252

**Comment by xmrdsc** [comment]
I'm actually not sure if Javascript HTTP calls freeze the UI. I would expect them to run in their own interpreter.

**Comment by selsta** [comment]
`src/qt/network.cpp`
