### ISSUE TITLE
Issue installing the Wallet

### ISSUE THREAD

**Issue by AS-tech-time** [monero-project/monero-gui#2260]
Hi Fellas, facing the following issue when creating the wallet for my Ledger X:

failed to generate new wallet: Wrong Device Status: SW=6e00 (EXPECT=9000, MASK=ffff)"

Any clue??

Thanks for your help!

**Comment by dEBRUYNE-1** [comment]
Do you have Ledger Monero App v1.3.1 installed? See:

https://www.reddit.com/r/Monero/comments/c8eg6k/gui_v01410_boron_butterfly_with_ledger_nano_x_and/esm8opd/

**Comment by AS-tech-time** [comment]
Checking right now after switched to developer. APP was already installed, let s try!

Thanks

**Comment by dEBRUYNE-1** [comment]
@AS-tech-time - Does it work properly now?

**Comment by dEBRUYNE-1** [comment]
@AS-tech-time - ping.

**Comment by AS-tech-time** [comment]
Dear,

Thanks for your help everything work perfectly! Had some time to download the all blocks but nothing else!

Best

**Comment by dEBRUYNE-1** [comment]
Good to hear and you're welcome!

**Comment by dEBRUYNE-1** [comment]
+resolved
