### ISSUE TITLE
Searching transaction history notes/descriptions.

### ISSUE THREAD

**Issue by kwukduck** [monero-project/monero-gui#2264]
I noticed the transaction filter does not search in the description/note field of the transaction.
I like to link my transactions with other applications for reference and use the description field to make a note. It would be very useful if this would be included in the search results.
Think of invoice numbers, tracking numbers or names.
Currently it is limited to the amount and address.

**Comment by selsta** [comment]
Thanks for the feature request, this will be added in the next version.

#2250 

+resolved
