### ISSUE TITLE
Date filter in transaction history resetting.

### ISSUE THREAD

**Issue by kwukduck** [monero-project/monero-gui#2265]
When setting a date filter in the transaction history tab, this does not persist. Switching to a different tab and back again will reset the filter. 
In previous GUI the filter settings would persist throughout the session.
Not sure if this is a bug or intended behaviour. I experience it as annoying as it takes considerably longer to load an extensive list of transactions over and over compared to just the last week.

**Comment by selsta** [comment]
+resolved
