### ISSUE TITLE
2 additional spaces added after passphrase is pasted from clipboard in dialogue

### ISSUE THREAD

**Issue by bosomt** [monero-project/monero-gui#2271]
2 additional spaces added after passphrase is pasted from clipboard in dialogue
Please see screenshot.
If paste your passphrase wallet will add 2 more spaces.
This will generate completely different wallet/account/address compared to passphrase that you enter via keyboard

And no spaces are not included in pasted text

![60710708-9b49a280-9f13-11e9-96c5-a533297142d3](https://user-images.githubusercontent.com/31506317/60714720-e962a400-9f1b-11e9-9116-0478eb1610fd.png)
![60710846-dea41100-9f13-11e9-8725-c5028300249e](https://user-images.githubusercontent.com/31506317/60714722-e962a400-9f1b-11e9-8fce-3dfa31af2a47.png)

**Comment by selsta** [comment]
Thanks for the report but I can’t reproduce this issue. Looks like you copied your password together with a newline afterwards.

+invalid
