### ISSUE TITLE
ver 0.14.1.0 Wallet shows "Monero sent succesfully: 0 transaction(s)" after sending a transaction

### ISSUE THREAD

**Issue by pankrats** [monero-project/monero-gui#2275]
Tried to send a tx with Monero-gui using Trezor. 
The process went normally and the transaction was actually sent, but the wallet showed the following:
<img width="981" alt="Screenshot 2019-07-08 at 09 07 48" src="https://user-images.githubusercontent.com/31442634/60789782-359e2600-a160-11e9-8a13-11cf3e1d4cdb.png">

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by dEBRUYNE-1** [comment]
Paging @ph4r05 as well :-P

**Comment by ph4r05** [comment]
@pankrats what is pls your Trezor firmware version?

**Comment by ph4r05** [comment]
@pankrats and which OS do you use?

**Comment by pankrats** [comment]
I use MacOS Mojave (ver 10.14.5) and Trezor T.

**Comment by ph4r05** [comment]
The problem should be global, not just Trezor related. 
The PR #2276 fixed it for me.

**Comment by rating89us** [comment]
I have the same issue with macOS and Trezor.
