### ISSUE TITLE
Text in the Daemon log hard to read on white theme

### ISSUE THREAD

**Issue by lmick** [monero-project/monero-gui#2278]
Because the text is white and the background is very bright, it is hard to read the text of the daemon log while the white theme is active.
![image](https://user-images.githubusercontent.com/40724422/61177816-475b4f80-a5de-11e9-8bdb-a359fcdbbed5.png)

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by selsta** [comment]
This only happens if you enter something in the daemon log console and then change theme layout. I can’t think of a simple solution to fix this.

**Comment by selsta** [comment]
Closing as duplicate of #3475
