### ISSUE TITLE
Minor UI Nicety - Password Dialog Lag When Sending

### ISSUE THREAD

**Issue by Thunderosa** [monero-project/monero-gui#2281]
There's a small moment of doubt for the user when the password dialog pops when confirming the sending of transaction. The lag isn't super long, but it's long enough that a visual indication that it's processing would be a nice.

**Comment by selsta** [comment]
I don’t have this lag. Are you using a really slow / old machine?

**Comment by Thunderosa** [comment]
No, but I do have a high latency connection. I went back to watch another transaction more closely, it's the very last prompt when sending that's the most noticeable...3-4 seconds, something like that.

**Comment by Realchacal** [comment]
There are MANY of these lags everywhere in the GUI! (Sorry to say it.) Just try to go to the `Accounts` page: 2-3 seconds lag, cursor doesn't change, user doesn't know what's happening, user panics, clicks again. MANY, MANY of these situations everywhere! (Again, sorry to say it.) Or try to add a new account: 5 seconds lag without any feedback, then the cursor changes to that spinning animation (like when the wallet is freezing) and 30 seconds later everything is fine and the new account has been created.

**Comment by selsta** [comment]
@Realchacal Are you using a Ledger ?

**Comment by Realchacal** [comment]
@selsta Yes, only!

**Comment by selsta** [comment]
Well, that’s why it’s laggy. The things you are describing are calculated on the Ledger, so it will always be slow.

**Comment by Realchacal** [comment]
@selsta Thanks, I didn't know. These things will scare off new users, though :(

**Comment by Thunderosa** [comment]
I'll not speak for Realchacal, but I don't think either of us are saying that unavoidable lags be fixed, just that they be indicated so they don't feel like a freeze.

**Comment by Realchacal** [comment]
That's exactly my opinion. Waiting time is more than ok (of course!), but not waiting time that looks like freezing.

**Comment by selsta** [comment]
We reworked the transaction flow. Please open a new issue if you still experience this lag.
