### ISSUE TITLE
4 proposals to make the `Account` page more intuitive

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2312]
[Updated]

**1.** 
![image](https://user-images.githubusercontent.com/46682965/61712275-4486fa00-ad56-11e9-8771-28f49c830be3.png)
- "Account" can be misinterpreted as "user account" / "user profile". Calling it "Accounts" would improve that a little bit.
______________________________________________

**2.** 
![image](https://user-images.githubusercontent.com/46682965/61796230-48ce1880-ae25-11e9-8d8e-fe756131feaf.png)
- Using multiple accounts is **optional**, sending and receiving is **not**. This should be reflected by the menu order. (You wouldn't put `Advanced` at the top, right?)

______________________________________________

**3.+4.**
![image](https://user-images.githubusercontent.com/46682965/64069593-ea2e6280-cc4c-11e9-8dfa-2aa6a5c80466.png)

- What is "Balance All"?
- "Total unlocked balance" should be removed for the same reasons as in #2298.
- "Balance" in each row is bad
- Shortening the balance with `...` to replace just 2 zeros is bad
- The edit icon and the copy icon have unintuitive positions
- Showing one address per account leads to misconceptions for new users. They may think:
     - **_"Ah, in Monero an account is an address!"_**
     - **_"Ah, every account has exactly one address!"_**
     - **_"Ah, every account has one account number!"_**
Solution: Introduce a header line to explain a little bit.
- `+ Create new account` sounds like the account doesn't exist yet - but it does, it's just not shown.

![image](https://user-images.githubusercontent.com/46682965/64069643-e2bb8900-cc4d-11e9-8fee-e0ca9cf64e4c.png)
![image](https://user-images.githubusercontent.com/46682965/64069461-e3522080-cc49-11e9-9af7-5c418ba03d9e.png)

**Comment by rating89us** [comment]
I agree with all your points, except with hiding addresses of accounts. After seeing them many times, you start to remember which address refers to each account, and this improves security.

**Comment by selsta** [comment]
I appreciate the feedback.

**Comment by Realchacal** [comment]
Updated! Feedback integrated! Thx.

**Comment by selsta** [comment]
Proposal 3. and 4. looks good, I will try to implement it.

Regarding the sidebar I will implement concept #1 from @GBKS which you can find here: https://www.reddit.com/r/Monero/comments/c23zxn/feedback_request_ideas_for_improving_how_multiple/

**Comment by Realchacal** [comment]
Thanks for the link, I wasn't aware of that! But @GBKS #1 brings tears to my eyes!!! (Sorry!) I totally understand the points he made, but still:
- the hierarchy is so confusing! (Account above wallet)
- the GUI gets visually **more** complex while all those normies don't even use multiple accounts

Alternative proposal:
![image](https://user-images.githubusercontent.com/46682965/63981128-1a93c680-cabe-11e9-96c6-de3a724f7a78.png)
SOOO simple & intuitive & super quick account change!

**Comment by selsta** [comment]
I’ll have to think about it. What about making the whole `Account #0 Retirement Savings` area clickable and this brings you to the account page?

**Comment by Realchacal** [comment]
> What about making the whole `Account #0 Retirement Savings` area clickable and this brings you to the account page?

THAT WOULD BE INCREDIBLE NICE!!! My only requirement would be that the user **somehow** can see that it is click-able (mouse curser changes/ text changes when mouse is hovering/ drop down menu symbol as shown/ or anything else)

**Comment by Realchacal** [comment]
> What about making the whole `Account #0 Retirement Savings` area clickable and this brings you to the account page?

THAT WOULD BE INCREDIBLY NICE! It simplifies visually, it doesn't bother average users who don't use multiple accounts, it reduces potential account hierarchy misinterpretation, it still allows 1-click access to `Accounts`, and it can't get any more intuitive than clicking on the account to change the account!

My only requirement would be:

- The user **somehow** must be able to see that the area is clickable! Maybe some change when the mouse is hovering, for example cursor change / text color change / text gets underlined / rectangle around the area. Or maybe use an icon like in the menu:
   ![image](https://user-images.githubusercontent.com/46682965/64004205-14c5d180-cb0e-11e9-8fed-c36195781296.png)

**Comment by Realchacal** [comment]
We could also do these changes (icons):
![image](https://user-images.githubusercontent.com/46682965/64008215-f19f2000-cb15-11e9-908d-ac164bb49652.png)
SOOO intuitive!

**Comment by GBKS** [comment]
Great discussion here. I agree with the detail improvements in the accounts page, but disagree about the accounts/wallet hierarchy.

Underneath wallet, we find accounts, address book (used in all items underneath account), settings (+ subitems) and advanced (+ subitems).

Underneath account, we find send, receive, and transactions.

I think it's important to be clear about this and label things appropriately. I'd also argue that generally interfaces are not more intuitive because there's less in them, but because they do a better job at explaining what's going on - so in this case I'm not concerned about the complexity. It's problematic when you're hiding a whole top-level feature underneath a pretty thin arrow in the corner of another element and rely on a hover-state for people to discover it. Obvious is better here.

I'm also not sold on the "normies don't use accounts" argument. It's a very new feature in the GUI, we don't have analytics, so we just don't know how how people want to use it (let me know if you have some info on this). Maybe people love it if we just treat it like a real, useful feature?

And a small note, I find that the grey logo looks disabled. I'd make it colored. Or maybe it can be grey while syncing, and colored when ready to transact?

Love the discussions. It's a great place when you're discussing such details, it means a lot of bigger things are in good shape.

**Comment by Realchacal** [comment]
> It's problematic when you're hiding a whole top-level feature underneath a pretty thin arrow

- this is not more or less hidden than any other menu item, is it!?
![image](https://user-images.githubusercontent.com/46682965/64009950-26f93d00-cb19-11e9-9d75-c6754d453fb5.png)

According to your proposal we would have `Account` above `Wallet`. This is confusing because it reflects the wrong hierarchy. And as if that was not confusing enough, your proposal also has `Accounts` below `Wallet`. At least now the average user's brain surrenders. 

We just don't need to introduce a separate section `Wallet` because everything that happens in the wallet already is related to the wallet, which hopefully will be reflected soon by the wallet name in the title bar (#2325):
![image](https://user-images.githubusercontent.com/46682965/64011129-6163d980-cb1b-11e9-89e8-8e584d31a244.png)

> let me know if you have some info on this

I just started a small poll:
https://www.reddit.com/r/Monero/comments/cxesm4/poll_to_find_out_if_the_monero_gui_should_be/
Maybe this gives us some hints. But polls are tricky...

> And a small note, I find that the grey logo looks disabled.

I don't see it like that but if it looks disabled to you it probably also looks disabled to others so we should change it! (I just found our brown balance card to not harmonize well with our orange.)

**Comment by Realchacal** [comment]
@GBKS what you're aiming at is ABSOLUTELY right! But IMO it would require a much deeper redesign:
![image](https://user-images.githubusercontent.com/46682965/64028597-35f4e500-cb43-11e9-90e2-4ed6b5b6afbf.png)
Disclaimer: I do **NOT** propose this, since I know it's too much work. My previous proposal is good enough to get an intuitive GUI!

**Comment by Realchacal** [comment]
Closing this because it's bullshit compared to #2367.
