### ISSUE TITLE
Drop "Change account"

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2316]
![image](https://user-images.githubusercontent.com/46682965/61848605-f20d2100-aeae-11e9-9dc0-37e86162c636.png)
Proposal: Drop marked "feature".

Rationale:
- You can access the `Account` page with just one click anyways.
- It is confusing for new users. They think: _"I just want to send money. What is this strange `(change account)` thing!? Is that a separate account for my change money!??? Oh wait, it looks like I can click on it. Do I have to do that!??? Shit, I don't know, but it must be important, otherwise it probably wouldn't be there. Gosh, why is that Monero thing so complicated!? I just wanted to send money, now I have anxiety because I could make something wrong and lose my money."_
- Using multiple accounts is optional. Why bother everyone with it on the `Send` page?

**Comment by rating89us** [comment]
In my opinion:
- Simple wallet: display "Amount ("Name of account").
- Advanced wallet: display "Amount ("Name of account") ("change account link").

**Comment by Realchacal** [comment]
Thanks for your feedback! Why do you propose to even **add** the name of the current account? Isn't it shown clearly enough on the balance card?

**Comment by rating89us** [comment]
The intent here is to prevent user to inadvertently spend funds from wrong account.

When you are in Send page, you must have a clear and explicit indication informing from which account you are spending from. 

I believe the account's name in balance card is not highlighted enough.

An alternative could be that the background color of balance card changes according to selected account. So, if my Savings account is selected, my balance card would be purple, and so on...

**Comment by Realchacal** [comment]
> I believe the account's name in balance card is not highlighted enough.

True, but that's hopefully gonna change (#2298):
![image](https://user-images.githubusercontent.com/46682965/62118114-697eee00-b2bd-11e9-8afd-5af3d310bade.png)

> When you are in Send page, you must have a clear and explicit indication informing from which account you are spending from.

Balance card IS explicit. Everything in the wallet (sending / receiving / transaction history) relates to the **current** account shown in the balance card. With your logic you would have to add an account info to the `receiving` page and the `transactions` page as well.

**Comment by Realchacal** [comment]
Closed because #2367 is much better and includes this proposal here (implicitly).
