### ISSUE TITLE
Intuitive node symbols

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2318]
![image](https://user-images.githubusercontent.com/46682965/61868228-3a413900-aed9-11e9-83a1-f3c3645446b9.png)

Local node symbol: "Reload page"???
Remote node symbol: "Paper with arrow"???

More intuitive:
![image](https://user-images.githubusercontent.com/46682965/61868302-652b8d00-aed9-11e9-96f4-4ba9f596d745.png)

**Comment by selsta** [comment]
<img width="627" alt="Screenshot 2019-07-25 at 14 31 44" src="https://user-images.githubusercontent.com/7697454/61874543-f7875d00-aee8-11e9-9955-7bd748330618.png">
<img width="636" alt="Screenshot 2019-07-25 at 14 32 17" src="https://user-images.githubusercontent.com/7697454/61874569-02da8880-aee9-11e9-902f-b0edc9a39aa6.png">

Opinion?

**Comment by Realchacal** [comment]
@selsta ULTRA NICE!!! Your cloud seems just a LITTLE bit too fat IMO (needs shrinking in height).

We should ask @GBKS for the correct design that fits GUI-wide. MAYBE the house symbol is too complex, since all our other symbols are super sleak/simplified.

**Comment by GBKS** [comment]
Not sure where these white icons are coming from. I had designed icons for this a while back that I assumed we used (but maybe someone changed them, which is also cool). Here are the ones I came up with (this is a screen that's also in [Zeplin](https://scene.zeplin.io/project/5a0777492a92d8ac5beb3125) and my [Github repo](https://github.com/GBKS/monero-wallet-design/blob/master/screens/desktop-dark/onboarding%20-%20how%20to%20connect.png)). There are several more of these larger, orange icons that are used in the onboarding flow ([see here](https://github.com/GBKS/monero-wallet-design/blob/master/screens/desktop-dark/Icons.png)).

![onboarding - how to connect](https://user-images.githubusercontent.com/695901/61877240-e0e40480-aeee-11e9-8a38-6161fcc6b644.png)

**Comment by selsta** [comment]
> Not sure where these white icons are coming from.

They are on the left middle side [here](https://github.com/GBKS/monero-wallet-design/blob/master/screens/desktop-dark/Icons.png), but I don’t know what they were originally intended for.

**Comment by Realchacal** [comment]
- Nice to see that you already had the idea with the cloud, @GBKS !!
- @selsta see the cloud from @GBKS? That's a healthy cloud!
- But double arrows NOT good. They don't add any value, just make it more complex.
- @GBKS your local node symbol is technically more correct, but the house symbol actually gives the better impression on a glance.

I'd go with @selsta's symbols (with improved cloud) and hope I could convince @GBKS so that he may help us to improve @selsta's symbols.

**Comment by selsta** [comment]
@GBKS Can you upload just the cloud icon alone to the icons page? The white arrows don’t play well together with the white theme.

**Comment by GBKS** [comment]
@selsta sorry, I was just wondering how those white icons made it in the interface, because we used to have the orange ones in there. Maybe it was changed when the white theme was added. Can we use different icons for the dark and white themes? That would be ideal. 

@Realchacal not sure I agree about the icons not adding value. Please also keep in mind that these icons are part of a family of larger icons you can [see here](https://github.com/GBKS/monero-wallet-design/blob/master/screens/desktop-dark/Icons.png). They are meant to match in style, visual weight, color treatments, etc. I'd like to avoid doing per-icon adjustments that result in things don't matching overall (obviously a balance of both of these approaches, the whole context vs. consistency thing). What icon would you use for the bootstrapped mode (called "Recommended" in [this mockup](https://scene.zeplin.io/project/5a0777492a92d8ac5beb3125/screen/5c5701cf125496435bbe04bd))? A smaller house?

**Comment by selsta** [comment]
Yes, a different icon for each theme would work.

**Comment by Realchacal** [comment]
@GBKS  I TOTALLY get the corporate design thing! That's why I dropped your name here.

I didn't had the mode selection window on my mind when making my proposal. Thanks.
![image](https://user-images.githubusercontent.com/46682965/61879633-b6487a80-aef3-11e9-9ac6-ed630c14dd70.png)

I definitely COULD live with your logos. They are nice and they are technically more correct. But I insist that @selsta's are more intuitive.

Bootstrap mode I'd go with something like this:
![image](https://user-images.githubusercontent.com/46682965/61880115-949bc300-aef4-11e9-9760-7f5e99872636.png)

**Comment by Realchacal** [comment]
> @selsta sorry, I was just wondering how those white icons made it in the interface...

I assume that was because the orange ones had too much visual weight (color and size) to be integrated into the settings!

**Comment by Realchacal** [comment]
This issue should wait for #2320 and #2321.

**Comment by GBKS** [comment]
The diagonal strike-through line instantly makes me think that it's not allowed (or disabled), like the way it's used in street signs.

If we want to use the old orange icons, I created white versions and put them on Zeplin ([here](https://scene.zeplin.io/project/5a0777492a92d8ac5beb3125)). 

Regarding the visual weight, I had reduced the icons in the settings page by 50% in size to accommodate for that.

Can you maybe explain what you mean by corporate design? I can't tell if you're trolling or not, and what non-corporate design would be if you're not. Either way is fine, just want to know what you mean.

**Comment by Realchacal** [comment]
> The diagonal strike-through line instantly makes me think that it's not allowed (or disabled), like the way it's used in street signs.

I didn't see that at first, now I see it! You're absolutely right!

> If we want to use the old orange icons, I created white versions and put them on Zeplin ([here](https://scene.zeplin.io/project/5a0777492a92d8ac5beb3125)).

**They look great! Let's use them! A million times better than what we have right now.**

(But just for the record: Now we'll be using the same icon for "Advanced mode" and for "Local node":
![image](https://user-images.githubusercontent.com/46682965/62299657-a42b8680-b475-11e9-9537-08709adef45c.png)
That's just SUPER messy! But the problem is NOT the icons! The problem is our UNLOGICAL bundling of things that do not belong together, which needs fixing! (#2320)

> Can you maybe explain what you mean by corporate design? I can't tell if you're trolling or not, and what non-corporate design would be if you're not. Either way is fine, just want to know what you mean.

Naaa, I was not trolling! I was just using the term "corporate design" to refer to our concept of using the same design language everywhere. But I guess I used that term wrong, since normally it is only used for company (corporate) design - not for open source project design.

**Comment by selsta** [comment]
I openend #2351 for now.

@GBKS, I kinda agree with @Realchacal, using the same icon for “Advanced mode” and “Local node” isn’t perfect and I think the colored icons don’t fit on the node settings page (they do fit into the mode selection page).

**Comment by GBKS** [comment]
Cool. Consistent icons help people recognize things more easily. We could create monotone versions of the colored ones for the settings page to avoid a visual clash.

The benefit of some more visual icons is that they can then also be used on the website. This was very handy in my [landing page mock-ups](https://www.reddit.com/r/Monero/comments/cnn57p/feedback_request_concept_for_a_new_landing_page/).

Anyhow, let's decide on something and move forward. I'm good either way.

**Comment by Realchacal** [comment]
- For the node settings all variants are great. I'd prefer @selsta's variant for now.
- The mode selection page is where I see a problem. A noob wonders: "Why is the cloud a symbol for simplicity?! Why is a computer a symbol for Advanced?! What am I missing here??" (--> #2320 IMO)

**Comment by Realchacal** [comment]
Closing this because #2351. Nice.
