### ISSUE TITLE
Windows x64 v0.14.1.0

### ISSUE THREAD

**Issue by Lollypops** [monero-project/monero-gui#2319]
The GUI walkthrough for Windows is missing key information. Possibly the text colours are the same as the background.

https://imgur.com/HKB6bsn

**Comment by selsta** [comment]
It should look like this:
<img width="1026" alt="Screenshot 2019-07-25 at 22 47 55" src="https://user-images.githubusercontent.com/7697454/61907686-3f7ca300-af2e-11e9-9837-68c417e78417.png">
Are you using a VM? Any special setup? Can you try to start the GUI using `start-low-graphics-mode.bat`?

**Comment by Lollypops** [comment]
Nothing special, stock windows, brand new computer. I'm unfamiliar with how to open the GUI with start-low-graphics-mode.bat.

**Comment by selsta** [comment]
Simply double click on it.

**Comment by Lollypops** [comment]
Thanks : )

It's working in low graphics mode.

**Comment by xmrdsc** [comment]
Which graphics card + drivers?

**Comment by Lollypops** [comment]
Intel(R) UHD Graphics 620, drivers version 26.20.100.6911

**Comment by dEBRUYNE-1** [comment]
+resolved
