### ISSUE TITLE
Unbundle "connection type selection" and "difficulty selection"

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2320]
Currently "connection type selection" and "difficulty selection" are bundled:
![image](https://user-images.githubusercontent.com/46682965/64239480-9a77c180-cf00-11e9-9521-7dcdeaecc92f.png)

Proposal:
![image](https://user-images.githubusercontent.com/46682965/64240076-99935f80-cf01-11e9-9277-83a5bd92eefe.png)

Reasons:
- **This is SO CLEAR AND LOGICAL.**
- The wording is simple and non-technical. (Correct, though.)
- It sucks to have to close and reopen the wallet to change modes.
- Many users will suffer from reduced privacy because they will choose the mode that sounds the simplest to them, which is "Simple mode" (without bootstrap).
- A lot of other problems around our 3 modes (#2304, #2321)

**Comment by GBKS** [comment]
I looked into this earlier this year, here's one of my explorations. I forgot the rationale why we ended up combining the options. Maybe somebody else remembers?

![monero-wallet-onboarding-node-mode-gbks-190211](https://user-images.githubusercontent.com/695901/61938625-d9296c00-af91-11e9-8435-5cd7587592d4.png)

**Comment by Realchacal** [comment]
@GBKS ABSOLUTELY STUNNINGLY BEAUTIFUL AND LOGICAL!!! And it doesn't surprise me at all that you came up with that idea independently from me.

> Maybe somebody else remembers?

It MUST have been the lack of bootstrap mode. Right?

**Comment by Realchacal** [comment]
Closed and integrated in #2321.
