### ISSUE TITLE
Add wallet name to title bar

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2325]
[Updated! Thx @GBKS]
![image](https://user-images.githubusercontent.com/46682965/64293800-ae0d4180-cf6d-11e9-9edd-b225b2275855.png)
(Ignore changes from #2298, #2339, #2304.)

This is financial safety-critical because it's super easy to confuse wallets when the name is not shown prominently.

Alternative:
![image](https://user-images.githubusercontent.com/46682965/64327347-d1ff7000-cfcb-11e9-9f7b-f90aa9810e27.png)

**Comment by Realchacal** [comment]
The added (visual) complexity sucks so much.

**Comment by Realchacal** [comment]
Alternative proposal:
![image](https://user-images.githubusercontent.com/46682965/62004721-f5134600-b128-11e9-8e71-38f3e09f80f8.png)
(Actually, most programs don't have a logo in the title bar! But we have one in the title bar **and** one in the balance card.)

**Comment by rating89us** [comment]
Where would you get the wallet's title from? From the .keys file?

**Comment by Realchacal** [comment]
Sure!

**Comment by rating89us** [comment]
That's a good idea. Window title should be "Mywallet.keys - Monero GUI"

**Comment by Realchacal** [comment]
- Agreed on putting the wallet name in front and dropping the logo.
- Not so sure about adding `.keys`. A normal user probably isn't aware at all that his wallet file actually is a `.keys` file. Even when opening a wallet the wallet names are presented without `.keys`.

**Comment by rating89us** [comment]
Maybe we should start educating our users that a Monero wallet is nothing more than a .keys file.

**Comment by Realchacal** [comment]
> Maybe we should start educating our users that a Monero wallet is nothing more than a .keys file.

I think we can be happy enough if all users understand the basic safety concept of mnemonic seeds. We want to board millions of normal people in the future! :)

> What about displaying .keys extension when in Advanced wallet, and don't displaying it in simple mode?

Advanced users wouldn't need it.

**Comment by GBKS** [comment]
How about removing "Monero" from the title bar altogether and just show the wallet name? It's not shown anyways if you disable custom decorations. The logo is still shown in the balance card on the left.

**Comment by Realchacal** [comment]
@GBKS That would be awesome!!! But we should make sure that for example in the Task Manager it still would say "Monero" somehow.

Would you go with/ without logo when showing only the wallet's name?

**Comment by dginovker** [comment]
@GBKS I'd rather see both variations before deciding on that. To avoid clutter on small resolution monitors, I could see it working well for taskbars, but on the actual GUI bar it offers aesthetics

**Comment by Realchacal** [comment]
> I'd rather see both variations before deciding on that.

Proposal updated now showing @GBKS's variant. By far the best. (For older variants see "edited".)

**Comment by selsta** [comment]
See #2376.

![menubar](https://user-images.githubusercontent.com/7697454/64300880-ebc69600-cf7e-11e9-8b1d-d73a8c3ab862.gif)

Also ping @dEBRUYNE-1, what do you think of not having the Monero logo in the titlebar?

**Comment by Realchacal** [comment]
Very nice! And nice GIF, as always!

With regard to the 2 logos: It all comes down to the question if you see beauty in the [simplified design](https://github.com/monero-project/monero-gui/issues/2325#issue-473608716). If yes, then dropping the logo is one step in that direction. (We'd still have the logo in the balance card.)

**Comment by Realchacal** [comment]
Very nice but **font size should be smaller** (like the title was before)!

With regard to the logo: It all comes down to the question if you see beauty in the [simplified design](https://github.com/monero-project/monero-gui/issues/2325#issue-473608716). If yes, the logo must go. In case you want to keep the logo for clarity, this would be **more** helpful **and** visually simpler:

![image](https://user-images.githubusercontent.com/46682965/64325170-f5c0b700-cfc7-11e9-8c4f-e7f67cf6e7e3.png)

**Comment by selsta** [comment]
I reduced the font size from 24 to 20.
