### ISSUE TITLE
Change buttons to radio buttons

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2330]
![image](https://user-images.githubusercontent.com/46682965/62223066-9d890a80-b3b4-11e9-824a-d90126ed74a5.png)
- Because radio buttons are the proper component for this. (--> intuitive)
- Because it's always the wrong button that looks active. In the screenshot, a noob could think that he is restoring from keys.

**Comment by selsta** [comment]
<img width="1092" alt="Screenshot 2019-07-31 at 18 14 06" src="https://user-images.githubusercontent.com/7697454/62229048-2ad15c80-b3bf-11e9-9c6b-2ab3f6cfaf8f.png">
<img width="1092" alt="Screenshot 2019-07-31 at 18 15 12" src="https://user-images.githubusercontent.com/7697454/62229057-2e64e380-b3bf-11e9-91bf-69ccaf7478e8.png">
Which one do you prefer?

**Comment by Realchacal** [comment]
First one! This is WAY TOO BEAUTIFUL!!!!!!!! GOOOOOOOOOSH IS THIS BEAUTIFUL!!!!!!!!!!!!!!!!
