### ISSUE TITLE
GUI 0.14.1 - laggy and unresponsive when trying to close

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-gui#2333]
I've got my wallet fully synced, and I click the "X" on the top right to close the wallet. It takes quite a while (still running), and I can't click anywhere else on the GUI either while this is happening.

Some specs:

Manjaro Linux, Kernel 5.2.4-1, KDE Plasma 5.16.3, neither CPU nor RAM are near limits, internet is connected.

*****

Edit: Can't reproduce. Trying to narrow down now. It was after a long sync, while another wallet was also open, however.

**Comment by selsta** [comment]
v0.14.1.2 addresses this, which will be out really soon.

+resolved
