### ISSUE TITLE
Improve title bar icons

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2339]
[Updated!]

- Currently, the "show/hide menu" icon doesn't give away what it's about.
- Currently, the "close wallet" icon is misplaced in the balance card because it doesn't close the "balance" or the account.

![image](https://user-images.githubusercontent.com/46682965/64287649-895e9d00-cf60-11e9-80c3-2e9cb48f6981.png)

**Comment by xiphon** [comment]
https://github.com/monero-project/monero-gui/pull/2358

**Comment by Realchacal** [comment]
Updated.

**Comment by Realchacal** [comment]
Do I close this since we have the moon now? Or does anybody see any merit in the rest?

**Comment by selsta** [comment]
I think the current globe icon is fine. A Google search for “language icon” shows both a globe and Chinese characters.

Regarding the flag as an alternative, see https://github.com/monero-project/monero-gui/issues/1092.

**Comment by Realchacal** [comment]
> I think the current globe icon is fine. A Google search for “language icon” shows both a globe and Chinese characters.

Damn you're right!! Convinced with regard to the globe.
