### ISSUE TITLE
Restore with 24 words failed: Electrum-style word list failed verification

### ISSUE THREAD

**Issue by feugen** [monero-project/monero-gui#2342]
I just tried to restore my wallet from seed and I get the gui message: Electrum-style word list failed verification

In terminal it says: 

2019-08-08 11:25:18.334	E Invalid seed: language not found
2019-08-08 11:25:18.334	E Invalid seed: failed to convert words to bytes

My seed contains english words so I changed the language to english but it doesnt work. Its an bip39 seed from Ledger nano S, I guess it should work, or how do I access my wallet now without hardware device since gui is not working with hardware (https://github.com/monero-project/monero-gui/issues/2341) ?

**Comment by selsta** [comment]
Did you enter your Ledger seed directly into the GUI? That’s not going to work. You’ll have to use this tool: https://github.com/LedgerHQ/ledger-app-monero/tree/master/tools/python

> gui is not working with hardware

The GUI *does* work with a hardware wallet, I explained it in the other issue.

**Comment by feugen** [comment]
Ah ok, thanks I did not try it yet, but ill mark it as resolved
