### ISSUE TITLE
Splash screen when interacting with hardware wallet

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2343]
![image](https://user-images.githubusercontent.com/46682965/64254147-141ea800-cf1f-11e9-95a8-d00957831830.png)
Add text: "Please check your hardware wallet - your input may be required."

Update: @selsta added this for creating and transacting (#2353), only opening is missing.

**Comment by Visco33** [comment]
👍

**Comment by selsta** [comment]
Added this for wallet creation in #2353. I also want to add such a message while transacting, but that’s more difficult to add.

**Comment by Realchacal** [comment]
Closed and moved to #2209.
