### ISSUE TITLE
Improvements when denying "Export View Key" on hardware wallet

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2344]
[Updated]
![image](https://user-images.githubusercontent.com/46682965/64254398-9a3aee80-cf1f-11e9-99c0-b64f049a1c1f.png)
When you deny "Export View Key"...
- the user should be informed _"You have denied the export of your public view key, therefore calculations will have to be done on your hardware wallet. This may take a very long time."_
- `Wallet blocks remaining: 12345 blocks` should be updated every block - not every 999 blocks. (1 block takes about 1 second with Ledger Nano S and subaddress lookahead 1:1)
- clicking on the "close wallet" icon in the balance card shouldn't close the whole GUI.

**Comment by selsta** [comment]
When you deny it, the calculations are all done on your Ledger and scanning gets really slow. Last time I tried it, it was unusably slow.

**Comment by Realchacal** [comment]
Experiment:
- Fully synced blockchain
- Restoring from Ledger 
- Subaddress lookahead 1:1
- Restore height = `current block height - 100`

Results:
- In the beginning it said `Wallet blocks remaining: 1092 blocks` (I expected 100)
- `Wallet blocks remaining: 1092 blocks` didn't change for ~18 minutes
- After a total time of ~20 minutes the wallet was synced
- Clicking the door symbol still closes the whole GUI instead of just the wallet

Conclusions:

This feature only seems usable for new wallets/ super young wallets and with subaddress lookahead 1:1, otherwise it could easily take multiple years to restore a wallet. If we want to keep the future, we should:
- inform the user: `You have denied the export of your public view key, therefore calculations have to be done on your hardware wallet. This may take an extremely long time.`
- update the `Wallet blocks remaining: 1092 blocks` more frequently (every block)
- we should fix the door button

**Comment by Realchacal** [comment]
Thx! I updated the issue.

**Comment by Realchacal** [comment]
I guess nobody needs this anyway, right? Close?

**Comment by selsta** [comment]
AFAIK the GUI doesn’t know if the view key gets exported or not. Changing this behavior isn’t trivial, I think it’s unlikely that this will get changed soon. People export their view key anyway.

**Comment by Realchacal** [comment]
I see, and I wouldn't recommend putting any work in it. So close, right?

**Comment by Realchacal** [comment]
Closed because not really important. Let's hope noobs just will click "export".
