### ISSUE TITLE
"monero-wallet-gui.exe" not showing correct current status of connection with remote node

### ISSUE THREAD

**Issue by GreatAlazar** [monero-project/monero-gui#2352]
While Monero GUI shows disconnected but it connected to a node.
While Monero GUI shows synchronizing but there is no connection from "monero-wallet-gui.exe"

Just a tip, the status label is too vague too tell what the hell is going on

Tools Used:
_TCPView_ (www.sysinternals.com)
_CurrPorts_ (www.nirsoft.net)

**Comment by Realchacal** [comment]
> While Monero GUI shows synchronizing but there is no connection from "monero-wallet-gui.exe"

**IMO** this could be ok, since "monerod.exe" should do the network communication (not "monero-wallet-gui.exe"). 
 
> Just a tip, the status label is too vague too tell what the hell is going on

You're right with that. #2304 is trying to do the first improvement step in this direction.

**Comment by GreatAlazar** [comment]
If you are using remote node, "monerod.exe" doesn't even need to start so connections are made from "monero-wallet-gui.exe"

**Comment by Realchacal** [comment]
You are right, the wording is wrong/misleading, as pointed out in detail in #2304 number 4 (updated!). You may consider closing this issue.

**Comment by GreatAlazar** [comment]
#2304 is much detailed issue so I'm closing this one
