### ISSUE TITLE
Poll: Rename menu item "Transactions" to "History"

### ISSUE THREAD

**Issue by Realchacal** [monero-project/monero-gui#2364]
"History" is more intuitive because "Transactions" could also be a place where you make/check/prove transactions. Also, it's more widespread in the crypto space:

- **"Transactions":** Bitcoin Core, Trezor
- **"History":** Electrum, Wasabi Wallet, Myetherwallet, Coinbase, Binance, Kraken, Poloniex

Poll: See 2 comments below.

**Comment by Realchacal** [comment]
Like this comment if you prefer "Transactions"

**Comment by Realchacal** [comment]
Like this comment if you prefer "History"

**Comment by selsta** [comment]
We recently changed it from `History` to `Transactions`.

**Comment by Realchacal** [comment]
Oh thanks I didn't know! Then obviously people here like `Transactions` :) (--> Close)
