### ISSUE TITLE
Decrease default confirmation/unlock times in GUI

### ISSUE THREAD

**Issue by 1blockologist** [monero-project/monero-gui#2379]
Can we decrease the unlock time from ~20 minutes to 5 or less? This is tied to estimated block time, and therefore how many blocks are necessary

What is the current rationale for so many blocks?

**Comment by xiphon** [comment]
We can't. While 10 blocks confirmation is just a wallet requirement, it will be enforced on the consensus level soon.
See https://github.com/monero-project/monero/issues/5712

**Comment by 1blockologist** [comment]
@xiphon I see, before I contribute there, couldn't we drop it to 5 confirmations just because the anonymity set is larger now than before?

**Comment by Realchacal** [comment]
> couldn't we drop it to 5 confirmations just because the anonymity set is larger now than before?

The lock time has nothing to do with the anonymity set. It's about network consensus / reverting blocks / double spends and likes.

If you want to reduce the block time you should present strong arguments, possibly based on your research, why a lock time of 5 blocks is (almost) as secure as 10 blocks.

**Comment by xiphon** [comment]
> couldn't we drop it to 5 confirmations just because the anonymity set is larger now than before?

no sure about that, i think anonymity set size is not the main factor here.

**Comment by selsta** [comment]
Not something we can decide on GUI side.

+invalid
