### ISSUE TITLE
Add to F-Droid?

### ISSUE THREAD

**Issue by jluttine** [monero-project/monero-gui#2380]
Not sure if this is the right place to ask or place a request, but are there plans to add Monero Android wallet to F-Droid repository? For a privacy respecting cryptocurrency like Monero, that'd be great. Do you know if there are something preventing this at the moment and if those issues could be easily fixed?

**Comment by Realchacal** [comment]
Wrong place. This is about the "Monero GUI" which is not even available for Android. It looks like:
![image](https://user-images.githubusercontent.com/46682965/64473561-76b6b480-d168-11e9-976d-54117cd7643c.png)
The most popular Monero Android wallet would be [Monerujo](https://www.monerujo.io/). Also, I'd recommend [Reddit](https://www.reddit.com/r/Monero/) for general questions.

You may want to consider to close this issue to keep things clean here.

**Comment by jluttine** [comment]
This repo had `android` repo so I thought it'd be available for Android: https://github.com/monero-project/monero-gui/tree/master/android

But yes, doesn't seem to be yet. Thanks!

**Comment by selsta** [comment]
You can build the GUI on Android if your phone / tablet display is large enough :)
