### ISSUE TITLE
fatal error: wallet/api/wallet2_api.h: No such file or directory

### ISSUE THREAD

**Issue by dchmelik** [monero-project/monero-gui#2407]
Since it's unclear how to install precompiled gui wallet (normally there'd at least be instructions for setup in /usr/local) I tried compliling gui wallet 0.14.1.0 on Kubuntu 19.04 (with a 
[log](https://gist.github.com/dchmelik/0cb855b3df148443f80d73bcb5db5dde).)  It ends up saying several times 'fatal error: wallet/api/wallet2_api.h: No such file or directory.'  I see someone had this error in the past and the ticket was closed without anything really being explained.

**Comment by xiphon** [comment]
You have to `git clone` GUI repository instead of using .zip source archive.

**Comment by dchmelik** [comment]
Alright.  I had another problem when I did that (will post shortly) so someone on the freenode IRC said don't do that, rather than download a stable normal version-numbered release.

**Comment by xiphon** [comment]
Just do `git checkout v0.14.1.0` after cloning the repo to switch the source tree to the latest tagged release version.
