### ISSUE TITLE
Cannot build master on OSX

### ISSUE THREAD

**Issue by rotavele** [monero-project/monero-gui#2408]
I am trying to build the master branch from a fresh clone on OSX. 

This happens with both 
`./build.sh`
and
`./build.sh release-static`

The daemon build script appears to be building randomx submodule and the resulting binary is in the external dir as expected but I keep getting this error when the wallet tries to link/include it:

`ld: library not found for -lrandomx`

**Comment by rotavele** [comment]
Awesome thank you. I will watch that issue and give feedback if I can.

**Comment by selsta** [comment]
+resolved
