### ISSUE TITLE
Why ability to add custom remote node working !!! 

### ISSUE THREAD

**Issue by panagiotos** [monero-project/monero-gui#2409]
While using remote node feature it automatically selects a remote node. Unable to provide my custome node.

after editing that remote node to my node it automatically switches to unknown remote node. not cool.

![imageedit_1_5754906903](https://user-images.githubusercontent.com/46250897/66252991-b381c580-e77f-11e9-8d0c-4305f90c6144.gif)

**Comment by dEBRUYNE-1** [comment]
See the answer here:

https://monero.stackexchange.com/questions/11647/remote-node-ip-is-always-changing-in-monero-gui-wallet

**Comment by panagiotos** [comment]
Thanks. Enough. Its time to fire UX guy.

**Comment by erciccione** [comment]
maybe it worth putting a warning on the remote node page about this. Or maybe make impossible to edit the details of the node in simple mode? not an optimal UX if people are able to change the settings, but these settings don't go live.

**Comment by panagiotos** [comment]
> make impossible to edit the details of the node

That would work.

**Comment by xiphon** [comment]
Fixed via https://github.com/monero-project/monero-gui/pull/2373. No more Node settings tab in Simple Mode.

**Comment by selsta** [comment]
> Thanks. Enough. Its time to fire UX guy.

It was a bug, not intentional UX design.

**Comment by panagiotos** [comment]
> It was a bug, not intentional UX design.

I'm sorry. Frustrated that time.
