### ISSUE TITLE
Incorrect fee labels

### ISSUE THREAD

**Issue by jtgrassie** [monero-project/monero-gui#2412]
Please see https://monero.stackexchange.com/a/11658/7493.

Essentially the multiplier amounts are labelled incorrectly.

https://github.com/monero-project/monero-gui/blob/e6458b58ef34a74aa45d48d54ac7b659a2400c8c/pages/Transfer.qml#L214-L217

**Comment by rating89us** [comment]
I see that 
0.2 x1  = 0,2

0.2 x 1000 = 200

0.2 x25 = 5

**Comment by jtgrassie** [comment]
@rating89us 
> Where does this 0.2 come from?

As the internal multipliers are actually `1, 5, 25, 1000`. Scaling to Normal being x1, the display multipliers can be calculated: 
<pre>slow = 1/5 = <strong>0.2</strong>
normal = 5/5 = <strong>1</strong>
fast = 25/5 = <strong>5</strong>
fastest = 1000/5 = <strong>200</strong></pre>.

**Comment by selsta** [comment]
+resolved
