### ISSUE TITLE
Error writing wallet from hardware device. Check application logs. ?

### ISSUE THREAD

**Issue by gorenom** [monero-project/monero-gui#2414]
Hello, I've run into a snag trying to create a monero wallet with trezor.
Their support directed me here.

I followed the instructions here:
https://wiki.trezor.io/Monero_(XMR)#Monero_in_Trezor 

When I tried to create the hardware wallet (from device), I always got the following error message:
_Error writing wallet from hardware device. Check application logs. ?_

Can you help?
Thanks

**Comment by xiphon** [comment]
What OS do you use?

**Comment by gorenom** [comment]
Thanks for the quick response!

1. I'm on Windows 10.

2. There's no additional error message on the bottom.
Screenshot of the screen where I get the error message:
https://i.imgur.com/xgxv6dT.png

**Comment by xiphon** [comment]
>     2\. There's no additional error message on the bottom.
>         Screenshot of the screen where I get the error message:
>         https://i.imgur.com/xgxv6dT.png

It should appear for 5 seconds right after you click on `Create wallet` button. Could you please check it?

**Comment by xiphon** [comment]
>     1. I'm on Windows 10, 64 bit

GUI writes the log into `%APPDATA%\monero-wallet-gui\monero-wallet-gui.log`. Does it contain any Trezor-related error messages>

**Comment by gorenom** [comment]
> It should appear for 5 seconds right after you click on Create wallet button. Could you please check it?

Ah, yes, it says:
"failed to generate new wallet: Cannot get a device address"

> GUI writes the log into %APPDATA%\monero-wallet-gui\monero-wallet-gui.log. Does it contain any Trezor-related error messages>

Yes, two lines I can discern:

WARNING	device.trezor.transport	src/device_trezor/trezor/transport.cpp:716	Reading from UDP socket failed: An existing connection was forcibly closed by the remote host
ERROR	device.trezor	src/device_trezor/device_trezor.cpp:174	Get public address exception: Trezor returned failure: code=1, message=Unknown message

**Comment by xiphon** [comment]
Paging @ph4r05

**Comment by selsta** [comment]
Make sure the latest version of the Trezor firmware and Trezor bridge is installed.

**Comment by ph4r05** [comment]
It may be the case that your Trezor has not been initialized. Did you setup the Trezor via webwallet?

**Comment by rating89us** [comment]
Must Trezor's first run (seed creating) be done through Trezor webwallet, or could it be done in a third party app (like Monero GUI/CLI)?

If it must be done through Trezor webwallet, then we could inform users on our GUI/CLI wallets.

**Comment by ph4r05** [comment]
The initialization must be done via webwallet, it is the only one supported mechanism. Trezor should inform on the setup procedure on the first start

**Comment by rating89us** [comment]
> The initialization must be done via webwallet, it is the only one supported mechanism. Trezor should inform on the setup procedure on the first start

Actually no. Exodus desktop wallet can initialize a new Trezor device ([video](https://www.youtube.com/watch?v=N4L8EjQoyVM)). 

Monero GUI should also be able to do it.

**Comment by ph4r05** [comment]
As far as I am aware the only official initialization is via officia webwallet.

Integration this to Monero codebase is not planned.

**Comment by ph4r05** [comment]
Also, the Trezor asks user to personalize the device after the first start so user should follow the official device guidelines (including proper backup) before using the device. 

Maintaining another init version is costly and error prone. From the mentioned reasons, we won’t support/recommend the init in Monero apps.

**Comment by selsta** [comment]
Please comment if initializing didn’t resolve your issue.

+resolved
