### ISSUE TITLE
Impossible to complete syncing

### ISSUE THREAD

**Issue by fineartcommodities** [monero-project/monero-gui#2425]
Monero Classic 0.1.0.5 gui for win. I have try several time to sync and everytime, at some point, some kind of error merge. Have to be related to size of the db. Don't know. I attach the logfile for information. 
[bitmoneroclassic.log](https://github.com/monero-project/monero-gui/files/3800528/bitmoneroclassic.log)

**Comment by selsta** [comment]
+invalid

Wrong repo?

**Comment by fineartcommodities** [comment]
I have updated the issue pasting the log file because it was not accessible as attachment.

**Comment by selsta** [comment]
Monero Classic is a different repo.

+resolved
