### ISSUE TITLE
Adhere to naming conventions in the UI

### ISSUE THREAD

**Issue by maitscha** [monero-project/monero-gui#245]
Working on the German translations I found some inconsistencies in the UI regarding the labels. I would like use this ticket to discuss some important terms in the UI:

**Payment vs. Transactions**

What is the difference between the two? The UI uses the two terms in different contexts:
* Payment ID
* Transaction ID
* Transaction priority
* Transaction cost
* Verify payment
* Transaction history

**(Mnemonic) Seed**

For the inexperienced user the term "Seed" or "Mnemonic Seed" leads to confusion. Instead I would suggest the term "Recovery Words" or "Recovery Phrase".

**Account vs. Wallet**

The Wizard uses the term "Account" and "Account name", whereby the term "Wallet" is also often used. Isn't it the same?

Examples (from 5 total):
* Account name
* This is my first time, I want to create a new account
* I want to recover my account from my 25 word seed

I suggest to use "Wallet" everywhere.

**Comment by xmr-eric** [comment]
Personally, I think user friendliness is most important, so changing the GUI phrase "mnemonic seed" to "recovery seed" feels like a good decision. However, I've only been involved in cryptocurrency for less than a year, so I'm not an expert at all.

**Comment by NanoAkron** [comment]
You're an expert on being a newbie though, which is of course the target audience ;)

**Comment by erciccione** [comment]
Looks that this PR didn't get much traction in the last two years and meanwhile, a lot of naming changed. If still meaningful, please open a new issue

+resolved
