### ISSUE TITLE
Checkbox description text broken

### ISSUE THREAD

**Issue by sebseb7** [monero-project/monero-gui#2450]
same for all checkboxes

![image](https://user-images.githubusercontent.com/57943861/69345540-90e53680-0c71-11ea-8891-f4e2131f972c.png)

**Comment by selsta** [comment]
What OS, Qt, GUI version are you using? Self compiled?

**Comment by sebseb7** [comment]
windows, self compiled, used fully updated msys (qr 5.13.2)

**Comment by sebseb7** [comment]
this fixes this for me

diff --git a/components/CheckBox.qml b/components/CheckBox.qml
index 99ea641..a248bfa 100644
--- a/components/CheckBox.qml
+++ b/components/CheckBox.qml
@@ -105,7 +105,7 @@ Item {
             font.pixelSize: checkBox.fontSize
             color: MoneroComponents.Style.defaultFontColor
             textFormat: Text.RichText
-            wrapMode: Text.Wrap
+            wrapMode: Text.NoWrap
         }
     }

**Comment by selsta** [comment]
It does not happen on macOS with Qt 5.13 so I’ll look into it.

Thank you for the potential fix.

**Comment by selsta** [comment]
@sebseb7 Using Qt 5.13.2 I can’t reproduce this on macOS. Seems to be a Windows thing. Can you check the following diff?

```
diff --git a/wizard/WizardModeRemoteNodeWarning.qml b/wizard/WizardModeRemoteNodeWarning.qml
index be53b16..6c80546 100644
--- a/wizard/WizardModeRemoteNodeWarning.qml
+++ b/wizard/WizardModeRemoteNodeWarning.qml
@@ -103,6 +103,7 @@ Rectangle {
                 MoneroComponents.CheckBox {
                     id: understoodCheckbox
                     Layout.topMargin: 20
+                    Layout.fillWidth: true
                     fontSize: 16
                     text: qsTr("I understand the privacy implications of using a third-party server.") + translationManager.emptyString
                     onClicked: {
```
