### ISSUE TITLE
Error building Monero-Gui from source in Windows + Fix from Monero-Dev Community

### ISSUE THREAD

**Issue by keatond** [monero-project/monero-gui#2451]
Hello All!

So I took the plunge to learn how to build software from source. I was following the instructions within the README.md.

Everything went smoothly until I got to the "make deploy" command. 
I received the error: 
```
Release` build
cp: cannot stat '/mingw64/bin/libdouble-conversion.dll': No such file or directory
make: *** [Makefile:471: deploy] Error 1
```
I reached out to the monero-dev community about the issue and iDUNK requested that I install:
`pacman -S mingw-w64-x86_64-double-conversion`

I then re-did the "make deploy" command and it built successfully and was able to open the GUI.

**Comment by selsta** [comment]
`mingw-w64-x86_64-double-conversion` is a required dependency by `mingw-w64-x86_64-qt5` which is included in the readme. Not clear why it was missing on your PC.
