### ISSUE TITLE
start-gui.sh and start-tails.appimage not shipped with v0.15.0.1 release archive

### ISSUE THREAD

**Issue by tobtoht** [monero-project/monero-gui#2453]

**Comment by selsta** [comment]
We don’t use the linuxdeploy helper script anymore, that’s why they are missing.

Do you know the point of `start-gui.sh` and `start-tails.appimage`? Do we need both?

**Comment by tobtoht** [comment]
`start-gui.sh` is unnecessary.
`start-tails.appimage` was added for Tails users to start the wallet without needing to open the terminal and cd to the right directory. It depended on `start-gui.sh`, but can be changed to launch `monero-wallet-gui` directly, I suppose.

**Comment by xiphon** [comment]
`start-tails.AppImage` will be included in v0.15.0.2 point release
