### ISSUE TITLE
Tails: text missing from startup prompt

### ISSUE THREAD

**Issue by tobtoht** [monero-project/monero-gui#2454]
Affected version: v0.15.0.1

![tails_prompt](https://user-images.githubusercontent.com/41021257/69482382-51a21b80-0e12-11ea-9a07-21dc5c9e884a.png)

**Comment by selsta** [comment]
Hmm. This didn’t get touched since it got PRed.

**Comment by tobtoht** [comment]
It worked at the time, not sure what happened either.

**Comment by xiphon** [comment]
Will be fixed in v0.15.0.2 point release
