### ISSUE TITLE
User is prompted to keep daemon running upon closing wallet when connected to a remote node

### ISSUE THREAD

**Issue by tobtoht** [monero-project/monero-gui#2455]
Expected behaviour: The wallet closes without the prompt.

**Comment by selsta** [comment]
Can reproduce when switching from local to remote node. If the GUI starts with a remote node connection, the GUI closes without a prompt.

**Comment by tobtoht** [comment]
Not resolved in v0.15.0.2.

Steps to reproduce:
1. During wallet setup connect to an .onion node
2. Close the wallet

**Comment by xiphon** [comment]
@tobtoht 

Yep, another bug gets triggered this time though, please re-open this issue

**Comment by tobtoht** [comment]
I can't. @luigi1111 ?

**Comment by xiphon** [comment]
@tobtoht 
Should be fixed via https://github.com/monero-project/monero-gui/pull/2604.

**Comment by selsta** [comment]
+resolved
