### ISSUE TITLE
Do not automatically start a local node when connection to remote node failed.

### ISSUE THREAD

**Issue by tobtoht** [monero-project/monero-gui#2456]
Especially on Tails, as running a local node will not work without additional setup. 

User choice to use a remote node should be respected. The 10 second countdown is anxiety inducing. Instead, let the user know that the connection to the remote node failed.

**Comment by selsta** [comment]
Can you post steps to reproduce? This does not happen on my system.

> The 10 second countdown is anxiety inducing.

Yea this should be improved.

**Comment by tobtoht** [comment]
Create a new wallet with advanced mode.
Select "Connect to a remote node".
Enter an offline (or nonexistent) remote node.
Go to Settings -> Node, hit Connect (with the offline node still entered)
Wait 30 seconds. The starting local node countdown will pop-up.
