### ISSUE TITLE
Can't change wallet restore height after restoring a wallet

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2463]
I was recovering a wallet from seed and forgot to add my wallet restore height.

So I tried to change it in Settings > Info during the sync, but it didn't work, because the wallet kept returning its value to 0.

I'm using GUI 0.15.0.1 in Windows.

Steps to reproduce:
1. Import a wallet from seed
2. Don't set a restore height
3. Select remote node
4. Wallet will start sync from block 0
5. Go to Settings > Info and change _Wallet restore height_ to a higher height (I set 1819000)
6. Confirm the prompt about the wallet cache
7. Wallet automatically returns to restore height = 0 and start sync from the block 0 again.

**Comment by selsta** [comment]
Does this happen latest master version?

**Comment by rating89us** [comment]
Yes, it's still present and it's probably the same bug of this user: 
- https://www.reddit.com/r/monerosupport/comments/nuny84/restoring_hardware_wallet_monerowallet_gui/
- https://www.reddit.com/r/monerosupport/comments/nuny84/restoring_hardware_wallet_monerowallet_gui/h1238qi?utm_source=share&utm_medium=web2x&context=3

PR #3563 fixes this bug.
