### ISSUE TITLE
Unnecessary scroll bar in many pages

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2471]
Many pages (see Settings) are displaying an unnecessary scroll bar when the content is being completely displayed in the window. 

This seems to happen because the scroll bar is always enabled, unless the window height is at least 
~970 px.

**Comment by selsta** [comment]
Many pages? Can you check to see if this happens in other places apart from settings?

**Comment by rating89us** [comment]
I think there are two different problems:

Problem 1: all pages of Settings have a large scroll bar, even when the content fits in the window.

![image](https://user-images.githubusercontent.com/45968869/69487596-1416b000-0e5d-11ea-8158-4fdb29c5553c.png)

Problem 2: in the remaining pages (not in Settings), it seems that there is a black bar at bottom that is being considered as part of the content. Because of this black bar the scroll bar is appearing even when all content is being displayed. See below:

![image](https://user-images.githubusercontent.com/45968869/69487553-58558080-0e5c-11ea-8d3d-3ad99aafc749.png)

For example, see the send page below. All content is being displayed, and a scroll bar shouldn't appear:
![image](https://user-images.githubusercontent.com/45968869/69487539-1c222000-0e5c-11ea-8725-dceff6f37214.png)

This problem of the black bar at bottom seems to be worse in Transactions page, which is dynamic, and because of this it almost always display the scroll bar.
