### ISSUE TITLE
[GUI] v0.15.0.1 (Qt 5.9.7) 

### ISSUE THREAD

**Issue by TheFuzzStone** [monero-project/monero-gui#2482]
When you enter the password, I see this:

![24-11-19_18:49:34](https://user-images.githubusercontent.com/16173361/69497963-706be500-0eda-11ea-9cdb-af1201949c9b.png)
---

My system: KDE Neon (User Edition)

![24-11-19_18:53:06](https://user-images.githubusercontent.com/16173361/69497992-ea9c6980-0eda-11ea-9986-3630093066c4.png)

**Comment by selsta** [comment]
Did you use the getmonero.org binary or is this self compiled?

**Comment by xiphon** [comment]
Will be fixed in v0.15.0.2 point release

**Comment by TheFuzzStone** [comment]
> Did you use the getmonero.org binary or is this self compiled?

I'm using the binary from getmonero.org.

**Comment by selsta** [comment]
+resolved

**Comment by TheFuzzStone** [comment]
@selsta, updated to 0.15.0.2 and now:

![image](https://user-images.githubusercontent.com/16173361/71170816-1d285080-2254-11ea-92f9-cc507a5451e1.png)

They're a little circumcised from above.
