### ISSUE TITLE
Password prompt increases text field height when typing (Windows)

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2492]
![3](https://user-images.githubusercontent.com/45968869/69523212-97bac480-0f63-11ea-99d1-029d0ffadfd8.gif)

**Comment by selsta** [comment]
Can’t reproduce on macOS.

**Comment by xiphon** [comment]
Reproducible on Win. Though have no clear fix at the moment. Probably will workaround it by hardcoding the height.
