### ISSUE TITLE
No confirmation dialog is displayed when closing wallet

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2493]
This confirmation dialog should appear when the wallet (file) is closed (I'm not refering to GUI wallet software).
![image](https://user-images.githubusercontent.com/45968869/69525532-94760780-0f68-11ea-8f7c-df2c9a57abea.png)

**Comment by selsta** [comment]
I think it’s fine the way it is currently. Closing a wallet is not like e.g. deleting something, where a dialog would make sense.

**Comment by rating89us** [comment]
Closing because now we display a tooltip on close wallet button.
