### ISSUE TITLE
Could you please make offline GnuPG signatures for GUI/CLI packages?

### ISSUE THREAD

**Issue by hiviah** [monero-project/monero-gui#2495]
Following up on the latest web hack on package distribution, could you please make offline GnuPG signatures before publishing the packages and upload them on the getmonero page?

It is almost weird that someone could have changed the packages, but not the hashes (that were not signed, I'm guessing some kind of CDN hack).

So could you please publish GnuPG signatures of the packages on the web, while publishing the keys elsewhere? Key distribution is hard, but Keybase.io offers proofs via various ways (twitter, github, web, ...). It's hard to attack all of those. Another possibility is Key Transparency from Google (it has the same principial issue that you can't prove who was the first to register key). PGP keyservers could be an additional way. The more ways to check the key, the better.

**Comment by dEBRUYNE-1** [comment]
I might be missing something here, but there are GPG signed hashes (from Fluffypony) available here.

https://web.getmonero.org/downloads/hashes.txt

His key is hosted on Github as well as in some other places.

https://github.com/monero-project/monero/blob/master/utils/gpg_keys/fluffypony.asc

**Comment by hiviah** [comment]
OK I see it now. Though never noticed there were any signatures before. It's PEBKAC, but the "canonical way" is to have signature for each package (like basically other software has).
