### ISSUE TITLE
Welcome page requires user to understand two English words

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2503]
**Current:**
The first page that is opened in Monero GUI is a welcome page with two buttons with English words (`Language` and `Continue`). Not everyone knows what these words mean. See below:
![image](https://user-images.githubusercontent.com/45968869/69651799-eb670400-1070-11ea-8e1c-910e37640609.png)

**Suggestion:**
The first page should be a welcome page AND a selection language page, so that anyone can understand it:
![image](https://user-images.githubusercontent.com/45968869/69652550-20c02180-1072-11ea-9559-b7e9a80db785.png)

**Comment by erciccione** [comment]
We used to use flags for showing the available languages, but that was changed (See #1092). I agree would be better to avoid English words, maybe we could make the globe clickable?

Anyway, this is very minor IMO. The page seems intuitive enough to me.

**Comment by garlicgambit** [comment]
Alternative option: Open the language selection menu by default and remove the `Language` button.

**Comment by rating89us** [comment]
Fixed in #3210
