### ISSUE TITLE
Windows: can't maximize/minimize with keyboard when using custom decorations

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2519]
If `Custom decorations` is enabled in settings, it's not possible anymore to use the keyboard to maximize (Win + ↑) or minimize (Win + ↓) Monero GUI window.

**Comment by selsta** [comment]
Found a potential solution but not a lot of information: https://forum.qt.io/topic/26108/customize-window-frame/12

**Comment by selsta** [comment]
#578 

+duplicate
