### ISSUE TITLE
Font Size on High DPI Devices

### ISSUE THREAD

**Issue by jeffro256** [monero-project/monero-gui#2537]
Hello! Maybe this has been asked already, but I couldn't find it. I'm running Windows 10 with a 3840x2160 screen. The font size in the GUI wallet is tiny. I included a screenshot of what it looks like:
![Screenshot](https://user-images.githubusercontent.com/10839482/69904363-6d09ab00-136b-11ea-8d67-c44ec8933e53.png)
Keep in mind that this is a laptop screen so the text is itty bitty in physical size. I think it would be a good idea to detect what kind of screen the user is using and scale the text accordingly.

**Comment by selsta** [comment]
As a temporary workaround: add a file called `start-high-dpi.bat` to the same folder as the `monero-wallet-gui.exe` with

```
@echo off

set QT_SCALE_FACTOR=2

start /b monero-wallet-gui.exe
```

**Comment by selsta** [comment]
Windows releases now come with a `start-high-dpi.bat`
