### ISSUE TITLE
MacOS Catalina Connection error

### ISSUE THREAD

**Issue by bajalatiw** [monero-project/monero-gui#2538]
I get a connection error in the new version.
[<a href="https://hizliresim.com/odRRGq"><img src="https://i.hizliresim.com/odRRGq.png"></a>](url)
"Error writing wallet from hardware device. Check application logs."

**Comment by bajalatiw** [comment]
The problem I did with the Ledger Update has improved.

**Comment by dEBRUYNE-1** [comment]
@bajalatiw - To be clear, you resolved your issue?

**Comment by bajalatiw** [comment]
Ledger Firmware Update Version 1.6.0 the problem I did with the update was solved.

**Comment by selsta** [comment]
+resolved
