### ISSUE TITLE
New wallet: password fields aren't displaying lock icon

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2544]
Current:
![image](https://user-images.githubusercontent.com/45968869/70032648-23f56900-15ae-11ea-83cd-45d72dde9ce7.png)

Expected:
![image](https://user-images.githubusercontent.com/45968869/70032660-2d7ed100-15ae-11ea-879c-bc02f2e1bd2c.png)

**Comment by xiphon** [comment]
Can't reproduce

**Comment by selsta** [comment]
I will fix it
