### ISSUE TITLE
Menu: colored dots aren't consistent with wallet's design

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2573]
After removing the color stripe at the top (#2527), we should also remove colored dots in Menu.

Current:
![image](https://user-images.githubusercontent.com/45968869/70397839-f2e5c000-1a15-11ea-809e-ce87d1e42ace.png)

After:
![image](https://user-images.githubusercontent.com/45968869/70397842-f5e0b080-1a15-11ea-93b0-e7d7306f88e5.png)

**Comment by dEBRUYNE-1** [comment]
Whilst perhaps inconsistent, I think removing them would be a step back with respect to aesthetics.

**Comment by xiphon** [comment]
Could someone explain the meaning of different colors used there?

**Comment by tobtoht** [comment]
I would like to see the colors and dots removed as they have no meaning. Less visual noise for a cleaner look.
