### ISSUE TITLE
Wallet password prompt can be brute forced

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2608]
There should be increasing waiting delays after wrong passwords are entered.
![image](https://user-images.githubusercontent.com/45968869/70871146-d51adc80-1f7a-11ea-977f-8b812a9c3516.png)

**Comment by tobtoht** [comment]
Anyone attempting to bruteforce a wallet wouldn't be typing passwords manually into the GUI.

**Comment by selsta** [comment]
Yep, any visual delays can easily be bypassed with a custom wallet. Don’t think there is anything we can do here.

**Comment by selsta** [comment]
Closing this as there is nothing we can do about this. Use safe passwords.

+invalid

**Comment by LimerBoy** [comment]
good way it's implement custom iterations count for password derivation methods.

**Comment by Manus84** [comment]
> [@LimerBoy](https://github.com/LimerBoy) monero supports this by setting KDF rounds

But what is the best number of "KDF rounds" to set when creating a new wallet in order to have a wallet that can resist brute force attacks?

**Comment by selsta** [comment]
@Manus84 the higher you set it, the longer it will take to open your wallet. but it will also be more difficult to brute-force. In general it is enough to set a strong password without changing the KDF parameter.
