### ISSUE TITLE
Passing -D ARCH=default with ./build.sh

### ISSUE THREAD

**Issue by kpcyrd** [monero-project/monero-gui#2609]
We're currently shipping monero-gui in Arch Linux, which means the binary is built on a cpu that may be different from the cpu the binary is going to be executed on. To avoid AVX2 issues in monerod we pass `-D ARCH=default` to cmake.

cmake is called by `get_libwallet_api.sh` which is called by `build.sh`, which we use, but it seems there's no way to make `get_libwallet_api.sh` to pass `-D ARCH=default` without patching it. Being able to control this with a environment variable would be great. Advice also very welcome.

**Comment by xiphon** [comment]
Added `ARCH` environment variable support, would you like to test it? #2615
