### ISSUE TITLE
Scan of wallet export qr code using an iPhone camera app dials the phone number 147000 automatically.

### ISSUE THREAD

**Issue by satoshi-n** [monero-project/monero-gui#2624]
Might get someone in trouble one day. Seems like a very odd issue I know but who knows what it will resolve fixing this. My battery is low I’ll add a demo in an update. 

Also why do we need so many external links in pdf user guides? Damn I need to contribute

**Comment by selsta** [comment]
Can't reproduce with the latest version of iOS.

**Comment by rating89us** [comment]
I can reproduce this bug. Go to Seed & Keys page, select "View-only wallet" and scan QR code with the Iphone. It will try to call a telephone number that represents restore height: `&height=1810000` iPhone recognizes as a call to 1 (810) 000

**Comment by rating89us** [comment]
I'm not sure if it is a bug, since my Iphone doesn't have any app that recognizes `monero:` URI

**Comment by selsta** [comment]
I think there isn't much we can do here. iOS parsing the URI and deciding that a number in the strings means it's a phone number.
