### ISSUE TITLE
Settings: too much text in Settings > Wallet

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2647]
We should remove buttons with repeated text and add some nice icons (similiar to Settings > Node page):
![image](https://user-images.githubusercontent.com/45968869/71263273-5c23d800-2320-11ea-902b-2cbc59e41518.png)

Current Settings > Node page:
![image](https://user-images.githubusercontent.com/45968869/71263308-68a83080-2320-11ea-8d8f-ec88a8af8270.png)

Current Settings > Wallet page:
![image](https://user-images.githubusercontent.com/45968869/71257651-0ac11c00-2313-11ea-96f5-2bfb697d1dbd.png)

See also issue #2652

**Comment by tobtoht** [comment]
This is great. Can you share the icons?

**Comment by tobtoht** [comment]
![image](https://user-images.githubusercontent.com/41021257/71266295-07905500-2340-11ea-9d74-3f654ddaa3b1.png)


How does this look? I feel like I need to play around with the margins a bit more.

**Comment by rating89us** [comment]
Icons' vertical alignment isn't centered in the row (see Node page)

**Comment by rating89us** [comment]
Can you make the whole row clickable (like Node page items)?

**Comment by tobtoht** [comment]
Yes, it is like that now. Should I highlight the row on mouseover?

**Comment by tobtoht** [comment]
![gui_settings_wallet](https://user-images.githubusercontent.com/41021257/71270552-c56c1100-2349-11ea-9d1d-372bde084872.gif)

What do you think?

**Comment by rating89us** [comment]
I think it's fine hightlighting. But we should also highlight items in Settings>Node for consistency.

**Comment by rating89us** [comment]
And I would change the locker icon in `Change wallet password` to a *** icon, because a locker icon will be used in Lock wallet function (issue #2005)

**Comment by SamsungGalaxyPlayer** [comment]
Reference #2654. I like the proposed changes here with icons. If these are added, we should not change #2654 to keep both pages consistent.

**Comment by rating89us** [comment]
Too much vertical margins. This could be more compact:
![image](https://user-images.githubusercontent.com/45968869/71302462-e05e7580-2389-11ea-917b-42cdc203cc9b.png)

**Comment by selsta** [comment]
Visual margin helps with make the page feel less cluttered and overwhelming.

**Comment by GBKS** [comment]
I would recommend keeping the buttons. Otherwise we are confusing two different types of interaction models ("choose one from a list of options" vs. "a series of independent actions"). Without buttons, there is not visual indication how these items work.

An easy to keep spacing consistent is what I had setup with the original (orange/white) icons. Each icon is centered in a  60x60px frame. The whole item has top and bottom padding of 16px either from the icon frame or the text content, whichever one is taller.

**Comment by rating89us** [comment]
Closed with PR #2821
