### ISSUE TITLE
Settings > Node: no radio buttons

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2654]
Radio buttons are better suited for this case:
Option 1
![image](https://user-images.githubusercontent.com/45968869/71269725-c3488900-232e-11ea-8a62-2f0d0af79a6e.png)

Current:
![image](https://user-images.githubusercontent.com/45968869/71269760-d2c7d200-232e-11ea-8b30-bc704666c6c1.png)

**Comment by selsta** [comment]
IMO looks worse.

**Comment by rating89us** [comment]
Option 2
![image](https://user-images.githubusercontent.com/45968869/71270657-e6743800-2330-11ea-9b65-c23cc9762bf5.png)

Option 3
![image](https://user-images.githubusercontent.com/45968869/71270699-fee45280-2330-11ea-9ae1-27416a8df393.png)

**Comment by selsta** [comment]
All 3 looks visually more complex.

**Comment by rating89us** [comment]
Option 4
![image](https://user-images.githubusercontent.com/45968869/71270828-47037500-2331-11ea-89c5-f909fb9e4bd2.png)

**Comment by SamsungGalaxyPlayer** [comment]
Is the main concern consistency or clarity? I like the look of current the best, but if there's a strong argument that the option selection method is currently unclear, then option 6.

**Comment by rating89us** [comment]
Closing because we've just implemented the same selection indicator in all lists (#3640).
