### ISSUE TITLE
Settings > Wallet: missing "Lock wallet" function

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2656]
Currently you can't actively lock your wallet (put it in standby, waiting for a password). It is only done passively, when the wallet is inactive for a period of time.

We should add a "Lock this wallet" item in Settings > Wallet page. Explanatory text could be something like this: "Locks this wallet and asks for password to unlock".

Icon should be: ![image](https://user-images.githubusercontent.com/45968869/71279635-03603980-2338-11ea-892b-0ffda0e55d21.png)

See also issue #2005

**Comment by tobtoht** [comment]
![image](https://user-images.githubusercontent.com/41021257/71281339-8e9bf800-2355-11ea-91e7-4c0ce1a4bbc2.png)

Will add to #2655 
I changed the order of the items slightly, do you agree?

**Comment by rating89us** [comment]
That's fine

**Comment by selsta** [comment]
#3859
