### ISSUE TITLE
Open wallet: wallet icons are folders

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2668]
Wallet file icons should be wallets or hardware wallets.

There are 4 types of wallet files, and we should use different icons for each type:
- Normal wallet (spend wallet)
- View-only wallet
- Ledger wallet
- Trezor wallet
![image](https://user-images.githubusercontent.com/45968869/71289005-bc2f7400-234a-11ea-9d0f-2dbca618563f.png)

Currently all wallets use a folder icon:
![image](https://user-images.githubusercontent.com/45968869/71289055-e123e700-234a-11ea-93b2-11428229e763.png)

**Comment by xiphon** [comment]
No way to determine the wallet type looking at the file.

**Comment by rating89us** [comment]
> No way to determine the wallet type looking at the file.
You mean you must open the file to know the wallet type?

**Comment by xiphon** [comment]
> You mean you must open the file to know the wallet type?

Yes, open and decrypt it.

**Comment by rating89us** [comment]
All wallet files presented in this page have already been opened before. The wallet could cache the wallet types.

**Comment by xiphon** [comment]
Won't fix. Introduces a privacy leak.

**Comment by rating89us** [comment]
Ok. But we should at least change icons from folder icons to wallet icons (https://fontawesome.com/icons/wallet?style=solid)
