### ISSUE TITLE
How to build monero lib for ios?

### ISSUE THREAD

**Issue by yubinhong** [monero-project/monero-gui#2671]
I execute the ios_get_libwallet.api.sh, but it can't work.what should I do ?  Thank you.

**Comment by selsta** [comment]
Do you want to build monero or the monero-gui for iOS?

**Comment by yubinhong** [comment]
I want to build monero-gui . For example , CakeWallet.

**Comment by selsta** [comment]
Ok, Cake wallet has its own repository.

**Comment by yubinhong** [comment]
I think cake should use monero's repoository same as before? Although they're not open source now.

**Comment by robster7674** [comment]
Same here: I'm trying to build monero-gui / monero-cli on old jailbroken (checkra1n) iPhone 6. Any guidance on that? Is it even possible?

**Comment by selsta** [comment]
Possible? Probably yes. But I don't think anyone has written down a guide for it.
