### ISSUE TITLE
Settings > Info: wallet paths use slash in Windows

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2672]
They should use backslash (`C:\`) instead of slash (`C:/`)

![image](https://user-images.githubusercontent.com/45968869/71306410-7c09d900-23be-11ea-8f59-c5383dadc0ad.png)

**Comment by rating89us** [comment]
@xiphon 
I'm not sure if it was fixed in #2580

**Comment by xiphon** [comment]
Nope, didn't touch this in the PR

**Comment by selsta** [comment]
AFAIK fixed in https://github.com/monero-project/monero-gui/pull/2854
