### ISSUE TITLE
failed to generate a new wallet: Cannot get a device address

### ISSUE THREAD

**Issue by got3nks** [monero-project/monero-gui#2685]
I'm trying to setup a Trezor with Monero-Wallet-GUI on MacOS but get this error when creating a new wallet:

`failed to generate a new wallet: Cannot get a device address`

I can't find the log path to check more details. The Trezor is working fine in Chrome browser with latest bridge driver installed.

**Comment by got3nks** [comment]
I think I've found the reason. Monero-Wallet-GUI supports Trezor T only?

Is there any wat to use Monero with an older Trezor One?

**Comment by dEBRUYNE-1** [comment]
There is currently no Monero support for the older Trezor One.
