### ISSUE TITLE
I build fail on windows and OSx

### ISSUE THREAD

**Issue by ScottGold** [monero-project/monero-gui#2698]
**message on windows :**
Project MESSAGE: Host is 64bit
Project MESSAGE: Target is 32bit
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
Project MESSAGE: Host is 64bit
Project MESSAGE: Target is 32bit
Project MESSAGE: Host is 64bit
Project MESSAGE: Target is 32bit
WARNING: Failure to find: debug/monero-wallet-gui_resource_res.o
make[1]: *** 没有规则可制作目标“../../../../../msys64/mingw64/include/QtWidgets/QApplication”，由“release/main.o” 需求。 停止。
make: *** [Makefile:38：release] 错误 2

**message on OSx**
Sorry, macx is ok now, it's my fault, It need build monero first, which install the dependencies.

**Comment by selsta** [comment]
#2617

+duplicate
