### ISSUE TITLE
Deselecting "Custom decorations" does not restore default title bar on OSX

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#274]
On OSX 10.12.1

Wallet installs with custom title bar, which looks great. The question mark symbol (?) doesn't seem to do anything, but everything else works really well.

Unfortunately if you go into Settings and deselect "Custom decorations" the wallet should restore whatever title bar is default for the OS. But on OSX the title bar simply disappears completely, and theres no way to minimize the window or exit out of the program.

**Comment by xmr-eric** [comment]
https://www.youtube.com/watch?v=hoKH2ViAgdY

**Comment by xmr-eric** [comment]
Related to #354

**Comment by medusadigital** [comment]
is this unfixed?

**Comment by erciccione** [comment]
A lot of releases during this year and the original account of the poster has been deleted. If the problem still exists another issue can be opened

+resolved
