### ISSUE TITLE
Can't create transaction: no connection to Damon. Please make sure Damon is running. With remote node

### ISSUE THREAD

**Issue by rlewkowicz** [monero-project/monero-gui#2745]
Right now my money is essentially stuck in my wallet. I can receive transactions, but I can't actually send anything. Wallets like exodus can send from remote nodes

**Comment by xiphon** [comment]
Did you try another remote node?

**Comment by rlewkowicz** [comment]
Yea, idk what the deal was. Today I went in to the settings and clicked on remote node again. It asked if I wanted to kill the running local node (there wasnt one running) and then I also marked the node as trusted. Then the transaction went through. I did try 3 nodes yesterday and they had the same issue. The node I used today was one of those 3
