### ISSUE TITLE
windows 64 bit flagged unsafe by Norton

### ISSUE THREAD

**Issue by unclemantis** [monero-project/monero-gui#2751]
Sorry guys but this is bull. What is it that Monero-GUI want to do that Norton flags as unsafe? I have downloaded the TronLedger wallet and installed with no warnings. I do not trust this currency. I am selling unless I get a honest answer. I am not going to turn off Norton. No thank you.

**Comment by selsta** [comment]
https://monero.stackexchange.com/questions/10798/my-antivirus-av-software-blocks-quarantines-the-monero-gui-wallet-is-there

+invalid
