### ISSUE TITLE
Offer monero builds where all binaries are signed

### ISSUE THREAD

**Issue by mcgroarty** [monero-project/monero-gui#2754]
Currently, most of the executables in a Monero install are unsigned. eg., on macOS:

```
$ find /Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras/ -type f -exec codesign --verify {} \; 
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-gen-trusted-multisig: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-depth: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-wallet-cli: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-ancestry: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-usage: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-gen-ssl-cert: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-prune-known-spent-data: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-wallet-rpc: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-mark-spent-outputs: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-stats: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-prune: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-export: code object is not signed at all
In architecture: x86_64
/Applications/Monero/monero-wallet-gui.app/Contents/MacOS/extras//monero-blockchain-import: code object is not signed at all
In architecture: x86_64
```

This is a big red flag for AntiVirus engines.

AntiVirus vendors typically rely on reputation associated with a code signing key when determining whether to trust a binary. It's far from the only heuristic they use, but it seems to be heavily weighted. Some vendors flat out flag all unsigned binaries as malware unless they come from companies which are large enough to create large support case loads.

Additionally, when malware installs Monero mining binaries, AntiVirus vendors may be talked into focusing on the unsigned binaries that install copies of a signed miner rather than flagging the miner itself.

**Comment by selsta** [comment]
Code signing + reproducible builds don’t mix well :/

**Comment by mcgroarty** [comment]
That's an important consideration. To the best of my knowledge, code signatures are appended to the end of the file and the remainder of the file is unchanged.

Can anyone verify?

Is anyone aware of a comparison tool that can ignore the signature section and compare the remainder of an executable?

**Comment by selsta** [comment]
AFAIK Bitcoin core found a workaround (at least on macOS), but the process is complicated and results in that the final signature can’t easily be verified.

**Comment by selsta** [comment]
The macOS GUI binaries are now signed and will also be notarized in the future.
