### ISSUE TITLE
Hidden XMR amount flashes briefly when closing wallet

### ISSUE THREAD

**Issue by rehrar** [monero-project/monero-gui#2761]
When an active GUI session times out, the display of the amount changes to ?.?? in an attempt to keep the amount private. 

When I click the "Cancel" button (which takes me back to the "Select wallet" screen, the actual amount flashes briefly, ruining the intended effect. 

Windows 10

GUI version: v0.15.0.2 (Qt 5.9.7)

Embedded Monero version: v0.15.0.1

**Comment by selsta** [comment]
Already fixed in master :)

+resolved
