### ISSUE TITLE
Ledger / Trezor restore ignores restore height.

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#2782]
Any value entered here gets ignored, the current estimated blockchain height gets used.

<img width="1026" alt="Screenshot 2020-02-25 at 21 10 17" src="https://user-images.githubusercontent.com/7697454/75283454-3a106f80-5813-11ea-949f-9164789d3303.png">

Changing the restore height in Settings -> Info -> Wallet creation height works.

Introduced somewhere between v0.15.0.2 and v0.15.0.3.

Reported here: https://www.reddit.com/r/Monero/comments/f6kokz/mnemonic_seed_changed_itself/fi7bte3/

**Comment by selsta** [comment]
Introduced in https://github.com/monero-project/monero-gui/pull/2590

**Comment by rating89us** [comment]
I'm not sure if #2463 is somehow related.
