### ISSUE TITLE
After successful synchronization, the balance remains 0

### ISSUE THREAD

**Issue by ann61wang** [monero-project/monero-gui#2791]
After synchronizing with a simple mode or connecting to a remote node, the balance is still 0, but there is actually Monroe money and it is transferred to the primary account.
In easy mode, I use an old wallet and connect to a remote node with a new wallet.
GUI wallet is 15.0.2 Mac version. I successfully displayed the balance when transferring money before, but now why is my balance always 0?
I used the old version, but it was uninstalled due to some problems, and I haven't used GUI wallet for half a year.

**Comment by xiphon** [comment]
Make sure you set the correct wallet restore height

**Comment by ann61wang** [comment]
> 确保设置正确的钱包还原高度



> Make sure you set the correct wallet restore height

The height of my recovery is up to date

**Comment by selsta** [comment]
> The height of my recovery is up to date

What did you enter as restore height?

**Comment by selsta** [comment]
Not a Monero bug. Please ask on https://www.reddit.com/r/monerosupport/ or https://monero.stackexchange.com
