### ISSUE TITLE
What does Output Match: False mean?

### ISSUE THREAD

**Issue by ann61wang** [monero-project/monero-gui#2793]
My address is to receive Monroe，and I went on xmrchain.net and want to see transaction information. It;s say "output Match:False." What does this mean?

**Comment by selsta** [comment]
This is a bugtracker, please use the monero stackexchange (https://monero.stackexchange.com) or the monerosupport subreddit (https://reddit.com/r/monerosupport) to ask questions :)

**Comment by SamsungGalaxyPlayer** [comment]
https://monero.stackexchange.com/questions/12031/what-does-output-match-false-mean

**Comment by dEBRUYNE-1** [comment]
@ann61wang - Did you manage to resolve your issue?
