### ISSUE TITLE
[Fiat API] Error: "Problem with reply from server. Check connectivity." - fiatPriceError: Invalid ticker value: 0

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero-gui#2798]
Release: `v0.15.0.4`

When connecting to a remote node on MacOS 10.14.6, I am unable to retrieve any fiat exchange rates:
```
2020-03-06 14:09:17.899	D fiatPriceError: Invalid ticker value: 0
2020-03-06 14:09:17.899	D undefined
2020-03-06 14:09:24.286	D "Fetching: https://api.coingecko.com/api/v3/simple/price?ids=monero&vs_currencies=usd"
2020-03-06 14:09:24.287	E [Fiat API] Error: "Problem with reply from server. Check connectivity."
```

I have tried:
* with different circuits
* with USD and EUR
* 3 of the available providers in the GUI

None succeeded.

**Update:** This error is not Tor specific.

**Comment by tficharmers** [comment]
Yes. 0.15.0.1 successfully shows a fiat price conversion for me. 0.15.0.4 just has question marks (?.??) for both EUR and USD conversions. Also, this isn't through Tor.

MacOS Catalina 10.15.3

<img width="287" alt="Screenshot 2020-03-07 at 10 32 28" src="https://user-images.githubusercontent.com/23356013/76141741-16dd8f80-605f-11ea-96e3-68efaebe65e8.png">

**Comment by jonathancross** [comment]
Confirmed on MacOS 10.14.6 _without_ Tor -- still no fiat.

**Comment by selsta** [comment]
Will be fixed with v0.15.0.5

**Comment by selsta** [comment]
Can also reproduce on Linux. Works on Windows.

**Comment by selsta** [comment]
Fixed in source code, will be included with next release.

**Comment by jonathancross** [comment]
@selsta Can you please link to the commit fixing this? Thanks.

**Comment by xiphon** [comment]
@jonathancross 
https://github.com/monero-project/monero-gui/commit/55b548f31cc87d36193a578b00d5a55e35e421f1
