### ISSUE TITLE
 Newly downloaded wallet prompts wrong version

### ISSUE THREAD

**Issue by caozi522** [monero-project/monero-gui#2810]
Connected daemon is not compatible with GUI.Please upgrade or connect to another daemon.

**Comment by selsta** [comment]
Please click on the two arrows in the bottom left corner to connect to a new node. Wait a minute and see if the message goes away. If not, restart the GUI and try again.

**Comment by caozi522** [comment]
I have tried many times and it has no effect

**Comment by selsta** [comment]
Can you open main menu, go to “Change wallet mode” and select advanced mode? Then open your wallet, go to Settings -> Node, click on remote node and enter the following:

```
address: node.xmr.to
port: 18081
```

or alternatively

```
address: node.supportxmr.com
port: 18081
```

Does this work?

**Comment by caozi522** [comment]
> 您可以打开主菜单，转到“更改钱包模式”并选择高级模式吗？然后打开您的钱包，进入设置->节点，单击远程节点并输入以下内容：
> 
> ```
> address: node.xmr.to
> port: 18081
> ```
> 
> 或者
> 
> ```
> address: node.supportxmr.com
> port: 18081
> ```
> 
> 这样行吗？

How to modify the address and port I did not find where to modify

**Comment by selsta** [comment]
<img width="1026" alt="Screenshot 2020-03-18 at 22 59 32" src="https://user-images.githubusercontent.com/7697454/77011522-57e17800-696c-11ea-941e-36ecced5a251.png">
