### ISSUE TITLE
issue recovering wallet...

### ISSUE THREAD

**Issue by alanhasgari** [monero-project/monero-gui#2814]
attempting to recover wallet with mnemonic and restore height... for some reason it will not accept my wallet name... my wallet name is 11 characters, and the box is red... when i enter the first 10 characters, the box becomes green, but that is not the full wallet name...

any ideas??

**Comment by selsta** [comment]
The wallet name already exists.

**Comment by alanhasgari** [comment]
I'm trying to recover it... So, I'm suppose to enter a new name? I tried that and it gave me an error...

**Comment by selsta** [comment]
Yes, you have to enter a new name. Which error?

**Comment by alanhasgari** [comment]
Says electrum-style word list failed verification

**Comment by alanhasgari** [comment]
After half a dozen tries, it finally went through... Never had this kind of problem with other wallets...

Thank you, selsta.

**Comment by selsta** [comment]
electrum-style word list failed verification means that you didn’t enter the seed correctly.

**Comment by alanhasgari** [comment]
It was a direct copy and paste... Inside not enter it incorrectly.
