### ISSUE TITLE
Prevent monero-gui.desktop file creation

### ISSUE THREAD

**Issue by jluttine** [monero-project/monero-gui#2815]
It seems that every time I run Monero GUI, it creates the following desktop file: `~/.local/share/applications/monero-gui.desktop`. I delete it, but it always creates the file when running. Can this be disabled somehow? I don't want that file (I don't want this custom entry to show up in my app menu) and the resulting file doesn't even work in my system. Is there any way to disable it?

**Comment by selsta** [comment]
See the comment here: https://github.com/monero-project/monero-gui/pull/2802#issuecomment-598161099

We will try to improve it. AFAIK there is no way to disable it currently.

**Comment by xiphon** [comment]
Closed via https://github.com/monero-project/monero-gui/pull/3260, https://github.com/monero-project/monero-gui/pull/3251
