### ISSUE TITLE
Support for importing and exporting outputs

### ISSUE THREAD

**Issue by jluttine** [monero-project/monero-gui#2816]
In a setup with an offline private-key wallet and an online view-only wallet, one needs to import key images from the offline wallet to the view-only wallet in order to see the true balance that takes into account spending. But the offline wallet needs to know the outputs for it to be able to create the key images. So, one needs to be able to export the outputs from the view-only wallet and import them to the offline wallet. However, GUI doesn't support these two operations. CLI supports `export_outputs` and `import_outputs`. It would be nice to have these features available in the GUI too.

The source of my information was this dicussion:

https://www.reddit.com/r/Monero/comments/fra1k5/questions_on_key_images/flusnou/

Which gave the following instructions:

- Import address, private view key into watch only wallet. Scan for incoming transactions.

- Export the list of outputs from the watching wallet to the offline wallet.

- Import the outputs into the offline wallet, generate key images, export key images to watching wallet.

- Watching wallet is now ready to create unsigned transactions for the offline wallet to sign.

**Comment by jluttine** [comment]
A side note: Why is "Import key images" disabled in my view-only wallet?

![image](https://user-images.githubusercontent.com/2195834/77949748-2784cc80-72d0-11ea-8fa4-ce74923e145b.png)

It even states above that I should import key images, so why is it disabled?

**Comment by selsta** [comment]
@jluttine You have to set the daemon as a trusted daemon or use a local node.
