### ISSUE TITLE
Add Unstoppable Domain Addresses

### ISSUE THREAD

**Issue by trymeouteh** [monero-project/monero-gui#2853]
Please add support for using unstoppable domains names as cryptocurrency addresses you can enter in to send payments to. Unstoppable domains allow you to send crypto to .zil and .crypto domain names.

**Comment by selsta** [comment]
Monero supports openalias.org

Unstoppable Domains has an affiliate system + premium domains which make me immediately skeptical of it.

**Comment by trymeouteh** [comment]
The investors part is true and is a concern. But it is very popular and the domains are censorship resistant, making it so the domains cannot be stolen from you and if you post your XMR address or any other crypto address on your unstoppable domain, since this data is saved on the ethereum or zilliqa blockchain, it cannot be tampered with. No hacker can hack my domain and change my XMR address or other crypto address. If I post a XMR address on my website, a hacker can hack my site and change the XMR address and I may not notice for quite some time.

I do not know if OpenAlias has this security in it. I do know that unstoppable domains are trying to prevent domain grabbing so people cannot buy company names and try to sell them to those companies later on like the dot com era.

I think this should be added since it seems to be the universal blockchain domain system out there. I would say it has had more success than OpenAlias and Namecoin.

**Comment by trymeouteh** [comment]
Another option is using FIO but to my understanding unstoppable domains are more secure since they are censorship resistant making it so no hacker can hack the domain and change the wallet addresse.

https://github.com/monero-project/monero-gui/issues/2900

**Comment by selsta** [comment]
Closing as we most likely won't add anything with a token.
