### ISSUE TITLE
I can't mine with the GUI-wallet

### ISSUE THREAD

**Issue by Coringa131830** [monero-project/monero-gui#2886]
Why can't I mine with the GUI-wallet in linux.? The daemon has already synchronized, and the wallet too. But the error could not start mining.
Can anyone help me? I'm very new to this.

**Comment by dEBRUYNE-1** [comment]
Which `Wallet mode` are you using? You can check on the `Settings` page.

**Comment by Coringa131830** [comment]
Tks bro.

**Comment by Coringa131830** [comment]
Can you help me? I'm trying to mine Monero with xmrig on ubuntu 20.04, but I don't know how to install, and configure the miner. On windows, I was already mining and it was much easier. Do you have a tutorial to indicate? I've been looking for days but I can't find it.
Thank you.

**Comment by Coringa131830** [comment]
I'm using the miningpoolhub

**Comment by selsta** [comment]
I would suggest asking in r/moneromining subreddit.

This is a bug tracker for monero-gui.

**Comment by Coringa131830** [comment]
ok. i'm sorry.
Thanks
