### ISSUE TITLE
subaddresses as the standard

### ISSUE THREAD

**Issue by Sunray-Nucleon** [monero-project/monero-gui#2923]
Can we make subaddresses the standard? Let's hide the 4... address behind a "advanced" menu named 'show secret integrated address' and advice users to not give out this main address.

Maybe create a first subadress automatic at first wallet-start and display it, or just show a button 'create address' but not show 4... address in first place, instead hide it.

We would want to propagate the use of subaddresses, right? [_edit: removed naming thought_]

Integrated addresses would, of cause, still work. Its meant as change of display and treat addresses in a better way.

**Comment by rating89us** [comment]
I agree with your proposal.

Currently the wallet's primary/main address (4...) is being displayed in the Settings > Seed & Keys page, and I believe it should only be displayed there: 
![image](https://user-images.githubusercontent.com/45968869/82987161-647eee00-9ff7-11ea-89ba-f7524a4b4a8a.png)

Account page should not display main address or subaddresses anymore (see #2925)

Receive page should only create and display subaddresses (I'll redesign this page soon).

**Comment by Sunray-Nucleon** [comment]
> remove first address of each account: displaying a single address for each account incentivizes address reuse, discourages use of subaddresses, and gives a false idea that each account has an "official" or "main" address

this point of #2925 hits it - hide initial 4... integrated address and show subaddress! thank you
