### ISSUE TITLE
Text cursor always on focus

### ISSUE THREAD

**Issue by pijcab** [monero-project/monero-gui#2924]
The text cursor for the wallet password text field is always blinking like the GUI is in focus even when it's not on Widows.
This has led me to type multiple times my password on a Discord chat which was in focus instead of the wallet...
I don't know if I'm the only one having this issue or not but this is infuriating, I've changed my password like 5 times this month.

**Comment by selsta** [comment]
What OS are you using? I can’t reproduce this on my system (macOS), the cursor only blinks when in focus.

**Comment by rating89us** [comment]
Can't reproduce on Windows and Discord chat.

**Comment by pijcab** [comment]
Hi,
It doesn't happen all the time but here is an exemple : https://i.imgur.com/FEm8hUX.png
I'm on W10, as you can see I have a 2 monitor setup, which could be causing this issue

**Comment by xmrdsc** [comment]
I was able to reproduce the bug and PR a fix.

**Comment by pijcab** [comment]
Damn, I was looking at that specific line in the .qml file but I didn't know how to fix it... 😅 

Thank you for the fix !
