### ISSUE TITLE
Receive "Help" box and Sign/verify boxes still need styling

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#293]
All of the rest of the information/alert boxes in the wallet are styled nicely except for those two.

![screen shot 2016-12-15 at 7 43 06 pm](https://cloud.githubusercontent.com/assets/21302237/21247699/95bbd3bc-c2ff-11e6-9984-669d0a8c370e.png)
![screen shot 2016-12-15 at 7 44 54 pm](https://cloud.githubusercontent.com/assets/21302237/21247701/97561098-c2ff-11e6-9312-0404d0b9230d.png)

**Comment by erciccione** [comment]
Not meaningful anymore

+resolved
