### ISSUE TITLE
Unable to create wallet in Ledger nano s

### ISSUE THREAD

**Issue by mavs111** [monero-project/monero-gui#2930]
Hey there,
I've been trying to add account on the ledger nano s Monero app. I have downloaded the latest Monero GUI wallet on my PC and im trying to create a wallet from the advanced tab. I have installed the full node version of the wallet on the pc.

![Screenshot (4)](https://user-images.githubusercontent.com/59227624/83400531-a3120f80-a420-11ea-91f7-fa9efe3f0974.png)

Can someone please explain what i should do to make this work ?

**Comment by dEBRUYNE-1** [comment]
Please see:

https://www.reddit.com/r/monerosupport/comments/gu3h2a/a_note_for_ledger_monero_users/

**Comment by mavs111** [comment]
Thank you for the reply.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dEBRUYNE-1** [comment]
You're welcome.

**Comment by dEBRUYNE-1** [comment]
The new version of the Ledger Monero App has been released.

https://www.reddit.com/r/Monero/comments/gx3zqr/ledger_monero_app_160_now_available/
