### ISSUE TITLE
Ledger Nano X Issue

### ISSUE THREAD

**Issue by DominiSpensar** [monero-project/monero-gui#2934]
My goal is to set up my wallet using the ledger. Why do I continue to get this error? Please help. I am new to this. Thanks. 

failed to generate new wallet: Wrong device status: 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), MASK 0xffff

**Comment by selsta** [comment]
Ledger has to release a new app version to support v0.16. When they do this is out of our control.

**Comment by DominiSpensar** [comment]
I am currently publishing a review of this Nano X and will include this information, cool? I also received the NANO S. Should I use that instead of the NANO X for now...?

Best

**Comment by selsta** [comment]
Both Ledger Nano X and S require an app update, see here: https://github.com/LedgerHQ/app-monero/issues/58

**Comment by DominiSpensar** [comment]
Thanks for speedy response.

**Comment by JamesF1010** [comment]
I am having the same response with Ledger/Monero.  There doesn't appear to be any other solution.

**Comment by lacksfish** [comment]
@JamesF1010 There is no other solution, just wait a few hours/days for the update and keep using v0.15 of Monero until then.

**Comment by selsta** [comment]
Please follow the linked issue for updates.

**Comment by dEBRUYNE-1** [comment]
The new version of the Ledger Monero App has been released.

https://www.reddit.com/r/Monero/comments/gx3zqr/ledger_monero_app_160_now_available/
