### ISSUE TITLE
Funds transfer not successful, Daemon fully synched  

### ISSUE THREAD

**Issue by Ommy77** [monero-project/monero-gui#2938]
On 2020/05/04 10:52am CEST I sent 2.19990000 XMR from my Bittrex acc to my Nano S. The money has still not showing in my Gui wallet despite the wallet and Daemon being fully synched. Bittrex is no longer showing the XMR in my acc and says that the withdrawl was successful. Ive tried resynching the wallet a number of times now and I am still not seeing my funds.

Can someone help? 

![IMG_3387](https://user-images.githubusercontent.com/43322701/84025781-70ba6200-a98c-11ea-9f72-35ba6c8e6ccb.jpg)

**Comment by selsta** [comment]
What wallet mode are you using? You can check in Settings -> Info.

**Comment by Ommy77** [comment]
<img width="511" alt="Screen Shot 2020-06-08 at 13 42 28" src="https://user-images.githubusercontent.com/43322701/84026920-6ef19e00-a98e-11ea-8e10-31a287d896f0.png">

**Comment by selsta** [comment]
You are using extremely outdated software. Update to v0.16 and try again. You will also have to update your Ledger firmware and monero app.

**Comment by Ommy77** [comment]
Ok , once I update, should I be able to see the funds?

**Comment by selsta** [comment]
Yes.

**Comment by Ommy77** [comment]
K, cheers. I'll give that a go.

**Comment by selsta** [comment]
It might take a while to sync up when you update.

**Comment by Ommy77** [comment]
Hi,
I downloaded the latest version, and after signing in, I had this circling for 2 hours with no change. Does this sound right to you? I eventually had to stop it, should I have waited longer?
Thx

<img width="835" alt="Screen Shot 2020-06-08 at 14 35 30" src="https://user-images.githubusercontent.com/43322701/84065195-3e2c5b80-a9c4-11ea-83a1-43796c6da9ec.png">

**Comment by selsta** [comment]
Did you export the view key on your Ledger?

**Comment by Ommy77** [comment]
yes

**Comment by selsta** [comment]
Which monero ledger app version do you have? Also can you try again and make sure to look on the Ledger in case it requires input?

**Comment by Ommy77** [comment]
ok, Ill try again. Im about an hour away from home so I will update later.
Thx.

**Comment by Ommy77** [comment]
Hello,
Me again. I think I'm doing something wrong at this point. I updated the firmware on my ledger and I spent the last two days syching everything in the Monero wallet and I still see a zero balance in my Monero wallet. The Monero wallet app I have is 1.6.0.
Is there something else I can try?
Thanks in advance :)

**Comment by Ommy77** [comment]
Hello,

Me again again :)

Just logged out of the wallet and back in and my funds are now showing. 

Really appreciate your help. Thanks a million :)

**Comment by selsta** [comment]
@Ommy77 Good to hear. If you are having a problem in the future you can open a new issue or ask on Reddit / Stackexchange.
