### ISSUE TITLE
Not getting rewards for mining

### ISSUE THREAD

**Issue by jon-ryan** [monero-project/monero-gui#2944]
I'm new to Monero mining and tried it out the last couple of days. But it looks like that I don't get any rewards. I had my miner running for a couple of hours at about 2k H/s and didn't receive any rewards yet. I only have one wallet.
Any ideas?

**Comment by selsta** [comment]
Solo mining is more like a lottery. It will take you on average 550 days to find a block with your hashrate. If you are lucky, it will be sooner.

If you want more consistent payout I would recommend you a mining pool.

Also note that mining with 2kH/s is more for supporting the network, don’t expect it to be profitable.

**Comment by jon-ryan** [comment]
Alright, thank you!
