### ISSUE TITLE
Transactions stuck at pending (Waiting for transaction to leave txpool)

### ISSUE THREAD

**Issue by neponel** [monero-project/monero-gui#2954]
Hi all,

I'm new to this so would appreciate any help even if my question is dumb. 
A transaction of mine was stuck at pending. I've tried re-naming my {wallet} to {wallet}-old, and re-syncing, and sent another transaction. It's stuck again!
I think I'm using a remote node, on mac GUI client - the settings section of the client doesn't have a "log" tab too. 
What should I do? 

Thanks!!

**Comment by selsta** [comment]
Are you using simple mode? You can check in Settings -> Info.

**Comment by neponel** [comment]
Thanks for your reply. I am indeed using simple mode. Already tried switching to a new node - it says "successfully connected to a new node" but it hasn't resolved the problem unfortunately.

**Comment by selsta** [comment]
Ok, will take a look if there are problems with node switching.

In the meantime you can click on the exit icon in the top left corner, click on "Change wallet mode" -> Advanced mode, then open your wallet, go to Settings -> Node, select remote node and enter node.xmr.to port 18081

**Comment by neponel** [comment]
Ok, so I swapped to Advanced mode and noticed that I in fact have a local node, not remote! The transaction is still pending...

**Comment by selsta** [comment]
Did you select a remote node and entered node.xmr.to 18081?
<img width="1026" alt="Screenshot 2020-06-15 at 14 15 13" src="https://user-images.githubusercontent.com/7697454/84656217-a1f9db80-af12-11ea-9ff1-9828ba0a2f07.png">

**Comment by neponel** [comment]
I have managed to resolve the issue using the advanced settings. Thanks a lot for your help!
