### ISSUE TITLE
Monero GUI with Local node - Failed to read line. monerod log spam

### ISSUE THREAD

**Issue by NewEraCracker** [monero-project/monero-gui#2958]
When starting the GUI wallet with local node option, the logs of monerod become filled with:
ERROR	console_handler	contrib/epee/include/console_handler.h:397	Failed to read line.

Workaround to prevent this, is to start wallet in low graphics mode.

![LogSpam](https://user-images.githubusercontent.com/416945/84707257-4c472280-af56-11ea-9959-20d97894afe3.png)

**Comment by selsta** [comment]
Fixed in #3360
