### ISSUE TITLE
Trouble think about users in mainland China ----Hope to open a proxy function

### ISSUE THREAD

**Issue by vvring** [monero-project/monero-gui#2970]
Trouble think about users in mainland China
Hope to open a proxy function
麻烦考虑一下中国大陆区的用户
希望开个代理功能

**Comment by selsta** [comment]
Can you explain the problem a bit more? Do you have problems connecting to remote nodes?

**Comment by vvring** [comment]
Switched multiple times
Always in this state
![捕获](https://user-images.githubusercontent.com/47848167/85925349-712e8480-b8ca-11ea-9f9f-d7624c615391.PNG)

**Comment by vvring** [comment]
![捕获](https://user-images.githubusercontent.com/47848167/85925693-b653b600-b8cc-11ea-8dd9-247b27ce1805.PNG)

多次切换
始终处于此状态

**Comment by selsta** [comment]
I can’t read Chinese. It seems to be working in the second picture you posted.

**Comment by vvring** [comment]
> I can’t read Chinese. It seems to be working in the second picture you posted.

No, more than ten hours have passed
Still like this

**Comment by unknown52** [comment]
@selsta - Potentially the remote nodes are blocked in China then?

**Comment by xiphon** [comment]
Fixed via https://github.com/monero-project/monero-gui/pull/3033 and https://github.com/monero-project/monero-gui/pull/3089.
