### ISSUE TITLE
Error opening wallet: internal error: failed to deserialize keys buffer

### ISSUE THREAD

**Issue by deathmorlock** [monero-project/monero-gui#2983]
Hello,  tried to restore monero gui wallet from keys and have such bug while import .key file
Error opening wallet: internal error: failed to deserialize keys buffer

**Comment by selsta** [comment]
What OS are you using? Can you try to restore from seed?

**Comment by deathmorlock** [comment]
OS win 7 and tried on win 10.  Will test on ubuntu now.
No i  only have backups of keys file. What info i can collect for you for diagnosting?
Also can send .key file (but only in private message)

**Comment by selsta** [comment]
> failed to deserialize keys buffer

Usually means corrupted file. Where did you store it?

**Comment by deathmorlock** [comment]
on external hdd.
7,73 KB.

**Comment by selsta** [comment]
Did you manage to resolve the issue? Maybe try to directly copy it from HDD to Ubuntu.

Also my .keys file are 1.5KB, 7.73KB sounds weird.
