### ISSUE TITLE
monero-gui characters completely messed up

### ISSUE THREAD

**Issue by FabioNevesRezende** [monero-project/monero-gui#2985]
Hello, I've just installed `monero-gui` from archlinux repository and it doesn't matter if I put it in my native language or in english, the character shown is completely messed up, it looks like some encoding problem. Can you guys help me on that?

I'll leave this printscreen as an example:
https://i.imgur.com/EFF1WUZ.png

**Comment by selsta** [comment]
Can you test if the version from getmonero.org displays correctly? If yes please report to the arch package maintainer.

**Comment by FabioNevesRezende** [comment]
well, the official website version worked correctly, I'll contact the maintainer then. Thanks for the help
