### ISSUE TITLE
Feature request: Display subaddress label and subaddress against each incoming transaction

### ISSUE THREAD

**Issue by knaccc** [monero-project/monero-gui#2987]
Current situation:

User creates a subaddress to receive a payment, and assigns a label such as "Rent from Bob"
User sees incoming transaction, then has to click the 'down arrow' and then click the 'i' button to see which subaddress it came from. Then the user needs to keep a note of that address, go back to the 'Receive' tab, and then scroll through the list of subaddresses to match the subaddress to the label that they assigned. Only then will they know it was from Bob. If lots of subaddresses have been issued, this will be a very tedious process.

Proposal:
In the transactions section, show the abbreviated subaddress and full subaddress label next to each transaction. Then, when a transaction is received, the user can immediately see it was "Rent from Bob" without further effort.

**Comment by rating89us** [comment]
I'll take a look in this. Thanks.
