### ISSUE TITLE
Feature idea: Show solo mining block reward and daily chance of winning

### ISSUE THREAD

**Issue by knaccc** [monero-project/monero-gui#2990]
The GUI currently says "Mining also gives you a small chance to earn some Monero".

It would be much more compelling if it presented the user with the size of reward and probability of winning.

For example, if you were able to mine 1500H/s, it could tell you that you have a 1 in 1416 daily chance of winning 1.5813 XMR (those are real stats for a high-end laptop). That's much more exciting!

**Comment by selsta** [comment]
#2994
