### ISSUE TITLE
macOS version of GUI wallet is not updated

### ISSUE THREAD

**Issue by jorgschulze73** [monero-project/monero-gui#3005]
As per title, it seems that macOS version of GUI wallet is not updated on the monero website.
Links on the website allow to download version 0.16.0.2 for all the platforms except macOS, for which the link still points to 0.16.0.0

https://web.getmonero.org/downloads/#gui

**Comment by selsta** [comment]
Can you try to empty your cache or use a different browser? Works as expected here.

**Comment by jorgschulze73** [comment]
Wow that's true, cache was the issue.
Closing the issue 'cause it was problem on my side.
Thank you.
