### ISSUE TITLE
Docker static builds: undefined reference to symbol 'xcb_glx_id'

### ISSUE THREAD

**Issue by tobtoht** [monero-project/monero-gui#3011]
`docker run --rm -it -v $(pwd):/monero-gui -w /monero-gui monero:build-env-gui sh -c 'USE_SINGLE_BUILDDIR=ON DEV_MODE=ON make release-static -j4'` fails with:

```
[ 78%] Building CXX object src/CMakeFiles/monero-wallet-gui.dir/qrc_translations.cpp.o
[ 78%] Linking CXX executable ../bin/monero-wallet-gui
/usr/bin/ld: /usr/plugins/xcbglintegrations/libqxcb-glx-integration.a(qxcbglxintegration.o): undefined reference to symbol 'xcb_glx_id'
//usr/lib/x86_64-linux-gnu/libxcb-glx.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/monero-wallet-gui.dir/build.make:1554: recipe for target 'bin/monero-wallet-gui' failed
```

Tested on current master (b7b1221) and Docker version 19.03.12

**Comment by xiphon** [comment]
This can't be `docker build ...` output, this step doesn't build Monero GUI. Please double check this.

**Comment by tobtoht** [comment]
My bad, I copied the wrong command. I have updated the issue.

**Comment by xiphon** [comment]
Could you try to `rm -rf build` directory and run the build again?

**Comment by tobtoht** [comment]
I tried that just now, the issue is still there.

**Comment by tobtoht** [comment]
Full build logs: https://paste.debian.net/plainh/6343a879

**Comment by xiphon** [comment]
Could you please test the fix? https://github.com/monero-project/monero-gui/pull/3015

**Comment by tobtoht** [comment]
Thanks for taking the time to look into this. 

The build succeeds now.
