### ISSUE TITLE
Merchant page is not using the selected address but the primary address

### ISSUE THREAD

**Issue by dalecooper** [monero-project/monero-gui#3036]
When using the merchant page to generate a QR code with the amount, the "Currently selected address" is OK (it's the label of the sub address that I've selected in the receive page), but the address in the payment URL is always the primary address.
The QR code is also using the primary address.

**Comment by garlicgambit** [comment]
It will use the primary address of the account that you've selected. If you need to use the merchant page and need a different (sub)address you can create a new account. But it is a cumbersome workaround.

**Comment by zzaappedd** [comment]
so why the option to change in the merchant page if the change won't apply to the merchant page?
