### ISSUE TITLE
How does a process start with multiple threads

### ISSUE THREAD

**Issue by Black52** [monero-project/monero-gui#3039]
watch_only_wallet  rpc Node startup occupies only a single core CPU，And use 100 percent。Nodes often die。
It takes five minutes to create the address。Is there any way to start with multithreading？
My server is 4-core 8GB。
Version used：monero-x86_64-linux-gnu-v0.16.0.1。

**Comment by selsta** [comment]
Is this GUI or CLI?

**Comment by Black52** [comment]
> Is this GUI or CLI?
The operating system is ubuntu.
monero-wallet-rpc/monero-wallet-cli Both are slow。
