### ISSUE TITLE
Compilation GUI for Windows

### ISSUE THREAD

**Issue by gvozdi1234** [monero-project/monero-gui#3041]
I'm trying to compile GUI for Windows as described here https://github.com/monero-project/monero-gui. After execution "make deploy" I'm getting the error (see screenshot). How to fix it? Is there another way to compile it?
![Untitled](https://user-images.githubusercontent.com/69717319/90311569-9b281e80-deeb-11ea-9632-626d0db4f09d.png)

Also tried executing "windeployqt C:/msys64/home/Administrator/monero-gui/build/release/bin/monero-wallet-gui.exe -no-translations -qmldir=C:/msys64/home/Administrator/monero-gui", got error when launching compiled exe (screenshot 2)
![Untitled-2](https://user-images.githubusercontent.com/69717319/90311555-88154e80-deeb-11ea-9bb1-b3fcad5e9f88.png)

**Comment by selsta** [comment]
Can you drag and drop the screenshot here into Github?

**Comment by gvozdi1234** [comment]
> Can you drag and drop the screenshot here into Github?

Attached

**Comment by selsta** [comment]
Seems to be similar to https://github.com/monero-project/monero-gui/issues/3021

As an (unsatisfying) workaround you can start the GUI directly from the mingw64 console and skip the deploy step.

**Comment by selsta** [comment]
Will be fixed with #3047
