### ISSUE TITLE
Error writing wallet from hardware device...

### ISSUE THREAD

**Issue by epimazzo** [monero-project/monero-gui#3057]
Hey there,

I'm under the latest MacOS Catalina version running the latest 2.10.0 Ledger Live app and trying to create a new wallet from the hardware with Monero App client just downloaded. It fails all the time. I have a Nano S device.

ERROR:
 error writing wallet from a hardware device. Check the application logs.

Any idea how to fix it? 

Thanks for it.

**Comment by selsta** [comment]
What Ledger monero app version?

Also there should be an additional error message on the bottom of the screen, can you post it?

**Comment by epimazzo** [comment]
> What Ledger monero app version?
> 
> Also there should be an additional error message on the bottom of the screen, can you post it?

Hey Selsta,
Thanks for coming by...

I've just downloaded the latest version from the Monero community website for MacOS 64Bits. Version is 0.16.0.3 (qt 5.12.8)
The bottom message is: Failed to generate new wallet. Unable to open device 4:11415

I'm connected to Ledger Live and logged in with my Nano unlocked showing up all crypto. Manager is also opened. 

Thanks.

**Comment by selsta** [comment]
Please make sure that Ledger Live is closed when using Ledger + Monero, it can interfere. Also try to restart your computer.

**Comment by epimazzo** [comment]
Now I got a different error in the bottom:

Failed to generate a new wallet. Wrong channel. MacBook was restarted. No extra app opened. 

Thanks

**Comment by selsta** [comment]
Just to confirm:

- v0.16.0.3 GUI
- Firmware 1.6.1
- Monero Ledger app v1.6.0

? I also run latest MacOS Catalina so not sure what is going on here.

**Comment by epimazzo** [comment]
All versions are equal than yours except my Ledger Live firmware which is 1.2.4-4

Monero is 1.6.0 and GUI is 0.16.0.3 

That was funny. ;-)

**Comment by epimazzo** [comment]
Which 1.6.1 firmware is this?

**Comment by selsta** [comment]
Ledger firmware 1.6.1

**Comment by epimazzo** [comment]
Hummmm..... mine is getting a different Firmware version. Do you have a Nano S? Cause that's what I have with this updated firmware on it. Just grab it from the update notification right after I had plugged in. :-) Our Ledger Live is the same.

**Comment by selsta** [comment]
You sure that you don’t have a Ledger Nano X? :) Though it should also work with Monero.

**Comment by epimazzo** [comment]
Mine is a Nano X ledger. ;-) Sorry LOL! 

but it's using a different firmware version than you.

**Comment by selsta** [comment]
You have the correct firmware, S and X have different versioning.

Did you accept exporting the view key during wallet creation?

**Comment by epimazzo** [comment]
Nope, not even get into this point. It fails right in the beginning while in the creation window. Sounds weird. It should work as expected.

**Comment by selsta** [comment]
Did you connect using bluetooth or USB?

**Comment by epimazzo** [comment]
Connected through an USB Hub. My MacBook Pro is a 2019 15' with only usb-c input.

**Comment by epimazzo** [comment]
Hi Selsta,

No more clues ;-) can't figured out yet...

**Comment by selsta** [comment]
Sorry, forgot to reply. At this point I suspect its the USB hub, maybe the USB library used (hidapi) does not play well together with it.

Do you have a Micro USB to USB-C cable to test this?

**Comment by epimazzo** [comment]
No worries ;-) 
Unfortunately not. I'll try to borrow one USB-C cable. But Nano X has Bluetooth on it. Wouldn't work? I tried but it could be found too. LOL!

**Comment by selsta** [comment]
I’m not familiar with bluetooth.

**Comment by epimazzo** [comment]
Yep..Bluetooth does not work at all. Meanwhile, I got this new error:

Failed to generate new wallet: Wrong device status. 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), MASK 0xffff

**Comment by epimazzo** [comment]
Hi Selsta,

I just figured out what was causing this issue and believe me; it was a simple step! 

The Monero App must be up and running in your ledger Nano X before the wallet is created. Otherwise, you get these errors. 

It's all clear now! 

Thanks for your help and support.

**Comment by selsta** [comment]
Good to know for the future to ask this if someone has problems, thanks for the follow up.

**Comment by reanimat0r** [comment]
> Hi Selsta,
> 
> I just figured out what was causing this issue and believe me; it was a simple step!
> 
> The Monero App must be up and running in your ledger Nano X before the wallet is created. Otherwise, you get these errors.
> 
> It's all clear now!
> 
> Thanks for your help and support.


Thank you for the heads up, brother. It helped me to get over the errors as well, so I could complete the Ledger X Setup!
