### ISSUE TITLE
Improve highlighting of currently selected receive address and account

### ISSUE THREAD

**Issue by garlicgambit** [monero-project/monero-gui#3067]
The GUI only highlights the number at the beginning of the row. Example: `#0`. Suggest to highlight the entire row with a different color. This can prevent accidental address reuse. When you hoover over a row it will use a different color scheme. Apply this to the currently selected entry, but with a different color.  
  
Or redesign the interface in such a way that the selected entry is always visible. Like how you can configure a spreadsheet to freeze a specific row that will always be visible even when you scroll.

**Comment by rating89us** [comment]
see also #2572
