### ISSUE TITLE
Readme.md change http to https links

### ISSUE THREAD

**Issue by garlicgambit** [monero-project/monero-gui#3073]
There are a couple of http links. Please change them to https.

**Comment by xmrdsc** [comment]
It's open-source, have a go at a PR?

**Comment by selsta** [comment]
FWIW I will rework the sponsors in CLI / GUI readme once https://github.com/monero-project/monero-site/pull/1174 is merged.

**Comment by selsta** [comment]
All sites that support https now link to https.
