### ISSUE TITLE
"Syncing..." on account card not translated

### ISSUE THREAD

**Issue by danyim** [monero-project/monero-gui#3119]
The word "Syncing..." on the Left Panel isn't applying the translation [even though the entry exists](https://github.com/monero-project/monero-gui/blob/master/translations/monero-core_de.ts#L672)

This is in DE:
![image](https://user-images.githubusercontent.com/442889/94557405-5d6d2400-0213-11eb-98e2-088525bd2e1c.png)

**Comment by selsta** [comment]
Which version are you using?

**Comment by selsta** [comment]
Thank you for reporting, see #3120
