### ISSUE TITLE
History: received transactions don't display fee

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#3124]
transaction fee information could be recovered from the blockchain

**Comment by xiphon** [comment]
I doubt a recipient needs such information. Could you provide a use case?

**Comment by rating89us** [comment]
Someone from your family sends you a transaction paying a high fee ("Fastest (x200 fee)" option in GUI).
Then you warn this person "Hey, I saw that you used the fastest fee option. You don't need to use this fee level the next time".

Also, transaction fee is a public information, there is no reason to hide it in GUI.

**Comment by xiphon** [comment]
Providing tx fee information to a recipient will require some (most probably significant) efforts. The use case you mentioned doesn't seem to be worth it.
