### ISSUE TITLE
Transaction stuck at "waiting confirmation..."

### ISSUE THREAD

**Issue by gringofe** [monero-project/monero-gui#3149]
Hello,  

I tried to send funds yesterday and the transaction has been stuck with "Waiting confirmation..." in the "To" field ever since. 
When I click on the P icon, it says "Couldn't generate a proof because of the following reason: daemon returned wrong response for gettransactions, wrong txs count = 0, expected 1"

I am using latest Linux 64 bit (v0.17.0.1)

**Comment by selsta** [comment]
Please see this comment for a workaround:

https://github.com/monero-project/monero-gui/issues/3140#issuecomment-706440354

We are working on a new version to fix this issue.

Closing as duplicate.
