### ISSUE TITLE
Dropdown menus don't work on KDE Plasma

### ISSUE THREAD

**Issue by nameless1337** [monero-project/monero-gui#3152]
Title explains it. Expected behavior is to be able to select options from dropdown menus but they don't seem to display at all. First encountered this issue when trying to create a wallet from a hardware device and it wouldn't let me select the hardware device. Confirmed working in XFCE but I prefer not to use XFCE. Running Arch Linux using the latest monero-gui package from the community repository.

![image](https://user-images.githubusercontent.com/49504800/95841418-dea8d880-0d34-11eb-9358-fbd9e3c12f80.png)

![image](https://user-images.githubusercontent.com/49504800/95841345-c6d15480-0d34-11eb-9161-63b1e9cfb0d2.png)

**Comment by selsta** [comment]
Does this work with the getmonero.org binary? If yes, please report to the package maintainer.

**Comment by nameless1337** [comment]
> Does this work with the getmonero.org binary? If yes, please report to the package maintainer.

Yep it does. I didn't even know there was an AppImage binary for this application so I'll just use that from now on but I will be sure to report this to the package maintainer.
