### ISSUE TITLE
Getting wrong device error with the ledger (0x6a30 expected 0x9000

### ISSUE THREAD

**Issue by Belfor-IT** [monero-project/monero-gui#3154]
Hi, 

I'm getting the wrong device error when I try to log in on my GUI Monero wallet on windows 10 with my ledger. 
Error message"Wrong device status 0x6a30 (unknown)EXPECTED 0x9000 (SW_OK), MASK 0xffff"

**Comment by selsta** [comment]
Do you have some Anti Virus on your system?

**Comment by xiphon** [comment]
Ledger Monero app version is not compatible with the Monero GUI version.

**Comment by Belfor-IT** [comment]
> Ledger Monero app version is not compatible with the Monero GUI version. Check for updates.

I already was using ledger nano S with the Monero Wallet.. was working fine

**Comment by selsta** [comment]
Did you update Monero GUI?

**Comment by Belfor-IT** [comment]
> Ledger Monero app version is not compatible with the Monero GUI version. Check for updates.



> Do you have some Anti Virus on your system?
Yes, but I white listed monero

**Comment by Belfor-IT** [comment]
> Did you update Monero GUI? If yes, please also update Ledger monero app to v.1.7.x
I have updated my Monero GUI and Ledger app V1.7.3 still getting the wrong Device but now  "SW-CLA_NOT_SUPPORTED" status 0x6e00 EXPECTED 0x9000

**Comment by selsta** [comment]
And you used Monero GUI v0.17.0.1 ?

**Comment by Belfor-IT** [comment]
> And you used Monero GUI v0.17.0.1 ?

Yes!

**Comment by selsta** [comment]
Please try again with v0.17.1.0 and Ledger app v1.7.4 and make sure that Ledger Live is closed.

**Comment by Belfor-IT** [comment]
It's working again!
