### ISSUE TITLE
Existing sub address(s) no longer display - but still work.

### ISSUE THREAD

**Issue by ronohara** [monero-project/monero-gui#3162]
I had two extra subaddresses from the main wallet - and they still work because I just sent a test from Cake Wallet to one of them.

But when I opened up the accounts page they do not display(they used to). Other new ones which are now called 'accounts' but still have the '8' subaddress prefix, that I add do get displayed. 

file 1 main account ..  plus two new 'accounts' that I just added as per the Accounts page
file 2 - the test transaction to the old subaddress '89cq...' which no longer shows in the account page but still works.

![temp1](https://user-images.githubusercontent.com/4027321/96333356-3f9c1d80-1061-11eb-8caa-8454ef54632c.jpg)
![temp2](https://user-images.githubusercontent.com/4027321/96333360-43c83b00-1061-11eb-868f-55fdfce9c4fc.jpg)

**Comment by rating89us** [comment]
Probably you restored your wallet and the older subaddresses are not being displayed. But the wallet should display a subaddress after detecting a receiving transaction for it. I'm not sure if it is currently looking ahead subaddresses until finding it.

**Comment by selsta** [comment]
@ronohara 

Look on the Receive page. Every account has its own subaddresses so look through all 3 of them to find your address.

**Comment by ronohara** [comment]
@rating89us - wallet has never been restored.

**Comment by rating89us** [comment]
Account page displays only the first address (address #0) of each account. If you want to see the remaining addresses inside each account, you have to select the account and open Receive page. For example:

To see subaddresses of account #1, select account #1 in Account page, and then open Receive page.
To see subaddresses of account #3, select account #3 in Account page, and then open Receive page.

**Comment by ronohara** [comment]
@rating89us  -- Ah I see ... all good
