### ISSUE TITLE
Waiting Confirmation

### ISSUE THREAD

**Issue by userlip** [monero-project/monero-gui#3179]
I am using the latest Wallet version and this morning I tried to make a transaction that is now stuck at "Waiting Confirmation"
I was using my local node, but also tried it using the XMR.to Node, no changes still.

Also the Transaction appears in the "Transaction" Tab but disappears from there after 30 to 40 seconds.

GUI Version: 0.17.1.0-cb1f3ad

Also: I do not want this transaction to go through anymore as I already made the payment, do I need to do something? (I am scared that the transaction will go through if the bug is fixed)

**Comment by selsta** [comment]
What is the output of "status" if you enter it on Settings -> Log?

**Comment by userlip** [comment]
`>>> status
[18.10.2020 14:53] 2020-10-18 12:53:37.017 I Monero 'Oxygen Orion' (v0.17.1.0-release) 
Error: Couldn't connect to daemon: 127.0.0.1:18081`

**Comment by selsta** [comment]
Is this with local node running or connected to remote node?

**Comment by userlip** [comment]
I now have it connected to the remote node of XMR.to as mentioned in this comment https://github.com/monero-project/monero-gui/issues/3140#issuecomment-706480292

But at the time of the creation of the transaction I was running everything locally

**Comment by userlip** [comment]
Version 0.17.1.1 of the Wallet now shows the Transaction as failed
