### ISSUE TITLE
Not receiving transaction on second receive address

### ISSUE THREAD

**Issue by dundunn** [monero-project/monero-gui#3183]
I created a second receive address in the client and used that to buy coins. My exchange sent me the transaction ID but there is no transaction to be found in the client. I trust the exchange but how can I get to the coins from here? Network status is connected and the wallet is synced.

**Comment by selsta** [comment]
Do you have a transaction id?

**Comment by dundunn** [comment]
Sorry of course :facepalm: 

https://xmrchain.net/search?value=7f24dc9621247ff297c09859802351f08c16fb9e5ecfc07116d288f68f15b2c2

**Comment by selsta** [comment]
Did you create the new receiving address on the "Account" tab or on the "Receive" tab?

Also can you go to Settings -> Log and enter "status" and post the output here.

**Comment by dundunn** [comment]
> Did you create the new receiving address on the "Account" tab or on the "Receive" tab?

I created the wallet in the receive tab. 

```
>>> status
[10/20/20 10:08 AM] 2020-10-20 08:08:04.469 I Monero 'Oxygen Orion' (v0.17.1.1-release)
Height: 2212305/2212305 (100.0%) on mainnet, bootstrapping from 159.65.173.58:18089, local height: 1 (0.0%), not mining, net hash 1.64 GH/s, v14, 0(out)+0(in) connections
```

**Comment by selsta** [comment]
Looks all good.

Can you go to Settings -> Info and check if Wallet creation height is lower than 2211852

If yes, click on "(Change)" and press okay twice and wait for it to rescan.

**Comment by dundunn** [comment]
> Can you go to Settings -> Info and check if Wallet creation height is lower than 2211852
> 
> If yes, click on "(Change)" and press okay twice and wait for it to rescan.

Thank you so much, that was the issue. The XMR are now available after rescanning.

**Comment by dundunn** [comment]
Ok I still having issues with those coins, I can't do anything with them. When I'm trying to send them to an other wallet the transaction seems to go through but after some minutes the recipient changes from `Waiting for confirmations` to `Failed`. The transaction disappears when I restart the client.

**Comment by selsta** [comment]
How often did you try? If this happened multiple times I would try switching to a custom node as explained here: https://github.com/monero-project/monero-gui/issues/3140#issuecomment-706440354

**Comment by dundunn** [comment]
I tried it about 5 times with different wallets. But using the remote node worked :) Thanks for the help.
