### ISSUE TITLE
link to monero hashes.txt outdated

### ISSUE THREAD

**Issue by adrelanos** [monero-project/monero-gui#3189]
`https://web.archive.org/web/20201022105210/https://github.com/monero-project/monero-gui/releases/tag/v0.17.1.1` links to `https://getmonero.org/downloads/hashes.txt` which then redirects to `https://web.getmonero.org/downloads/hashes.txt`.

This makes it a bit harder to web archive these links.

If the location change is permanent, please consider updating that link for the next release.

**Comment by xiphon** [comment]
Please submit this to https://github.com/monero-project/monero-site/ repository.

**Comment by adrelanos** [comment]
https://github.com/monero-project/monero-site/issues/1419

**Comment by xiphon** [comment]
Thanks.

**Comment by erciccione** [comment]
This is unrelated to monero-site, since it's about the github release notes: https://github.com/monero-project/monero-gui/releases/tag/v0.17.1.1 

We correctly link to `www.getmonero` from the blog posts (even if the URL displayed is `https://getmonero.org/downloads/hashes.txt `, and yes, that should be fixed regardless)

**Comment by xiphon** [comment]
> This is unrelated to monero-site, since it's about the github release notes: https://github.com/monero-project/monero-gui/releases/tag/v0.17.1.1

@adrelanos  @erciccione 

Sorry, i misread web archive URL, thought it was getmonero.org page cache.

Reopened.

**Comment by erciccione** [comment]
@selsta @binaryfate FYI ^ (the link in the release notes will need to be fixed in the future)

**Comment by binaryFate** [comment]
Opinion on updating the link to `https://web.getmonero.org/downloads/hashes.txt` in latest release (v0.17.1.9) notes?
(I wouldn't edit older ones at this stage anyway).

**Comment by xiphon** [comment]
We just change the link, not the hashes, thus sounds good to me.

**Comment by erciccione** [comment]
> Opinion on updating the link to https://web.getmonero.org/downloads/hashes.txt in latest release (v0.17.1.9) notes?

The correct url is `https://www.getmonero.org/downloads/hashes.txt` and yes, sounds good to me as well.

**Comment by binaryFate** [comment]
> The correct url is `https://www.getmonero.org/downloads/hashes.txt` and yes, sounds good to me as well.

Thanks, done

**Comment by erciccione** [comment]
Hashes are fixed. I'd say this is resolved.
