### ISSUE TITLE
Can't create wallet from hardware device

### ISSUE THREAD

**Issue by gmcintyre-conga** [monero-project/monero-gui#3190]
using gui wallet 0.171.1, when I try to create wallet from hardware (NanoX), I receive this error:

failed to generate new wallet: Wrong Device Status 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), Mask 0xffff

I've tried on Mac Mojave & Windows 10. Tried re-installing Monero app on NanoX. Nothing works.

**Comment by selsta** [comment]
You need the latest version of Ledger Live, Ledger firmware 1.6.1 and Ledger Monero app 1.7.4

**Comment by garymcintyre** [comment]
Where can I find firmware v. 1.6.1? The support page only shows me 1.2.4-4, which is already on my device. 
To be clear, this is the url I'm looking at --> https://support.ledger.com/hc/en-us/articles/360013349800-Update-Ledger-Nano-X-firmware

Thanks for your help.

**Comment by selsta** [comment]
Yes, Ledger Nano X has a different firmware. Do you have Ledger Monero app 1.7.4 installed?

**Comment by gmcintyre-conga** [comment]
on the device itself, yes. It says Spec 1.0, App 1.7.4

**Comment by gmcintyre-conga** [comment]
got it. v0.17.1.4 did the trick. thanks again.
