### ISSUE TITLE
Upgrading to any 0.17.x.x version breaks ledger integration

### ISSUE THREAD

**Issue by balboah** [monero-project/monero-gui#3191]
v0.16.0.3 works fine together with Ledger view key.
It prompts to upgrade to the latest v0.17. When you close the app to upgrade and then try to login again, you get:

- wrong device status: (didn't save the hex codes)
- if you retry, the app crashes
- if you close, the app freezes and needs force close

I tried:
- restarting ledger
- reconnecting cable
- all available v0.17 releases

Downgrading to v0.16.0.3 fixes the issue.

**Comment by selsta** [comment]
You have to update your Ledger Monero app to v1.7.4

Also make sure Ledger Live is closed when using it in combination with Monero

**Comment by balboah** [comment]
Thanks, this fixed the issue
