### ISSUE TITLE
Balance does not show

### ISSUE THREAD

**Issue by MrTrewar** [monero-project/monero-gui#3206]
Hi, sorry for the question i'm new to this.
But I send an amount of mxr to the gui wallet and the when i check the prove/check Verification it says

"This address received 1.200000000000 monero, with 555 confirmation(s)."

But it does not show the balance in my wallet.

Do i need to wait longer?

kind regards

**Comment by xiphon** [comment]
Make sure your wallet restore height is less than the transaction height (`Settings` -> `Info` tab).

You can rescan the blockchain: click on wallet restore height `(Change)` -> `Ok` (keep the same wallet restore height value).

**Comment by MrTrewar** [comment]
transaction height is now less, but still no change

**Comment by xiphon** [comment]
Do you see a tx in the block explorer? Make sure your node is synced with the network.

**Comment by MrTrewar** [comment]
hi there, problem solved
conclusion: i was stupid, i put the block height to YYYYMMDD  instead of YYYY-MM-DD, resulting in a very big block heightsolution: put the block height real low 13500 and waited

sorry and thank you
kind regards

**Comment by MrTrewar** [comment]
:)
