### ISSUE TITLE
Language selector overlap on macOS

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero-gui#321]
![screen shot 2016-12-21 at 2 23 32 pm](https://cloud.githubusercontent.com/assets/1944293/21389221/37bd6f9e-c789-11e6-8e63-f388a585fbb9.png)

(also it's RSA not RPA, but minor fix that can be done separately)

**Comment by NanoAkron** [comment]
Send transaction now now or just now?

;)

**Comment by xmr-eric** [comment]
@fluffypony Can this issue be closed?

**Comment by erciccione** [comment]
+resolved
