### ISSUE TITLE
GUI v0.17.1.3 'Oxygen Orion' dosen' t show up on Debian Buster

### ISSUE THREAD

**Issue by mb291** [monero-project/monero-gui#3222]
GUI v0.17.1.3 dosen't  show up on Debian Buster with Backport Kernel and Gnome (Wayland)

`/opt/monero-gui-v0.17.1.3/monero-wallet-gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
2020-11-09 09:31:20.376	W Qt:5.15.2 GUI:0.17.1.3-158e0c3 | screen: 1920x1080 - dpi: 96 - ratio:1.24485
^C
`

Previous versions work.

**Comment by selsta** [comment]
Seems to be a libxcb bug affecting some linux distros. We are working on a new release.

**Comment by mb291** [comment]
I switched back to GUI v17.1.1. Works so far - hope I can send funds if needed.

Regards

**Comment by selsta** [comment]
Sending should work fine with a local node or with a trusted remote node: https://github.com/monero-project/monero-gui/issues/3140#issuecomment-706440354

Simple mode can potentially have issues during sending, use the above link to specify a remote node manually.

**Comment by mb291** [comment]
I'm using pruned node. Should be fine also ? 
Since I don' t understand exactly **do I need trusted node in prune mode?**

Thank you very much!

**Comment by selsta** [comment]
Pruned node is fine.

**Comment by selsta** [comment]
v0.17.1.4 is out
