### ISSUE TITLE
hashes.txt don't match official links

### ISSUE THREAD

**Issue by qertoip** [monero-project/monero-gui#3230]
To download file expected by `hashes.txt` (`monero-gui-linux-x64-v0.17.1.4.tar.bz2`) one needs to manually hack the URL from the official github releases page https://github.com/monero-project/monero-gui/releases

monero-gui-linux-x64-v0.17.1.1.tar.bz2 -> monero-gui-linux-x64-v0.17.1.4.tar.bz2

**Comment by dEBRUYNE-1** [comment]
Probably a local caching issue. Try a hard refresh on the downloads page or use incognito / private mode.

**Comment by qertoip** [comment]
I can see this is now fixed as the new official links were published.

(but this certainly wasn't a cache issue - my browser is hard amnestic - and I haven't visited the releases for weeks)

Thanks!
