### ISSUE TITLE
instructions page -- macos src build needs libsodium brew install

### ISSUE THREAD

**Issue by rednaxus** [monero-project/monero-gui#3234]
the instructions only have this as dependencies

brew install boost hidapi zmq libpgm miniupnpc ldns expat libunwind-headers protobuf libgcrypt

add libsodium

**Comment by selsta** [comment]
Is it required? We don’t use it for our Mac CI, though it could be preinstalled on CI.

https://github.com/monero-project/monero-gui/blob/master/.github/workflows/build.yml#L13

**Comment by rednaxus** [comment]
I had to add it... and my machine is pretty developer beefed up and up to date with latest Catalina, so I don't think it is pre-installed
