### ISSUE TITLE
Why is 0.17.1.4 being hidden by the github API?

### ISSUE THREAD

**Issue by luckman212** [monero-project/monero-gui#3235]
I am always extra careful with releases of crypto-apps, so I verify GPG hashes and things like that. Anything out of place triggers a red flag for me, which is why I'm asking...

```bash
$ curl -s -o- https://api.github.com/repos/monero-project/monero-gui/releases | jq -r '.[0].tag_name'
v0.17.1.3
```
Yet, there's clearly a non-beta 0.17.1.**4** release shown here: 
https://github.com/monero-project/monero-gui/releases/latest

Anyone know the reason?

**Comment by xiphon** [comment]
> Why is 0.17.1.4 being hidden by the github API? 

It is not.
```
$ curl -s -o- https://api.github.com/repos/monero-project/monero-gui/releases | jq -r '.[1].tag_name'
v0.17.1.4
```

**Comment by luckman212** [comment]
Strange, in all other repos I interact with, the first array element `[0]` returned by the API is always the latest release. This one seems inverted...

**Comment by xiphon** [comment]
You should have used `https://api.github.com/repos/monero-project/monero-gui/releases/latest` endpoint.

```
$ curl -s -o- https://api.github.com/repos/monero-project/monero-gui/releases/latest | jq -r '.tag_name'
v0.17.1.4
```
