### ISSUE TITLE
GUI issues 0.17.1.4

### ISSUE THREAD

**Issue by throoweway387** [monero-project/monero-gui#3238]
Some GUI issues I noticed after I started using monero, I'm using Linux with KDE desktop

1. In Settings - Log tab, there is "log level" menu, it doesn't have any option except 0. 

2. Settings - Log tab, "Daemon log" box has texts in invisible font when you use Dark theme. you must select the text  to see it. If you use Light theme then all new text in the box will be visible.

3. Send tab on left side, if you type something in the "Address" box, it's also invisible if you use dark theme, with light theme it's ok.

4. Settings - Node tab, Blockchain location and Daemon startup flags are invisible with dark theme, light theme OK again. Unless it is a bug in my desktop configs...

5. When creating new wallet, the seed and height were written in invisible font (dark theme was used).

**Comment by selsta** [comment]
Did you install using your package manager or from getmonero.org?

**Comment by throwawow581** [comment]
I installed it using package manager. 
(had to create new account, lost access to the previous, lol!)

**Comment by selsta** [comment]
Please try the getmonero version

**Comment by jonathancross** [comment]
Friendly ping @throoweway387

**Comment by xiphon** [comment]
Looks like invalid build env configuration.

Either [build reproducible Monero GUI from source (Linux, Windows)](https://github.com/monero-project/monero-gui#compiling-the-monero-gui-from-source) or use official Monero GUI binaries from https://getmonero.org.
