### ISSUE TITLE
Portable mode .cache traces

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#3241]
Hello Monero devs!
Portable mode is working fine but on Ubuntu, every time I open the portable wallet, "monero-project" directory is created with files in the ".cache" directory. A file "monero-gui.desktop" is also created in ".local/share/applications".
These directories and files should be created on the same directory as the portable configuration file, so absolutely zero traces of Monero wallet are left on the computer hard disk.

_Originally posted by @skaiaswiss in https://github.com/monero-project/monero-gui/issues/3026#issuecomment-728239765_

**Comment by xiphon** [comment]
Closed via https://github.com/monero-project/monero-gui/pull/3245, https://github.com/monero-project/monero-gui/pull/3251, https://github.com/monero-project/monero-gui/pull/3260, https://github.com/monero-project/monero-gui/pull/3262
