### ISSUE TITLE
Can't export key images - always 164 bytes output file

### ISSUE THREAD

**Issue by KarboDuck** [monero-project/monero-gui#3246]
I'm trying to export key images. But I always get a file with size just of 164 bytes.

Tried that using three different wallet files with some balance on them on:
- Laptop #1: Ubuntu 20.10, gui wallet 0.17.1.4
- Laptop #2: Windows 10, gui wallet 0.17.1.4

As mentioned [here](https://github.com/monero-project/monero/issues/7042) "wallet just exports what it's not exported before", and in CLI workaround is to add "all" and use `export_key_images all somefilename `.

In GUI it seems like it's impossible to export key images from scratch.

**Comment by selsta** [comment]
Would you prefer if the GUI always exports all key images?

**Comment by KarboDuck** [comment]
I'm not sure how it should work. My problem is, I'm trying to "communicate" cold and hot wallet. And because my hot wallet is phisically a new file, I can't update it because cold wallet thinks it's already gave me key images in the past and I have no way to have them again (in the gui).

Sorry if I'm confused how it's all works.

**Comment by jonathancross** [comment]
> Would you prefer if the GUI always exports all key images?

I think this would be preferable.  It may make a larger file, but avoids many situations that might confuse users.
