### ISSUE TITLE
Monero x64-v0.17.1.5 GUI slow to catch up on hard disk vs Bitcoin Core, why?

### ISSUE THREAD

**Issue by gab81** [monero-project/monero-gui#3261]
hi,

not sure this is an issue but GUI is slow in my opinion.. 

I have both Monero Core and Bitcoin Core on the same external hard disk. While we know that an external hard disk on usb3 is a bottleneck, the sync for BTC core (with few tweaks) is much faster compared with Monero Core. I have both clients disconnected for say 2 days.

BTC core takes about 30, 40 mins tops to sync all blocks, clearly using well my CPU whereas Monero Core can still use the CPU but relies so much on the disk, which in facts slows things down. But the difference is staggering.

i took a sample now and it did 270 blocks in 1 hour-ish. that's like 7 hours for 2000 blocks.

If i put it on my SSD on the other hand is faster, down to like 30 mins. I am not mining, just catching up blocks for the Core client.

So the question is, why is it so slow and needs so much disk work compared with BTC core? I can of course buy an external SSD hard disk, but that's no the point... 

thanks very much,
Gabrio

**Comment by selsta** [comment]
This is not a GUI issue, the daemon does the syncing.

Bitcoin does not have privacy so the verification process is way simpler. Monero benefits a lot with SSD drives because the verification process is disk read heavy.

**Comment by gab81** [comment]
ahhh got it, thanks for the clarification, so it has to do with the encryption of Monero's blockchain? just as a https page is heavier than a http? something like that i guess.

**Comment by dEBRUYNE-1** [comment]
In a sense. Verification per transaction effectively takes longer in Monero than in Bitcoin, hence the discrepancy in sync performance.

**Comment by gab81** [comment]
one more question, is there a setting in the software that will speed up sync? i have quite a bit of ram available.... or it's just the SSD that makes a difference really? thanks
