### ISSUE TITLE
New Blockchain Sync E Block verification failed, is it a blocker?

### ISSUE THREAD

**Issue by gab81** [monero-project/monero-gui#3265]
hi,

I had to re-sync all the blockchain. I've used the raw downloaded file... during database import process, at the very end i had:

**E Block verification failed, id** = e8404e3fda0393dfXXXXXXXXXXXXXXXXXXXXXXXXd5bd1ea6eb ? it happened twice as i wanted to be double sure.

however it completed afterwards 

Number of blocks imported: 2237438
Finished at block: 2237439  total blocks: 2237440

and now i am running monerod and is catching up latest blocks. is that an issue?

thanks

**Comment by gab81** [comment]
oh and also now that it's synced the new database / blockchain size is 100 GB is that right?

**Comment by selsta** [comment]
Yes, 100GB sounds correct. ~30GB when pruned.

Closing as the issue seems resolved.
