### ISSUE TITLE
Stuck at Creating Transaction

### ISSUE THREAD

**Issue by vitormilagres1992** [monero-project/monero-gui#3273]
Hi, I am trying to send my funds to another wallet and I get stuck at the CREATING TRANSACTION step. It keeps loading, but never creates the transaction. I am having the same issue with my software wallet on my laptop and also with my hardware ledger wallet. Both of them using the Monero-GUI interface

I am running the latest version of the software, that is monero-gui-v0.17.1.7. I have just upgraded the firmware on my ledger and updated the apps. Still the same issue

**Comment by selsta** [comment]
Did you accept it on your Ledger?

**Comment by vitormilagres1992** [comment]
> Did you accept it on your Ledger?

It never asked for anything on my ledger. I even have this issue with the software wallet saved on my computer

**Comment by selsta** [comment]
Which node are you using?

**Comment by vitormilagres1992** [comment]
I tried to use my own node, but apparently it did not work. Then i moved to a public node and it worked just fine. I have no clue as to why my node is not running properly, I do not have anything different to run my node, like startup flags or something that could make me mess up easily. I just click on LOCAL NODE and then START DAEMON. My wallet syncs up perfectly, but I cannot send transactions.

**Comment by selsta** [comment]
This might help for local node: https://www.reddit.com/r/Monero/comments/kdqj5i/running_01717_worked_at_first_without_ban_list/gfy1x01/?context=3

**Comment by xiphon** [comment]
Resolved in v0.17.1.9.
