### ISSUE TITLE
Error writing wallet from hardware device. Check application logs.

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [monero-project/monero-gui#3279]
Hi i wanted to create a new wallet from my Trezor T, but i got this error. How do i fix this?
Im running the latest firmware version and im using the latest windows version of the GUI Wallet

**Comment by selsta** [comment]
There should be a second error message. Can you post that too?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thanks for the quick response @selsta, but the issue seems to resolved itself. The only thing i did is restart my PC.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @selsta, i accidentally logged out of the wallet and tried to login, but i receive an error.
Could not open wallet: Could not connect to the device Trezor.
I dont understand why i get this because my Trezor is still connected to the PC.

**Comment by selsta** [comment]
Do you use the Trezor web wallet simultaneously?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No i do not.

**Comment by selsta** [comment]
Try installing the latest version of Trezor bridge: https://wiki.trezor.io/Trezor_Bridge

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This seems to have worked. Thanks!
