### ISSUE TITLE
Not able to download the GUI mac file

### ISSUE THREAD

**Issue by timfea926** [monero-project/monero-gui#3288]
I have tried to download the Mac GUI file from both getmonero.org, this github page, and even the official Reddit page and each time I got the same error message:

"This site can’t be reacheddownloads.getmonero.org refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED"

I have the free version of Sophos Home Free version and the logs show that it did not block this download. I am not a programmer by any means and would really appreciate having a simple DMG file to download from. Though I did download tar.bz file, I quite frankly have no idea what to with those files or how to install with this way. Please see video capture and advise.

Thank you.

https://user-images.githubusercontent.com/50429353/103454497-ae206d00-4c99-11eb-817f-efa65c6e23d5.mp4

**Comment by xiphon** [comment]
> would really appreciate having a simple DMG file to download from

See [Monero GUI Releases](https://github.com/monero-project/monero-gui/releases) section.
