### ISSUE TITLE
Seed Recovery

### ISSUE THREAD

**Issue by sainta13** [monero-project/monero-gui#3290]
I'm having an issue getting my 25 seed. I've found this page 

https://github.com/LedgerHQ/app-monero/tree/master/tools/python#requirements

but I have little to know python knowledge. I'm stuck on the requirements and how to add them to my mac. then where to enter the commands.

**Comment by jarjarfan666** [comment]
That's a command for Linux. You need to look at the command for OSX and use iterm. I don't use OSX, so can't help

This isn't an issue with monero-gui. I recommend opening a ticket on that repo.

**Comment by selsta** [comment]
@sainta13 try opening Terminal and then entering to following line by line:

```
pip3 install readline
pip3 install pycryptodomex
pip3 install ECPy
pip3 install ledgerblue
git clone https://github.com/LedgerHQ/app-monero
cd app-monero/tools/python
PYTHONPATH=`pwd`/src  python3 -m ledger.monero.seedconv.py offline
```
