### ISSUE TITLE
Add Monero CCS as default address in address book

### ISSUE THREAD

**Issue by sirjamesgray** [monero-project/monero-gui#3293]
I propose we pre-load the Monero GUI's address book with a few relevant addresses, such as the Community Crowdfunding System, or if the GUI has its own donation address that could be added in addition to the CCS. 

I know it's easy enough to add them manually (as I have done) but I think adding a few defaults could result in increased donations. 

Thoughts?

**Comment by selsta** [comment]
We do have a button for the general donation fund under Settings -> Info.

As for the CCS, this would require more work than just adding it to the address book as each proposal has its own address.

**Comment by selsta** [comment]
Closing as the idea does not work in this form, as explained in my previous comment.
