### ISSUE TITLE
[1/10/2021 4:24 PM] 2021-01-10 22:24:06.926 I Monero 'Oxygen Orion' (v0.17.1.9-release)  Error: Couldn't connect to daemon: 127.0.0.1:18081

### ISSUE THREAD

**Issue by RickyRiccardo1** [monero-project/monero-gui#3297]
Just installed Monero Gui wallet ('Oxygen Orion') tried to start daemon and received many "[1/10/2021 4:24 PM] 2021-01-10 22:24:06.926 I Monero 'Oxygen Orion' (v0.17.1.9-release) 
Error: Couldn't connect to daemon: 127.0.0.1:18081" errors

I then tried to start "monerod.exe" manually through the command line and then waited about 5 minutes for any glimpse of a "connection". During this 5 minutes the only thing that happened was the Network Status changed from "Disconnected" to "Connecting" (the status "Disconnected" lasted for about ten seconds whereas the "Connecting" status lasts for about one second). I'm new to Monero, and was advised to start a local node; any help would be greatly appreciated!

**Comment by selsta** [comment]
Do you use an anti virus / firewall?

Can you restart your computer, start monerod.exe, wait a minute and then start the GUI and report back if it connects?

**Comment by RickyRiccardo1** [comment]
I tried going through the windows cmd, didn't work. Then found monerod (application) in file explorer (Windows 10), tried to run it but it immediately closes.. so I assume it's a firewall issue. If that is, in fact, a correct assumption: do you have any recommended course of action?
   Thanks again

**Comment by selsta** [comment]
Can you open cmd.exe, drag and drop monerod.exe into it and then press enter and post the output here.

**Comment by RickyRiccardo1** [comment]
There was no output, it just tried to run the application "monerod" and then I got a message from Windows security saying "potentially unwanted app found"

**Comment by selsta** [comment]
This seems to be an issue with your anti virus. https://monero.stackexchange.com/questions/10798/my-antivirus-av-software-blocks-quarantines-the-monero-gui-wallet-is-there

**Comment by RickyRiccardo1** [comment]
okay, done! So now that that has been done.. do I just start up the gui and let it run?

**Comment by RickyRiccardo1** [comment]
Didn't work. Node wont start and the daemon can't connect.

**Comment by matthewjamesr** [comment]
@RickyRiccardo1 In your anti-virus, add a folder-level exception for the following path (default data directory): `C:\ProgramData\bitmonero`. @ respond if that did not work.

**Comment by RickyRiccardo1** [comment]
Um, sorry to keep you waiting so long, other things had to be done I hope you understand. But, regarding your previous response, @matthewjamesr, the creating an exclusion did Not work; also I don't have the folder "ProgramData" but have other folders titled "Program Files x86" and "Program Files", another folder starting with P is "PerfLogs" but it's empty.... wondering if I could mass file-level exclude the contents of the monero folder?

**Comment by matthewjamesr** [comment]
@RickyRiccardo1 you have to toggle Show Hidden Folders.

![image](https://user-images.githubusercontent.com/303321/104795764-17ed5a80-57f4-11eb-85f0-ca82c1c8fd25.png)

**Comment by selsta** [comment]
Closing, if you continue to have issues with your anti virus please ask on Reddit r/monerosupport

**Comment by dotnetspec** [comment]
I'm getting:
```
Timed out, local node is not responding after 120 seconds.
Please check your wallet and daemon log for errors. You can also try to start monerod manually.
```
in the wallet.
Network status then reverts to 'Disconnected' (so this is the problem).
I don't know how to start monerod manually in Linux, however, I'm not confident that would resolve this anyway (?).
If I can, how should I start monerod manually?
Is there any other way for me to connect the daemon?

**Comment by selsta** [comment]
monerod and the blockchain directory can be separate.
