### ISSUE TITLE
Wallet Issu

### ISSUE THREAD

**Issue by kcann0n** [monero-project/monero-gui#3299]
Getting the error 

Couldnt open wallet:Wrong Device Status:0x6e00 (SW_CLA_NOT SUPPORTED) EXPECTED 0x9000 (SW_OK) MASK 0xffff

How can I fix this?

**Comment by rating89us** [comment]
Update your Ledger firmware

**Comment by kcann0n** [comment]
I updated and now its just in a never ending loop of "Opening Wallet" and never actually opens?

**Comment by selsta** [comment]
@kcann0n Did you accept exporting your view key on Ledger?

**Comment by selsta** [comment]
Closing, if you have further issues please ask on Reddit r/monerosupport
