### ISSUE TITLE
No message when seed is not valid in Recovery wizard

### ISSUE THREAD

**Issue by ClementJnc** [monero-project/monero-gui#331]
If I enter an invalid sequence of 25 words in the Recovery wizard, there is no message indicating that I need to correct the sequence.

**Comment by Jaqueeee** [comment]
Additional info: GUI hangs on mac when trying to move forward with invalid seed #339

**Comment by dternyak** [comment]
@Jaqueeee Sorry, shouldn't have used the term 'hangs'. It simply does nothing when you click continue, you can still back out / try a different mnemonic.

**Comment by Jaqueeee** [comment]
OK. Thanks for clarification!

**Comment by NanoAkron** [comment]
What do you mean by 'invalid'? Do you mean words that aren't in the standard seed word dictionary, or it's a sequence with the wrong final word checksum, or it's a sequence that isn't your key but is still a valid selection of words?

**Comment by medusadigital** [comment]
can we close this ?

**Comment by dEBRUYNE-1** [comment]
+resolved
