### ISSUE TITLE
monero-wallet-gui.exe crashed

### ISSUE THREAD

**Issue by puca1024** [monero-project/monero-gui#3313]
Hi,
after I installed and ran application monero wallet gui (ver. 0.17.1.9, under OS Windows 10 Pro, build 19042.746) always ends this application with the same error:

Faulting application name: monero-wallet-gui.exe, version: 0.0.0.0, timestamp: 0x53510351
Faulting module name: ntdll.dll, version: 10.0.19041.662, timestamp: 0x27bfa5f0
Exception code: 0xc0000374
Error offset: 0x00000000000ff0f9
Faulting process ID: 0x12ec
Faulting Application Start Time: 0x01d6ef1f16c4636a
Path to the faulty application: C: \ Program Files \ Monero Wallet GUI \ monero-wallet-gui.exe
Path to the faulting module: C: \ Windows \ SYSTEM32 \ ntdll.dll
Message ID: d9c8972a-b109-4a7a-9e81-f070b1131c7e
Full name of the faulty package:
Application ID related to the faulty package:

Please, can anyone help me?
Thank you
~pu

**Comment by selsta** [comment]
Found similar issues online, does not appear to be Monero GUI specific.

https://answers.microsoft.com/en-us/windows/forum/all/app-crash-with-ntdlldll/9aa59f80-99a1-4f3c-b2f0-7eb72df05b2a

https://community.adobe.com/t5/indesign/indesign-2020-shows-error-on-launch-on-windows-10/td-p/11090680

**Comment by selsta** [comment]
Closing as this does not seem monero gui related.
