### ISSUE TITLE
Cannot choose hardware device: Creating new wallet

### ISSUE THREAD

**Issue by mr-optimate** [monero-project/monero-gui#3318]
See attached gif (the glitches around the sides of the program are from the screen capture software)
![no drop down](https://user-images.githubusercontent.com/78201439/106253527-99c28800-61e5-11eb-8bb3-b91a7ccb1bee.gif)
As you can see when I go to select what hardwear wallet i want to use from the drop down menu, no options drop down. The little arrow on the right is moving so it is registering as a click.

Specs:
monjaro - kernel 5.9.16-1 
Fresh install of monero-gui 0.17.1.9-1
ledger firmware is up to date as well as all the apps. (I dont think that maters in this case)

What I've tried to do:
restart the computer
reinstall monero-gui
restarting the program

I don't think this is a ledger problem since the drop down menu should appear even if I don't have a wallet plugged in, at least that's what the windows version of monero gui does.

**Comment by selsta** [comment]
Is this installed using your package manager? If yes please try the getmonero.org version

**Comment by mr-optimate** [comment]
Yes it was installed from the package manager. The getmonero.org version works as expected

**Comment by selsta** [comment]
Ok, please reach out to the package maintainer. This is out of our control.
