### ISSUE TITLE
Compliation Error on OSX - QUIRC

### ISSUE THREAD

**Issue by breadsax** [monero-project/monero-gui#3322]
Receive the following error on Mojave even though WITH_SCANNER should be set to OFF by default:

[ 57%] Building C object external/CMakeFiles/quirc.dir/quirc/lib/quirc.c.o
Scanning dependencies of target openpgp
/Users/hiro1/monero-gui/external/quirc/lib/quirc.c:126:22: error: result [ 57%] Generating monero-core.qm
of comparison of constant 8 with expression of type 'quirc_decode_error_t' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
        if (err >= 0 && err < sizeof(error_table) / sizeof(error_table[0]))
                        ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by selsta** [comment]
Can you post the exact steps you used to build?

**Comment by breadsax** [comment]
@selsta I followed the steps from the github instructions. The only thing I noticed just now is that it says to install full XCode and I've only ever needed the XCode Command Line Tools. Did that change perhaps?

On OS X:
Install Xcode from AppStore

Install homebrew

Install monero dependencies:

brew install boost hidapi zmq libpgm libsodium miniupnpc ldns expat libunwind-headers protobuf libgcrypt

Install Qt:
brew install qt5 (or download QT 5.9.7+ from qt.io)

Grab an up-to-date copy of the monero-gui repository

git clone --recursive https://github.com/monero-project/monero-gui.git
cd monero-gui
Start the build

make release -j4

**Comment by selsta** [comment]
Can you try deleting line 459 and 460 from CMakeLists.txt? The lines containing werror). Afterwards please try again.

**Comment by breadsax** [comment]
@selsta  I was able to compile successfully with this workaround. Thank you!

**Comment by selsta** [comment]
@xiphon Looks like quirc has an warning during compilation on older macOS systems which becomes an error with -Werror. What should we do here?

**Comment by xiphon** [comment]
Could you please post complete `make release -j4 VERBOSE=1` output? Consider to strip sensitive information.

**Comment by selsta** [comment]
Related: https://bugs.llvm.org//show_bug.cgi?id=16154
