### ISSUE TITLE
Application uses too many Unix sockets on Linux, causing issues with X11

### ISSUE THREAD

**Issue by Wyatt915** [monero-project/monero-gui#3324]
Every time `monero-gui` locks after a period of inactivity, it uses an additional 2 Unix sockets. When a password is entered to unlock the gui, an additional 32 sockets are used. This will continue until no more sockets can be opened, causing other apps (especially X11, resulting in the message `cannot open display: :0.0 Maximum number of clients reached`) to misbehave if a socket is needed.

This can be tested by running `lsof -U +c 15 | cut -f1 -d' ' | uniq -c | grep monero-wallet` while the app is open. Each time an unlock is required, run the command and it will show an increase of 32 open sockets.

I am running Arch Linux (kernel 5.10.11), and have installed monero-wallet-gui from the default repos.

GUI version: 0.17.1.9-3ca5f10f (Qt 5.15.2)
Embedded Monero version: 0.17.1.9-release
Wallet mode: Advanced mode (Local node)OpenGL

**Comment by selsta** [comment]
Please test if you have the same behavior with the getmonero.org binaries.

**Comment by Wyatt915** [comment]
Just tested it with the `monero-wallet-gui` binary and found it to have the same issue. I did not try the AppImage.

**Comment by xiphon** [comment]
Located the issue. Will submit a fix in a few.

**Comment by Wyatt915** [comment]
Gotta love a one-line fix :)
