### ISSUE TITLE
Error Writing Wallet From Hardware Device

### ISSUE THREAD

**Issue by Jlev8** [monero-project/monero-gui#3333]
I'm getting the above message when I try to set up the wallet for my Trezor Model T.  I've updated the firmware (which is the solution suggested in another post), but I'm still getting the error message.  I'm not sure what else I can do.

**Comment by selsta** [comment]
Please also try to install the latest version of Trezor Bridge.

Also try to restart your computer and make sure that only Monero GUI is open so that no other program can interfere.

**Comment by Jlev8** [comment]
Thanks so much!  I didn't have the latest version of the bridge (I thought I did).  That fixed it.
