### ISSUE TITLE
Binaries for ppc64le

### ISSUE THREAD

**Issue by JeremyRand** [monero-project/monero-gui#3337]
It would be useful to provide pre-built binaries of the Monero GUI for ppc64le (POWER8/POWER9).  There's a lot of overlap between the privacy community and the POWER community; POWER users are a natural audience for Monero.

**Comment by JeremyRand** [comment]
I suspect that the work needed to solve https://github.com/monero-project/monero-gui/issues/1441 would also be helpful here.

**Comment by selsta** [comment]
Closing as I don't own such a machine and I wouldn't be able to maintain it. No one else offered to work on such binaries in the meantime.
