### ISSUE TITLE
corrupted text everywhere

### ISSUE THREAD

**Issue by mikelpr** [monero-project/monero-gui#3338]
with the monero-gui-v0.17.1.9 linux binary and compiling from git, many texts are corrupted throughout the GUI
[screenshot](https://i.imgur.com/oJUF4hn.png)
[better screenshot](https://i.imgur.com/GKP8UjM.png)

on monero-gui-v0.16.0.3 this does not happen

**Comment by dEBRUYNE-1** [comment]
Can you try launching the GUI as follows?

`QMLSCENE_DEVICE=softwarecontext ./monero-wallet-gui`

**Comment by mikelpr** [comment]
> Can you try launching the GUI as follows?
> 
> `QMLSCENE_DEVICE=softwarecontext ./monero-wallet-gui`

yeah, that works

**Comment by selsta** [comment]
@mikelpr This seems to be an issue with your graphics drivers. Can you try (re)installing / updating your graphics drivers and make sure they properly support opengl?

**Comment by mikelpr** [comment]
@selsta I'm using amdgpu and radionsi. not thinking about moving to amdgpu pro. should I file a bug over at radionsi? also it could be a Qt bug

**Comment by selsta** [comment]
I'll close this as this is a single report and it sounds like a graphics driver issue. There isn't much we can do here.
