### ISSUE TITLE
Successful transaction box remains visible after wallet auto lock through inactivity

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-gui#3340]
After sending a transaction, if the GUI auto locks through inactivity and the success message hasn't been dismissed, it will remain visible. See attached image. I have obscured the transaction ID with a red rectangle.

MacOS Catalina
GUI: 0.17.1.9-3ca5f10

<img width="980" alt="gui" src="https://user-images.githubusercontent.com/23356013/108603489-00c7fc80-73a0-11eb-8385-e6cfda8bb2d1.png">

**Comment by rating89us** [comment]
This issue can be closed (fixed by #3512) @selsta
