### ISSUE TITLE
GUI not showing balance - Tried a lot of the solutions and nothing is working so far.  Please help?

### ISSUE THREAD

**Issue by hopi369** [monero-project/monero-gui#3344]
Hey guys,

I hope you are doing good.  I opened a new Monero GUI wallet and transferred funds into it but after 4 days I am still not seeing the balance.  I am hoping this is user error and that I just missed a step from the many things I've tried.

details. 

Linux system
Trezor T
Simple wallet mode
remote node 

I know I put in the correct address,  on exploremonero reads as "done".  I do not recognise the output addresses, but isn't that because of XMR's privacy with sending monero? 

I reset wallet height, but perhaps did that incorrectly? 
Tried renaming old wallet and making new one.  have it labeled like this.... "name" old 

This morning I tried to create a new wallet on a different computer but was not able to restore wallet, so I am guessing block height is an error?

Is anyone up for helping me to sort this out?

Looking forward to hearing from you, really feeling like I screwed something up.

**Comment by selsta** [comment]
What did you enter as restore height during wallet restore?

**Comment by hopi369** [comment]
The last time I did it, I entered, 2278708

**Comment by selsta** [comment]
Ok, do you know when you received that transaction? Do you have a transaction id?

> This morning I tried to create a new wallet on a different computer but was not able to restore wallet, so I am guessing block height is an error?

Could you be a bit more precise about the error?

**Comment by hopi369** [comment]
Yes, it was on February 19th.   

As far as the error, I just don't see my balance.  My wallet height says, 2278708, and on Daemon it is 2304605.  That means it's out of sync, right?

**Comment by hopi369** [comment]
Ah sorry, just saw you asked for transaction id.  Is that absolutely necessary?  It's on my other system so hard to transfer here.  Let me sort that out if you absolutely need it?

**Comment by hopi369** [comment]
here it is

https://www.exploremonero.com/transaction/b870789eb1dec5a44d777cc159c6122516eae8db4da4921c7a574c8dd1b48984

**Comment by selsta** [comment]
As a first step I would try to connect to a remote node in case simple mode has issues: https://github.com/monero-project/monero-gui/issues/3140#issuecomment-706440354

Afterwards go through the restore process again.

Did you ever use different accounts in the GUI?

**Comment by hopi369** [comment]
Ok cool, is it safe to connect to other remote nodes?  I heard they are compromised sometimes.

**Comment by hopi369** [comment]
Just read your pinned link from the hash...It says go into setting to change remote note but I don't see that option.  Can I also just click on the network status icon to switch to another public node?

**Comment by hopi369** [comment]
Ah, and I do have another account but it wasn't connected to this one at all.

**Comment by selsta** [comment]
You first have to switch to advanced mode. It should work if you follow all steps in the comment.

**Comment by selsta** [comment]
One more question: Do you use a Trezor passphrase?

**Comment by hopi369** [comment]
Ok cool, I'll start going through the process.

Shit, I thought I did because it always asks me to confirm the transaction, but I don't remember setting one up...thought I was only using a pin.

**Comment by selsta** [comment]
Pin is fine, Trezor passphrase is an advanced setting that is disabled by default.

**Comment by hopi369** [comment]
Ah ok great.  After changing to advanced mode, the only option I see that seems like it would work for my setup is create a new wallet from hardware.  Do I select that one?

**Comment by selsta** [comment]
> Do I select that one?

You can do that. Afterwards please change to a remote node.

**Comment by hopi369** [comment]
Shit, I read earlier today about how remote nodes can attack the IP address.  I'm super paranoid man.  How do I know which nodes are safe?

**Comment by selsta** [comment]
The ones in the linked comment are from trusted community members.

**Comment by hopi369** [comment]
ok cool.

**Comment by hopi369** [comment]
Thanks a lot for your help, I just have heard so much with scams even in official groups so I'm feeling uneasy about setting up a remote node.  Do you know of a way I can verify a node to see if it's safe or not?

**Comment by hopi369** [comment]
think I found a way to verify.  Sorry about that, just paranoid...gonna add one you suggested now.

**Comment by hopi369** [comment]
synching...

**Comment by hopi369** [comment]
While it's synching can I ask you another question, or are you busy?

**Comment by hopi369** [comment]
While it's synching do you mind if I ask you a different question?  Or are you already too busy?

**Comment by selsta** [comment]
Just ask :)

**Comment by hopi369** [comment]
First of all, thank you so much for all of your help it just worked!  I really can't thank you enough, I was quite stressed last night which gets into the other question.    Ok, so I had an issue come up that even though I am new to crypto I am embarrassed about because I am in general not someone that is easy to scam.  but anyway, last night while trying to get all of this sorted in the monero telegram group someone contacted me directly that I thought was part of admin :(  

Long story short I send him what I thought was my private keys and shortly after that I realised I was being scammed, and after I sent him in a website link what I thought were the keys, he said he was having issues 're-synching" my wallet, and asked if I was sure I sent the right wallet info.  This is where I came to my realised what was happening.  He tried to see if I would continue and said we could still reset my wallet through trezor but did not continue.  But then later noticed that what I sent him was...and especially now seeing my balance was all there I think was nothing because in the setting section where I copied the seeds, it only reads something like, "seeds protected by hardware device."   Given I had copied the seed link and only pasted the words "seed protected by hardware device," he got nothing, right?  Man, I am embarrassed and at the same time just want to make sure he doesn't have any access to my trezor coin seeds because I moved all other crypto last night as this was happening.  Do you think it's safe for me to move the crypto back to this Trezor I thought I gave him the seeds for?

**Comment by selsta** [comment]
Please go back to your telegram messages and check what you sent him.

If you only sent him "seeds protected by hardware device." then you are fine.

If you sent him your Trezor 14 word seed then you should move out your coins and setup your Trezor from scratch.

**Comment by hopi369** [comment]
Okay great, I definitely only sent him  "seeds protected by hardware device."  At least as far as I know...the trezor word seed would not be online on the GUI wallet or anywhere else online unless I put it there, right?  Because I only wrote down my phrase on paper and have not put it on any computers manually.

**Comment by hopi369** [comment]
I guess my question is that there is no way the GUI wallet embeds the see phrase in the show seed & keys section, right?

**Comment by selsta** [comment]
> the trezor word seed would not be online on the GUI wallet or anywhere else online unless I put it there, right?

correct

**Comment by selsta** [comment]
Closing as this seems resolved. Never share you seed, even if someone contacts you as an admin.

**Comment by hopi369** [comment]
Ok cool, I definitely did not put it anyway.  Yes, can't believe I shared anything with him...hard lesson learned.  Again, thanks so much again, I appreciate it so much.
