### ISSUE TITLE
Missing transactions (!)

### ISSUE THREAD

**Issue by JeanFrancoeur** [monero-project/monero-gui#3356]
There's missing transactions, the Monero-gui state that the wallet is synchronized and the daemon is started and even we use Rescan wallet balance nothing change.  What to do next?

Thank you in advance

**Comment by selsta** [comment]
Can you try restoring the wallet from seed and setting a proper restore height?

**Comment by JeanFrancoeur** [comment]
Thank you @selsta, since I never do that, do you suggest that I need to uninstall and do a reinstall using the seed & restore height we took in backup?  Or there's another way to do it?

**Comment by selsta** [comment]
You don't have to uninstall anything. You can go to the main menu by clicking the door symbol in the top left corner, then click on "Restore wallet from seed".

**Comment by JeanFrancoeur** [comment]
ok got it, but I'm feeling like a dumb.  I've tried by using seed or keys, but I simply cannot press the next button, it stays disabled.

**Comment by selsta** [comment]
You have to set an unique wallet name.

**Comment by JeanFrancoeur** [comment]
I thought I need to restore over the same wallet.  I did twice, first time using the restore height at the wallet creation and the second time with the restore height found under the Settings/Wallet page.   The ui retrieved the latest data, but the missing transactions are still present.  I have the missing transactions hashes.  Thank you for your support, it's very appreciated.

**Comment by selsta** [comment]
Please use the restore height from wallet creation.

Which "wallet mode" are you using? You can check under Settings -> Info.

**Comment by JeanFrancoeur** [comment]
I have tried both, but I note to use the creation one next time. I'm using 0.17.1.9-3ca5f10f (Qt 5.15.2) in advanced mode.

**Comment by selsta** [comment]
And under advanced mode, do you use a local node or remote one?

**Comment by JeanFrancoeur** [comment]
Local from day one.  I tried another time restoring the wallet with the restore height got at the creation.  The gui synchronize 39k-ish blocks.  But nothing change, same result.  Sorry for taking your time on this.

**Comment by selsta** [comment]
No problem, can you try entering your txid on xmrchain.net and use the decode output feature to check if you received the coins?

**Comment by JeanFrancoeur** [comment]
Ok, if I made the things correctly here's the result.  I'm getting 1 output match on 15.  But the public key doesn't match mine.  How that be be possible?  I'm having the proof of payment on the pool portal.

**Comment by selsta** [comment]
Hmm, not clear what the issue was. Please open a new issue if you encounter this again.
