### ISSUE TITLE
Gui wallet crashing while sending transaction 

### ISSUE THREAD

**Issue by hopi369** [monero-project/monero-gui#3368]
Hey guys,

I hope you are doing good.  When trying to send transactions from my Gui wallet the app crashes.  I've tried to change public node and it still does not work.  Could anyone help me with this?  Also tried to restore my wallet from Trezor hardware device and for some reason that is not working either.

Looking forward to hearing from you

**Comment by selsta** [comment]
Are you using the latest Trezor firmware and latest version of Trezor bridge?

Do you have any other Trezor wallets open?

**Comment by hopi369** [comment]
did have a different wallet up  as well, thanks a lot it worked!

**Comment by selsta** [comment]
Ok, this will be fixed in the next release so that having a different wallet open should not result in a crash anymore.
