### ISSUE TITLE
Ledger New Install - "Couldn't Open Wallet Wrong Device Status"

### ISSUE THREAD

**Issue by Neilpmcd** [monero-project/monero-gui#3375]
Hi, 

I've only just initialised my ledger nano x, and initialised my monero gui last night.  I only established the password for the wallet, but didn't do any transactions.  I then let the node run in the background afterward.

Today, just checking the config's etc, I cannot log into my wallet with the error:  could not open wallet, wrong device status.  0x6e00 SW_CLA_Not_Supported Expected 0x9000.  SW_OK MASK 0xffff

Thank-you, 

I have log files if you like.

Thanks,

Neil.

**Comment by selsta** [comment]
Please try restarting your computer and try again. Make sure Ledger Live is closed.

**Comment by Neilpmcd** [comment]
Thanks.  OK.

**Comment by selsta** [comment]
Please reach out to http://reddit.com/r/monerosupport if you still have issues.
