### ISSUE TITLE
Windows 10: memory mapped db file eats 11GB of physical RAM

### ISSUE THREAD

**Issue by tidux** [monero-project/monero-gui#3376]
Is there any way I can change this behavior of the local node?  My system is swapping for nearly everything else and it makes my PC borderline unusable.

**Comment by selsta** [comment]
Is this during sync or also afterwards?

**Comment by tidux** [comment]
This was during sync.

**Comment by selsta** [comment]
It should not be an issue afterwards. Sync is resource intensive. Closing as there isn't much we can do here on the GUI side (we already have reduced the concurrency for GUI users).
