### ISSUE TITLE
Can't see grab QR code icon

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#3396]
![image](https://user-images.githubusercontent.com/45968869/114767195-a330aa80-9d67-11eb-8105-128a2ca033d4.png)

all other fontawesome icons on the monero gui are displayed normally

Windows 7 64 bits
GUI version: 0.17.2.0-816eeb46 (Qt 5.15.2)

**Comment by selsta** [comment]
might be fixed by #3397

**Comment by rating89us** [comment]
Unfortunately it's not fixed by #3397:

![image](https://user-images.githubusercontent.com/45968869/114825243-3f899a00-9dc6-11eb-9570-973067f5b608.png)
GUI version: 0.17.2.1-2-g6116b972 (Qt 5.15.2)

**Comment by selsta** [comment]
@rating89us I just force pushed, please check again in ~2h here: https://github.com/monero-project/monero-gui/actions/runs/752081047

**Comment by rating89us** [comment]
@selsta 
Great, now it's working: 
![image](https://user-images.githubusercontent.com/45968869/114922030-7cd44300-9e2b-11eb-9082-c4ad8f91ef9c.png)

**Comment by selsta** [comment]
@rating89us thanks for testing, please approve the PR.
