### ISSUE TITLE
XMR balance not showing. Where did it go?

### ISSUE THREAD

**Issue by KeineWeissEs** [monero-project/monero-gui#3403]
I've withdrawn XMR from Binance to my wallet I've got from getmonero.org, the transaction has been confirmed but the balance still shows 0. I've tried resyncing it and I've confirmed that the transaction was sent to my wallet but still I haven't figured out why my balance won't update. 
Please help.

**Comment by selsta** [comment]
Which "wallet mode" are you using? You can check inside Settings -> Info.

**Comment by KeineWeissEs** [comment]
> Which "wallet mode" are you using? You can check inside Settings -> Info.

Advanced Mode (Remote node)

**Comment by selsta** [comment]
Can you also tell me the "Wallet restore height" inside Settings -> Info?

Also which remote node are you using? Try one of the following:

- node.xmr.to:18081
- node.supportxmr.com:18081
- 88.198.199.23:18081
- 78.47.80.55:18081

**Comment by KeineWeissEs** [comment]
I changed my wallet restore height to 1940000 because I read that this could help but it didn't change anything.
I'll try node.xmr.to:18081, I'll report if it changed anyting or stayed the same.

**Comment by selsta** [comment]
Which node did you use previously?

**Comment by KeineWeissEs** [comment]
node.moneroworld.com:18089

**Comment by selsta** [comment]
Closing as this seems to be a user support issue. If you still have issues comment here our reach out to http://reddit.com/r/monerosupport
