### ISSUE TITLE
canceling stuck tx

### ISSUE THREAD

**Issue by ZuckaBoy** [monero-project/monero-gui#3407]
hello, i sent a tx which showed as failed in To: tab, coins goes back to my wallet so i sent it again, after second sending the first sending goes through and confirmed, the second send is still on pending situation but shows failed in To: tab.  how can i cancel the second one? i dont have enough coins to cover the second one but i am afraid that when i have then this one goes through too. i need to cancel it so this dont happen, the tx id isnt still on blockchain. 

my version is: 0.17.1.9-3ca5f10f (Qt 5.15.2)
windows: 10
no tor
remote node

**Comment by selsta** [comment]
The tx will time out automatically.

> i dont have enough coins to cover the second one but i am afraid that when i have then this one goes through too.

This will not happen.
