### ISSUE TITLE
Can't Open Wallet Wrong Device Status: 0x6a30(UNKNOWN), EXPECTED 0x9000(SW_OK), MASK 0xffff

### ISSUE THREAD

**Issue by StoneYeti** [monero-project/monero-gui#3412]
This is bizarre. Installed Monero GUI desktop in December & used it with the key storage on Ledger Nano S.
Deposited successfully a few times and then 1 larger deposit later in January.
I left it unused for 3 months and went to deposit in April and the Monero Wallet was GONE!
Missing but all the old miscellaneous files were still there from Dec/Jan.
I Reinstalled and tried to get in and got this Error. I had the keys file in Documents so was ready to try and recover.
The keys files are in crazy chinese symbols and not legible.
Updated Ledger Live and Monero wallet is obviously newest version as it is freshly installed.
Any way to recover the older version of the wallet? Any other thoughts?

**Comment by selsta** [comment]
Did you make sure to install Ledger Monero app v1.7.6?

> The keys files are in crazy chinese symbols and not legible.

The keys file is in binary and not supposed to be readable.

**Comment by StoneYeti** [comment]
I thought I had done this and had not. I am so grateful for your help. I am in my wallet and Monero is there safe and sound. You Rock!
