### ISSUE TITLE
Add option to remove addresses

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#3418]
Addresses should have the ability to be archived

**Comment by AlennGK** [comment]
Posibility to hide them at least would be great.

**Comment by russoj88** [comment]
@Memerr69 are you referring to subaddresses?

**Comment by Memerr69** [comment]
yes

**Comment by russoj88** [comment]
> yes

I think hiding would be useful, but they cannot ever actually be removed since they are generated.  Maybe "archived" is a better term here?

**Comment by Memerr69** [comment]
yeah archived then

**Comment by xanoni** [comment]
Duplicate: https://github.com/monero-project/monero-gui/issues/3570

PR is here, please comment on the PR instead so we can focus the discussion and bundle the interest of the community:
https://github.com/monero-project/monero-gui/pull/2936

Think this here can be closed.
