### ISSUE TITLE
[Debian Buster]: (v0.17.2.1) Successful build yet 'QtQml.Models is not installed' error

### ISSUE THREAD

**Issue by possientis** [monero-project/monero-gui#3440]
I am attempting to build `monero-wallet-gui` on Debian Buster. I believe I have successfully installed all required dependencies as per the `README` and the build appears to be successful. Yet when I launch the wallet I am getting the error

```
2021-04-25 11:52:22.015	W Qt:5.11.3 GUI:0.17.2.1-8444a956 | screen: 1600x900 - dpi: 96 - ratio:0.842986
2021-04-25 11:52:22.289	W QQmlApplicationEngine failed to load component
2021-04-25 11:52:22.289	W qrc:/main.qml:29 module "QtQml.Models" version 2.12 is not installed
2021-04-25 11:52:22.289	E Error: no root objects
```
I thought maybe I had failed to install the package `qml-module-qtqml-models2` but this isn't the case.

It is possible this is my fault and I have done something wrong somewhere, but reporting the issue just in case someone else sees it. I am surprised the build should succeed if a dependency has not been properly installed.

**Comment by selsta** [comment]
@possientis try to build latest master

**Comment by possientis** [comment]
@selsta ack, will revert asap

**Comment by xiphon** [comment]
https://github.com/monero-project/monero-gui#on-linux

**Comment by possientis** [comment]
@xiphon Thank you, are you suggesting that I probably failed to follow these guidelines and should read the document again and retry?

**Comment by xiphon** [comment]
Yeah, did you install `qml-module-qt-labs-platform` dependency?

**Comment by possientis** [comment]
@xiphon I am very sorry, you are right, for some reason I had failed to install that dependency. All good now. My sincere apologies and thank you !

**Comment by possientis** [comment]
For the avoidance of doubt, the master branch is fine after installing missing dependency `qml-module-qt-labs-platform`, but `v0.17.2.1` still has the same failure as initially reported.

**Comment by xiphon** [comment]
Already fixed via https://github.com/monero-project/monero-gui/pull/3392, the fix will get included in the next release.
