### ISSUE TITLE
wallet-cli stuck on Starting refresh under Ledger

### ISSUE THREAD

**Issue by tbfvrs** [monero-project/monero-gui#3453]
Hello

I bought Ledger Nano X recently and moved all my coins from Trezor to it;
I've generated a new wallet using this [tut](https://monero.stackexchange.com/questions/8503/how-do-i-generate-a-ledger-monero-wallet-with-the-cli-monero-wallet-cli);
Everything went smoothly and was working (refreshing went well...);
Today I've synchronized the net, plugged Ledger and started Monero app;
Next started monero-wallet-cli, input wallet name, password, choose not to export viewkey (same when creating the wallet) but it is stuck on Starting refresh and cannot be interrupted (can't write, Esc, Ctrl+C does not work);
Tried to exit the deamon but it didn't close but stuck on Deinitializing core RPC server...

Anyone have a clue what went wrong and what to do...?

Greetz

**Comment by selsta** [comment]
You have to export the view key, the Ledger is not strong enough to do scanning on device.

**Comment by tbfvrs** [comment]
> 
> 
> You have to export the view key, the Ledger is not strong enough to do scanning on device.

Ohhh OK and I thought (judging by the formentioned tut) it will be slower but still refreshing...
Thanks
