### ISSUE TITLE
Save tx to file does not work

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-gui#3454]
There appears to be code for view only wallets to save transactions to a file: https://github.com/monero-project/monero-gui/blob/master/main.qml#L933

But it is not possible to click on the send button in "view only" mode: https://github.com/monero-project/monero-gui/blob/master/pages/Transfer.qml#L806

ping @rating89us, I think you have used this in the past

**Comment by rating89us** [comment]
To save tx to file on view-only wallet, you should fill Address + Amount and then click on Create button on Advanced options > Offline transaction signing > Create

**Comment by selsta** [comment]
Thanks!
