### ISSUE TITLE
Monero 'Oxygen Orion' (Error: Couldn't connect to daemon)

### ISSUE THREAD

**Issue by ajv87** [monero-project/monero-gui#3460]
Hi, 

I have a problem with my Monero Walllet 'Oxygen Orion', its appear the message "Error: Couldn't connect to daemon".

Also, I send some XMR from another wallet to Monero 'Oxygen Orion' and I didn't receive the coins.

Any ideas, thank you in advance.

Jairo

**Comment by ajv87** [comment]
there is the message 
![image](https://user-images.githubusercontent.com/83619131/117368485-99472680-ae91-11eb-9957-82c39814f267.png)

**Comment by selsta** [comment]
What happen when you start monerod.exe manually?

**Comment by ajv87** [comment]
just the following 
![image](https://user-images.githubusercontent.com/83619131/117368866-18d4f580-ae92-11eb-947d-4b5e27fbcd1c.png)

**Comment by selsta** [comment]
Do you have an anti virus running?

**Comment by ajv87** [comment]
![image](https://user-images.githubusercontent.com/83619131/117369247-aa446780-ae92-11eb-993e-49cc757a30bf.png)
No, I created an exception for the folder. 
It looks the percentage is developed, I hope get my coins when it finished.

**Comment by ajv87** [comment]
Thank you, all ok now
