### ISSUE TITLE
Monero GUI Wallet (x64) Latest Version Hangs on Black Screen

### ISSUE THREAD

**Issue by TheRealRequnix** [monero-project/monero-gui#3474]
Win10 x64 i9-11900k Z590 RTX 3090 system; all latest drivers and top notch. Just downloaded and whenever I run GUI Wallet, it always hangs on a black screen.

**Comment by selsta** [comment]
Can you try "low-graphics-mode.bat"?

**Comment by selsta** [comment]
Closing as we did not have any other reports about this so it seems to be a local setup issue. Please try to use the latest version and if that does not work please also try "low-graphics-mode.bat".
