### ISSUE TITLE
Monero GUI kills the system monerod on Linux

### ISSUE THREAD

**Issue by Tronic** [monero-project/monero-gui#3476]
I am running monerod via systemd, which I expect to be running at all times.

When starting the GUI, it issues a shutdown command to the system service and runs its own monerod instead (as my desktop user). Is there configuration to avoid this, and force using the already running daemon on localhost?

**Comment by selsta** [comment]
Switch to advanced mode. (Main menu -> Change wallet mode -> advanced mode)

**Comment by Tronic** [comment]
Thanks. So, now I am supposed to add localhost:18081 as remote node, right? For some reason the client doesn't appear to be connecting and just says network status disconnected.

**Comment by Tronic** [comment]
That works but it still asks to shutdown the server when GUI exits (and I could not find an option to avoid that). I also got localhost as remote node working after disabling socks proxy setting (my mistake), and that doesn't attempt shutdowns anymore.
