### ISSUE TITLE
Feature request: integrate security key/YubiKey support

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#3488]
Currently Monero GUI funds are only protected by the wallet password. If the desktop computer holds a hot wallet and it is compromised by a remote attacker, all balance can easily be stolen.

After linking the wallet file with a stronger authentication device, Monero GUI could ask the user to physically touch or insert a security key USB device when doing critical actions, like sending funds or displaying the mnemonic seed.

**Comment by t-anon** [comment]
Monero GUI already supports hardware wallets.

You really should avoid using a YubiKey or generic security token. Namely because:

- PIN entry would be insecure on a YubiKey as it would go need to go through the OS
- If you generate the seed on the YubiKey, it can never leave the YubiKey
- If you don't generate the seed on the YubiKey, you can't really safely load it onto the YubiKey

Hardware wallets (namely the Ledger) have a much better security model than a YubiKey because they have their own airgapped input methods.

**Comment by rating89us** [comment]
- A wallet file linked to the YubiKey means that every time you copy this wallet file into any monero wallet, this wallet must require authentication on YubiKey in order to confirm risky actions: confirm sending transactions and displaying its seed.
- The YubiKey will not store the seed, it will be stored in the wallet file. User will still have to write down the seed on a paper backup.
- Supporting YubiKey would enable users to carry higher amounts on their hot (connected on the internet) Monero GUI wallets on desktop (or mobile, when available).
- For example, you could generate a wallet file linked to YubiKey on a air gapped computer and then copy your wallet file into your Monero GUI on desktop. Now you have a wallet file in Monero GUI that will never send transactions and displays its seed, unless you authenticate with YubiKey.
- Also, YubiKey is cheaper than a hardware wallet, is multipurpose (more privacy), and is easier to carry.

**Comment by selsta** [comment]
> this wallet must require authentication on YubiKey in order to confirm risky actions: confirm sending transactions and displaying its seed.

This would only be a visual action, a custom GUI could patch these confirmations out. This isn't possible with a real hardware wallet.

Malware on your computer could still steal your seed once you open a wallet with a YubiKey, it would barely improve your security compared to a regular password.

**Comment by rating89us** [comment]
> This would only be a visual action, a custom GUI could patch these confirmations out. This isn't possible with a real hardware wallet.
My idea would require a special type of Monero wallet file. The wallet file itself should require the YubiKey to unlock it, just like a password works today. Therefore it doesn't matter in which wallet software you import this wallet file, you will not be able to open this wallet file without its "physical password". 

> Malware on your computer could still steal your seed once you open a wallet with a YubiKey, it would barely improve your security compared to a regular password.
When a wallet software has opened and unlocked a YubiKey wallet file, it should not have the "display seed" options enabled. I'm not sure if the seed can be stolen by analyzing memory, etc.

**Comment by t-anon** [comment]
The point is that for the use case that must be solved (a compromised client - malware on your computer), YubiKeys fail miserably.

It doesn't matter if the wallet software can't access your seed. Malware will just re-write the address you intend to send money to "behind the scenes."  As soon as you try to use the wallet to send money to someone, the malware will hook into the Monero client and change the recipient address while letting the "correct" address stay displayed on the GUI. Then, when you touch your YubiKey, you'll be signing a transaction for the wrong address, while thinking you signed a transaction for the correct one.

This is known as a "confused deputy attack" and it is the main issue with YubiKeys today. YubiKeys cannot really mitigate a compromised client - at which point you may as well just use a software wallet. It is why hardware wallets have displays, and it's why the wallet display shows the recipient address.

**Comment by rating89us** [comment]
Thanks for your explanations, it seems that YubiKey is not really useful for Monero GUI.
