### ISSUE TITLE
Stuck pending transaction in gui wallet v. 0.17.2.0

### ISSUE THREAD

**Issue by prometheus-aflame** [monero-project/monero-gui#3489]
I sent a transaction to a valid Monero subaddress using my GUI wallet. Here is some basic device information:

OS: Ubuntu 20.04.2 Focoal Fossa, 5.8.0-53-generic
Monero GUI wallet version: 0.17.2.0

Transaction ID: 6122b7b4246e0dd0d7d2ba7ea5caafdea75e40fb82f6fd01b3e0e9295160e520

I have a transaction that hasn't been picked up by a miner after one hour. Is there a manner in which I can cancel this transaction in the GUI wallet? The transaction ID is not present in blockchair or exploremonero. Please let me know. Thanks.

**Comment by prometheus-aflame** [comment]
I've rechecked the wallet and my local node. THe local node is fully synced. Transaction is still stuck in a "pending" state.

**Comment by selsta** [comment]
You can go to Settings -> Log and type `relay_tx txid` to relay the transaction again.

To abort the transaction enter `flush_txpool txid`

**Comment by prometheus-aflame** [comment]
Flushing the txid worked. Thanks.

Sent from ProtonMail mobile

-------- Original Message --------
