### ISSUE TITLE
Provide macOS Universal Binary (M1) release

### ISSUE THREAD

**Issue by t-anon** [monero-project/monero-gui#3495]
monero-wallet-gui uses a lot of energy running on ARM M1 Macs due to translation. We should provide a universal binary.

**Comment by counterbeing** [comment]
I actually can't even seem to get `monerod` running. It just unexpectedly quits immediately. 😢

**Comment by selsta** [comment]
As a first step the next release will make it easy to compile monero and monero-gui, currently some manual changes are required.

**Comment by BigslimVdub** [comment]
@selsta 
Is this the only change needed (as of today master) to build on M1:
https://github.com/monero-project/monero-gui/pull/3804

Just git pull master then make -j4 ?

**Comment by selsta** [comment]
master should build fine on M1.

Just clone and then `make`.

**Comment by artisr** [comment]
master builds, however when trying to mine with P2Pool it gives an error "Error starting mining" "Couldn't start mining"

**Comment by selsta** [comment]
First step towards M1 binaries: https://github.com/monero-project/monero/pull/8312

**Comment by selsta** [comment]
@artisr what hardware are you using?

**Comment by artisr** [comment]
I managed to get it working, I compiled https://github.com/SChernykh/p2pool and replaced p2pool binary in monero-wallet-gui/Contents/MacOS

If I'm guessing right, the app download the binary and we need to update it to download the correct one?

I'm using 16" M1 pro

**Comment by selsta** [comment]
Correct, currently p2pool doesn't offer M1 binaries yet.

**Comment by Janaka-Steph** [comment]
Can I ask an ETA for this?

**Comment by selsta** [comment]
Qt only added official M1 support in 5.15.9: https://www.qt.io/blog/commercial-lts-qt-5.15.9-released

This version won't be available open source until April 2023. It might be possible to get it working with previous versions but I didn't spend much time on it yet.

**Comment by Janaka-Steph** [comment]
> Qt only added official M1 support in 5.15.9: https://www.qt.io/blog/commercial-lts-qt-5.15.9-released
> 
> This version won't be available open source until April 2023. It might be possible to get it working with previous versions but I didn't spend much time on it yet.

Oh okay. Thank you for the quick reply

**Comment by Ishaanahuja7** [comment]
Qt 5.15.9 Community Version Officially Released [here](https://download.qt.io/official_releases/qt/5.15/5.15.9/single)

**Comment by selsta** [comment]
Qt doesn't provide precompiled libraries for Qt 5.15.3 or later, which means I have to compile it myself. I've been doing some tests but wasn't successful yet.

**Comment by selsta** [comment]
I made some progress here, I got the packaged GUI running natively with the following 2 issues:

- Starting local node fails
- Some icons don't display correctly

**Comment by selsta** [comment]
Next release will have native macOS ARM binaries.
