### ISSUE TITLE
A solution to the Janus attack

### ISSUE THREAD

**Issue by SlitheringMule** [monero-project/monero-gui#3515]
Problem: https://www.getmonero.org/2019/10/18/subaddress-janus.html
Solution: Include the address Monero has been recieved to (using the FULL address, unlike show_transfers), when Monero is recieved.

This could be included in the monero-cli-wallet and the monero-gui-wallet

**Comment by SamsungGalaxyPlayer** [comment]
In what way does this address the attack

**Comment by SlitheringMule** [comment]
It makes it clear which address the monero was sent to

**Comment by selsta** [comment]
Please see https://github.com/monero-project/research-lab/issues/62#issuecomment-870147617

**Comment by SlitheringMule** [comment]
@selsta could you please delete this issue, thanks!

**Comment by selsta** [comment]
I can't delete issues.

**Comment by SlitheringMule** [comment]
Is there anyone who can?
