### ISSUE TITLE
Feature request: New monero-gui icon for macos big sur

### ISSUE THREAD

**Issue by theerha1453** [monero-project/monero-gui#3556]
<img width="512" alt="moneroicon" src="https://user-images.githubusercontent.com/85779927/121767085-dffa0180-cb5e-11eb-8769-ba9561131615.png">

looks very nice

**Comment by theerha1453** [comment]
![Screenshot 2021-06-12 at 09 17 13](https://user-images.githubusercontent.com/85779927/121767106-facc7600-cb5e-11eb-9a47-abf48da46ecb.png)

**Comment by selsta** [comment]
Could you upload this as a .icns file? Thanks.
