### ISSUE TITLE
MoneroD CLI output skipping some records of launched treads

### ISSUE THREAD

**Issue by dzintars** [monero-project/monero-gui#3561]
Not sure is it important, but will leave it there in any case.

![image](https://user-images.githubusercontent.com/547420/121928160-8f45fc80-cd48-11eb-9efc-b4981323af32.png)

As you can see from the output, only 7 treads was started (actually 8), and 8 treads was stopped. 6th thread missing from the starting treads MoneroD CLI output.

**Comment by selsta** [comment]
Could be resolved by https://github.com/monero-project/monero/pull/7929

If not please open an issue here: https://github.com/monero-project/monero/ since this isn't GUI related.
