### ISSUE TITLE
History: some transaction amounts are exported to CSV file in scientific notation

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#3566]
![image](https://user-images.githubusercontent.com/45968869/122543369-ff47d180-d02b-11eb-916c-4ab0fefa6d63.png)

**Comment by selsta** [comment]
Did you confirm that this isn't just excel (or whatever you are using) converting it? Try to open the file in a text editor and check if it also contains scientific notation.

**Comment by selsta** [comment]
Oops, accidentally removed my comment. Did you confirm that it isn't Excel (or whatever program you are using) that converts the number to scientific notation? Fee uses display amount, this scientific notation should not happen.

**Comment by rating89us** [comment]
> Fee uses display amount, scientific notation should not happen.

You're right, just the amount is being exported in scientific notation. It was LibreOffice Calc that was converting fee to scientific notation.
