### ISSUE TITLE
Blockchain stops syncing

### ISSUE THREAD

**Issue by t-anon** [monero-project/monero-gui#3587]
After initializing a new wallet, a couple of blocks sync and then sync stops.

```
GUI version: 0.17.2.2-937cb98 (Qt 5.12.8)
Embedded Monero version: 0.17.2.0-release
Wallet mode: Simple mode (bootstrap)OpenGL
```

**Comment by selsta** [comment]
Do you mean wallet scan or blockchain sync?

The lock is only visual so I doubt that it stops syncing.

**Comment by t-anon** [comment]
Edited my post to reflect this. Looks like the syncing just... stops, after some time. Not sure what the cause is, could anyone help investigate?

**Comment by selsta** [comment]
Does it continue if you wait?

**Comment by t-anon** [comment]
No, it does not continue. I see there is a lot of network down, but the "Wallet Blocks Remaining" is stuck in the GUI. However, it says "Daemon is Synchronized."

Running some commands:

```
>>> status
[6/23/21 12:54 AM] 2021-06-23 04:54:33.815 I Monero 'Oxygen Orion' (v0.17.2.0-release)
Height: 2389265/2389265 (100.0%) on mainnet, bootstrapping from REDACTED, local height: 1366064 (57.2%), not mining, net hash 2.47 GH/s, v14, 0(out)+0(in) connections
>>> status
[6/23/21 12:55 AM] 2021-06-23 04:55:39.541 I Monero 'Oxygen Orion' (v0.17.2.0-release)
Height: 2389265/2389265 (100.0%) on mainnet, bootstrapping from REDACTED, local height: 1370584 (57.4%), not mining, net hash 2.47 GH/s, v14, 0(out)+0(in) connections
```

So it looks like there is progress, but it's not being reflected in the GUI progress bar, which is stuck at ~124k?

**Comment by selsta** [comment]
Does it continue if you click on the two arrow symbol in the top left corner?

**Comment by t-anon** [comment]
I don't see such a symbol on the top left, but rather bottom right. I clicked it but nothing happened.

**Comment by selsta** [comment]
Does this issue still happen?

**Comment by BigmenPixel0** [comment]
> Does this issue still happen?

Yes

**Comment by selsta** [comment]
@BigmenPixel0 Please open a separate issue with more details.

**Comment by BigmenPixel0** [comment]
> @BigmenPixel0 Please open a separate issue with more details.

Now the problem is gone, but maybe the tor proxy was to blame for this?

**Comment by selsta** [comment]
Possible, not clear.

**Comment by selsta** [comment]
It seems that you were using simple mode (bootstrap) which can connect you to a bad remote node. If you continue to have issues I'd recommend to select advanced mode instead.
