### ISSUE TITLE
transferring Monero to Ledger X Hardware Wallet

### ISSUE THREAD

**Issue by MarkyBel** [monero-project/monero-gui#3589]
yesterday i sent my monero to my Hardware wallet that i set up but i havent recieved it. i have double checked the address, i have the most updated wallet and from my end it seems to say that is synced. is there anytning im missing? anything technical that i may have to change?

appreciate any help?

**Comment by selsta** [comment]
Can you go to Settings -> Info and post the number under "wallet restore height".

**Comment by MarkyBel** [comment]
2389801
\

**Comment by selsta** [comment]
Could you also share the transaction id?

**Comment by MarkyBel** [comment]
trans id dfa206755669286a3720855729e2ac7dd836812bac1a762273add9ecbe603dc3

there is no number just simple mode bootstrap

**Comment by MarkyBel** [comment]
why do you need the transaction id?

the wallet is in simple mode

**Comment by MarkyBel** [comment]
there is no number under the wallet mode?

**Comment by selsta** [comment]
> why do you need the transaction id?

I need to know the block height of the transaction. I saw it now so not necessary to post it again.

> there is no number under the wallet mode?

Yes, it was a copy paste issue I meant the value.

-----------------------

Please go to Settings -> Info, click on "(Change)" next to wallet restore height and then enter `2389000` and click on okay twice. Wait for the wallet to rescan. Please report back if that works.

**Comment by MarkyBel** [comment]
it says it will delete the recieve adress etc? is that right?

**Comment by selsta** [comment]
yes

**Comment by MarkyBel** [comment]
says its startring node.

thanks very much for the help?

**Comment by MarkyBel** [comment]
i tried that but the number doesnt seem to be staying there. there is no number next to the block height

**Comment by MarkyBel** [comment]
its worked.

thank you so so much

**Comment by selsta** [comment]
Great :)
