### ISSUE TITLE
Why is there a Bitcoin Miner in your 64x-Bit installer?!?!?!?!

### ISSUE THREAD

**Issue by stran0s** [monero-project/monero-gui#3621]
Please tell me?

![image](https://user-images.githubusercontent.com/81618255/125468497-ad4a9aee-ac5d-4c52-973d-040b98c70775.png)

As you might see this is a Bitcoinminer, once you remove these Programs, the Wallet still loads and works, you just get an Pop-Up Window which shows "....-File missing".
Also why does a wallet need an Exception in my Firewall?!??! Often Miners need that....

**Comment by dEBRUYNE-1** [comment]
Please see:

https://monero.stackexchange.com/questions/10798/my-antivirus-av-software-blocks-quarantines-the-monero-gui-wallet-is-there

https://www.getmonero.org/get-started/faq/#antivirus
