### ISSUE TITLE
Trezor: segmentation fault error when entering passphrase on computer

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#3623]
@ph4r05

A "Segmentation fault" error appears and Monero GUI exits after entering passphrase on computer when creating or opening a wallet file. This error is not present when entering passphrase on device.

It's present in Trezor firmware 2.3.6 and 2.4.0, using GUI version 0.17.2.2 (Windows).

**Comment by selsta** [comment]
A PR for this exists already, will be fixed next version.

**Comment by selsta** [comment]
https://github.com/monero-project/monero/pull/7781
