### ISSUE TITLE
Monerod crashes with sigbus if I try to sync from my phone

### ISSUE THREAD

**Issue by seamasteruwu** [monero-project/monero-gui#3626]
So when i try to sync (using an sd card) monerod quickly crashes with an sigbus. It only happens if i am syncing since if i have no internet monerod works however is useless since i can't use monerod without an blockchain. It also isn't because my blockchain is corrupted since i'm trying to sync from scratch. I am using the latest version of the monero wallet and the lastest version of termux. 
[monero.error.log](https://github.com/monero-project/monero-gui/files/6827158/monero.error.log)
That is what i get by running
./monerod --data-dir ~/my/sdcard/bitmonero --log-level 4 > monero.error.log
before i get SIGBUS. I am running the precompiled monero binaries from getmonero.org. I'm in android 8.1 32 bits.

**Comment by seamasteruwu** [comment]
Also im writing the issue here because i cant do it in the main monero repo since i must have contribuited there.

**Comment by djemilbakhti** [comment]
> So when i try to sync (using an sd card) monerod quickly crashes with an sigbus. It only happens if i am syncing since if i have no internet monerod works however is useless since i can't use monerod without an blockchain. It also isn't because my blockchain is corrupted since i'm trying to sync from scratch. I am using the latest version of the monero wallet and the lastest version of termux.
> [monero.error.log](https://github.com/monero-project/monero-gui/files/6827158/monero.error.log)
> That is what i get by running
> ./monerod --data-dir ~/my/sdcard/bitmonero --log-level 4 > monero.error.log
> before i get SIGBUS. I am running the precompiled monero binaries from getmonero.org. I'm in android 8.1 32 bits.

you can use monerod without blockchain 
just run 
./monerod --no-sync --bootstrap-daemon-address auto

**Comment by selsta** [comment]
Please open an issue here if you continue to have issues: https://github.com/monero-project/monero
