### ISSUE TITLE
How do I update Monero-GUI on Linux Mint?

### ISSUE THREAD

**Issue by nb850** [monero-project/monero-gui#3645]
I've downloaded the latest update but its still on the old version, how do I update the GUI?

**Comment by selsta** [comment]
Did the update dialog pop up? You have to replace the old monero-wallet-gui binary with the new one.

**Comment by nb850** [comment]
Where are the binary files located? I've tried 'whereis monero' in terminal but no path is showing.

**Comment by selsta** [comment]
How did you install it in the first place?

**Comment by nb850** [comment]
I used the commands on the github page , just started using linux so apologies if its a stupid question.

**Comment by nb850** [comment]
Got it finally, thanks for the help.
