### ISSUE TITLE
Help Requested - Zero Balance after recovering via seed and blockchain/wallet sync - reset height to 0 same issue

### ISSUE THREAD

**Issue by InvoluntaryYoga** [monero-project/monero-gui#3664]
Hello,

I am having an issue after needing to reinstall Monero GUI that it shows a zero balance.
Windows crashed on me, so I decided to install Linux and Windows as a dual boot. 
I have the monero GUI on both of them now, and have tried the following on both, to no avail.

First, I did a recovery via my seed/recovery phrase, and used a rounded down value for my restore height.
I ran a local node (without pruning).
I let my blockchain sync. I let my wallet sync.
I looked at my wallet, which showed a zero balance. 

Prior to my PC crashing, my wallet definitely had more than a 0 balance, and had only received into that wallet and not sent from said wallet. Unfortunately, I do not have any transaction information. I only know my restore height (around 1750000) and recovery/seed phrase.

I have tried to follow the directions here: 
https://monero.stackexchange.com/questions/6640/i-am-missing-not-seeing-a-transaction-to-in-the-gui-zero-balance

The above directions, however, did not fix the issue.
I have tried setting the restore height ~ 10k before my restore height I wrote down, and also tried setting it to 0. 
I have tried a different operating system. 
I have verified I am synced up to the latest block via looking at the block explorer (XMRchain). (I am at 2424416 right now)
I have renamed my wallet in order to initiate my wallet to rebuild/sync. 
I have tried using a remote node (node.moneroworld.com:18089). 
Nothing seems to work.

I also see 0 transactions in/out from my wallet. 
I'm not sure if that is 100% way of knowing that I somehow did not have my wallet taken from me via bad actors or what. Just some more info...It makes it seem like this is not the case.

I'm running Monero GUI version 0.17.2.2-937cb98.
Embedded monero version is 0.17.2.0-release according to the GUI.
The only other thing that I can think of that changed between now and then is using a different router, which I don't believe is any issue with any firewall rules since the blockchain still synced and I have not had issues with other wallets.

Any help would be greatly appreciated!

Here is what displays if I look at the status:
[8/10/21 9:28 PM] 2021-08-11 01:28:13.938 I Monero 'Oxygen Orion' (v0.17.2.0-release)
Height: 2424418/2424418 (100.0%) on mainnet, not mining, net hash 2.71 GH/s, v14, 12(out)+0(in) connections, uptime 0d 0h 13m 20s

**Comment by selsta** [comment]
As a first step, please go to the Account page and check if you see your balance there.

**Comment by InvoluntaryYoga** [comment]
0 Balance under the account tab as well.

**Comment by selsta** [comment]
Do you have a transaction id from an incoming transaction?

**Comment by InvoluntaryYoga** [comment]
Unfortunately, no. I only wrote down my recovery phrase and restore height.

**Comment by selsta** [comment]
Do you know how to use the CLI wallet?

**Comment by InvoluntaryYoga** [comment]
I do not. I have been on Linux for roughly 10 days or so ... limited command line knowledge, but ....gotta start sometime.

**Comment by selsta** [comment]
You basically need these commands:

```
./monerod --detach
./monero-wallet-cli --restore-deterministic-wallet
```

Set restore height to 1.

**Comment by InvoluntaryYoga** [comment]
Should I close the GUI and keep the daemon running before I do this?

**Comment by selsta** [comment]
Close the GUI, if you keep the daemon running you don't have to run ./monerod

**Comment by InvoluntaryYoga** [comment]
I get an error "bash: ./monerod: No such file or directory".
This made me think I need to install the CLI version.

Sorry for the lack of understanding. Thank you for helping so far. 
Do I need to be in a certain directory for this?
Just verified and extracted the CLI.

**Comment by InvoluntaryYoga** [comment]
Ah, I follow now. Needed to be in directory of the CLI I just downloaded as suspected.

**Comment by InvoluntaryYoga** [comment]
Untagged accounts:
          Account               Balance      Unlocked balance                 Label
 *       0   xxxxxxx      0.000000000000        0.000000000000       Primary account
----------------------------------------------------------------------------------
          Total        0.000000000000        0.000000000000
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 0.000000000000, unlocked balance: 0.000000000000

[wallet xxxxxxx]: status
Refreshed 241952/241952, synced, daemon RPC v3.5, SSL
[wallet xxxxxxx]: version
Monero 'Oxygen Orion' (v0.17.2.0-release)
[wallet xxxxxxx (out of sync)]: balance
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 0.000000000000, unlocked balance: 0.000000000000
[wallet xxxxxxx (out of sync)]: show_transfers
[wallet xxxxxxx (out of sync)]: refresh
Starting refresh...
Refresh done, blocks received: 4916                             
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 0.000000000000, unlocked balance: 0.000000000000
[wallet xxxxxxx]: wallet_info
Filename: MyWallet1
Description: <Not set>
Address: xxxxxxx
Type: Normal
Network type: Mainnet
[wallet xxxxxxx]: show_transfers


This is what I have thus far.

Something I just noticed though.
The last word of my recovery phrase is a repeat of another word...When I went to write this in the CLI, I skipped one and noticed it also repeated a word. Does it repeat a word at the end of the mnemonic seed if you missed a word? 

If so...I may have made a very bad goof and wrote down an incorrect mnemonic seed.

If this is the case, I do have a backup of my wallet on a hard drive. Can I recover from this if I have the password?

**Comment by selsta** [comment]
In general a monero seed should have 25 words. One word repeating is normal, it's a checksum.

> If this is the case, I do have a backup of my wallet on a hard drive. Can I recover from this if I have the password?

Yes.

**Comment by InvoluntaryYoga** [comment]
Just to clarify, I did have 25 words in my recovery phrase. Just the last word was a repeat of another previously used.

Anyways, I could not get it to restore with the other methods, but sure enough super easy with the backed up wallet. 
Not sure why I hadn't thought of that days ago!

Thank you so much though!

**Comment by selsta** [comment]
Were you able to restore from backup? Can you confirm that the seed is the same as you wrote down? It should always be possible to restore from seed without issues and there are no known bugs around it.

Closing this for now as there doesn't seem to be any bug.

**Comment by InvoluntaryYoga** [comment]
Confident no bug.

I can confirm that it is not what I wrote down, but the seed phrase I got from the backup does seem familiar (I'd say 98+% sure of the first 5 words being used before for phrases).
I'm pretty confident now that I mix-matched recovery phrases for different cryptos. I do not have all of them here physically, but I have another copy in a safe place, but is hours away. I can confirm MAYBE this weekend with those copies if this is what happened, but not sure yet.

Sorry for your troubles. I am glad I got it sorted out though. And I also learned a teeny bit about the CLI. 
Can I throw a bit of XMR your way for your troubles?

**Comment by selsta** [comment]
>  Can I throw a bit of XMR your way for your troubles?

Not necessary as I get community funding (ccs.getmonero.org) :) But thanks anyway!

**Comment by Jon1325** [comment]
I was left in shock and depression after being deceived by bitfinex investment where I lost about 395,000 USDT of my entire life savings which I was planning to get a company after my retirement as life investment for my kids but this nitwits stole it from me. However after weeks of my depression I finally met REMOTESPYTECH (at) gmailc0m through a close friend referral and he got back all my stolen assets instantly without hassle or hidden fees. He’s the only real deal out here as I’ve tried many but they failed. He was my final and last hope. I’m grateful Mr Romero delivered. Get in touch with him now!!!!

Email: REMOTESPYTECH (at) GMAILC0M 

whatsapp: +1 (352) 870-0844

Real Deal 

Tremendous Service
