### ISSUE TITLE
Be able to use UnstoppableDomains for sending XMR

### ISSUE THREAD

**Issue by ZepsiZola** [monero-project/monero-gui#3668]
![image](https://user-images.githubusercontent.com/49735083/129934953-4e50c55c-5e3a-421f-a2f4-bbd97493fd08.png)
I saw that this wallet software allows the use of OpenAlias, but it could also use UnstoppableDomains which is more popular and used than OpenAlias.

E.g. You could enter "monero.crypto" into the text-box and that domain would direct to an actual wallet address through UnstoppableDomains.

**Comment by selsta** [comment]
Adding support for UnstoppableDomains is currently not planned.
