### ISSUE TITLE
Screen recording permission

### ISSUE THREAD

**Issue by NorthHub** [monero-project/monero-gui#3676]
Why would monero-gui ask for screen recording permission? I declined the request, explain to me the reason why you need it
![xmr](https://user-images.githubusercontent.com/60108969/130458213-7b762302-5538-4368-8be9-88ebe06d30b6.png)

**Comment by selsta** [comment]
It's for the grab qr code feature, you can decline it and the program will work just fine, it just won't be able to grab QR codes from screen.
