### ISSUE TITLE
Feature request : Ship a genuine AppImage in the download

### ISSUE THREAD

**Issue by cassepipe** [monero-project/monero-gui#3703]
It's all in the title. The current AppImage you find in the Linux download folder is just a hack to start the executable from a graphical session apparently.
Would you be willing to ship a genuine AppImage?

Thanks for all the great work

**Comment by selsta** [comment]
What would the advantages be?

**Comment by cassepipe** [comment]
Linux desktop integration

**Comment by selsta** [comment]
Did you install the desktop entry on first start? https://wiki.archlinux.org/title/desktop_entries

**Comment by cassepipe** [comment]
No I did not., thanks for pointing out to documentation. 

AppImages and Flatpak are becoming more and more common to distribute software on Linux especially when the software needs to be kept up to date. I thought it would be a worthwhile addition.
Especially as there no other way to know that the AppImage is not a standard AppImage without searching into the repo issues
which is confusing for non advanced Linux users.

Now if you tell me there no willingness for that to happen or that is poses technical issues, I'll just close this.

**Comment by selsta** [comment]
FWIW I think Monero GUI is available as a Flatpak. Is that good enough?

**Comment by cassepipe** [comment]
I did not know that. There wasn't any last time I checked. 
I looked it's only two months old and there is no mention of it neither on getmonero.org nor the Github's Readme 
(Can I trust it then ?)

It is not for me to judge if that's good enough or not, I am just making humble suggestions.
Thanks for your replies.

NB : You asked what are the advantages of Appimages, I think it is better worded [there](https://docs.appimage.org/introduction/advantages.html#advantages-for-application-authors ). (Now if you actually meant advantages *over* flatpaks I have no idea)

**Comment by BigmenPixel0** [comment]
Hi. You can look at the package [manifest](https://github.com/flathub/org.getmonero.Monero/blob/master/org.getmonero.Monero.yaml) and make sure that there are no bad functions inside.

**Comment by BigmenPixel0** [comment]
> I did not know that. There wasn't any last time I checked. I looked it's only two months old and there is no mention of it neither on getmonero.org nor the Github's Readme (Can I trust it then ?)
> 
> It is not for me to judge if that's good enough or not, I am just making humble suggestions. Thanks for your replies.
> 
> NB : You asked what are the advantages of Appimages, I think it is better worded [there](https://docs.appimage.org/introduction/advantages.html#advantages-for-application-authors). (Now if you actually meant advantages _over_ flatpaks I have no idea)

Hi. You can look at the manifest of org.getmonero.Monero and make sure that there are no bad functions inside.
