### ISSUE TITLE
MacOS Big Sur static compile error

### ISSUE THREAD

**Issue by 3s3s** [monero-project/monero-gui#3710]
I am trying to compile the monero-gui with static linking on system Apple MacOS Big Sur 11.5.2 . 
`monero release-static`
Almost all compilation is successful and almost all binaries except monero-wallet-gui are successfully created. At the end of compilation I got the error:

`
[100%] Building CXX object src/CMakeFiles/monero-wallet-gui.dir/usr/local/opt/qt@5/lib/cmake/Qt5Gui/Qt5Gui_QWebGLIntegrationPlugin_Import.cpp.o 

[100%] Building CXX object src/CMakeFiles/monero-wallet-gui.dir/usr/local/opt/qt@5/lib/cmake/Qt5Gui/Qt5Gui_QXdgDesktopPortalThemePlugin_Import.cpp.o 

make[3]: stat: /usr/local/opt/qt@5/lib/libQt5Gui.a -framework Metal -framework CoreGraphics -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libqtlibpng.a /usr/local/opt/qt@5/lib/libqtharfbuzz.a /usr/local/opt/qt@5/lib/libQt5QmlModels.a /usr/local/opt/qt@5/lib/libQt5Qml.a /usr/local/opt/qt@5/lib/libQt5Network.a -framework SystemConfiguration -framework GSS /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a /usr/local/opt/qt@5/lib/libQt5Network.a -framework SystemConfiguration -framework GSS /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libQt5Widgets.a /usr/local/opt/qt@5/lib/libQt5Gui.a -framework Metal -framework CoreGraphics -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libqtlibpng.a /usr/local/opt/qt@5/lib/libqtharfbuzz.a /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libQt5Gui.a -framework Metal -framework CoreGraphics -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libqtlibpng.a /usr/local/opt/qt@5/lib/libqtharfbuzz.a /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a -framework AppKit -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a /usr/local/opt/qt@5/lib/libQt5Gui.a -framework Metal -framework CoreGraphics -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libqtlibpng.a /usr/local/opt/qt@5/lib/libqtharfbuzz.a /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a /usr/local/opt/qt@5/lib/libQt5Widgets.a /usr/local/opt/qt@5/lib/libQt5Gui.a -framework Metal -framework CoreGraphics /usr/local/opt/qt@5/lib/libqtlibpng.a /usr/local/opt/qt@5/lib/libqtharfbuzz.a /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a -framework OpenGL -framework AGL -framework Metal /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a -framework AppKit -framework CoreGraphics -framework Foundation -framework OpenGL -framework AGL /usr/local/opt/qt@5/lib/libqtlibpng.a /usr/local/opt/qt@5/lib/libqtharfbuzz.a -framework ApplicationServices /usr/local/opt/qt@5/lib/libQt5Qml.a /usr/local/opt/qt@5/lib/libQt5Network.a -framework SystemConfiguration -framework GSS /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a /usr/local/opt/qt@5/lib/libQt5Network.a -framework SystemConfiguration -framework GSS /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a /usr/local/opt/qt@5/lib/libQt5Network.a -framework SystemConfiguration -framework GSS /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a /usr/local/opt/qt@5/lib/libQt5Core.a -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a -framework Security -framework CoreFoundation -framework CoreServices -framework SystemConfiguration -framework GSS -framework DiskArbitration -framework IOKit -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation /usr/local/opt/qt@5/lib/libqtpcre2.a: File name too long `

**Comment by selsta** [comment]
For macOS app bundle please follow the steps in: https://github.com/monero-project/monero-gui/blob/master/DEPLOY.md#macos
