### ISSUE TITLE
Monero GUI crashing on Mac

### ISSUE THREAD

**Issue by b3K1ndRw1nd** [monero-project/monero-gui#3722]
Whenever I try to run the Monero GUI on my Mac Catalina Vers 10.15.7, it crashes with the following logs
[monero-logs.txt](https://github.com/monero-project/monero-gui/files/7439274/monero-logs.txt)

I have to do
```
export QMLSCENE_DEVICE=softwarecontext;
/Volumes/Macintosh HD/Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
``` 
to get it to run

**Comment by Frontrunner1488** [comment]
GUI crashing on startup after latest OS update.

**Comment by sMtzDczDq** [comment]
The error I'm getting when starting it from terminal is this: W <Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth" No idea what it means. A quick google search points to Qt Framework

**Comment by selsta** [comment]
@Frontrunner1488 which OS?

@sMtzDczDq same question, which OS, and since when do you have this issue? You only posted a warning which is unrelated.

**Comment by sMtzDczDq** [comment]
@selsta macOS Catalina 10.15.7. I think it started after upgrading to 10.15.7 which according to my logs was October 26th. I tried the previous version of the gui but it has the same problem. I'm trying to get it running with a debugger attached. If I find anything I'll let you know.

**Comment by selsta** [comment]
Can you update to macOS 11? It appears if 10.15.7 has a bug. The code doesn't crash inside monero code, so there isn't much we can do.

Unfortunately I don't have a machine on 10.15 to reproduce.

**Comment by Frontrunner1488** [comment]
@selsta Catalina, going to try to upgrade OS to Big Sur or Monterrey and see if that resolves the issue.

**Comment by selsta** [comment]
```
export QMLSCENE_DEVICE=softwarecontext;
/Volumes/Macintosh HD/Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
```

As a workaround it's possible to use the GUI with these commands on 10.15.7, as written in the original issue post.

**Comment by TonyD83** [comment]
I have the exact same issue on 10.15.7. Seems like it started after the recent security update. I tried searching the specific error. From what I can find this is due to the application trying to access a deprecated gpu driver? Can anyone confirm? 

Error:
Application Specific Signatures:
Graphics kernel error: 0xfffffffb

**Comment by mouldysandals** [comment]
> ```
> export QMLSCENE_DEVICE=softwarecontext;
> /Volumes/Macintosh HD/Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
> ```
> 
> 
>      
>   
> 
> As a workaround it's possible to use the GUI with these commands on 10.15.7, as written in the original issue post.

Hi, it says no file or depository by that name but there 100% is, any advice? I'm running this in terminal, should it be console? Sorry for noob questions

**Comment by selsta** [comment]
@mouldysandals

If you have the GUI inside the application folder try with Terminal:


```
QMLSCENE_DEVICE=softwarecontext /Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
```

**Comment by TonyD83** [comment]
> @mouldysandals
> 
> If you have the GUI inside the application folder try with Terminal:
> 
> ```
> QMLSCENE_DEVICE=softwarecontext /Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
> ```

This worked for me. Thanks!

**Comment by richelo** [comment]
I am trying to run this for the first time on the M1 Mac Mini with MacOS 12.0.1.

I try and create a wallet, and at the set password screen it crashes. It always happens when I am retyping the password in the confirm field.

`Application Specific Information:
monero-wallet-gui(99047,0x2016cb600) malloc: Incorrect checksum for freed object 0x7fe6a370bcf8: probably modified after being freed.
Corrupt value: 0x4039642d0cfc4e3f
abort() called`

I tried running:

`QMLSCENE_DEVICE=softwarecontext /Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui`

I get this in the terminal: 

`2021-11-15 05:57:13.797	W <Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"`

I get a whole bunch of those and the application never starts.

**Comment by selsta** [comment]
@richelo I can't reproduce this on my M1 MBP.

Can you open Console.app, copy paste the full crash report and upload it to paste.debian.net?

**Comment by richelo** [comment]
@selsta do you want me to run the application from the console, or just run the app normally, and then grab the whole crash report?

Trying to run from the console never starts. It always just sits at `2021-11-15 06:24:04.243	W <Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"`

**Comment by selsta** [comment]
> or just run the app normally, and then grab the whole crash report?

Run the app normally and get a crash report.

**Comment by richelo** [comment]
@selsta , here you go.
[MoneroGuiCrash.txt](https://github.com/monero-project/monero-gui/files/7536358/MoneroGuiCrash.txt)

**Comment by selsta** [comment]
What kind of password did you enter? How many characters?

**Comment by richelo** [comment]
10 Characters, 1 capital letter and a ! and a few numbers as well.

**Comment by selsta** [comment]
Does it also crash if you enter e.g. 123 as your password? According to the crash log the issue is inside an external library for password strength.

**Comment by richelo** [comment]
123 as password works with no issue.

I will play around a bit with passwords to see if I can set a secure one without the app crashing.

I do think it is something that needs to be investigated and fixed. It's not some insane password I am trying to use.

**Comment by selsta** [comment]
Could you generate a password that makes it crash on your side so that I can reproduce and attempt to fix it?

**Comment by selsta** [comment]
Might have found the issue: https://github.com/tsyrogit/zxcvbn-c/pull/11

**Comment by mouldysandals** [comment]
> @mouldysandals
> 
> If you have the GUI inside the application folder try with Terminal:
> 
> ```
> QMLSCENE_DEVICE=softwarecontext /Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
> ```

thank you so much works perfectly

**Comment by mouldysandals** [comment]
> @mouldysandals
> 
> If you have the GUI inside the application folder try with Terminal:
> 
> ```
> QMLSCENE_DEVICE=softwarecontext /Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
> ```

hi sorry selsta, it's opening and 'working' it's showing me my funds, but it's stuck trying to connect to a remote node and i can't send the funds anywhere, on the terminal it just keeps saying daemon error - any advise? pls

**Comment by selsta** [comment]
Can you go to Settings -> Info and check which "wallet mode" you are using?

**Comment by mouldysandals** [comment]
> Can you go to Settings -> Info and check which "wallet mode" you are using?

Advanced mode (Remote node)

**Comment by mouldysandals** [comment]
Oh wait, for some reason it's working now without me changing anything... weird, but no complaining! Thanks for your help anyway!

**Comment by alexmagee123** [comment]
hey @selsta 

I have a similar problem to @richelo but it crashes as soon as monero and the password field loads. 

**Info**

- Mac OS Monterey 12.5.1
- Monero V18.1.2

Any ideas?

**Comment by selsta** [comment]
@ALM0000 does the same crash happen after creating a new wallet?

**Comment by ALM0000** [comment]
Hey @selsta 

Thanks for the quick reply. I can't even get to a wallet. As soon as I load the GUI wallet, it appears to enter password and then immediately crashes. 

I've also deleted my wallets but the same thing happens :(

**Comment by selsta** [comment]
The crash report shows a triggered assert into operating system related code, I have never seen this before and unfortunately no idea. Can you try out Feather Wallet?

**Comment by epoberezkin** [comment]
I have a similar issue with another wallet, the log says 
Get public address exception: Call method failed
Cannot get a device address

GUI version: 0.18.3.3-release (Qt 5.15.13)
Embedded Monero version: 0.18.3.3-81d4db08e

**Comment by kupietools** [comment]
I can't get this to work at all. A minute after I open it, Monero Wallet GUI consumes 100GB of virtual memory and then crashes. It's not generating anything under Crash Reports, but this is under Diagnostic Reports: https://pastebin.com/cFNeeWtT

Running `QMLSCENE_DEVICE=softwarecontext /Applications/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui` starts up the GUI app, but quickly freezes. Generated log has now sat for over 5 minutes with no new lines added to it and the app not starting: https://pastebin.com/CQp3swKK

Running on latest version of Monterey, 16 GB ram. Latest version of Monero-wallet-GUI, just downloaded it tonight.

**Comment by selsta** [comment]
@kupietools this sounds like a bizarre issue, never have seen such a report before on macOS... do you have a different Mac where you can test this?
