### ISSUE TITLE
Cant create wallet on Ledger S with Monero GUI

### ISSUE THREAD

**Issue by FreeRide23** [monero-project/monero-gui#3725]
Hi there, did not find any working solution, so i create this.

Ledger Nano S Firmware 2.0.0
Monero App for Ledger 1.7.7
Monero GUI Wallet 0.17.2.3-113efbf (Qt 5.15.2)

Error:
Tryed to create a wallet on the Ledger with the Monero GUI, advanced mode -> "create a wallet from hardware" -> named the wallet, wallet location selected, hard ware Model selected "Ledger Nano S" -> create a new wallet from device -> "create wallet" -> error "Error writing wallet from hardware device. Check application logs" -> also a second error on bottom "failed to generate new wallet: no device found"

I tryed to search the error log in the install folder "C:\Program Files\Monero GUI Wallet\" but there is no "log"... anywhere.... wtf!?

Any ideas?

And yes: i have started the monero app on the ledger, i have restartet, i have tryed an other USB, i have closed the ledger live.... no change......

**Comment by FreeRide23** [comment]
i will try it again on my linux laptop..... il write again when its done

**Comment by selsta** [comment]
Did it work in the past on your Windows machine?

**Comment by FreeRide23** [comment]
> 
> 
> Did it work in the past on your Windows machine?

This is the first time i try it, so... no.... i dont know....

**Comment by FreeRide23** [comment]
Works with fresh installation of win 10....

**Comment by mphelp** [comment]
@FreeRide23 I ran into this too when the Monero app wasn't open on my Nano S. I only had the Nano S main menu up. Making sure the Monero app was open fixed it for me. 

Does that mean you solved it and this issue can be closed?
