### ISSUE TITLE
Transaction stuck on pending

### ISSUE THREAD

**Issue by Felscream93** [monero-project/monero-gui#3729]
Hi,

I was trying to purchase something with Monero however it timed out on the merchants end and was sent back to myself. It is showing in my GUI wallet as Pending for the past 2 weeks now. My Monero Daemon is fully up to date with the blockchain. I have flushed the transaction ID, created a new wallet and still nothing. Any ideas would be greatly appreciated.

trans ID: 8694a20fc3a1f167da47228e8421f3af12af1376482b06b5eb7cf5edd540e035

PS - I have contacted the merchant and it is showing as processed their end.

**Comment by selsta** [comment]
"Still nothing", can you be more precise what this means? Is it "pending" or is it not showing up?

**Comment by Felscream93** [comment]
Oh its just a phrase meaning nothing has changed. It is showing as pending in my transactions

**Comment by selsta** [comment]
I don't understand how a new wallet can contain the same pending transaction.

Did you restore your wallet from seed?

**Comment by Felscream93** [comment]
I dont know what that means  I just flushed like it said in the manual and then renamed my wallet file to old. It loaded up a new address, took a while to load but all of my old transactions were still there

**Comment by selsta** [comment]
Closing this as this is a support ticket that's over a year old. Hopefully you were able to resolve the issue, if not please reply and I'll try give you more instructions.
