### ISSUE TITLE
Allow the option to disable the "Do you want to stop local node" screen.

### ISSUE THREAD

**Issue by Stetsed** [monero-project/monero-gui#3732]
Hello,

I am currently using monero-gui and running a local node. I run this local node via systemd because I found it easy to setup and it let's me easy run it always.

A problem I have encounterd is that when I set "Local Node" in my Monero GUI it detects the systemd node... so far so good. Now when I exit it it asks me if I want to stop the node, ofcourse I don't I run it on systemd for a reason.

Right now I have found that just setting remote node and then setting 127.0.0.1 as IP works, but I would rather just be able to select local node.

So I want to ask if it would be possible to add an option when selecting your desired option (So for me, don't stop node) and then save that with a "Remember" option so that in the future it just leaves it running.

If this isn't smth which get's added that's fine I hope you have a fantastic day and thanks for your project :D

**Comment by selsta** [comment]
#3734
