### ISSUE TITLE
Couldn't Start Mining

### ISSUE THREAD

**Issue by osakibill** [monero-project/monero-gui#3752]
Just installed monero-gui on windows 10. 

Wallet and Daemon are synchronized.

When I try to mine, I get a pop up error box that says " couldn't start mining"

Version is:
>>> version
[25/11/2021 23:52] 2021-11-25 23:52:05.789 I Monero 'Oxygen Orion' (v0.17.2.3-release) 
Error: The daemon software version is not available.
>>> update check
[25/11/2021 23:53] 2021-11-25 23:52:40.528 I Monero 'Oxygen Orion' (v0.17.2.3-release) 
No update available

Any ideas on what going on,,, or what I did wrong? :-/

**Comment by osakibill** [comment]
I am closing this issue until I know more about this. Just think I set it up incorrectly.

Thanks
Osakibill

**Comment by selsta** [comment]
Could it be anti virus related?

**Comment by osakibill** [comment]
Probably not. I did exclude the directories from my antivirus and I had no
error messages.

I think I did not have a connection to a node (?) or still trying to
download the chain.

So till I know about this I pulled my newbe issue. :-)

**Comment by selsta** [comment]
Yes, mining is not possible if you are still syncing / don't have to full blockchain.
