### ISSUE TITLE
Debian goes to read only state when im trying to sync my wallets

### ISSUE THREAD

**Issue by orestisb** [monero-project/monero-gui#3780]
Hello,
I have a dell laptop with all diagnostics passed.
Fresh install Debian on new ssd.
I transfred the blockchain from my old hdd.
When i open any wallet to sync the system goes to read only state.
This happen usualy when it gets at the 2400000 block (aprox).
Also i tried to restore from seed one wallet and nothing has changed it still goes to read only.
If i create a new wallet no problem occur.

Any ideas?

Thank you!

**Comment by selsta** [comment]
What does read only mean exactly? How do you see that it's read only?

**Comment by orestisb** [comment]
Thank you for your answer!
The problem solved.
I restored again from seed my wallet and this time was susseful.
