### ISSUE TITLE
Compile time option to disable "Would you like to register Monero GUI Desktop entry?"

### ISSUE THREAD

**Issue by kpcyrd** [monero-project/monero-gui#3787]
hi!

Arch Linux is distributing a monero-gui package that already includes a desktop entry.

Is there a way to disable this question with a compile time option?

![image](https://user-images.githubusercontent.com/7763184/145391346-21da313e-e82a-40c5-8c19-88f826ada741.png)

Thanks!

**Comment by selsta** [comment]
#3808

**Comment by selsta** [comment]
reminder that this release (v0.17.3.2) supports `-D WITH_DESKTOP_ENTRY=OFF`

**Comment by kpcyrd** [comment]
Thanks, we're now using this option in Arch Linux :heart:
