### ISSUE TITLE
Stylistic color bar is covered up and titles are uneven

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#379]
**Old build** (Color bar exists and "Monero" & "Amount" are vertically centered):
 
![goodd](https://cloud.githubusercontent.com/assets/21302237/21579347/15fb0820-cf78-11e6-91fa-1279d53f4fcc.png)

**Current build** (Corners of the color bar poking out the sides, "Monero" and "Amount" uneven):

![badd](https://cloud.githubusercontent.com/assets/21302237/21579346/07a1d2e0-cf78-11e6-8bb6-ea80490d2940.png)

**Comment by skftn** [comment]
Old user interface. 0.12.2 features the black theme.

+resolved
