### ISSUE TITLE
GUI Not Clearing Password After Wallet Creation

### ISSUE THREAD

**Issue by spackle-xmr** [monero-project/monero-gui#3794]
When using the GUI to create a set of wallets, the password used for the initial wallet was still filled in on the 'Give your wallet a password' screen when creating a second wallet. This is repeatable, in that if a second wallet is created it's password will still be entered when creating a third.
This was observed using the latest release (0.17.3.0) on Windows.

**Comment by selsta** [comment]
@rating89us Can you check this? IIRC there were some changes to this recently.

**Comment by rating89us** [comment]
I can't reproduce this issue on Windows (tried creating two new wallets and restoring two wallets).

**Comment by selsta** [comment]
At first I also couldn't reproduce but after trying a couple times I was able to reproduce, don't know why exactly.

**Comment by rating89us** [comment]
I could reproduce now, will investigate what is causing this.
