### ISSUE TITLE
Please stop relying on 3rd party.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [monero-project/monero-gui#3807]
Hello,
I was wondering why is the monero relying on 3rd party community driven applications?
Why not create an official one supported by the monero foundation.
- prajwal

**Comment by selsta** [comment]
Can you be a bit more precise with what you are suggesting? 3rd party what?

**Comment by Prajwal-Koirala** [comment]
https://github.com/monero-project/monero-gui#installing-the-monero-gui-from-a-package

**Comment by selsta** [comment]
We don't rely on 3rd party packages. The official place to download monero / monero-gui is here: https://www.getmonero.org/downloads/

Anyone can decide themselves if they
- download the official binaries
- compile the program themselves
- use their package manager (which are mostly community maintained)

We don't have the resources to "officially" maintain packages for every package manager out there, so the only official place to download monero is the website.

**Comment by Prajwal-Koirala** [comment]
> We don't rely on 3rd party packages. The official place to download monero / monero-gui is here: https://www.getmonero.org/downloads/
> 
> Anyone can decide themselves if they
> 
> * download the official binaries
> * compile the program themselves
> * use their package manager (which are mostly community maintained)
> 
> We don't have the resources to "officially" maintain packages for every package manager out there, so the only official place to download monero is the website.

This is literally a crypto, how in the world does a crypto not have enough funding to support package managers.

Set aside a couple of million for proper development for the protocol and the apps that support it.

**Comment by selsta** [comment]
Monero doesn't have a pre-mine or dev tax, there aren't "a couple millions" we can set aside for this. Development is funded by donations and a lot of the work is done by volunteers.

I'll close this as I think none of the devs are interested in maintaining packages for every single package manager out there. Monero is a community driven project so having packages maintained by community members fits the project philosophy.

**Comment by Prajwal-Koirala** [comment]
> Monero doesn't have a pre-mine or dev tax, there aren't "a couple millions" we can set aside for this. Development is funded by donations and a lot of the work is done by volunteers.
> 
> I'll close this as I think none of the devs are interested in maintaining packages for every single package manager out there. Monero is a community driven project so having packages maintained by community members fits the project philosophy.

should add something like, "Would you like to donate 1% of the transaction amount to the monero development fund."
