### ISSUE TITLE
Shortcut hides GUI on macOS

### ISSUE THREAD

**Issue by AdamSiddique** [monero-project/monero-gui#3814]
The Command+H shortcut is used to navigate to the "Transactions" tab in the GUI, but is already keybound to hiding a window in MacOS.

**Comment by selsta** [comment]
⌃H works, I'll update it :)

**Comment by AdamSiddique** [comment]
Okay thanks, i'll just close the issue.

**Comment by selsta** [comment]
#3815

thanks
