### ISSUE TITLE
[Bug] Can't Use Wallet in Stagenet or Testnet on Windows

### ISSUE THREAD

**Issue by elibroftw** [monero-project/monero-gui#3816]
There's no way to open a wallet in Stagenet on Windows

Reproduction steps:
From the advanced wallet menu, select stagenet under network
![image](https://user-images.githubusercontent.com/21298211/149237013-f8f3b03a-0023-48df-aaa0-ec98955e9250.png)
Click "Create new wallet"
Use remote node monero-stagenet.exan.tech:38081
![image](https://user-images.githubusercontent.com/21298211/149237144-7c9558c7-3d32-46fe-9be8-c3af087b7ba4.png)
Network type is Mainnet now???

Opening from file:
![image](https://user-images.githubusercontent.com/21298211/149237221-cdeb1cd5-4223-4400-b017-8f4739e62284.png)

**Comment by rating89us** [comment]
I can't reproduce your issue. Which GUI version are you using?

**Comment by elibroftw** [comment]
I'm using the second latest version. It doesn't matter now because it decided to work. It might have something to do with opening a stagenet wallet already and then creating a stagenet wallet.

Anyways the workaround is just using the CLI.

**Comment by elibroftw** [comment]
I'm closing because the bug is hard to reproduce.

**Comment by rating89us** [comment]
I could reproduce your bug now, please reopen the issue.

**Comment by rating89us** [comment]
1. Select stagenet in advanced options
2. Open a mainnet wallet
3. Return to main menu (stagenet will still be selected in network dropdown)
4. Click on create a new wallet. A stagenet wallet should be created, but wizard is creating a mainnet wallet instead.
