### ISSUE TITLE
GUI Freezes upon canceling wallet password

### ISSUE THREAD

**Issue by riverliway** [monero-project/monero-gui#3835]
The Monero GUI asks for the wallet password every so often. I accidentally clicked cancel and a screen popped up saying "closing wallet" with a little loading circle. The circle then stopped moving and I was unable to interact with the GUI at all. I could not use the minimization, fullscreen, nor close window buttons. I was forced to kill it with task manager. 

My wallet was in the middle of synchronizing, so it is possible that the GUI would have unfrozen when the synchronization completed, but I did not wait for it to complete.

OS: windows x64
GUI version: 0.17.3.1-release (Qt 5.15.2)
Embedded Monero Version: 0.17.3.0-release

**Comment by selsta** [comment]
Yes, it's most likely related to the wallet still syncing. It would close once it finished.

Closing this as there are similar reports about this open.
