### ISSUE TITLE
status shows wrong version

### ISSUE THREAD

**Issue by Addictc** [monero-project/monero-gui#3837]
I installed monero-wallet-gui from monero-gui-linux-x64-v0.17.3.1.tar.bz2 but when running 

>>> status
[12.02.22 17:13] 2022-02-12 16:13:53.706 I Monero 'Oxygen Orion' (v0.17.3.0-release)
Height: 2530439/2557951 (98.9%) on mainnet, not mining, net hash 3.27 GH/s, v14, 12(out)+0(in) connections, uptime 0d 14h 42m 55s

it says v0.17.3.0-release instead of v0.17.3.1

**Comment by selsta** [comment]
That's the daemon version.

See Settings -> Info.
