### ISSUE TITLE
Monero Blockchain download from gui (advanced)

### ISSUE THREAD

**Issue by Kekko93** [monero-project/monero-gui#3847]
Daemon blocks remaining its 357070 this is taking so long for like 3rd day now.. its done 80% atm but its extremely slow , i have 200download , good pc i7 9700k 16gb ram , hdd 2tb but it was some cheap one , im downloading blockchain to that HDD. 

please help , im new to this

**Comment by selsta** [comment]
Can you go to Settings -> Log, enter "status" and post the output here?

**Comment by Kekko93** [comment]
![image](https://user-images.githubusercontent.com/100800917/156439951-193ff5d9-cb74-4499-8eb1-db36de20bbb9.png)

**Comment by selsta** [comment]
So it does sync, it's just slow? It is most likely related to your HDD. An SSD would speed up syncing significantly.

**Comment by Kekko93** [comment]
oh yeah my hdd is kinda slow when im installing games too from steam.. could be

**Comment by Kekko93** [comment]
problem with my ssd is that its too small so i cant download this onto ssd , need to use HDD unfortunately

**Comment by Kekko93** [comment]
![image](https://user-images.githubusercontent.com/100800917/156442086-9623d2f7-5b66-40fc-b84e-013daee365b2.png)

**Comment by Kekko93** [comment]
@selsta you think this is bad?

**Comment by selsta** [comment]
You can enable pruning then the blockchain is only around 40GB.

> @selsta you think this is bad?

I don't know but slow sync with HDDs are normal.

**Comment by Kekko93** [comment]
![image](https://user-images.githubusercontent.com/100800917/156442480-3d8fcb93-b250-43ea-bf6a-14b1cc758c63.png)
ah idk i think il just wait then i just hope it doesnt need 3more days :D

**Comment by selsta** [comment]
Did you manage to sync up?

**Comment by Kekko93** [comment]
yes i did and thanks for answers! , now i have other problems haha  https://github.com/monero-project/monero-gui/issues/3880
