### ISSUE TITLE
Wallet.cpp error on windows build

### ISSUE THREAD

**Issue by reemuru** [monero-project/monero-gui#3848]
This is my mistake. Since this #3828 was my first pull request doesn't look like workflows ever ran to catch this. Will patch today and update my forks to run ci.

<details>
<summary>
logs
</summary>
<code>
 D:/a/monero-gui/monero-gui/src/libwalletqt/Wallet.cpp:859:5: error: 'u_int64_t' was not declared in this scope; did you mean 'uint64_t'?
</code>
<br />
<code>
  859 |     u_int64_t total;
</code>
<br />
<code>
      |     ^~~~~~~~~
</code>
<br />
<code>
      |     uint64_t
</code>
<br/>
<code>
D:/a/monero-gui/monero-gui/src/libwalletqt/Wallet.cpp:860:14: error: expected ';' before 'spent'
</code>
<br/>
<code>
  860 |     u_int64_t spent;
</code>
</details>

**Comment by selsta** [comment]
I opened #3849, let's see if CI is green now.
