### ISSUE TITLE
Daemon failed to start - Linux Mint

### ISSUE THREAD

**Issue by harrwester** [monero-project/monero-gui#3854]
I ran a local node (advanced mode) monero wallet (gui 0.17.3.1-release qt 5.15.2) on linux mint 20.3 cinnamon without issues for several weeks. Today, it suddenly decided not to connect to daemon and showed me "Daemon failed to start" after 120s of trying. I'm very new to crypto stuff in general and have no idea where to begin with this issue, let alone how to fix this. Any suggestions for the rookie?

**Comment by selsta** [comment]
Is the blockchain stored on an external hard drive?

**Comment by harrwester** [comment]
Well, it is on a 1TB HD since I downloaded the blockchain, but waiting for SSD already.

**Comment by selsta** [comment]
It sounds like your blockchain is corrupted, that can happen when you unplug the external hard drive during sync. You will have to delete the blockchain and resync.

Maybe it's best if you wait for the SSD and use a remote node in the meantime.

**Comment by harrwester** [comment]
Yes, probably. I'll wait for SSD and will give a feedback afterwards. Thanks!

**Comment by selsta** [comment]
So basically, once you delete the corrupted database the daemon should start again. I'm closing this, if you continue to have issues in the future please comment and I can reopen.
