### ISSUE TITLE
Bug in Address book when adding entries

### ISSUE THREAD

**Issue by JRB202** [monero-project/monero-gui#3872]
To reproduce :

Install monero gui latest march 2022 version on windows 10

Create a wallet

Create a 1rst entry in Address book with name and XMR address.

Then Add other entries

The bug :

After each add of a new entry (IP and Name)  the name of entry of the first entry (zero index) is overwritten 
with the name of of the last created entry.

Apparently, xmr address is left untouched in the first entry, only the name is lost

**Comment by JRB202** [comment]
Problem still here with V0.17.3.1

**Comment by selsta** [comment]
Thanks for the report, this is already fixed in the codebase. The next release will solve this.
