### ISSUE TITLE
Ledger Nano S Plus support

### ISSUE THREAD

**Issue by AdamSiddique** [monero-project/monero-gui#3877]
The Ledger Nano S Plus does have a Monero Application but is not yet supported by the Monero GUI wallet, choosing the other Ledger wallets results in the device not being detected.

**Comment by selsta** [comment]
Support for it will be added once we release the next CLI / GUI release.

**Comment by AdamSiddique** [comment]
Nice! Thanks for the quick response.

**Comment by mrusme** [comment]
@selsta I was trying to find the related ticket for that but couldn't. Would you mind linking it? I would like to subscribe to that to get notified when this happened. Thank you!

**Comment by selsta** [comment]
@mrusme do you mean https://github.com/monero-project/monero/pull/8239 ?

**Comment by FreddieChopin** [comment]
So the big question remains - is there maybe some rough release schedule? (;

**Comment by selsta** [comment]
hopefully sometime in the next days

**Comment by selsta** [comment]
https://www.getmonero.org/2022/04/29/monero-GUI-0.17.3.2-released.html

**Comment by pchristod** [comment]
I can give quick feedback about this and tell you that it works.
Thanks for the addition!

**Comment by jonathancross** [comment]
@AdamSiddique @FreddieChopin  Have you had a chance to test?

**Comment by FreddieChopin** [comment]
New release works fine with Ledger Nano S Plus.

**Comment by jonathancross** [comment]
> @jonathancross confirm what? multiple people got it working

I just thought it was good to loop back around to the people who had issues.

I now see all the things you've done to help fix problems and answer questions. Thanks @selsta
