### ISSUE TITLE
auto changes all address book descriptions to the last one

### ISSUE THREAD

**Issue by alias-bitsignal** [monero-project/monero-gui#3882]
When creating an address book entry with a description and then adding a 2nd entry with a different address description, the first entry description gets automatically also changed to the 2nd address description.

Macos 12.3
GUI version 0.17.3.1-release (Qt 5.12.8
![test](https://user-images.githubusercontent.com/39199608/162137950-03fbb4bc-5736-4e57-8ee4-db22286523a7.jpg)
)

**Comment by selsta** [comment]
Is already fixed in code and will be included in the next release.
