### ISSUE TITLE
Adding new address book entry corrupts previous entries (bug)

### ISSUE THREAD

**Issue by edisondotme** [monero-project/monero-gui#3886]
I encountered a serious bug with the address book today that cost me $100 in XMR
My steps to reproduce:

1. Have a few entries in the address book (4 in my case)
2. Click "Add address"
3. Fill out address information
4. Monero GUI adds the new entry to the bottom, but OVERWRITES the first address label with the newly created address book entry label while leaving the alphanumeric address intact.

I accidentally sent some XMR to the wrong address this way. Luckily the recipient was contactable and he was nice enough to send it back, but this could have gone much worse!

**Comment by selsta** [comment]
Hello, thank you for the bug report. We have it already fixed in code and it will be included in the next release, which I hope will be released in 2 weeks or so.

**Comment by edisondotme** [comment]
Excellent! Sorry to leave a possible duplicate bug report. Thanks!
