### ISSUE TITLE
Monero Gui not showing funds

### ISSUE THREAD

**Issue by DarkAngel85** [monero-project/monero-gui#3892]
I had funds in my Monero Gui wallet which I had set up with the Ledger Nano S. 

I transferred more funds, but the wallet never updated the amount of XMR in the wallet. I deleted the monero wallet and the Monero files and downloaded the Monero Gui from scratch with the Ledger. The receiving wallet address is exactly the same as before. So it's the same wallet. However it is saying I have zero balance. It is not even showing the funds that were showing up before.

**Comment by selsta** [comment]
What did you set as your restore height?

**Comment by DarkAngel85** [comment]
2396387

**Comment by marlonpnz** [comment]
Same problem here. I notice the "secret view key" is all zeros, like "000000...". I do not know if ledger also protect the private view key, like it does with the spend key. However I suspect it may be related with the fact that the balance is not shown anymore. I have a balance I did transfer some months ago, which was ok at that time. But now is not showing, it is, the balance always show as zero, even after complete synchronization. Any suggestion?

**Comment by selsta** [comment]
@marlonpnz As long as you export the view key everything is fine. The keys don't get displayed by the GUI.

------

Can both of you go to Settings -> Info and post the "wallet mode" and "wallet restore height"?

@DarkAngel85 I know you posted it already but I just want that you confirm what it says on that page.

**Comment by marlonpnz** [comment]
thanks @selsta,
update: it finally worked some minutes ago. I set it up today once more, creating a new hardware wallet in simple mode. After some hours the balance show up. This is weird, once I did this process many times and let it syncing for many hours before. Luckily I was not in a hurry to sell. Don't know what could be the reason.
I will try again in some days, than will check the info page as stated.

**Comment by selsta** [comment]
@marlonpnz I would recommend to setup advanced mode with a remote node.

Simple mode can be a bit spotty because it uses a random remote node :/ Do you need instructions for that?

**Comment by DarkAngel85** [comment]
the wallet mode in my case is: Simple mode and the Wallet restore height: 2396387. Today my original amount is showing up, but still no sign of the rest of the funds I transferred a week ago. 

Yes please, if you suggest Advance mode I would appreciate instructions.

**Comment by selsta** [comment]
You can go to the main menu by clicking on the exit symbol in the top left corner.

Then click on "Change wallet mode" and select "Advanced mode". Afterwards open your wallet again, go to Settings -> Node, select "Remote node" and enter the following node:

address: `88.198.199.23`
port: `18081`

This should resolve your issue for now. No extra hard disk space required.

----------

Other remote node in case the above has issues:

address: `node.supportxmr.com`
port: `18081`

address: `78.47.80.55`
port: `18081`

address: `node.melo.tools`
port: `18081`

**Comment by DarkAngel85** [comment]
Thanks. Am still trying to wait for the wallet to fully load. Will keep you updated once it's sorted out.

**Comment by selsta** [comment]
Do you have the transaction id of the funds that are missing?

**Comment by DarkAngel85** [comment]
I can finally see the funds in my wallet. Thanks for your help! Hope you have a good rest of the week :)

**Comment by DarkAngel85** [comment]
I just tried making a donation to the Monero core team, but the wallet has come up with error 64

**Comment by selsta** [comment]
Can you make a screenshot of this error?

**Comment by selsta** [comment]
@DarkAngel85 did you make sure that you export the Ledger view key on wallet opening? Also did you make sure that your Ledger is unlocked the whole time during transaction creation?

**Comment by DarkAngel85** [comment]
Hi I tried it twice. Once when the Ledger was not connected and another time when it was. The error came up both times. I have closed and reopened the wallet and it has now worked. I sent a small donation to thank you for your help. 

The best thing to do in that situation is for the wallet to give the user feedback to connect the Ledger beforehand so the error does not come up. I'm a UX designer so if the Monero team needs any advice you can ask :)

**Comment by selsta** [comment]
Yes, that definitely has to be improved! Thank you for the donation :)
