### ISSUE TITLE
Bug v0.17.3.2 Generate payment proof button

### ISSUE THREAD

**Issue by tczee36** [monero-project/monero-gui#3909]
Hello found a bug,

Environment

    Windows 11 x64 Virtual Machine in VMware workstation
    Remote node: xmr.support
    Ran monero-gui as admin
    No password key file

How i found the bug:

   - Created a temp wallet in monero-gui v0.17.3.1
   - temp wallet sent a transaction, generated payment proof, works no problem
   - Same temp wallet loaded in v0.17.3.2, tried to generate payment proof, no response.

Not sure why this is happening, already whitelisted v0.17.3.2 in windows defender.

thanks

**Comment by selsta** [comment]
@reemuru could you take a look? :)

**Comment by reemuru** [comment]
confirmed that payment proof button is no longer working from tx list on v0.17.3.2 with the error message below and no response.

```bash
2022-05-05 14:44:21.622 W qrc:/pages/History.qml:1723: Error: Insufficient arguments
```

**Comment by selsta** [comment]
> @selsta could you confirm?

I honestly have no idea, I never use the proof features.

**Comment by reemuru** [comment]
@selsta correct I was able to generate `SpendProof` and `OutProof` (tx proof) from the advanced menu v0.17.3.2.
@westz36 could you try putting tx id and recipient address on the advanced tab for tx proof?

**Comment by westz36** [comment]
@reemuru hihi,

yes, v0.17.3.2 'check transaction' and 'prove transaction' both works for me.

**Comment by reemuru** [comment]
> @reemuru hihi,
> 
> yes, v0.17.3.2 'check transaction' and 'prove transaction' both works for me.

@tczee36 cool, thanks for checking. Apologies for the inconvenience. I tested a patch that will restore the payment proof button on the transaction list. Next version that button should be working again.
