### ISSUE TITLE
Monero GUI suddenly restarts syncing blockchain from block 0

### ISSUE THREAD

**Issue by stefan-reich** [monero-project/monero-gui#3929]
Hi, I have Monero GUI wallet running with a pruned blockchain. After 2 days it was finally done downloading the (pruned) blockchain and ready to use. I did successfully send a transaction too IIRC.

However, another few days later, the wallet suddenly started syncing the blockchain from the very first block again.

I literally didn't do anything to it, it just exhibited this behavior spontaneously.

Obviously, I can't use the wallet in this state, waiting 2 days for it to sync again...

Any idea what may be going on?

Wallet GUI version is 0.17.3.2 on Ubuntu 20 in a LUKS partition.

**Comment by selsta** [comment]
Can you go to Settings -> Info and post the output of "status" ?

**Comment by stefan-reich** [comment]
Hi,

"custom blockchain location" is empty. 

Hm, I don't see "status" in Settings / Info... I see "GUI version", "Embedded Monero version" and some more items...

**Comment by selsta** [comment]
Sorry, I meant Settings -> Log and post the output of "status".

Also did you previously set a custom blockchain location?

**Comment by stefan-reich** [comment]
No, I never changed the blockchain location.

Here is a [screenshot.](https://botcompany.de/images/1103134)

**Comment by selsta** [comment]
The blockchain gets saved into ~/.bitmonero/lmdb/data.mdb

Any idea if that file got somehow deleted? monero and monero-gui don't have any function to delete it.

**Comment by stefan-reich** [comment]
The file is there but small (1 GB). Incidentally, I just noticed the .bitmonero was on the wrong drive (not in the LUKS partition), which is also almost full. So I just moved it there and will let it re-sync. Maybe this was actually the problem (lack of space on the drive). Thank you
