### ISSUE TITLE
Monero Blockchain Downloading Very Slowly

### ISSUE THREAD

**Issue by DavisRee** [monero-project/monero-gui#3937]
I've been synching the entire blockchain for days now.  Per speedtest.net, I have 500MBps download speed available so that is not the issue.  (Would take less than 4 minutes at that speed!)  When I started the synch, it looked like it should take a few hours based on the rate at which the blocks were synching.  I left it for the night and came back the next day with about 60%  of blocks synched, but rate was much slower.  Now a couple more days later, I checked the actual file size and it is at about 78GB and changing by less than 100KBps and making corresponding progress on blocks (maybe a few blocks per second with over 600,000 to go).

**Comment by selsta** [comment]
Syncing is not the same as just downloading a file. It also verifies all the cryptography which is the slow part.

To speed sync up try the following:

- Use an SSD instead of HDD
- Make sure to use the latest version v0.17.3.2

Closing as this is a question and not a big report.
