### ISSUE TITLE
Drop-down menus not opening on Manjaro (KDE)

### ISSUE THREAD

**Issue by SandaruKasa** [monero-project/monero-gui#3938]
I'm running Manjaro Linux x86_64 with Plasma 5.24.5 and kwin-bismuth tiling extension 3.1.1 (though, I don't think Bismuth is relevant here, because the issue persists even when I turn the tiling off).

I've installed monero-gui 0.17.3.2-1 via pacman and the dropdown menus in it don't seem to be working. When I click on one, nothing happens. Such menus include, for example, the network selection (mainnet/stagenet/testnet) during wallet setup or transaction priority in the "Send" tab of the app.

**Comment by SandaruKasa** [comment]
Tried building from source instead, same issue.

**Comment by selsta** [comment]
Can you try the getmonero.org binary for testing purposes?

**Comment by SandaruKasa** [comment]
Okay, tried it, it works properly

**Comment by selsta** [comment]
Similar report: https://github.com/monero-project/monero-gui/issues/3152

**Comment by devhyper** [comment]
I get this issue when compiling from source, but when compiling statically with docker it works fine.

**Comment by selsta** [comment]
I always assumed it's related to how arch package manager compiles Qt.

**Comment by devhyper** [comment]
I'm on Fedora, so it might be related to their packaging too.

**Comment by selsta** [comment]
@devhyper do you use KDE on fedora?

**Comment by devhyper** [comment]
> @devhyper do you use KDE on fedora?

Yes.

**Comment by dginovker** [comment]
Another data point - 

```
Kubuntu 22.04 LTS x86_64 
DE: Plasma 5.24.4 
WM: KWin 
Theme: Breeze Light [Plasma], Breeze [GTK2/3]
Install Method: Flatpak
```

Dropdowns don't work and a lot of text fields are just white - including my address and my mnemonic when I created the wallet.

![image](https://user-images.githubusercontent.com/32943174/173290533-af6286b1-1ec8-4bbf-83db-92ab0d304621.png)

*****

The Flatpak install works perfectly fine on the below system:

```
Xubuntu 21.10 x86_64 
DE: Xfce 
WM: Xfwm4 
Chicago95 [GTK2], Greybird [GTK3]
Install Method: Flatpak
```

**Comment by BigmenPixel0** [comment]
I can confirm. The problem occurs in the flatpak version and from the repository in archlinux. (but the official binary works fine)

**Comment by IModThings** [comment]
Can confirm this is still an issue.

**Comment by damianchoc** [comment]
tested now on Manjaro with KDE and it still doesn't work

**Comment by aminordistraction** [comment]
Can confirm this issue with EndeavourOS KDE. Only works with sudo

**Comment by selsta** [comment]
Can someone compile monero-gui with Qt installed using https://github.com/engnr/qt-downloader instead of from package manager?

**Comment by SandaruKasa** [comment]
> Can someone compile monero-gui with Qt installed using https://github.com/engnr/qt-downloader instead of from package manager?

I'd love to try, but as an effort to help Ukrainian civilians (I guess), qt.io doesn't allow downloading anything from a Russian IP address.

I've tried using VPN, but that qt-downloader thing gave me an error anyways. Although this time it looks like a qt-downloader bug and not a byproduct of war:
```
$ ./qt-downloader/qt-downloader linux desktop 5.15.6
OS type: linux
Target: desktop
Qt version: 5.15.6
Discovering available toolchains...b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n</body></html>\n'
 Done
  Choose from: 
```

**Comment by selsta** [comment]
@SandaruKasa try 5.15.2, Qt does not offer prebuilt binaries for newer 5.15 versions.

**Comment by SandaruKasa** [comment]
> @SandaruKasa try 5.15.2, Qt does not offer prebuilt binaries for newer 5.15 versions.

It works. I have to `LD_LIBRARY_PATH=~/qt/5.15.2/gcc_64/lib/ ./monero-wallet-gui`, but drop-down menus work just fine.

**Comment by selsta** [comment]
As I suspected here: https://github.com/monero-project/monero-gui/issues/3938#issuecomment-1149561913

Don't really know how to continue here, since it seems to be an issue with how Qt gets compiled when installing from package manger. Not sure if they add custom patches on top.

**Comment by SandaruKasa** [comment]
Well, since the static binary seems to work without any problems, I've added it to AUR: https://aur.archlinux.org/packages/monero-gui-static-bin

Hope it'll help Arch/Manjaro/etc. users out there.

**Comment by IModThings** [comment]
Bumping this issue. I would rather not use the AUR workaround

**Comment by jkhsjdhjs** [comment]
The following line is logged for me 71 times if I run `monero-wallet-gui` from the command line:

    2022-11-25 14:39:49.174 W Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.

This doesn't happen with the downloaded qt version (I used the same method described in https://github.com/monero-project/monero-gui/issues/3938#issuecomment-1266765352).
I'm using Arch Linux, but maybe this also happens on other distros where the dropdowns don't work.

**Comment by devhyper** [comment]
I found a workaround, to disable KDE's theming of monero-gui:

1. Install `qt5ct`
2. run monero-gui-wallet with `QT_QPA_PLATFORMTHEME=qt5ct`

**Comment by jkhsjdhjs** [comment]
Works perfectly, thank you so much for this! The `recursive rearrange` warnings are still shown on startup, so it's possible they aren't related to this issue.

**Comment by RootInit** [comment]
But... what if we don't want to change theme. Running it with that as an argument did nothing.

**Comment by selsta** [comment]
It's a QML application. We don't support any themes and I have no idea what exactly these KDE themes are supposed to change.

**Comment by selsta** [comment]
@RootInit did you do

```
QT_QPA_PLATFORMTHEME=qt5ct monero-wallet-gui
```

It seems to have worked for the other user.

**Comment by RootInit** [comment]
@selsta No I did `monero-wallet-gui QT_QPA_PLATFORMTHEME=qt5ct`

Did work the proper way. I guess I will use that workaround.

**Comment by Mart-Bogdan** [comment]
> Dropdowns don't work and a lot of text fields are just white - including my address and my mnemonic when I created the wallet.

I've solved issue with white textboxes, by swithcing wallet to white theme.

But no luck with dropdowns.

**Comment by Mart-Bogdan** [comment]
Indeed `QT_QPA_PLATFORMTHEME=qt5ct` helps.

so I've basically changed my `monero-gui.desktop` to following, and it works.

```ini
[Desktop Entry]
...
Exec=env QMLSCENE_DEVICE=softwarecontext QT_QPA_PLATFORMTHEME=qt5ct monero-wallet-gui %u
```
I'm using QMLSCENE_DEVICE to disable fancy effects like blur, becouse:
1. Reduce VRAM usage
2. increase startup time
3. Blured window still leaks some personal information. 

But first 2 are more important for me.

This aren't related to this issue.


Now comes the question, how we should proceed? can we make some workaround insied monero GUI to detect/reject nonstandard QT themes?
Or we should just ping distros maintainers to fix the desktop file with workaround? ( as I understand problem is not only on Manjaro)

**Comment by jkhsjdhjs** [comment]
[Antonio Rojas recommended](https://bugs.archlinux.org/task/72489#comment213161) to report this issue to KDE, which is what I did: https://bugs.kde.org/show_bug.cgi?id=462293

**Comment by jkhsjdhjs** [comment]
Can a dev put together a simple testcase that can be run with `qmlscene` and illustrates the issue? That would really help the KDE devs locate the issue! Thanks in advance!
https://bugs.kde.org/show_bug.cgi?id=462293#c3

**Comment by devhyper** [comment]
#4091 will fix this, an alternative workaround that does not require qt5ct is to use the env var `QT_QUICK_CONTROLS_STYLE=desktop`

**Comment by Mart-Bogdan** [comment]
> #4091 will fix this, an alternative workaround that does not require qt5ct is to use the env var `QT_QUICK_CONTROLS_STYLE=desktop`

Wuld this be actual fix? If it sets "desktop", but correct fix them is `qt5ct`

**Comment by Mart-Bogdan** [comment]
yeah. it works. thanks)))))) would wait for PR

**Comment by Rikj000** [comment]
Please re-open this issue as it still occurs on Manjaro Linux to this day.

### Work Around
1. Install `qt5ct` through `pamac`
2. Alter the `Exec` entry in `/usr/share/applications/monero-gui.desktop` as following:
    ```properties
    Exec=QT_QPA_PLATFORMTHEME=qt5ct monero-wallet-gui %u
    ```

**Comment by selsta** [comment]
@Rikj000 The issue has been fixed in code so we closed the issue. You have to wait for the next release.

**Comment by Rikj000** [comment]
> @Rikj000 The issue has been fixed in code so we closed the issue. You have to wait for the next release.

Thank you @selsta, happy too hear that!   
I've altered my comment accordingly :slightly_smiling_face:
