### ISSUE TITLE
Monero GUI Wallet not displaying balance

### ISSUE THREAD

**Issue by RonnyBlack1978** [monero-project/monero-gui#3939]
I am a bit of a newbie to this.

Having checked other threads on here, I am running Windows 10 (64-bit - clean with no malware) and am using the Monero GUI Wallet (V.0.17.3.2). When using the wallet I disable my VPN and anti-virus software.

I have transferred Monero (XMR) from Binance to my GUI Wallet (advanced). The main address is correct and I can see the transaction on XMRchain.net. The GUI wallet displays as correctly syncing and connecting. However, the balance does not update.

I have tried:

Uninstalling and reinstalling the GUI Wallet. Changing the wallet restore height to an earlier number. Using several remote nodes that try to connect but unfortunately disconnect straight away. Changing the wallet file name (the one without an extension) to perform a refresh.

Nothing seems to work. The only thing that appears strange is that every time I check the log status it shows 0 (Out) and 0 (In) connections.

Does anyone have any suggestions? I would greatly appreciate some help.

Thanks.

**Comment by selsta** [comment]
https://github.com/monero-project/monero-gui/issues/3912#issuecomment-1119632082

Can you do these steps to set Advanced mode with a remote node?

Also can you post the transaction id of the transaction that is missing and can you go to Settings -> Info and post the output of "Wallet restore height".

**Comment by RonnyBlack1978** [comment]
Thanks for your response.

Advanced mode with remote node address: 88.198.199.23 and port: 18081 stays disconnected on the network status (bottom left) after 5 minutes.  I restarted the GUI wallet - same thing.

The transaction ID is: 433e52038b2bf96209da34d3a650eb61f18602a8ea74da718a6948273d4a220d

and the Wallet restore height: 2637979

Thanks.

**Comment by selsta** [comment]
Is this transaction id that you posted the first transaction that you received?

Can you go to Settings -> Info and click on "(Change)" and then enter 2500000 and then ok twice?

Then wait for it to resync.

**Comment by RonnyBlack1978** [comment]
Yes, first transaction.

I have tried:

address: node.supportxmr.com
port: 18081

address: 78.47.80.55
port: 18081

address: node.community.rino.io
port: 18081

None of them connect.  It always displays Network Status as being disconnected in the bottom left corner.

**Comment by selsta** [comment]
Did you change random settings around? E.g. Settings -> Interface did you enable socks5 proxy?

**Comment by RonnyBlack1978** [comment]
If I change to 2500000 but am disconnected on any of those remote nodes, will that change anything?

I will try now.

**Comment by RonnyBlack1978** [comment]
No changes made to any settings. Default installation with a new wallet created and advanced mode selected.

**Comment by selsta** [comment]
You have to be connected to a node first before anything works. All these nodes are online so the issue is somewhere on your own end, we just have to figure it out.

**Comment by selsta** [comment]
Can you open

88.198.199.23:18081/get_info

in your browser and see if it loade?

**Comment by RonnyBlack1978** [comment]
Agreed.  

88.198.199.23:18081/get_info loads fine.

My internet is running fine and my VPN and anti-virus software are both definitely off.

**Comment by selsta** [comment]
Settings -> Interface: the enable socks5 proxy setting has to be disabled.

Can you check for that?

**Comment by RonnyBlack1978** [comment]
Yes, that is disabled.

**Comment by selsta** [comment]
What kind of anti virus and VPN are you using?

**Comment by RonnyBlack1978** [comment]
Bitdefender Total Security and NordVPN.  I have permanently disabled the Bitdefender AntiVirus Shield and completely quit NordVPN.

**Comment by RonnyBlack1978** [comment]
Hang on, just checked Bitdefender and the firewall is blocking the GUI Wallet.  Let me see if  I can connect to a remote node now.

**Comment by RonnyBlack1978** [comment]
I had disabled Bitdefender but didn't realise the firewall was still on.  It was blocking the Monero GUI Wallet.

Balance now updated!

Thank you very much for your help.

 I really appreciate it.

**Comment by selsta** [comment]
Glad it's resolved. If the remote nodes makes issues in the future you can choose a different one from the linked comment.
