### ISSUE TITLE
Official Build for M1 Macs and ARM

### ISSUE THREAD

**Issue by boskovicbalsa** [monero-project/monero-gui#3940]
Hi, we need official M1 Mac ARM support. Current version can be compiled on M1 and it works but it has a lot of bugs, like minimize  and quit not working (stuck on not responding) and it just crashes sometimes. Why we ask for M1 official version? It is faster about  40-50% syncing with network and overall better experience. Thank you.

**Comment by selsta** [comment]
The next CLI release will come with M1 binaries.

For the GUI there are still some issues that we have to figure out.

**Comment by selsta** [comment]
Duplicate #3495

**Comment by boskovicbalsa** [comment]
Ok, thank you. It is important that u work on it and it is planned for release 👍
