### ISSUE TITLE
Error: Electrum-style word list failed verification

### ISSUE THREAD

**Issue by Russia9** [monero-project/monero-gui#3945]
Monero GUI/CLI Version: `Monero 'Oxygen Orion' (v0.17.3.2-release)`
I have 25-word recovery key that contains the word `stacking` from file https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h.
I assume the problem is that the word `stacking` is not in BIP-39. How can I convert my recovery phrase to access the wallet?

**Comment by Russia9** [comment]
Monero GUI, English

**Comment by selsta** [comment]
When did you create this seed?

**Comment by selsta** [comment]
> I assume the problem is that the word stacking is not in BIP-39.

Also what do you mean with that exactly? If you have a seed that was generated by monero-gui you don't have to convert anything.

**Comment by Russia9** [comment]
If I try to use this seed in monero-gui or monero-cli, I get this error:
![image](https://user-images.githubusercontent.com/33428293/173125360-3602bda8-a247-4fda-8f36-2c2745f556c1.png)

**Comment by selsta** [comment]
Did you find all 25 words in this list? https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h

**Comment by Russia9** [comment]
Sorry, my bad, there was a typo in one word

**Comment by warrenc5** [comment]
> Did you find all 25 words in this list? https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h

Seems like a manual task that would be vulnerable to human error.
Why not just get the computer to do that for you? 
Right there in the editor/cmdline. Even get it to show you the words that are missing?

For those that don't program in C or have severe dyslexia use the following command 

> tr -s '[:space:]' '\n' < mykey.txt | sort | join -v1 -j1 - bip39.txt

[bip39.txt](https://github.com/user-attachments/files/24146497/bip39.txt)

with a little effort you can use aspell

> aspell --personal=./bip39.dict check mykey.txt

I also believe that it's only the first 4 chars that represent the word (something to do with UTF-8, bytes and big integer data types I presume)
