### ISSUE TITLE
Payment proof issue

### ISSUE THREAD

**Issue by rikanox** [monero-project/monero-gui#3951]
I try to receive payment proof on Monero 0.17.3.2-release (Qt 5.15.3) in advanced mode (Remote node), portable. I use Monero on Whonix Xfce. I see "P" button. But nothing happens when I click on this button.

![alt text](https://i.ibb.co/VDV9vnV/o.jpg)

**Comment by reemuru** [comment]
It is fixed by #3910. See issue #3909 for info. For now you can use "advanced" tab to prove and verify tx.

**Comment by selsta** [comment]
Closing as this is resolved in code. Use the workaround from the previous comment.
