### ISSUE TITLE
Monero GUI showing zero balance issue

### ISSUE THREAD

**Issue by purpleskie5** [monero-project/monero-gui#3961]
Would appreciate any help here:

I made a withdraw yesterday from the exchange to my MoneroGUI, I first had an issue with connecting to a node but that was solved after connecting to a remote one.

But the issue is it's not showing any transactions and the balance is zero.
I double checked the address before and after I made the withdrawal and it's the same.

I recently changed the wallet block to 1940000 as someone suggested but that still didn't work, I tried previous blocks as well but it's still not showing.

I also went to the tool where you can check if the transaction succeeded and entered the Tx Id, Private view key and Primary address. I then got an error saying "View Key doesn't match your address".
So I tried searching the MoneroBlocks and entered the Tx ID and it showed me a transaction but neither the inputs or outputs belong to me.

I'm also not using Trezor or a Ledger wallet,  The only thing I could think would be out of the box is that at the beginning I forgot my wallet's password and had to restore it using the seeds and noticed a new wallet was added (or the same one) with different seeds and with the new name I entered.

Soon after, I remembered the password for the first one so I thought why keep the new one and proceeded in deleting it.
I don't think it had something to do with this but again I'm new to this and could be wrong.

**Comment by selsta** [comment]
As a first step, please go to Settings -> Info and post

- Version
- Wallet restore height
- Wallet mode

**Comment by purpleskie5** [comment]
It's resolved right now, The issue was with the address.
I don't know if I'm the only one who faced this but there is an obvious glitch in the GUI address based on what I've experienced.

For some reason when you click on copy the primary address and paste it, a totally different address appears, even when you double click and paste it.

I checked this before making the transaction and thought that Monero or Kraken decodes your address into another one since it is a stealth address crypto and proceeded with the withdraw.

It is not until I made another wallet and tried to register the address to make a withdraw that an error message appeared and said it was already registered.
Turns out you have to manually copy the address with the cursor and leave the last character out then adding it later, to give the same address that is showing in the GUI.

The fault also lies with me for not probably researching more about this, Is there a way you can retrieve funds sent to another address (maybe not even registered?)

**Comment by selsta** [comment]
Which operating system are you using? Could it be that you have malware on your system? The address should never change after pasting.

**Comment by purpleskie5** [comment]
I'm using windows 11, I'm not running any anti-virus only windows security.
Even though I'm copying the correct one right now it's showing me a different one, it could be a malware.
What do you recommend to do?

**Comment by purpleskie5** [comment]
I searched it, It is a malware, Other people have reported it.

**Comment by purpleskie5** [comment]
I tried to locate the path and found a folder with these commands:

Retrying to obtain clipboard.
Detected recursive rearrange. Aborting after two iterations.
Retrying to obtain clipboard.
Retrying to obtain clipboard.
Unable to obtain clipboard.

That's the one right?

**Comment by purpleskie5** [comment]
Will do, Thanks for the advice and everything.
I will figure out how to download Ubuntu and install a new operating system as soon as I can.
At least I won't lose the lesson
Thanks again.

**Comment by Tribe78** [comment]
Hi, I have a similar issue.
I copy and pasted the address I wanted to send funds to. I didn't check it properly and sent funds. I assumed it changed the address for security.
The funds are gone and never arrived.
There is a red circle next to the transaction and says sent to "unknown recipient".
Any advice if its gone, or can recover?

**Comment by selsta** [comment]
@Tribe78 what do you mean with "it changed the address"? Can you elaborate? Do you have a transaction id?

**Comment by Tribe78** [comment]
I copied the address from where I wanted to send the funds, and pasted the address into Monero and sent the funds.
The funds never arrived at destination. I have rescanned, changed to larger block height. Opened new wallets and used keys and seed to restored. I cant seem to get them back. So paranoid I have lost them. 
There is a red dot next to the sent transaction. So Im hoping it didnt arrive and its recoverable.
Here is the transaction ID.
b0bdf05fe733fcc16fcc077de562e8de48ff8db44c0c78ce2206996217c1d1e7

**Comment by selsta** [comment]
Just to clarify, do you own the wallet that should have received it?

**Comment by Tribe78** [comment]
No I don’t own the wallet it went to.

**Comment by selsta** [comment]
How can you be sure that the issue isn't on the receiving side?

Also which operating system are you using? Is it possible that there is address changing malware installed, e.g. Windows?

**Comment by Tribe78** [comment]
I don’t know if problem is on other side.
I am on a Mac. I have scanned my computer for malware. Monero always shows up as effected. But no malware. 

I was wondering if it was malware as well.

**Comment by selsta** [comment]
Did you try to reach out to the receiver with the transaction id?

**Comment by Tribe78** [comment]
How do I do that?
The transaction ID is different to the address for the address I tried to send to?
Is there a way to contact the owner of the ID?

**Comment by selsta** [comment]
I don't know who you sent it to. If it was an exchange contact their support, if it was a website try to send an email.

> The transaction ID is different to the address for the address I tried to send to?

Yes. The transaction ID is the identification of the transaction itself, the address is where the transaction ID is getting sent to.

> Is there a way to contact the owner of the ID?

Not in monero directly. You have to manually reach out to the person, e.g. by email, support chat or whatever.
