### ISSUE TITLE
Failed to connect the aemon on Android

### ISSUE THREAD

**Issue by hmsjy2017** [monero-project/monero-gui#3963]
I successfully built an Android APK of monero-gui, but there are some errors.
![Screenshot_20220709_141103_org qtproject example monero_wallet_gui](https://user-images.githubusercontent.com/42692274/178094137-5b47a5da-28f5-4efe-85f3-085d3643a9d9.jpg)

In addition, could you tell me how to customize the package name and icon?

**Comment by selsta** [comment]
Not sure if local monerod is supported yet on Android. You can set a custom remote node?

**Comment by hmsjy2017** [comment]
Even if I chose a simple mode, it still cannot work normally.

https://user-images.githubusercontent.com/42692274/180104190-b44647a2-d4a4-48d3-abfd-7dc20a60f8c2.mp4

**Comment by selsta** [comment]
You have to manually connect to a remote node with advanced mode, not simple mode.

**Comment by hmsjy2017** [comment]
It works. Thank you!

**Comment by selsta** [comment]
Regarding package name and icon - I don't know and unfortunately don't have an Android phone so it's not something I will look into soon.
