### ISSUE TITLE
Error building from source for windows

### ISSUE THREAD

**Issue by ronnkling** [monero-project/monero-gui#3977]
I'm trying to build from source and having an issue.

I have never had msys on this machine before so it is clean install.

The first thing is following the directions the step

Exit the MSYS shell using Alt+F4

Edit the properties for the MSYS2 Shell shortcut changing "msys2_shell.bat" to "msys2_shell.cmd -mingw64" for 64-bit builds or "msys2_shell.cmd -mingw32" for 32-bit builds

is incorrect now, there is no msys2_shell.bat in the shortcut

so I bring up the 64 bit window

![image](https://user-images.githubusercontent.com/2185334/180187215-d7f8c6cf-44ea-42a2-b957-a864a5153dd2.png)

and I do the following commands
pacman -Syu
pacman -S mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-unbound

used the git cmd window to clone monero

then in the msys window I did 

cd monero

make release-static-win64

and get this error

$ make release-static-win64
/bin/sh: line 1: git: command not found
mkdir -p build/"MINGW64_NT-10.0-19044/"/release
cd build/"MINGW64_NT-10.0-19044/"/release && cmake -G "MSYS Makefiles" -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=Release -D BUILD_TAG="win-x64" -D CMAKE_TOOLCHAIN_FILE=../../../../cmake/64-bit-toolchain.cmake -D MSYS2_FOLDER=C:/msys64/ ../../../.. && make
CMake Warning:
  Ignoring extra path from command line:

   "../../../.."

CMake Error: The source directory "C:/msys64/home/klingr" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [Makefile:155: release-static-win64] Error 1
mkdir

**Comment by selsta** [comment]
> used the git cmd window to clone monero

Why? You have to use the `mingw64` shell for the whole process.

**Comment by ronnkling** [comment]
I get an unrecognized command if I do that

**Comment by selsta** [comment]
Try also to install `mingw-w64-x86_64-tools-git` and then post the full log.

**Comment by ronnkling** [comment]
$ pacman -S  mingw-w64-x86_64-tools-git
warning: mingw-w64-x86_64-tools-git-10.0.0.r54.gb4116e310-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-tools-git-10.0.0.r54.gb4116e310-1

Total Installed Size:  0.98 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-tools-git      [#####################] 100%

klingr@Kronos4 MINGW64 ~
$ cd monero/

klingr@Kronos4 MINGW64 ~/monero
$ make release-statc-win64
/bin/sh: line 1: git: command not found
make: *** No rule to make target 'release-statc-win64'.  Stop.

This is really strange, the log does a reinstall I get the same error

**Comment by selsta** [comment]
Something is wrong with your msys2 / mingw64 environment. if you install git you also should have git as an available command.

**Comment by ronnkling** [comment]
I was able to fix this using pacman -S git

**Comment by selsta** [comment]
Is this issue resolved now? Does monero build?

**Comment by ronnkling** [comment]
yes it does
