### ISSUE TITLE
Submodules not being initialized for Apple M1 CPUs

### ISSUE THREAD

**Issue by garth-xmr** [monero-project/monero-gui#3979]
If I `git clone --recursive https://github.com/monero-project/monero-gui.git` it works fine.

But if I omit the `--recursive` flag and instead run `git submodule init && git submodule update` in the main directory after simply cloning the repo (non-recursively) it only pulls in two of the submodules (external/quirc and monero), and not the entire set.

Is this a real issue or should I close this?

**Comment by selsta** [comment]
It's just how git works. You can use

```
git submodule update --init --recursive
```

to do everything in one command.

**Comment by garth-xmr** [comment]
Ok good to know
