### ISSUE TITLE
can not create a new hardware wallet with nano x

### ISSUE THREAD

**Issue by flomagic** [monero-project/monero-gui#3981]
Keep getting message: failed to generate new wallet, monero ledger app doesnt support current monero version, try to update the monero ledger app, at least 1.6.0 is required.

Nano X app version 1.7.8
Windows 64 bit installer Fluorine Fermi, version 0.18.0.0

**Comment by selsta** [comment]
Please continue to use the older version (v0.17.3.2) for now until Ledger releases an update.

**Comment by selsta** [comment]
If I don't forget I can comment here once they put out an update. It will be in time before the network upgrade.

**Comment by flomagic** [comment]
ok sounds good
