### ISSUE TITLE
Impossible to create an HW wallet with monero GUI 

### ISSUE THREAD

**Issue by BeginningRace1270** [monero-project/monero-gui#3982]
Monero Ledger App v: 1.7.8
Monero GUI Wallet v: 0.18.0.0 - Fluorine Fermi

As the image shows, I can't create a wallet.
All the apps updated.

What could be the problem?

![sasd](https://user-images.githubusercontent.com/99705939/180700207-4f5f07b0-2c68-4887-8a33-32895cbd4c3b.png)

**Comment by dembarthe** [comment]
Hi, same issue here. Latest Ledger App, doesn't work neither on Windows Bare-Metal nor on Linux Virtual Machine (though I can use the Ledger Live App, so not an issue on connection but same error message).

**Comment by selsta** [comment]
Please see https://github.com/monero-project/monero/issues/8461#issuecomment-1193374955

There will be a second release to support Ledger. In the meantime please use v0.17.3.2.
