### ISSUE TITLE
Splash Screen showing Oxygen Orion not Fluorine Fermi 

### ISSUE THREAD

**Issue by BitVenturesUSA** [monero-project/monero-gui#3984]
![Screenshot 2022-07-25 120341](https://user-images.githubusercontent.com/80940451/180834590-a99b70e7-ab6a-4fdf-9125-4a428c2b4c69.png)

Downloaded 2x from https://www.getmonero.org/downloads/#gui
monero-gui-install-win-x64-v0.18.0.0.exe
SHA-256 matches: A42EA47F6CC128E428ED115B0496D5D9817542DCF29807C2B674E518864418B5

**Comment by selsta** [comment]
Thank you for the report, will be fixed in the next release.
