### ISSUE TITLE
Monero GUI wallet + Ledger

### ISSUE THREAD

**Issue by raivotorim** [monero-project/monero-gui#3986]
Hi, cannot open GUI wallet:

"Monero Ledger App doesnt support current monero version. Try to update the Monero Ledger App, at least 1.6.0 is required."

Actual version is 1.7.8

How this can be fixed?

**Comment by selsta** [comment]
Please see https://github.com/monero-project/monero/issues/8461#issuecomment-1193374955

There will be a second release to support Ledger. In the meantime please use v0.17.3.2.
