### ISSUE TITLE
Couldn't open wallet v0.18

### ISSUE THREAD

**Issue by Petr-Mi** [monero-project/monero-gui#4002]
I get error **_Couldn't open wallet: failed to read file "C:\Users\...keys"_** from v0.18+
In version 0.17.3.2 it's OK.

I try v0.18.0.0 and v0.18.1.0 now. Both give this error.

**Comment by selsta** [comment]
Can you make a screenshot? Can you post the file size of your wallet and your wallet.keys file?

**Comment by Petr-Mi** [comment]
@selsta 
The problem is in the diacritics in name of user.
Wallet has 3,11 MB, keys has 1,54 kB

![Monero v0 18 1 0](https://user-images.githubusercontent.com/81816858/184241516-fce1f1b3-7ad6-4ead-a682-988212245586.png)
[monero-wallet-gui.log](https://github.com/monero-project/monero-gui/files/9312118/monero-wallet-gui.log)

**Comment by selsta** [comment]
Can you reproduce the same behavior with monereo-wallet-cli ?

**Comment by Petr-Mi** [comment]
CLI (monero-wallet-cli.exe) cannot find wallet.

![image](https://user-images.githubusercontent.com/81816858/184300418-98e207ba-e056-4b90-a320-0d206688051c.png)

![image](https://user-images.githubusercontent.com/81816858/184300459-44f4dea0-c93c-41e1-b5c6-534d0ecedd3a.png)

**Comment by Petr-Mi** [comment]
CLI v0.17.3.2 also don't work. GUI v0.17.3.2  work.

**Comment by selsta** [comment]
Did you start it like this? `monero-wallet.cli.exe --wallet-file C:\path\to\wallet.keys`

**Comment by Petr-Mi** [comment]
The same issue with diacritics in path. If I moved *.keys to folder without diacritics then Monero CLI work.
I had to use quotes in the path.

![image](https://user-images.githubusercontent.com/81816858/184594798-f16d755d-e39c-457f-886f-9299b9af68b8.png)

**Comment by AlennGK** [comment]
Moving my *.keys to the path without diactritics solved the same error. Díky.

**Comment by selsta** [comment]
I don't think this is anything we have touched in a long time that's why I'm surprised that this errors on v0.18 and works on v0.17

**Comment by selsta** [comment]
We found the issue and it will be fixed in the next release.

**Comment by selsta** [comment]
Fixed in v0.18.1.1
