### ISSUE TITLE
"Unknown Error"

### ISSUE THREAD

**Issue by JamesAngelX** [monero-project/monero-gui#4005]
I updated my Wallet yesterday to the newest version, but since the update my Wallet cant connect to the network anymore.
'Unknown Error" appears, and Log-files are clean.

Also exchanger like Fixedfloat, Binance etc. dont support XMR payouts atm. Can anyone help?

**Comment by selsta** [comment]
Can you make a screenshot of your issue?

**Comment by f2ph7z02sdb** [comment]
Simple mode?

**Comment by selsta** [comment]
Closing as there was no reply.
