### ISSUE TITLE
Funds Lost from CEX to Private Wallet

### ISSUE THREAD

**Issue by pjbukem** [monero-project/monero-gui#4007]
Hi there, I transferred some XMR from a CEX to my primary receiving address and it has failed to show up. CEX has told me it's not their problem and that I should try to contact the receiving platform. Apologies if this is not the right place, but I can't see how the transfer could have gone wrong as the receiving address matches up with my account. Any suggestions as to what might have gone wrong would be greatly appreciated. Happy to provide more details about transaction if it helps.

**Comment by selsta** [comment]
Can you go to Settings -> Info and say which

- Version
- Wallet mode

you have?

**Comment by pjbukem** [comment]
It's 0.18.1.0-release (Qt 5.12.8)

Advanced mode (Remote node)

**Comment by selsta** [comment]
Which remote node did you set? What block height are you on in the bottom left corner?

**Comment by pjbukem** [comment]
The remote node was uwillrunanodesoon.moneroworld.com, but recently switched to http://209.97.185.45:18089. I believe the block height is 2688925 but I'm not sure what it was at the time.

**Comment by selsta** [comment]
Please use a remote node from here: https://github.com/monero-project/monero-gui/issues/3989#issuecomment-1214412781

The blockheight has to be the same as on xmrchain.net, it seems your remote node wasn't updated for v0.18

**Comment by pjbukem** [comment]
Fantastic, it worked! Thanks for your help, really appreciated.
