### ISSUE TITLE
Lost $500 in MAINNET "Monero" PLEASE HELP !

### ISSUE THREAD

**Issue by b4sh1t1** [monero-project/monero-gui#4008]
Hello,

Yesterday I transferred a "completed" transaction from Incognito to mymonero wallet "Android" and the Incognito confirmed to me the transaction has been successfully completed and in my monero wallet "Android" + "iOS" + Monero GUI doesn't show me the balance.

The transaction show me it's confirmed a day ago (Yestarday) and i didn't see the balance or funds any where, mobile or monero GUI.. can somebody help me in this ??

Please, this is urgent upfront of my project and I need it urgently.

Thanks for your help!

**Comment by selsta** [comment]
What is Incognito? Inside Monero GUI, can you go to Settings -> Info and post

- Version
- Wallet mode

**Comment by b4sh1t1** [comment]
Hi @selsta 

I'm using Incognito Wallet (Android) and it has work fine with me to transfer to other wallets with no issue, even i have transfer before to this wallet .. but not sure was Incognito wallet or MyMonero wallet i use that time, but now i have download Monero GUI and try using remote note to check the balance... still not completed.. 

https://ibb.co/55G4y4F

if there any recommended remote node plz advice.

Version: "0.18.1.0-release (Qt 5.15.5)". 
Wallet Mode: Advanced mode (Remote node)".

**Comment by selsta** [comment]
What did you set as your wallet restore height? You don't have to sync from height 0.

**Comment by b4sh1t1** [comment]
The Incognito has nothing wrong with them, they transaction has been completed like others i have did before with no issue, but the problem in monero since i don't see the amount there.. that's all

I didn't set anything, should i put 0 height ? or something else..

**Comment by selsta** [comment]
Transaction has been completed does not mean much if it is completed on the wrong chain.

You can put in a date that was before you first used monero.

If you first used Monero in March 2021 you can enter: `2021-03-01`

Make sure to use this exact format. Then you skip all the blocks before this date.

**Comment by b4sh1t1** [comment]
I did that on july, and now it's finished sync ..i find my funds.. thanks alot @selsta ! your my hero today).

**Comment by selsta** [comment]
Great :) Hopefully MyMonero is able to update in the next days. Otherwise use MoneroGUI, Cake Wallet, Monerujo for now.

Closing this solved.
