### ISSUE TITLE
The money didn't come!

### ISSUE THREAD

**Issue by VikingBe** [monero-project/monero-gui#4010]
Monero was transferred to me. On the monerhash.com website, the confirmation is visible, but the coins are not reflected in the application.
Wallet checked. The wallet is correct.
I restarted the app and then updated it. Despite all my efforts, the money is not reflected.

**Comment by selsta** [comment]
Please go to Settings -> Info and post

- Version
- Wallet node

**Comment by VikingBe** [comment]
0.18.1.0-unknown (Qt 5.15.5)
Advanced mode (Remote node)

**Comment by VikingBe** [comment]
Now stands http://sf.xmr.support. I dislike him. But this all happened before I installed it. Before that, after the release of the application, it connected automatically and quickly. After I didn't see the money, I installed the node.
I don't see the height

**Comment by VikingBe** [comment]
Sorry, I don't speak English well. Do you trust cake wallet? I installed it on my phone and I'm trying to log in from it.

**Comment by selsta** [comment]
<img width="301" alt="123" src="https://user-images.githubusercontent.com/7697454/185689773-008259ac-130b-43fa-b5c6-c93081241e71.png">

Does it look like this in the bottom left corner? If yes, please go to Settings -> Wallet, click on "Scan transaction" and enter the transaction id of the missing transaction.

**Comment by VikingBe** [comment]
The top bar is still filling up. And the bottom is filled, but does not display the numbers

**Comment by selsta** [comment]
Wait for the top bar to fill up.

**Comment by VikingBe** [comment]
Everything appeared, thanks for giving me the time.

**Comment by selsta** [comment]
Glad to hear, closing this as resolved. And yes, you can also try out Cake Wallet.
