### ISSUE TITLE
I used the monero gui, my balance is not displayed and my transaction history is missing. 

### ISSUE THREAD

**Issue by web26082022** [monero-project/monero-gui#4016]
I used the monero gui, my balance is not displayed and my transaction history is missing. The balance is positive and today there is an incoming transaction, I have its hash and the balance was not zero even before this transaction. Nothing was deleted. Help please. Thanks.

**Comment by selsta** [comment]
Please go to Settings -> Info and post

- Version
- Wallet mode
- Wallet restore height

**Comment by web26082022** [comment]
GUI version: 0.18.1.0-release (Qt 5.12.8)
Embedded Monero version: 0.18.1.0-release
Wallet restore height: 2598683
Wallet mode: Advanced mode (Local node)
Graphics mode: OpenGL

**Comment by selsta** [comment]
When was the first time you received a transaction into this wallet? Approximately?

**Comment by web26082022** [comment]
A few months ago. There were several transactions. Here, for example, is the hash of today's transaction:
f3d35982d23c9a3879c4eb8a60be840030cdcfcc770140dc0b03457849620fd6

**Comment by selsta** [comment]
So if you go to Transactions tab it shows not a single transaction? It's not clear from your description.

**Comment by web26082022** [comment]
That's right, all transactions have disappeared and the balance is zero.

**Comment by selsta** [comment]
Can you go to Settings -> Log, type "status" into the textbox and post the output here?

Afterwards go to Settings -> Info, click on "(Change)" next to wallet restore height and then ok twice. Wait for it to resync, this might take a while.

**Comment by web26082022** [comment]
[26.08.2022 4:41] 2022-08-25 20:41:18.521 I Monero 'Fluorine Fermi' (v0.18.1.0-release)
Error: Couldn't connect to daemon: 127.0.0.1:18081
[26.08.2022 4:41] 2022-08-25 20:41:33.127 I Monero 'Fluorine Fermi' (v0.18.1.0-release)
Height: 1178299, target: 1178299 (100%)
Downloading at 0 kB/s
Next needed pruning seed: 8
1 peers
Remote Host Peer_ID State Prune_Seed Height DL kB/s, Queued Blocks / MB
212.33.255.208:18080 0000000000000000 before_handshake 0 0 0 kB/s, 0 blocks / 0 MB queued
0 spans, 0 MB
[]

**Comment by selsta** [comment]
Your node isn't synced.

**Comment by web26082022** [comment]
"Info, click on "(Change)" next to wallet restore height and then ok twice. Wait for it to resync, this might take a while"
-- I do not see such a button and opportunity, I only display the information that I have already sent to you

**Comment by selsta** [comment]
Your local node isn't synced. You either have to get it synced with the network first or you have to use a remote node.

**Comment by web26082022** [comment]
Yes, I found it, it's done  "(Change)" .

**Comment by selsta** [comment]
You need a synced node first before you can rescan your wallet.

Go to Settings -> Node, select Remote node and then add one from this list: https://nodes.monero.com

Or alternatively you can wait for your local node to sync.

**Comment by web26082022** [comment]
How to use a remote node? Since it's been more than 12 hours such a trial?

**Comment by web26082022** [comment]
I will try to log into another node. Thanks for the help.

**Comment by web26082022** [comment]
This is how the login and password of the node are requested, but I did not find such information

**Comment by selsta** [comment]
you don't have to enter login / password

just address and port (the number)

for example address: xmr.fail port: 18081

**Comment by web26082022** [comment]
Synchronization is going on a new node, I will wait for the result. Thanks again for your help.

**Comment by web26082022** [comment]
[26.08.2022 4:41] 2022-08-25 20:41:18.521 I Monero 'Fluorine Fermi' (v0.18.1.0-release)
Error: Couldn't connect to daemon: 127.0.0.1:18081
[26.08.2022 4:41] 2022-08-25 20:41:33.127 I Monero 'Fluorine Fermi' (v0.18.1.0-release)
Height: 1178299, target: 1178299 (100%)
Downloading at 0 kB/s
Next needed pruning seed: 8
1 peers
Remote Host Peer_ID State Prune_Seed Height DL kB/s, Queued Blocks / MB
212.33.255.208:18080 0000000000000000 before_handshake 0 0 0 kB/s, 0 blocks / 0 MB queued
0 spans, 0 MB
[]
[26.08.2022 5:11] 2022-08-25 21:11:26.621 I Monero 'Fluorine Fermi' (v0.18.1.0-release)
Stop signal sent
[26.08.2022 5:11] 2022-08-25 21:11:31.301 I Monero 'Fluorine Fermi' (v0.18.1.0-release)
Error: Couldn't connect to daemon: 127.0.0.1:18081

**Comment by web26082022** [comment]
There is no speed change

**Comment by selsta** [comment]
Settings -> Log is not relevant if you have a remote node set.

**Comment by web26082022** [comment]
I'll have to wait until he downloads all the blocks, as I understand? Tell me approximately the weight and how long will it take?

**Comment by selsta** [comment]
What does it say in the bottom left corner? How many blocks remaining?

**Comment by web26082022** [comment]
Problem has been solved, the data has been updated, the balance is in place and the transaction history has been restored. Thanks for the help.

**Comment by DaniDumitrache** [comment]
> Can you go to Settings -> Log, type "status" into the textbox and post the output here?
> 
> Afterwards go to Settings -> Info, click on "(Change)" next to wallet restore height and then ok twice. Wait for it to resync, this might take a while.

[06/01/2025 15:31] 2025-01-06 13:30:59.637 I Monero 'Fluorine Fermi' (v0.18.3.4-release) 
Height: 3319388/3319388 (100.0%) on mainnet, not mining, net hash 3.42 GH/s, v16, 12(out)+0(in) connections, uptime 0d 0h 23m 33s
