### ISSUE TITLE
xmr purchase not showing in wallet

### ISSUE THREAD

**Issue by danx42** [monero-project/monero-gui#4019]
I made a purchase on Monero Local. The transaction was sent successfully but is not showing in my monero wallet (GUI). I have verified the transaction on xmrchain.net. Have triggered wallet refresh but still nothing. Any help would be really appreciated!

**Comment by cnxnhcv** [comment]
I have the same problem although I'm 100% I sent the xmr, however, downloaded the latest version, now the new version keeps saying couldn't open the wallet file,

**Comment by selsta** [comment]
@danx42 @cnxnhcv Can both of you go to Settings -> Info and post

- Version
- Wallet mode
- Wallet restore height

then I can give further instructions.

**Comment by cnxnhcv** [comment]
> @danx42 @cnxnhcv Can both of you go to Settings -> Info and post
> 
> * Version
> * Wallet mode
> * Wallet restore height
> 
> then I can give further instructions.

Thanks for the fast replay,

Im atm using the latest version (0.18.1.0)
wallet mode: I normally use simple mode, however, Im trying Advanced mode (Local node) at the moment 
Wallet restore height (228705)

Noteworthy, I was using a really old version something around 0.13, it was going fine with me so I didnt want to upgrade - which is dumb from my side-,, Also the old version opens my wallet file with no issue but the new version keeps saying it can not do that until I change the file path, but unfortunately it shows the balance without the added xmr.

thanks for your time

**Comment by cnxnhcv** [comment]
>>> status
[01/09/2022 05:21] 2022-09-01 01:21:07.619 I Monero 'Fluorine Fermi' (v0.18.1.0-release) 
Height: 1351204/2702027 (50.0%) on mainnet, not mining, net hash 115.86 MH/s, v5, 10(out)+0(in) connections, uptime 0d 4h 18m 33s

**Comment by cnxnhcv** [comment]
wow!
It actually worked, my issue was I was connected to a dead old node probably, updated my node and the xmr showed up.

I am really really grateful, for you to have the time to answer noobs like me, the Brightside I found this website where I can learn more about xmr.

wish you all the best,

**Comment by danx42** [comment]
> Your node is only 50% synchronised. You can either wait for it to go to 100% (which can take between 12h and multiple days depending on your hardware) or you can set a remote node.
> 
> You can set a remote node in Settings -> Node -> Remote node. https://nodes.monero.com has a list of remote nodes.
