### ISSUE TITLE
monerod fails to start when installed as windows service on startup

### ISSUE THREAD

**Issue by zubair72** [monero-project/monero-gui#4023]
Steps to reproduce error

1. Run command as administrator
2. Switch to path where monerod.exe is located
3. type monerod --install-service
4. After successfull message if you did run the monero wallet gui and then closed the service then you can start the service else it fails
5. Please note it will fail to start automatically on windows startup but if one logins and run the monero-gui-wallet afterwards you may stop the daemon when from gui or when closing the wallet and able to start the daemon service without issue

Note: if prior to starting service you run the monerod from cmd line it again fix the service start issue

Please have look into this

**Comment by selsta** [comment]
What is `monerod --install-service` ? I don't think this is anything we support. Or is this a Windows feature?

**Comment by selsta** [comment]
Can you reproduce this issue without monero-wallet-gui being involved?

**Comment by zubair72** [comment]
Issue appears if monero-wallet-gui is not run, it does not appear if you run monero-wallet-gui prior to doing steps upto 4, similarly if you run monerod from elevated command line prior to doing 4 steps, issue again does not appear

**Comment by selsta** [comment]
If this issue also appears without running monero-wallet-gui then please open an issue here instead: https://github.com/monero-project/monero

**Comment by zubair72** [comment]
done as advised to and create new issue at [https](https://github.com/monero-project/monero)

**Comment by selsta** [comment]
https://github.com/monero-project/monero/issues/8560
