### ISSUE TITLE
Allow local monerod server when using Socks5 proxy

### ISSUE THREAD

**Issue by zquestz** [monero-project/monero-gui#4027]
Currently there is no way to connect to a local monerod instance and have all other connections go over the Socks5 proxy. When the Socks5 proxy is set, you lose connection to your local node. Many users will want to make sure price discovery is happening over Tor, and that is not currently possible when connecting to your own local monerod instance.

![image](https://user-images.githubusercontent.com/83898/189452150-8fbb116a-0093-4273-88c8-e5831e61e4d5.png)

Ideally we can add a check box that allows it to bypass the proxy for local connections.

![image](https://user-images.githubusercontent.com/83898/189452455-28574380-b814-4e10-bcd7-b38404825738.png)

I wouldn't mind looking into adding it, as long as that is something that would be accepted.

**Comment by plowsof** [comment]
Confirmed issue:
- ./monerod
- point wallet at localhost:18081 (connected)
- enable socks5 proxy 
- note the disconnection from localnode
`Some problems at connect, message: Socks request rejected or failed`

**Comment by selsta** [comment]
This does work by selecting "Local node" inside Settings -> Node with socks5 proxy enabled.

**Comment by plowsof** [comment]
Confirmed this fixes the problem, thanks!
