### ISSUE TITLE
Sent XMR to GUI WALLET, balance shows 0

### ISSUE THREAD

**Issue by gregus79** [monero-project/monero-gui#4029]
I ve sent XMR from Kraken to Gui wallet primary account address.
My balance shows 0.
My network status is disconnected.
Can someone help? am new on the monero blockchain

**Comment by selsta** [comment]
Please go to Settings -> Info and post

- Version
- Wallet mode
- Wallet restore height

**Comment by gregus79** [comment]
Version 0.18.1.0 release
wallet mode   advanced mode
wallet restore height 2690998

**Comment by selsta** [comment]
Does it say Advanced mode (Local node) or (Remote node)?

**Comment by gregus79** [comment]
local node

**Comment by selsta** [comment]
Did you sync up a local node?

**Comment by gregus79** [comment]
nope

**Comment by selsta** [comment]
You either have to sync a local node or connect to a remote node, see for example nodes.monero.com

**Comment by gregus79** [comment]
any reliable node to connect to?

**Comment by selsta** [comment]
Look on https://nodes.monero.com for example. I don't have any specific recommendations.

**Comment by gregus79** [comment]
ok I am now synchronised to remote node

**Comment by selsta** [comment]
Do you have a transaction id?

What does it say in the bottom left corner? Is the wallet synchronized? It can take a bit with a remote node.

**Comment by gregus79** [comment]
432cca45b16540d33fb89ee328e55ed5434abec0a6532158b2f81d1bbd5fc21b

It says wallet is synchronised, Daemon is synchronised, artwork status is remote node

**Comment by gregus79** [comment]
OK its now showing balance
I had to scan transaction in settings

**Comment by selsta** [comment]
Ok, if you are connected to a proper node this should not happen again.
