### ISSUE TITLE
Fee estimate not updating

### ISSUE THREAD

**Issue by plowsof** [monero-project/monero-gui#4032]
Reported by reddit user Br0kenRabbitTV. On the pre-send screen, there is a fee estimate which does not update when you scroll through slow/fast/fastest. (it displays correctly on the confirmation screen) But they state this was not always the case... 

[fee-estimate.webm](https://user-images.githubusercontent.com/77655812/190929069-b5ad25e0-51fd-4d4d-9171-5083a85772ef.webm)

Is this true? should the value here update? did it ever update? or is this a feature request?

**Comment by selsta** [comment]
https://github.com/monero-project/monero/blob/master/src/wallet/api/wallet.cpp#L1767 does not take the priority into account.

**Comment by selsta** [comment]
https://github.com/monero-project/monero/pull/8610
