### ISSUE TITLE
Monero not an option to add as account in Ledger Nano X - please help!!

### ISSUE THREAD

**Issue by novocals** [monero-project/monero-gui#4035]
The only option I get is Wrapped Monero.  Can someone please tell me what I am doing wrong? 

![image](https://user-images.githubusercontent.com/114088718/191536955-ba6518b0-cbeb-4fcf-a803-052db5d9ed56.png)

![image](https://user-images.githubusercontent.com/114088718/191537309-c6be642c-14ac-451d-ad7f-61434f48f78d.png)

**Comment by selsta** [comment]
Ledger Live itself does not support monero, you have to use a dedicated monero wallet in combination with Ledger, see getmonero.org
