### ISSUE TITLE
XMR did not come to my wallet

### ISSUE THREAD

**Issue by 1Maestro** [monero-project/monero-gui#4037]
I bought some XMR with bitcoin via ChangeNow.io and they claim everything went succesfull and the funds should have arrived in my wallet but i cant see any funds or transactions have been made and i am still a beginner in the crypto space so i dont really understand how this would happen when the adress and everything was correct

**Comment by selsta** [comment]
Can you go to Settings -> Info and post:

- Version
- Wallet mode
- Wallet restore height

Do you also have a transaction id?

**Comment by 1Maestro** [comment]
Wallet mode is: Simple mode (bootstrap)
Version is: 0.17.3.1-release (Qt 5.15.2)
Wallet restore height :2716307 this one i changed becuase i thought thats what they meant with "resynchronize the blocks from [2716307]"
i dont know what the transaction id would be but i asked the support to send me one so ill post it shortly!

**Comment by selsta** [comment]
As a first step you have to update to v0.18, the there was a network upgrade.

Afterwards I would recommend to set a custom remote node.

**Comment by 1Maestro** [comment]
https://changenow.io/exchange/txs/3ae8382e41ca2f here is the transaction ID i think? and i updated the wallet to 0.18 but i dont now how to change to a custom remote node

**Comment by selsta** [comment]
You can follow the steps here to change to a custom remote node: https://github.com/monero-project/monero-gui/issues/3989#issuecomment-1214412781

**Comment by 1Maestro** [comment]
Done

**Comment by 1Maestro** [comment]
wow it fixed it! Thanks alot!!!!!<3333
