### ISSUE TITLE
T

### ISSUE THREAD

**Issue by novocals** [monero-project/monero-gui#4038]
Trying to create a GUI wallet following a video (https://www.youtube.com/watch?v=kAHcZvFo4_I&t=41s) and getting the error in the screenshot.  Please help!  What am I doing wrong??

![image](https://user-images.githubusercontent.com/114088718/191802355-29089804-090a-4185-8be2-d39dc0daf4d3.png)

**Comment by selsta** [comment]
Which OS are you using? How did you connect your Ledger?

**Comment by novocals** [comment]
At 0:35 seconds of the video, he says he just searches the catalog for Monero, but when I search, I do not have an option for Monero.  How do I get it as an option?  Wonder why he didn't address there is more to it.

**Comment by novocals** [comment]
Windows.  Connected with USB cord.

**Comment by selsta** [comment]
- Do you have the latest Ledger Live version?
- The latest Ledger firmware installed and the latest monero app?
- Ledger unlocked and monero app opened?
- Anti virus disabled

**Comment by novocals** [comment]
Trying to figure out how to update my ledger nano x.

**Comment by selsta** [comment]
Any update?
