### ISSUE TITLE
Monero GUI does not update after transaction

### ISSUE THREAD

**Issue by Lowlay75** [monero-project/monero-gui#4052]
Hello, I think the problem has already been encountered. I made a transaction on local monero and it never reached my wallet. I performed a "Wallet restore height" and I put the current date (20221021).
But now I have 0.000000 XMR instead of 0.500000 before.
I should have several hundred currency. I would really like your help....

**Comment by Lowlay75** [comment]
I would like to add that the transaction is effective here is the ID :  6ef284989deb62f9edc3cd2bdc26e0394dd2841fb9fdaebfdf1182005f292302

**Comment by selsta** [comment]
You have to enter a date in this format: YYYY-MM-DD not YYYYMMDD

And you have to enter a date that was before your first received transaction, not the current date.

**Comment by Lowlay75** [comment]
Thank you for your help, I did exactly what you told me, it still doesn't work

**Comment by selsta** [comment]
Please post more information, go to Settings -> Info and post:

- Version
- Wallet mode
- Wallet restore height

**Comment by Lowlay75** [comment]
yes, i already do that

**Comment by selsta** [comment]
You did not. I only see that you posted a transaction id, no version, no wallet mode and no wallet restore height.

**Comment by Lowlay75** [comment]
oh, my bad I misunderstand. 

Version : 0.17.3.2-release
Wallet mode : Simple mode
Wallet Restore height : 2713588

**Comment by selsta** [comment]
The problem is that you are using v0.17, monero had a network upgrade and you have to use v0.18.

**Comment by Lowlay75** [comment]
Thanks !
Can you explain me how can i update it ?
I'm on Linux

**Comment by selsta** [comment]
It depends on how you installed it in the first place. Did you download it from the website or using a package manager?

Does the GUI ask you to update on startup?

**Comment by Lowlay75** [comment]
The GUI don't ask to me for an update.
I use a virtual machine and GUI was already here and I already suspect the version to be bad, so i download on the website and now i have just a files called monero-wallet-gui but i can't open it

**Comment by selsta** [comment]
Try to double click on the .appimage file, and if that doesn't work start monero-wallet-gui from the command line.

**Comment by Lowlay75** [comment]
should i uninstall my actual monero gui ?

**Comment by selsta** [comment]
Delete the old version and download the new version.

**Comment by selsta** [comment]
Closing this since there is no bug report here. If you continue to have issues you can comment.

**Comment by Lowlay75** [comment]
Hello again, 
I would like to thank you foir your help

so during the night, I update Monero GUI on my VM.
Now i have : 
Version : 0.18.1.2-release 
Wallet mode : Simple mode
Wallet Restore height : 2631268

And i have a new feature called "Scan transaction" but i can't use it

**Comment by Lowlay75** [comment]
And my transaction of yesterday has not arrived yet

**Comment by Lowlay75** [comment]
I found my funds before I changed height wallet, but the transaction of yesterday is not on my wallet

**Comment by Lowlay75** [comment]
I got all my funds back thanks to the update

Thank you for your help !!
