### ISSUE TITLE
Virustotal analysis

### ISSUE THREAD

**Issue by RonaldBolado** [monero-project/monero-gui#4067]
https://www.virustotal.com/gui/file/c5dbf3e8fca7341dea1194e57b22f233ceb9471aca8692da6ffd0b4bc3a54a1b

>monero-gui-install-win-x64-v0.18.1.2.exe 

Whats up with all these positives?

**Comment by selsta** [comment]
Some AV flag the built in miner as malware or potentially unwanted software, nothing we can do on our side.

**Comment by selsta** [comment]
https://www.getmonero.org/get-started/faq/#antivirus
