### ISSUE TITLE
[UX] If User tries to open a stagenet wallet, let them

### ISSUE THREAD

**Issue by elibroftw** [monero-project/monero-gui#4069]
Suppose I open up the GUI and now select a wallet from the file. I know the wallet is a stagenet file, but when I try unlocking it, Monero hits me with the you can't open this in the mainnet wallet. 

Tell the user to switch it from the previous page or add an option to make it easier to switch the network from the unlock page itself.

**Comment by plowsof** [comment]
Confirmed:
on the 'gui' screen with wallet file icons in the default folder, selecting a wallet from a different network works fine, you can go back and forth no problem.
the issue is when you specifically click on "browse file system" and select the wallet from here - then you see the old error
