### ISSUE TITLE
failed to deserialize keys buffer

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-gui#4086]
https://old.reddit.com/r/monerosupport/comments/zpz5zs/keys_file_cant_restore_couldnt_open_wallet/

this is the second instance I've seen of this. Old monero users getting new software and running into this with old wallet files.

and if there's 2 people that post something, that means there's millions!

**Comment by selsta** [comment]
This should be opened here, there's no specific GUI code for opening keys:

https://github.com/monero-project/monero/issues

**Comment by Gingeropolous** [comment]
ok

**Comment by Gingeropolous** [comment]
for reference

https://github.com/monero-project/monero/issues/8684
