### ISSUE TITLE
Monero GUI no longer working after Tails 5.8 upgrade 

### ISSUE THREAD

**Issue by psoidon** [monero-project/monero-gui#4087]
Monero GUI was working prior to Tails upgrade.
After upgrade it no longer starts, I believe this is an issue due to Weyland change in Tails 5.8
Unable to access wallet :-(

**Comment by nahuhh** [comment]
https://gitlab.tails.boum.org/tails/tails/-/issues/19326

**Comment by tobtoht** [comment]
Workaround:

Open `monero-wallet-gui.AppImage` in a text editor and change it to:

    QT_QPA_PLATFORM=xcb ./monero-wallet-gui

Save the file and run it like normal.

**Comment by psoidon** [comment]
Awesome, that worked, many thanks.

**Comment by selsta** [comment]
This should be fixed on Tails side.
