### ISSUE TITLE
Monero wallet  loss of all funds.

### ISSUE THREAD

**Issue by vlc823** [monero-project/monero-gui#4094]
was not syncing, I tried to put restore height to the date 2022-12-15  I went from all my monero now it shows none. it will not connect, I am scared, please help

**Comment by selsta** [comment]
Please go to Settings -> Info and post

- Version
- Wallet mode
- Wallet restore height

**Comment by SChernykh** [comment]
Your monero is not gone, you need to fix your connection to the node you use and restore from height 0.

**Comment by selsta** [comment]
No reply from issue creator.
