### ISSUE TITLE
Ubuntu and Windows actions not completing

### ISSUE THREAD

**Issue by brg2** [monero-project/monero-gui#4100]
Ubuntu just needs qt5-default replaced with qtchooser, qt5-qmake and qtbase5-dev-tools (I have a fix [here](https://github.com/monero-project/monero-gui/pull/4099))
Not sure what windows needs but it halts at obj_epee:
![image](https://user-images.githubusercontent.com/760126/211624545-e5018519-c6b6-42de-a445-e138f9934e85.png)

**Comment by selsta** [comment]
Ubuntu will be solved by #4079 and Windows will be solved by https://github.com/monero-project/monero/pull/8683

**Comment by selsta** [comment]
Resolved in #4120
