### ISSUE TITLE
Must I register Monero GUI Desktop entry?

### ISSUE THREAD

**Issue by ch9PcB** [monero-project/monero-gui#4101]
Relevant details:

Debian 11.6, 64-bit updated with latest security fixes
LXQt minimal desktop
Monero GUI wallet is monero-gui-linux-x64-v0.18.1.2.tar.bz2

After extracting monero-gui-linux-x64-v0.18.1.2.tar.bz2 and creating the corresponding application launcher, I launched Monero GUI and the first question was:

"Would you like to register Monero GUI Desktop entry?" (see attached screenshot)
![Register Monero GUI Desktop entry (15 01 2022)](https://user-images.githubusercontent.com/24192216/212594447-b17e4555-9e43-4c8d-94fa-0bcc8626d834.png)

If I answered "Yes", what are the consequences?

If I clicked "No", what are the consequences?

**Comment by selsta** [comment]
See https://wiki.archlinux.org/title/desktop_entries

If you accept it a shortcut is added to your application menu. If you deny it nothing happens.

**Comment by ch9PcB** [comment]
@selsta

Thanks.
