### ISSUE TITLE
Offset is larger than total outputs when creating viewwallet for stagenet wallet

### ISSUE THREAD

**Issue by elibroftw** [monero-project/monero-gui#4106]
To reproduce create a stagenet wallet, and click create view wallet.

![image](https://user-images.githubusercontent.com/21298211/213600529-94d25159-7962-458e-93d8-84058968b624.png)

Creating a view wallet a second time results in this error.

![image](https://user-images.githubusercontent.com/21298211/213600558-852fb94b-5dad-4786-9750-9520bcb9cada.png)

**Comment by selsta** [comment]
Solved by https://github.com/monero-project/monero/pull/8616
