### ISSUE TITLE
Please make the password entry field have focus

### ISSUE THREAD

**Issue by MikeRich88** [monero-project/monero-gui#4114]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/7113073/216235883-e7d68213-b46e-426e-b20c-21e3cffe8f42.png">

I keep seeing this screen and the password field is not selected. Being the only field on the screen, most users will assume that it is selected.

Therefore I type my entire password in and press enter and nothing happens. I do this very quickly. It is muscle memory.

Then I look at the screen and nothing's happened. I have to click in the field, and type it again.

It's a very minor thing but making the field selected would improve quality of life.

**Comment by plowsof** [comment]
Im on linux/ubuntu right now, and when i launch the gui the text box is in focus already. what OS are you on? `focus: true` would be the fix but i cant reproduce at the moment

**Comment by selsta** [comment]
You have to provide steps to reproduce and your OS. This also doesn't happen on my system.

**Comment by selsta** [comment]
No reply from issue creator.

**Comment by MikeRich88** [comment]
It looks like this was fixed even though I didn't provide the extra info.

**Comment by MikeRich88** [comment]
The issue is not fixed, reopened as #4114
