### ISSUE TITLE
Pick a more common open source license to dual-license the project under and ease adoption

### ISSUE THREAD

**Issue by chris00001** [monero-project/monero-gui#4115]
The current license complicates getting it into Debian and hundreds of downstream distributions. While I'm not seeing anything particularly problematic with the license itself (I don't think anyway)  the fragmentation of licenses (each project having a different unique license) makes inclusion into distributions difficult. Debian is generally the ideal distribution to get software into as most mainstream distributions and desktop-oriented distributions geared toward users that need greater privacy or security are derived from it. Tails for instance is a small however very popular distribution focused on privacy and Tor (it's very much connected to the Tor project). It is derived from Debian. While Tails developers and users want to include Monero GUI they can't easily do so right now. The first thing they need is it packaged for Debian, but it can't be packaged for Debian (or not for the core repo anyway) until after there is an acceptable license. An acceptable license is basically something that has been reviewed and thus with Monero GUI being a unique license even if open source it's not made its way into Debian or Tails. Selecting one of the other licenses to dual-license the software under would really help achieve the aim of easing adoption and increasing the adoption of Monero.

There are a list of licenses in Debian's main repository that would be ideal to pick from:

https://www.debian.org/legal/licenses/

**Comment by selsta** [comment]
Monero uses https://opensource.org/licenses/BSD-3-Clause which is linked on the debian page.

**Comment by chris00001** [comment]
Yes, but it's this program, monero-gui that I'm referring to that uses some custom license, not the BSD 3-Clause license: https://github.com/monero-project/monero-gui/blob/master/LICENSE

**Comment by selsta** [comment]
Can you be more precise? monero-gui does not use a custom license. It uses the exact license I linked, BSD 3-Clause.

The only difference is that we have "All rights reserved." which is used in some places and not in others, see for example: https://joinup.ec.europa.eu/licence/bsd-3-clause-new-or-revised-license

**Comment by chris00001** [comment]
How did you come to that conclusion? The license file doesn't say anything about the BSD 3-Clause license. I just linked to the license for the monero-gui source which includes a license file that says: Copyright (c) 2014-2018, The Monero Project

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Parts of the project are originally copyright (c) 2012-2013 The Cryptonote
developer

**Comment by selsta** [comment]
I'm not sure if you are trolling at this point, in case you are not here is a different example project that uses 3-Clause BSD: https://github.com/openthread/openthread/blob/main/LICENSE
