### ISSUE TITLE
Outdated Readme Copy Right

### ISSUE THREAD

**Issue by itsMikeLowrey** [monero-project/monero-gui#4129]
I updated my gui wallet and I noticed that the copyright read me was outdated. The relevant file is [here](https://github.com/monero-project/monero-gui/blob/064c145aa8dc68d28ac8b4aa04ae8b4dbad2e2ce/installers/windows/ReadMe.htm). I noticed that this issue is in around 10ish files in this repo. I would gladly make a pr that fixes this htm file issue and the other issues if that would be helpful and desired.

**Comment by selsta** [comment]
The year isn't too important, but if you open a PR I'm fine with merging it.
