### ISSUE TITLE
Wallets created in monero-wallet-gui don't open in monero-wallet-cli and vice versa

### ISSUE THREAD

**Issue by PeculiarProductions** [monero-project/monero-gui#4141]
I'm using archlinux and have tried the bleeding edge packages(always using `monero-wallet-cli` and `monero-wallet-gui` from the same repo to confirm same version plus higher likelihood of compatibility) from arch community repo, building monero-gui from source, and using binaries from getmonero.org. 
When I create a wallet using `monero-wallet-cli`, I'm unable to open that wallet in `monero-wallet-gui` on archlinux(but can open it on other operating systems after sending the wallet over).
When I create a wallet using `monero-wallet-gui`, I'm unable to open that wallet in both `monero-wallet-cli` on archlinux or with 'monero-wallet-cli' on any other operating system.
I always leave the password blank or copy-paste it in (after various attempts of typing the correct password).

The error that appears in cli when I try to enter password is: "Error: failed to load wallet: invalid password" The error that appears in gui when I try to enter password is: "Couldn't open wallet: invalid password"
the gui also gives the following in terminal when I run `monero-wallet-gui` via a terminal:

```
W Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
W Logging to "/home/user/.bitmonero/monero-wallet-gui.log"
W file:///usr/lib/qt/qml/QtQuick/Controls/ApplicationWindow.qml:259:9: QML ContentItem: Binding loop detected for property "implicitWidth"
W qrc:/wizard/WizardWalletInput.qml:112: TypeError: Cannot read property 'btnPrev' of undefined
W qrc:/wizard/WizardWalletInput.qml:111: TypeError: Cannot read property 'btnPrev' of undefined
W qrc:/wizard/WizardWalletInput.qml:112: TypeError: Cannot read property 'btnPrev' of undefined
W qrc:/wizard/WizardWalletInput.qml:111: TypeError: Cannot read property 'btnPrev' of undefined
W WARNING: no majority of DNS TXT records matched (only 2/7)
E portable_storage: wrong binary format - signature mismatch
E !r. THROW EXCEPTION: error::invalid_password
E Error opening wallet: invalid password
E Error opening wallet with password:  invalid password```

**Comment by plowsof** [comment]
can't reproduce in manjaro kde 

[arch-screen0.webm](https://user-images.githubusercontent.com/77655812/228526494-0c89b5e0-3d03-44d6-9eaa-6bed602b2d1a.webm)

**Comment by selsta** [comment]
Can you confirm that your KDF value field looks like this?

<img width="401" src="https://user-images.githubusercontent.com/7697454/228534806-bb04f4b4-a66c-4ffb-8a7f-b8d9a493ef2e.png">

Did you try pressing "Ok" with your mouse instead of Return / Enter while password entry?

**Comment by PeculiarProductions** [comment]
> Can you confirm that your KDF value field looks like this?
> 
> <img alt="" width="401" src="https://user-images.githubusercontent.com/7697454/228534806-bb04f4b4-a66c-4ffb-8a7f-b8d9a493ef2e.png">
> 
> Did you try pressing "Ok" with your mouse instead of Return / Enter while password entry?
> 
> Are you creating a hardware wallet?

In all of my attempts to create a wallet, I used either 1024 KDF rounds or used simple mode (and was promptly unable to open the wallet in `monero-wallet-cli`). I believe the set number of KDF rounds may have still been in effect from when it was set in advanced mode.
I just tried advanced mode with 1 KDF round and was able to open open the wallet in `monero-wallet-cli` after its creation in `monero-wallet-gui`. Is this intended behavior? Why can I not open wallets created with 1024 KDF rounds in `monero-wallet-cli after this? Must I set the `--kdf-rounds` argument(after some testing it appears this *does* allow me to open the wallet)? If this is what I must do, would it be best for an update to monero-wallet-cli to automatically detect kdf-rounds to be implemented(or is this not currently possible to implement in a way that doesn't drag down the rest of the application)? 
[Warn When Adjusting KDF Rounds #4076](https://github.com/monero-project/monero-gui/issues/4076) - If there *was* a warning implemented, I certainly didn't see it.

**Comment by plowsof** [comment]
@PeculiarProductions are you kidding me. youve had 2 days of tech support on matrix from 2 people , both of whom have tried to replicate your results and can't. now suddenly you reveal youve changed the number of kdf rounds to 1024. im not going to read the rest of your comment

**Comment by selsta** [comment]
> Is this intended behavior? 

Yes, you need to set the same KDF rounds everywhere you open the wallet.

> would it be best for an update to monero-wallet-cli to automatically detect kdf-rounds to be implemented

How would this work? Try to decrypt with 1, if it fails 2, ...? This wouldn't work. There might be some ways by saving the KDF round value separately but this would reduce security and is not something we are going to implement.
