### ISSUE TITLE
Values input to prove/check remain cached

### ISSUE THREAD

**Issue by luphoria** [monero-project/monero-gui#4148]
I entered a TXID, address, and OutProofV2 to the Check Transaction / Reserve section, verified the transaction, and then fully signed out and deleted the wallet. I created a new wallet without closing the GUI, and I still see all of the values I previously input.
This is a security risk given physical access - especially considering it bypasses the timer to lock the wallet, if someone wants to view the data in there.

**Comment by plowsof** [comment]
Hi, a similar issue was fixed in this pull request https://github.com/monero-project/monero-gui/pull/4078/files , won't be a problem to have these cleared also , thanks for reporting
