### ISSUE TITLE
Balance is wrong

### ISSUE THREAD

**Issue by franny2023** [monero-project/monero-gui#4152]
Hello, i have tried resyncing my wallet but my balance is wrong and does not show my transaction that had been confirmed to be sent through today. Im not sure what to do. I have already reset my wallet with mimic keys and blockheight.

**Comment by selsta** [comment]
Please go to Settings -> Info and share what it says under

- Version
- Wallet restore height
- Wallet mode

**Comment by franny2023** [comment]
version: 0.17.3.2-unknown (Qt 5.15.3)

wallet restore height: 1212345

wallet mode advanced mode (Local node)

**Comment by selsta** [comment]
Update to the latest version. Monero has had a network upgrade half last year.

**Comment by franny2023** [comment]
is there a link for the update or do i have to fresh install. Thank you also for your quick response

**Comment by selsta** [comment]
https://www.getmonero.org/downloads/

**Comment by franny2023** [comment]
do i also have to restart my sync for my wallet? i downloaded it half way through the wallet reset

**Comment by selsta** [comment]
You will have to wait for your local daemon to sync first and then for your wallet to sync.

**Comment by franny2023** [comment]
thnak you the update has solved my problem. Thanks again for your support
