### ISSUE TITLE
Monero GUI Wallet - Unable to switch between wallets - A bug or by design?

### ISSUE THREAD

**Issue by ch9PcB** [monero-project/monero-gui#4166]
Below are the software that I use on my device (Intel 12th generation CPU, 24GB of RAM, 1TB of PCIe NVMe SSD):

```
Debian 11.7.0, 64bit (backported kernel version 6.1.15-1~bpo11+1)
Monero GUI Wallet, 0.18.2.2 - Fluorine Fermi

```
I managed to create a second and third wallet on the same device. Both three wallets -including the first- share the same wallet path. Let's call it `/media/richard/Kolomb/Monero`

Below is the description of the problem that I am facing:

1. Upon launching Monero GUI Wallet, there is a message stating `Please enter password for:` <name of third wallet>. `Please enter password for:` always asks for the latest/most recently created wallet.

2. There is no menu whatsoever to let me choose which wallet I wish to log into. In my case, I have three wallets: the first, second and third.

Is the above scenario a bug or by design?

**Comment by selsta** [comment]
> There is no menu whatsoever to let me choose which wallet I wish to log into. In my case, I have three wallets: the first, second and third.

After opening the GUI you can click on "Cancel" during password entry and you will go back to the main menu. Afterwards you can click on "Open wallet from file". This should show a list of wallets. If you keep them in the default location you can simply select them from the list, if you selected a custom wallet location you have to click on "Browse filesystem" and select the wallet file you want to open.

**Comment by ch9PcB** [comment]
@selsta 

> If you keep them in the default location you can simply select them from the list, 

Just to clarify: the default location of the wallet is /home/<the name of the user of Debian OS>/Monero/wallets, is that correct?

**Comment by selsta** [comment]
Yes. But even if you don't save them in the default location you can click on "Browse filesystem" and select whatever wallet you want to open.

**Comment by ch9PcB** [comment]
@selsta

Thanks for your clarification.

I will close the issue now.
