### ISSUE TITLE
"NO DC" Text

### ISSUE THREAD

**Issue by GitHubUser5672** [monero-project/monero-gui#4179]
So today when i ran the app, i noticed it says NO DC in the upper left corner, everything else works the same just that text won't disappear. What does it even mean?

**Comment by selsta** [comment]
Can you share a screenshot of it?

**Comment by GitHubUser5672** [comment]
![image](https://github.com/monero-project/monero-gui/assets/132058535/095036cb-4c9b-4ce6-8dfa-bdbd6829e95a)

**Comment by selsta** [comment]
https://www.reddit.com/r/godot/comments/lpgyyy/no_dc_in_upper_left_corner/

This is injected by some third party program on your computer, e.g. NVIDIA driver. Not related to Monero GUI.
