### ISSUE TITLE
p2pool isInstalled check confirm latest hashes?

### ISSUE THREAD

**Issue by plowsof** [monero-project/monero-gui#4191]
the Monero GUI will check if a binary called p2pool is in the same dir, if not, it will download the latest version. if the user has an old p2pool binary there, the GUI wont make them update.  I expect the [isInstalled](https://github.com/plowsof/monero-gui/blob/00ca9920dcdacb28e962b8cc1f7414659d3ba907/src/p2pool/P2PoolManager.cpp#L121) function to look something like this:

```C++
bool P2PoolManager::isInstalled()
{
    if (!QFileInfo(m_p2pool).isFile())
    {
        return false;
    }

    QString validHash;

    #ifdef Q_OS_WIN
        validHash = "";
    #elif defined(Q_OS_LINUX)
        validHash = "4aed4abc7a19833a19d599416933f203df49346c67562774a980e0022b1b203f";
    #elif defined(Q_OS_MACOS_AARCH64)
        validHash = "";
    #elif defined(Q_OS_MACOS)
        validHash = "";
    #endif

    QFile file(m_p2pool);
    if (!file.open(QIODevice::ReadOnly))
    {
        return false;
    }

    QCryptographicHash hash(QCryptographicHash::Sha256);
    if (hash.addData(&file))
    {
        QString fileHash = QString::fromUtf8(hash.result().toHex());
        file.close();

        if (fileHash == validHash)
        {
            return true;
        }
    }

    return false;
}
```
this way, anyone who downloads a new version of the Monero GUI and places it in the same dir as before (and does not manually delete the old p2pool binary) will update it. 

If this is valid / intended behaviour then sech would have to list the hashes of the binaries / update those too (each p2pool update) (along with the zip hashes) .. and the verify script would require a small change also.

**Comment by SChernykh** [comment]
New version of the Monero GUI, if you run the installer (at least on Windows), will delete the old p2pool folder, so the new GUI will download new p2pool.

**Comment by plowsof** [comment]
Thanks for the information, i hadn't considered this, closing the none issue now
