### ISSUE TITLE
Grey out empty wallets 

### ISSUE THREAD

**Issue by skyerjoe** [monero-project/monero-gui#4193]
Gui-Version: **0.18.2.2-unknown**
Is there any option to grey out empty wallets when u switch to the menue to open a walllet ? 

best regards

**Comment by selsta** [comment]
This is not possible.

**Comment by skyerjoe** [comment]
Could i delete the wallet on my own in the folder structure ? 
i have a win portable version.

Cause i have a bunch or wallets there all empty and it confuses me. 

best regards

**Comment by selsta** [comment]
Yes, you can open a wallet and if it is empty you can delete the folder. Make sure that you don't delete anything you might need later.

**Comment by skyerjoe** [comment]
I made an copy folder inside the folder location 

Now the Wallets in the open history are gone 

thnx for help
