### ISSUE TITLE
Distribution Question: Is the Flathub version of Monero GUI maintained by you?

### ISSUE THREAD

**Issue by Oymate** [monero-project/monero-gui#4196]
I have come across a version of Monero on flathub.org (a site for application distribution on Linux).
- https://github.com/flathub/org.getmonero.Monero
- https://flathub.org/apps/org.getmonero.Monero
Are these maintained by you? If not, are these trustworthy to install?

**Comment by selsta** [comment]
Currently it is maintained by monero-gui contributor @BigmenPixel0. If it's trustworthy depends on your threat model, though note we do link to it in the README, similar to other package managers: https://github.com/monero-project/monero-gui#installing-the-monero-gui-from-a-package

**Comment by Oymate** [comment]
Thanks linked from README is trustworthy enough. I checked in because it wasn't linked from the website. Would hope to see it linked from the website in the future.
