### ISSUE TITLE
Balance on GUI Walle not updating 

### ISSUE THREAD

**Issue by orte9011** [monero-project/monero-gui#4202]
Transaction ID 
2a65feb14b1c99da0b1caab67210a70e460deef565a1e3c7c52d1706dc3f5baf

GUI
0.18.2.2-unknown (Qt 5.15.8

Wallet mode: Simpled mode 
Wallet Height 2500000

I have tried changing height , renaming wallet name 

Nothing works 

To update the balance with the last transactions , first transaction on this wallet 

Network status shows connected

Please help

**Comment by selsta** [comment]
Try to use advanced mode and set a custom remote node. You can go to the main menu by clicking on the exit symbol in the top left corner.

Then click on "Change wallet mode" and select "Advanced mode". Afterwards open your wallet again, go to Settings -> Node, select "Remote node" and enter the following node:

address: `selsta2.featherwallet.net`
port: `18081`

This should resolve your issue for now. No extra hard disk space required and no issues with monerod not starting.

----------

Other remote node in case the above has issues:

address: `selsta1.featherwallet.net `
port: `18081`

address: `node.community.rino.io`
port: `18081`

More nodes: nodes.monero.com

After that try to change the height again and do a full rescan. If you still have issues afterwards I will give you further steps.

**Comment by orte9011** [comment]
Hi Selsta :

Thanks for your prompt reply. I have tried two different nodes and restarted the wallet changing the size but did not work.
Can you please send me further steps 

![image](https://github.com/monero-project/monero-gui/assets/140928545/48ec57c0-183e-4dd3-8def-af415da7eaa5)

**Comment by orte9011** [comment]
Thanks my balance finally updated

**Comment by orte9011** [comment]
Hi I scan the transactions and I can see the balance but I can't send funds, Are you able to give me a hand? please

**Comment by selsta** [comment]
What happens when you try to send the funds?

**Comment by orte9011** [comment]
I was getting failed , not sure why . But finally I transferred funds successfully.Thanks for your help Sent from my iPhoneOn 30 Jul 2023, at 21:56, selsta ***@***.***> wrote:﻿
What happens when you try to send the funds?

**Comment by selsta** [comment]
Glad to hear that you were able to send your funds. If you continue to have issues please open a new issue.
