### ISSUE TITLE
Opening multiple instances

### ISSUE THREAD

**Issue by MoroccanMalinois** [monero-project/monero-gui#421]
The GUI does not prevent from opening multple instances with the same wallet

**Comment by fresheneesz** [comment]
And why would it? I'm currently doing that to test. If you don't want more than one instance, why are you running the executable more than once?

**Comment by MoroccanMalinois** [comment]
And why would it?

Because it is likely that someone opening the same wallet twice is doing it by mistake.

    why are you running the executable more than once?

To open different wallets

**Comment by fresheneesz** [comment]
If you open a second instance by mistake close it. I would imagine the more likely scenario is that you meant to do it. Until tabs gets implemented https://github.com/monero-project/monero-core/issues/394 opening multiple instances shouldn't be prevented.

**Comment by MoroccanMalinois** [comment]
If you open a second instance by mistake the close it **ffs**.

Thank you so much @fresheneesz. I never thought about it. You saved my day !

    And how do you expect to open 2 different wallets at once without allowing multiple instances?

... multple instances **with the same wallet**

**Comment by dEBRUYNE-1** [comment]
This might be a bug as it could cause issues with the wallet cache.

+bug

**Comment by xiphon** [comment]
The issue has been fixed at some point. The current release 13.0.4 correctly handles the case, preventing you from opening the same wallet file multiple times.

**Comment by dEBRUYNE-1** [comment]
+resolved
