### ISSUE TITLE
MoneroD initializes cryptonote protocol

### ISSUE THREAD

**Issue by I-got-mine** [monero-project/monero-gui#4225]
I installed the GUI to Debian from binaries. When monerod(v0.18.2.2-release) starts it says "Crypronote protocol initialized OK." It is my understanding that randomX is completely separate from crypronote. Am I misunderstanding something, or is monerod initializing the wrong protocol?

**Comment by selsta** [comment]
RandomX is the mining algorithm used, CryptoNote is the name of the software monero is originally based on.

There's nothing wrong with the message you are seeing.
