### ISSUE TITLE
Trezor Safe 3 launch

### ISSUE THREAD

**Issue by Hannsek** [monero-project/monero-gui#4227]
Hello,

New Trezor Safe 3 was launched. Please try it with the [emulator](https://github.com/trezor/trezor-user-env/). And give us a feedback if you find any bugs. 

Cheers.

**Comment by plowsof** [comment]
trezor suite detects the emulated trezor (and im able to allow the connection for it to 'check' the device and for it to tell me its not geniune etc). 

when trying to get the monero-gui to create a hardware wallet (is this intended to work?):

```
E No device found
E No matching Trezor device found. Device specifier: ""
E Device connect failed
```

**Comment by Hannsek** [comment]
What transport type does Monero GUI use?

**Comment by ZhenyaPav** [comment]
Just received my Trezor Safe 3. Monero GUI does not detect it when creating, not when opening a wallet created with Feather
