### ISSUE TITLE
REDACTED FOR PRIVACY

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#4228]
REDACTED FOR PRIVACY

**Comment by selsta** [comment]
Can you share the output of

```
brew info qt
```

and

```
brew info qt@5
```

and also which macOS version you use, which command you are using to build monero-gui and any other information that might be useful.

**Comment by selsta** [comment]
@tobtoht found the issue, you have to uninstall qt6 for compilation to work. Easiest solution for now:

```
brew uninstall qt6
```

**Comment by Mike-Bou** [comment]
It did compile, but app quit unexpectedly. Im using Monero Org new ARM version instead.

**Comment by selsta** [comment]
You have to share a crash log, see Console.app

**Comment by Mike-Bou** [comment]
￼

**Comment by selsta** [comment]
@Mike-Bou your comment is empty, it's best to share the log on paste.debian.net or similar site

**Comment by Mike-Bou** [comment]
Posting 1295169 from @Mike-Bou for 24 hrs on paste.Debian.netSent from my iPhoneOn 15 Oct 2023, at 20:16, selsta ***@***.***> wrote:﻿
@Mike-Bou your comment is empty, it's best to share the log on paste.debian.net or similar site

**Comment by selsta** [comment]
@Mike-Bou try to compile your own Qt instead of relying on the homebrew one

```
git clone https://github.com/qt/qt5.git
cd qt5
git checkout v5.15.9-lts-lgpl
./init-repository
mkdir build
cd build
../configure -prefix /Users/selsta/dev/qt-test/ -opensource -confirm-license -release -nomake examples -nomake tests -no-rpath -skip qtwebengine -skip qt3d -skip qtandroidextras -skip qtcanvas3d -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdoc -skip qtgamepad -skip qtlocation -skip qtnetworkauth -skip qtpurchasing -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech -skip qttools -skip qtvirtualkeyboard -skip qtwayland -skip qtwebchannel -skip qtwebsockets -skip qtwebview -skip qtwinextras -skip qtx11extras -skip gamepad -skip serialbus -skip location -skip webengine
make
make install
cd ../qttools/src/linguist/lrelease
../../../../build/qtbase/bin/qmake
make
make install
cd ../../../../qttools/src/macdeployqt/macdeployqt/
../../../../build/qtbase/bin/qmake
make
make install
```

**Comment by Mike-Bou** [comment]
the output of ../confgure was:
Info: creating super cache file /Users/mike/qt5/build/.qmake.super
Info: creating cache file /Users/mike/qt5/build/.qmake.cache
Info: creating stash file /Users/mike/qt5/build/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output

**Comment by selsta** [comment]
That's a Qt bug, you can apply this diff: https://raw.githubusercontent.com/Homebrew/formula-patches/086e8cf/qt5/qt5-qmake-xcode15.patch
