### ISSUE TITLE
start of monerod gives "Segmentation fault (core dumped)" on Archlinux

### ISSUE THREAD

**Issue by ZombB** [monero-project/monero-gui#4233]
When the monerod daemon is started on Archlinux it segfaults every time. I have attached the shelloutput when trying to start the daemon manually and the logfile that is produced.

[monero.log](https://github.com/monero-project/monero-gui/files/13062957/monero.log)
[shelloutput.log](https://github.com/monero-project/monero-gui/files/13062958/shelloutput.log)

This bug first appeared on Monero 'Fluorine Fermi' (v0.18.2.2-release)

This is my Linux kernel version: 6.5.8-arch1-1

**Comment by selsta** [comment]
How did you install monerod? Package manager or binary from the website?

What is /mnt/ ? A network drive or an external HDD? Did you sync up partially before it started to segfault?

**Comment by ZombB** [comment]
Hi selsta,

monerod was installed using the package manager which is pacman on Archlinux. So this affects the official monero Archlinux package: https://archlinux.org/packages/extra/x86_64/monero/

/mnt/ is a local harddrive on the PC. Precisely it is an ext4 filesystem on a raid 5 array.

**Comment by selsta** [comment]
Did you sync up partially before it started to segfault? Or did this segfault show up instantly on first start and monerod never worked before?

**Comment by ZombB** [comment]
duplicate of #9055 https://github.com/monero-project/monero/issues/9055

**Comment by rslay** [comment]
I ran it with the flag `monerod --db-salvage` and that saved me from having to resync from the start
