### ISSUE TITLE
No update when latest version is 0.18.3.1?

### ISSUE THREAD

**Issue by DopamineUser** [monero-project/monero-gui#4235]
![image](https://github.com/monero-project/monero-gui/assets/148219987/7ec71cbc-0fcd-41d8-808b-23d563fa2038)

I also just realized the time displayed is different than my time, is this intentional?

**Comment by selsta** [comment]
We will activate the auto updater soon. For security reasons activating the auto updater requires multiple people from the core team, so it's sometimes a bit delayed. We also make sure that there are no new major bug reports.
