### ISSUE TITLE
Choice of Where to Download the Blockchain

### ISSUE THREAD

**Issue by ThisNekoGuy** [monero-project/monero-gui#4242]
Using the Monero GUI flatpak, I noticed that the wallet seems to choose where to download the blockchain for you in the initial setup (it doesn't seem to ask) and this is a problem because, on OS/system drives that are tight on space (smaller SSD, for example, which is my problem), users may not be able to perform this process at all despite having a spare storage drive capable of doing this task.

An issue like this can be completely preventative from helping people enter the ecosystem.

**Comment by mateMathieu** [comment]
Hi @ThisNekoGuy ,
Here, there is an issue with flatpack access to an internal disk.
Maybe it come from the btrfs filesystem. Other software like steam have no problem accessing it.

I tried to use flatseal to configure additional access to the HDD folder. But I get this error despite all the efforts (permission and ownership check) of making it available.
![Screenshot from 2024-02-01 16-21-44](https://github.com/monero-project/monero-gui/assets/3027020/ac934b89-6899-4281-ba8e-625dd5e233c5)


from /etc/fstab
`UUID=d4071983-a3a6-4621-a5e1-xxxxxxxxxxxx /mnt/d4071983-a3a6-4621-a5e1-xxxxxxxxxxxx  btrfs nosuid,nodev,nofail,x-gvfs-show 0 0`

Can you help?

**Comment by mateMathieu** [comment]
Dear @BigmenPixel0,
Maybe you can help, all the folder's management by the gui app is not behaving well. 
For instance you get an error if you select any file-path of the app with the "Browse" button.
I am on linux Mint 23.1 here.
Thank you

**Comment by mateMathieu** [comment]
More here: https://lr.vern.cc/r/Monero/comments/6zid4h/flatpak_of_the_monero_gui_wallet/
