### ISSUE TITLE
Device not found. Trezor

### ISSUE THREAD

**Issue by stoicvig** [monero-project/monero-gui#4274]
Hello all, I am not a tech person and would like some help identifying why my trezor wont connect to the monero gui anymore. I have had it working before but recently tried to open it and got the error message after putting in my password - devise not found. Trezor.  I use the recent update on both. Thanks

**Comment by stoicvig** [comment]
Not sure what that is. It rings a bell

**Comment by selsta** [comment]
How did you install monero-gui?

**Comment by selsta** [comment]
What you posted means monero-gui is compiled without Trezor support but that's not possible when downloaded from getmonero.org

Are you 100% sure it's not installed from a package manager?

**Comment by stoicvig** [comment]
Im sorry but I am not sure. I do know I had it working with Trezor before as I transferred monero to the wallet and from using trezor. But now I cant access it. 

Is there a way to find out the information you need?

**Comment by selsta** [comment]
You can try to go to getmonero.org, download the Linux GUI and then start exactly that binary and check if it works.

If it doesn't work please post the exact error message.

**Comment by stoicvig** [comment]
Would I need to create a new wallet from hardware or restore from seed? 

Another thing I noticed is that I never had a seed with the GUI only for the trezor.  Is the trezor seed the one I would use?

**Comment by selsta** [comment]
No, you would not need to create a new wallet, just open the existing one.

**Comment by stoicvig** [comment]
It has been stuck on the opening wallet page for 10 minutes now.

**Comment by stoicvig** [comment]
Nothing on the Trezor

**Comment by stoicvig** [comment]
Ok sorted. There were 2 options for me to choose from monero gui and monero gui applmage. It has worked with Applmage
