### ISSUE TITLE
Windows: Can't to send my moneros

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero-gui#4276]
https://youtu.be/HWNU-CSeakc
I screened the video with this error.
I restored my wallet from high 0 and connected to remote node. But I can't to send my moneros!
If I rescanned my balance the error is not going anywhere.

**Comment by selsta** [comment]
How did you generate this wallet? Did you change around the source code? Does this also happen on other platforms other than Windows?

**Comment by developergames2d** [comment]
> How did you generate this wallet? Did you change around the source code? Does this also happen on other platforms other than Windows?

I generated it with [lincoins-master](https://xmr.llcoins.net/). The first and last 2 hexadecimal-seed symbols are 0.
No, I didn't change, this is official wallet.
In other platforms I see some output transactions from account # 0, but I didn't see output transactions from subaccounts # 1 and # 2.

**Comment by selsta** [comment]
Does your primary address have 11111111111 in the middle?

**Comment by developergames2d** [comment]
> Does your primary address really have 11111111111 in the middle?

Yes, this is abbey x25 seed.

**Comment by selsta** [comment]
Why did you send funds to this address? Everyone can generate the private key and steal your funds.

**Comment by developergames2d** [comment]
> Why did you send funds to this address? Everyone can generate the private key and steal your funds.

I did not send to this any moneros, I just rescanned this address, but monero-gui writes that it has 10 moneros.

**Comment by selsta** [comment]
You claimed they are "your" monero so it seemed like you have sent them to this address.

It says 10 monero because it's not a valid seed. It requires a source code change to see the correct balance.

**Comment by developergames2d** [comment]
> You claimed they are "your" monero so it seemed like you have sent them to this address.
> 
> It says 10 monero because it's not a valid seed. It requires a source code change to see the correct balance.

Thanks, but it would be nice if your application worked with any Seed.

**Comment by plowsof** [comment]
Developergames2d stop spamming this repo with useless issues. Asking for help to drain the infamous "Abbey seed" wallet?  Whats next, how to access the general fund view wallet moneros?
