### ISSUE TITLE
18.3.2 GUI Shows Network Status Disconnected When Connecting to Own Node Running Locally (So I Downgraded GUI to 18.3.1) - UPDATE: Will be resolved in 18.3.3

### ISSUE THREAD

**Issue by ajsingh007** [monero-project/monero-gui#4293]
Hope this helps other users...

But I upgraded my remote node running locally as well as my GUI to 18.3.2 (I'm on MacOS, Intel). 

On the 18.3.2 GUI the Network Status kept saying "Disconnected" whether my node was running 18.3.2 or 18.3.1

When I downgraded the GUI back to 18.3.1, it connects just fine whether my node is running 18.3.2 or 18.3.1

I'm not sure why this is but I hope it can come in handy to others who have the same issue!

Thanks

**Comment by selsta** [comment]
Did you have a login / password set? If yes, this is a known issue that will be resolved in v0.18.3.3.

**Comment by ajsingh007** [comment]
> Did you have a login / password set on your node? If yes, this is a known issue that will be resolved in v0.18.3.3.

Yes I do! Thanks for the quick reply. I was searching in closed issues to see if this was the case but wasn't able to find this out so thanks for informing me. Looking forward to 18.3.3

Cheers
