### ISSUE TITLE
WinInstaller 0.18.3.1 being downloaded and not 0.18.3.2

### ISSUE THREAD

**Issue by 0hne** [monero-project/monero-gui#4295]
Hello, in the [download](https://www.getmonero.org/downloads/#gui:~:text=30%2B%20languages%20available-,Downloads,-Current%20Version%3A) section, clicking on the [Windows 64-bit (Installer)](https://downloads.getmonero.org/gui/win64install), downloads the old version 0.18.3.1 for me, instead of the current version 0.18.3.2.
On GitHub it's not a problem, just on the download website.

**Comment by selsta** [comment]
I think this is a CDN issue, depending on the location it correctly links to v0.18.3.2.

**Comment by 0hne** [comment]
It might be something locally as well though? I just tried inPrivate mode in Edge, and then it downloads the correct 0.18.3.2.

**Comment by plowsof** [comment]
clear your browser cashe or use a different* link to download the file. for example: https://downloads.getmonero.org/gui/win64install_some_text_here

**Comment by plowsof** [comment]
if this is a big enough problem, perhaps the version number could be tagged into the url and then nobody would run into this issue

**Comment by selsta** [comment]
Closing as this doesn't appear to be a GUI bug. monero-site repo would be better suited to further discuss the website and download link.
