### ISSUE TITLE
monero not appearing in monero GUI wallet

### ISSUE THREAD

**Issue by fentyman** [monero-project/monero-gui#4296]
i just just installed monero GUI wallet and purchased monero on localmonero.com from a high reputation seller using paypal. its been 2 days and localmonero says the transaction is complete and the monero should be in my wallet, but when i open my wallet it shows nothing has been added. i have just installed the app and the daemon still has blocks remaing. is there a fix to this or have i been scammed.

**Comment by selsta** [comment]
Please go to Settings -> Info and share

- Version
- Wallet mode
- Wallet restore height

> i have just installed the app and the daemon still has blocks remaing

You have to connect to a fully synced up daemon for your funds to show up. If there are blocks remaining it means you are still syncing the blockchain.

**Comment by fentyman** [comment]
GUI version: 0.18.3.2-unknown (Qt 5.15.12)
Embedded Monero version: 0.18.3.2-unknown
Wallet restore height: 3089362
Wallet mode: Advanced mode (Local node)

how long does it usally take to sync i have 1786897 blocks left

**Comment by selsta** [comment]
Syncing will take between 24h and a couple days depending on your hardware and if your blockchain is stored on SSD.

**Comment by fentyman** [comment]
ok thanks for your help :)
