### ISSUE TITLE
Log menu outputs inaccurate mining info

### ISSUE THREAD

**Issue by PPPDUD** [monero-project/monero-gui#4298]
Earlier today, I started p2pool mining on the Mini chain.

Next, out of curiosity, I visited Settings>Log and typed the "status" command.

It said the following: `Height: 3117113/3117113 (100.0%) on mainnet, not mining, net hash 1.81 GH/s, v16, 12(out)+0(in) connections, uptime 0d 0h 7m 42s`, despite the fact that I'm actively mining.

I'm using Monero GUI Fluorine Fermi (v0.18.3.2-release) on Windows 11 Pro.

**Comment by selsta** [comment]
You were mining with p2pool and not monerod. monerod does not know about p2pool mining so it can't display the correct mining status in this case.

**Comment by PPPDUD** [comment]
That will explain a lot! Thanks!
