### ISSUE TITLE
Monero transaction missing from GUI wallet

### ISSUE THREAD

**Issue by SidelinedGazelle** [monero-project/monero-gui#4305]
I bought some monero from localmonero.co and on the site it says the transaction is complete but i cant see the transaction or the monero in my wallet.
when i check the transaction on https://xmr.llcoins.net/checktx.html it says "Failed to get transaction data! Perhaps LocalMonero is down?"
i think my GUI wallet program hadn't been updated when i made the transaction but i have since updated it and still nothing.
i have tried to refresh the wallet and when it was syncing i saw the wallet balance go up briefly to the right amount but when it finished it was down again.
anyone have any idea what would cause this?
thanks in advance for any help anyone can provide

**Comment by selsta** [comment]
Please go to Settings -> Info and share

- Version
- Wallet mode
- Wallet restore height

**Comment by SidelinedGazelle** [comment]
Hi,
Version: 0.18.3.3-unknown (Qt 5.15.13)
Wallet mode: Advanced mode (Remote node)
Wallet restore height: 3101668

**Comment by selsta** [comment]
What does it say in the bottom left corner?

**Comment by SidelinedGazelle** [comment]
Wallet is synchronized
Deamon is synchronized (3117947)
Network status
Remote node

**Comment by SidelinedGazelle** [comment]
it says "failed to scan transaction: failed to scan transaction: failed to get transaction from deamon"

**Comment by selsta** [comment]
What remote node are you using?

**Comment by SidelinedGazelle** [comment]
http://157.90.234.17
18089

**Comment by selsta** [comment]
This node isn't even synced up, try a different one.

**Comment by SidelinedGazelle** [comment]
is this one ok?
88.198.199.23
18081

**Comment by selsta** [comment]
yes, try this one

**Comment by SidelinedGazelle** [comment]
Yay!! that fixed it, thanks alot, i was really starting to panic

**Comment by SidelinedGazelle** [comment]
yeh i'll do that, thanks :]
