### ISSUE TITLE
start mining when PC is locked and stop when unlocked

### ISSUE THREAD

**Issue by aakashjan** [monero-project/monero-gui#4309]
My PC is on 24*7 for convenient it never shutdown. because it's available to me on click(don't have to wait for it to start).

A setting that allows the behaviour that allows start of mining process automatically and when i unlock it either shut down mining completely and option to reduce CPU core used for mining.

**Comment by selsta** [comment]
The miner inside monero-gui is intentionally simple, for what you are suggesting it would be better to use something like `xmrig`.
