### ISSUE TITLE
Monero Daemon not sync and not showing my balance will pay $2 for fixing help

### ISSUE THREAD

**Issue by AMbns01** [monero-project/monero-gui#4311]
I downloaded and created monero wallet fron get monero and bought monero from changnow but now my balance is not showing as my daemon not sync. Please help
![XMR](https://github.com/monero-project/monero-gui/assets/168646452/bfc4ba5e-4eb8-4194-ae20-c30b571b08af)

**Comment by selsta** [comment]
Your balance won't show up until you have a fully synchronized daemon and wallet.

Can you go to Settings -> Info and share

- Version
- Wallet mode
- Wallet restore height

**Comment by selsta** [comment]
You selected local mode, this means you first have to fully sync up with the network. This can take around a day. Once both bars are at 100% your balance should show up.

**Comment by AMbns01** [comment]
how to make it fast

**Comment by selsta** [comment]
You can go to Settings -> Node -> Remote node and then add a remote node from this list: https://monero.fail

Or you can simply wait for your local node to sync up.

**Comment by AMbns01** [comment]
![sync](https://github.com/monero-project/monero-gui/assets/168646452/bb5bbeaa-c1fa-44ed-a72b-1bf1da5d99c3)
It shows complete when i am offline is this ok can it show balance while its offline as it never show my balance since i deposited due to no commplete sync

**Comment by selsta** [comment]
You need an internet connection and wait for it to fully sync up. If you don't have an internet connection it won't show you the correct progress.

**Comment by AMbns01** [comment]
can i make the process fast

**Comment by AMbns01** [comment]
is there any risk using remote node

**Comment by AMbns01** [comment]
Please help me brother and also how can i give you the $2 as gift

**Comment by selsta** [comment]
Using a remote node is slightly worse for privacy, but it is faster, since you don't have to wait for your node to sync up.

**Comment by AMbns01** [comment]
How much risky is it and also let me know about thank you gift

**Comment by selsta** [comment]
See the explanation here: https://monero.stackexchange.com/a/10701

> thank you gift

This is not necessary but thank you!

**Comment by AMbns01** [comment]
sorry i didnt understand the explanation can you please describe what if i use remote node also will it permanent or temporary and i can change it later

**Comment by selsta** [comment]
Yes, you can change between local and remote node whenever you want.

**Comment by AMbns01** [comment]
and what is the risk if i use remote node

**Comment by AMbns01** [comment]
can you please describe

**Comment by selsta** [comment]
A malicious remote node can for example collect your IP address, make it so that your balance doesn't show up, make it so that you can't send transactions, etc.

The risk is quite low but still a possibility.

**Comment by AMbns01** [comment]
what is remote node i have rdp can i use it for that

**Comment by AMbns01** [comment]
once the wallet sync fully completed will it require the sync again and if yes then when

**Comment by selsta** [comment]
> once the wallet sync fully completed will it require the sync again and if yes then when

Only new blocks, per day around 720 blocks get added so each day these 720 blocks have to be synced.

**Comment by AMbns01** [comment]
is there any tips to speed up the process

**Comment by AMbns01** [comment]
Hello brother i need some help my daemon started sync there are 443000 blocks remaining but there is a problem i got my storage full can i change the drive for this and if i change the location will the sync will start from beginning?

**Comment by selsta** [comment]
#4312
