### ISSUE TITLE
Funds dont appear on my wallet, please help.

### ISSUE THREAD

**Issue by dawco998** [monero-project/monero-gui#4326]
Hi, today i send monero to my wallet, 200 confirmatios. I used several nodes and had all fully synched, but my account shows 0
Please help.

Hash: 207c6e7281e04a1ebbce3048d852ab9b81a287ec10f229a58a5f80baecd098b1

**Comment by selsta** [comment]
Can you got to Settings -> Info and share

- Version
- Wallet mode
- Wallet restore height
