### ISSUE TITLE
Error: Invalid last argument: xxxxxx Payment id

### ISSUE THREAD

**Issue by JsonAndrx** [monero-project/monero-gui#4327]
Hi, I am trying to make a transfer through wallet cli of monero with a payment id but when I do it I get the error Invalid last argument, the structure I use to make the transfer is as follows:

transfer <address> <amount> <payment_id>
transfer xxxxxxxx 0.3 xxxxxxx

the version I use is: Monero 'Fluorine Fermi' (v0.18.3.3.3-release)

**Comment by selsta** [comment]
Try sending to the integrated address directly instead of separately specifying the payment id.

**Comment by JsonAndrx** [comment]
> Try sending to the integrated address directly instead of separately specifying the payment id.

without in the payment_id if I can make the transfer, but the problem is when I want to attach a payment_id

**Comment by selsta** [comment]
You have to be more clear what you are doing. Long payment IDs are obsolete, so you have to do

```
integrated_address
```

to get an payment id and integrated address

and then

```
transfer 4JtkiNvoi3iSPHHvcfXPPyj66zHQ9h1X9hmLCjDZ6kbNUhtYwDhAMm79p9GZ1iPCUhDMEvKMkMJdgb7JURAkCZUuhr8aQWw7q9r2h8juTv 0.1
```

**Comment by JsonAndrx** [comment]
> You have to be more clear what you are doing, I don't really understand it from your post. To do it correctly you have to enter
> 
> ```
> integrated_address
> ```
> 
> to get an payment id and integrated address
> 
> and then
> 
> ```
> transfer 4JtkiNvoi3iSPHHvcfXPPyj66zHQ9h1X9hmLCjDZ6kbNUhtYwDhAMm79p9GZ1iPCUhDMEvKMkMJdgb7JURAkCZUuhr8aQWw7q9r2h8juTv 0.1
> ```
ok I got it, I was just getting my bearings from old resources for the payments_id payment, sorry for the newbie issue but I couldn't find any information on how to do this process, thanks a lot.
