### ISSUE TITLE
[Feature] new Ledger Flex support as hardware wallet

### ISSUE THREAD

**Issue by mathieupotier** [monero-project/monero-gui#4344]
Hi there, seems Ledger flex is not supported from monergo GUI.

https://shop.ledger.com/products/ledger-flex

The product is quite recent, but do you have planned to work on this support ?

**Comment by selsta** [comment]
Did you try v0.18.3.4 and select one of the Ledger devices?

Its not in the dropdown yet but selecting one of the others should work.

**Comment by mathieupotier** [comment]
working fine with 0.18.3.4 ... didn't noticed that there was a new release ... 😉
