### ISSUE TITLE
possible 2 trojans on main website windows gui downloads

### ISSUE THREAD

**Issue by lubi888** [monero-project/monero-gui#4371]
Hi guys,

My Windows TotalAV anti virus thinks that both windows downloads are riddled with trojans. I hope TotalAV is wrong but perhaps it is correct. I need someone else to check this to make sure nobody else is getting infected on windows and tha the main website is not compromised.

Both of the windows gui appear to have trogans.

[Windows 64-bit (Installer)](https://downloads.getmonero.org/gui/win64install)
[Windows 64-bit (Zip)](https://downloads.getmonero.org/gui/win64)

Take a look at this screenshots. 
<img width="603" alt="Screenshot 2024-11-01 150217" src="https://github.com/user-attachments/assets/b15fa143-ba9a-4c71-94bb-c8a58008680d">
<img width="603" alt="Screenshot 2024-11-01 151142" src="https://github.com/user-attachments/assets/46a07402-79b7-46ff-9fa3-94d7e1bca1e8">

**Comment by selsta** [comment]
Please see https://www.getmonero.org/get-started/faq/#antivirus
