### ISSUE TITLE
Building for Windows in MSYS2. All fine until `make release-win64 -j4`

### ISSUE THREAD

**Issue by imfatant** [monero-project/monero-gui#4373]
I'm not going to describe the number of errors, or post a log. Usually I would. I think a dev should simply try this and feel his nuts shrink.

I'll put it on hold until you get a chance to look at this. Just follow your own install instructions and you'll see what I mean.

:)

**Comment by selsta** [comment]
The monero submodule we currently use doesn't compile with the latest boost version used by MSYS2. To fix that you have to manually check out the latest version.

```
cd monero-gui
cd monero
git fetch origin
git reset --hard origin/release-v0.18
cd ..
MANUAL_SUBMODULES=1 make release-win64 -j4 
```

If that does not work for you you wil have to share build logs.

**Comment by selsta** [comment]
Closing due to lack of reply.
