### ISSUE TITLE
Monero Wallet

### ISSUE THREAD

**Issue by tacobella1** [monero-project/monero-gui#4379]
I really hope someone can help me, I've been trying to get my wallet to sync and I just can't seem to do it. I thought perhaps my laptop was not sufficient to run the wallet so I just bought a new laptop. I spent loads of money on the new laptop and it still won't load, I'm really pulling my hair out. I tried deleting everything and then to restore my wallet from a ledger nano x. I tried running it in simple mode, then tried the next level up and then full bootstrap. The wallet blocks get stuck and don't load.  The bar at the bottom loads and then the bar above it gets stuck usually at 999025 but sometimes other blocks and won't go beyond. Any ideas gratefully received.

**Comment by Vickynicole** [comment]
Hello @tacobella1 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MON07638
Please see the link below to our dedicated support line:
[Monero Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by selsta** [comment]
@tacobella1 ignore the comment above, that's a scam. will try to get it removed

**Comment by tacobella1** [comment]
Oh yes, haha. They tried to get me to put in my mnemnomic (or however you spell it) phrase. I went there before I saw your message. lol

**Comment by selsta** [comment]
Regarding your issue, did you export your view key when opening the wallet?

**Comment by tacobella1** [comment]
Yes, I did that and it all starts to load but then gets stuck and won't go any further

**Comment by selsta** [comment]
When restoring the wallet, which restore height or restore date did you set?

**Comment by tacobella1** [comment]
I set the date as 2021-01-01 as I don't know the restore height

**Comment by selsta** [comment]
Is the before you first received monero? Setting a date closer to when you first received monero means it will sync faster / skip more blocks.

Also I would recommend you to select advanced mode with a dedicated remote node. Do you know how to do that or do you need instructions?

**Comment by selsta** [comment]
Try to use advanced mode and set a custom remote node. You can go to the main menu by clicking on the exit symbol in the top left corner.

Then click on "Change wallet mode" and select "Advanced mode". Afterwards open your wallet again, go to Settings -> Node, select "Remote node" and enter the following node:

address: `node.monerodevs.org `
port: `18089`

Please report back if syncing with this one works or if it also gets stuck.

----------

Other remote node in case the above has issues: https://monero.fail

**Comment by tacobella1** [comment]
Thanks so much I will let you know

**Comment by Misthh** [comment]
Hello @tacobella1  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by tacobella1** [comment]
Hey, I left the wallet running all night. This morning the daemon has synchronized completely but the daemon has not synced at all yet. It did not work.

![image](https://github.com/user-attachments/assets/ff76feea-23c6-43f6-9003-6ceeeb3b8856)

**Comment by Misthh** [comment]
Hello @tacobella1  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by selsta** [comment]
I have never seen this behaviour before but let's try a couple more steps to debug this issue.

Try this node, I just tested it locally and it works as expected.

address: `node3.monerodevs.org `
port: `18089`

If you still get the "waiting for daemon to sync" message then close your wallet, and create a new non-Ledger wallet and report back if it's able to sync up, or not.

These two steps should narrow down the issue.

**Comment by tacobella1** [comment]
I got it working, I changed to a different node and it worked. Thanks so much for helping!

**Comment by selsta** [comment]
Good to hear, closing this as resolved.
