### ISSUE TITLE
Easy way for users to register an address with OpenAlias

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#483]
How about a GUI feature to create and register an address with OpenAlias that you can start to hand out to your friends?

**Comment by xmr-eric** [comment]
Hmmmm. Maybe a link to Afraid.org? I'm not sure how editing DNS entries would work in a decentralized manner.

**Comment by NanoAkron** [comment]
Doesn't have to work in a decentralised manner, and I believe @tewinget wrote the implementation that's already in monero core.

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by selsta** [comment]
Not aware of such a feature and I don’t see how this would be possible inside the GUI. Please open a new issue with a detailed proposal if still wanted.
