### ISSUE TITLE
Fields have different fontsizes

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#531]
Some pages in the wallet (Send, Address Book, History, Settings) have fields with a larger fontsize. Other pages in the wallet (Receive, Check Payment, Sign/Verify) have fields with a smaller fontsize. Ideally these should look the same.

Address book:
![addressbook](https://cloud.githubusercontent.com/assets/21302237/23561751/9810769a-000d-11e7-924e-74669460dd0b.png)

Receive page:

![receive](https://cloud.githubusercontent.com/assets/21302237/23561758/9f8913b4-000d-11e7-9df8-21f4ee112ced.png)

The smaller fontsize looks best, but it may be slightly on the small size. So perhaps the ideal field fontsize for the entire wallet is one click up, perhaps 16px.

**Comment by xmr-eric** [comment]
The only exception to this would be pages where a single field is the main focus. For example, it's probably ideal to keep the Password / Confirm password fields in the Wizard at 26px since they are the main focus of the entire page.

**Comment by skftn** [comment]
New theme is coming for next release.

**Comment by skftn** [comment]
+wontfix
