### ISSUE TITLE
Confusing arrow on History page

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#575]
I don't understand the function of this arrow on the history page:

![uparrow](https://cloud.githubusercontent.com/assets/21302237/24083694/6e8192e4-0cb2-11e7-9915-bf41b9de6ea1.png)

If I click it then the history section slides up, and it looks awkward.

![downarrow](https://cloud.githubusercontent.com/assets/21302237/24083711/c766a2dc-0cb2-11e7-9019-b65fe5c06326.png)

**Comment by medusadigital** [comment]
we can either remove the functionality or fix it..

removing probably the way to go.

+enhancement

**Comment by skftn** [comment]
Newest version does not have the arrow.

+resolved
