### ISSUE TITLE
Add margin around Remote Node area in Settings

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#581]
For the first time I tried connecting to a remote node. I kept typing in node.moneroworld.com and clicking Start daemon, because that's how I assumed the connection was initialized. Yet it kept simply launching the local daemon.

Only after people in #monero-dev told me that I should not click Start daemon was the remote node connection established.

So ideally the Start daemon button should probably be disabled if somebody is connecting to a remote node, so they don't get confused like I did. This could go along with Issue #542 that clicking "Restore localhost" also enables the "Start daemon" button.

**Comment by xmr-eric** [comment]
Or wait, is that what the Save button does? The Save button isn't just for the Login (optional) field?

**Comment by Jaqueeee** [comment]
that's right. The save button is for all those fields. I agree it's a bit confusing after we've added the rpc login options. Maybe we could add a margin and also rename the button to Connect?

**Comment by xmr-eric** [comment]
Great. I'll rename the Issue.

**Comment by Jaqueeee** [comment]
Thought some more on this @xmr-eric. I don't think we should disable "start daemon" if connected to remote node. Because there is a scenario where you want your local daemon to sync while you are connected to a remote node.

**Comment by xmr-eric** [comment]
Cool

**Comment by erciccione** [comment]
New theme, new life

+resolved
