### ISSUE TITLE
Repo improvements

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero-gui#62]
I know we are _all_ pressed for time but I think the organization of this repo could use a little more work:
1. ~~build instructions are out of date (one apparently only needs only run `build.sh`)~~
2. we desperately need a CMake recipe (we don't need all these build scripts)
3. ~~we should consider using a git submodule for the `monero` repo~~
4. ~~these scripts shouldn't be commandeering all of my cpu cores~~ Thanks @moneromooo-monero #106 

These are just a few issues off the top of my head. I look forward to contributing to monero-core so if these issues aren't resolved by then, I'll be happy to make fixes.

**Comment by moneromooo-monero** [comment]
The most trivial of these is fixed :D https://github.com/monero-project/monero-core/pull/106

**Comment by xmr-eric** [comment]
@anonimal Can this issue be closed?

**Comment by anonimal** [comment]
@xmr-eric step 2 is unresolved. I would advise to keep this issue open until that is addressed.

**Comment by TheCharlatan** [comment]
Pull Request for cmake is open: https://github.com/monero-project/monero-gui/pull/2404

**Comment by selsta** [comment]
#2404 is now merged.

+resolved
