### ISSUE TITLE
Show desired fiat's value near XMR balance [+1]

### ISSUE THREAD

**Issue by sanecito** [monero-project/monero-gui#621]
It would be nice to see the fiscal value of my XMR holdings (e.g. if holding 100 XMR and <XMR, USD> pairing is $20, it shows USD balance of $2,000)

Monero isn't particularly volatile so a re-sync of fiscal value of every 60 seconds should suffice although in the future advanced settings might allow configuring this. At the very least, fiscal currencies supported should be the primary currencies used in countries where the ~11 translated languages thus far are the primary language (e.g. English is the primary language in the US, Canada, Great Britain, etc and thus USD, CAD, GBP, etc should be supported)

**Comment by dternyak** [comment]
AFAIK, this would require a centralized source (API), that would provide such data. I don't think we should bake in network calls to any centralized source, so I don't think this issue should be implemented, as much as I agree it would be nice to see the fiat value of your balance.

**Comment by xmr-eric** [comment]
I'm more ok with centralization on this issue, since pulling in the XMR/USD conversion has no effect upon the security or functionality of Monero. We could API into Bitfinex. I remember my Ethereum wallet displaying my balance in USD in parentheses, and it was really helpful.

**Comment by SamsungGalaxyPlayer** [comment]
This could be one of the optional extensions for the GUI that we keep talking about.

**Comment by sanecito** [comment]
Did the idea of extensions die out? I haven't seen much of it as late.

**Comment by rex4539** [comment]
+1

**Comment by skftn** [comment]
+wontfix
