### ISSUE TITLE
OpenSuSE 42.2: Need to manually export QT_SCALE_FACTOR=0.5 to fit GUI window on full HD display

### ISSUE THREAD

**Issue by villabacho** [monero-project/monero-gui#623]
The scaling should somehow be automatic depending on screen resolution.
Without setting QT_SCALE_FACTOR, fonts and other GUI elements are unnecessarily large.

**Comment by skftn** [comment]
Cool, I did not know of `QT_SCALE_FACTOR`.

Side-note: GUI is releasing a new (black) theme soon. Might improve things on small resolutions.

**Comment by erciccione** [comment]
was this solved with new theme?

**Comment by skftn** [comment]
No, best to keep this one open.

**Comment by selsta** [comment]
Full HD doesn’t sound like any high DPI scaling, the GUI should fit on a full HD display fine.

Please open a new issue if this problem still persists.

+resolved
