### ISSUE TITLE
Strange non-uniform character spacing in closing dialog

### ISSUE THREAD

**Issue by villabacho** [monero-project/monero-gui#624]
This refers to the "Daemon is running" text:

![image](https://cloud.githubusercontent.com/assets/6043551/24394867/efb0b04c-139d-11e7-88eb-ba77639f549c.png)

**Comment by villabacho** [comment]
Observed on OpenSuSE 42.2

**Comment by xmr-eric** [comment]
Mine doesn't look like that (OSX)

**Comment by erciccione** [comment]
+resolved
