### ISSUE TITLE
Seems like bitmap fonts are used in some places

### ISSUE THREAD

**Issue by villabacho** [monero-project/monero-gui#625]
Look at the poor scaling of the "Please enter wallet passwort" text:
![image](https://cloud.githubusercontent.com/assets/6043551/24395029/6ead8d3e-139e-11e7-9f15-db57d89ee9a5.png)

Observed on OpenSuSE 42.2 with QT_SCALE_FACTOR=0.7 (needed to fit the window on my screen)

**Comment by skftn** [comment]
AFAIK the current version does not use bitmap fonts. Could you confirm?
