### ISSUE TITLE
da_DK translation

### ISSUE THREAD

**Issue by x775** [monero-project/monero-gui#639]
Hi!

Is someone currently working on a Danish translation? I asked in the IRC previously and it sounded like someone _might_ be working on one? If that is the case, do you need any help? And, if not, is there someone I can reach out to when it comes to getting started on translating properly?

Thanks!

**Comment by NanoAkron** [comment]
Hi @x775 please feel free to help out! 

I'd recommend cloning the repo locally, making a new branch, copying the english (or other language if you prefer) translation from `src/monero-core/translations/monero-core_en.ts` to `monero-core_dk.ts` then opening it up and translating as necessary.

Then submit a pull request with a national flag in the appropriate size inside `src/monero-core/lang/flags`, amend the `src/monero-core/lang/languages.xml` file as necessary and voila!

It's actually easier than it sounds, and the existing code helps you a lot.

**Comment by x775** [comment]
Hi again!

Thank you very much for getting back to me - and for the instructions, much appreciated!

I will get right to it!

**Comment by x775** [comment]
Hi.

I figured an update here was appropriate: I am still working on this, though to a number of unexpected events time has been incredibly limited. I hope to get around to wrapping this up and proofreading accordingly as soon as possible.
