### ISSUE TITLE
Feature Request: Daemon rate limits

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-gui#652]
would be helpful to encourage users running nodes if they could modulate how much bandwidth it uses.

**Comment by KanoczTomas** [comment]
fully agree! One of cool features I like in the daemon.

**Comment by gaillard** [comment]
I can't get the limit GUI command or daemono startup option --limit 100 (set in GUI) to do anything. Are they unimplemented?

**Comment by Jaqueeee** [comment]
@gaillard Limit is not a valid flag. Try any of these instead:
```
  --limit-rate-up arg (=-1)             set limit-rate-up [kB/s]
  --limit-rate-down arg (=-1)           set limit-rate-down [kB/s]
  --limit-rate arg (=-1)                set limit-rate [kB/s]
```

**Comment by gaillard** [comment]
Even doing --limit-rate 100, and restarting daemon in the gui daemon log command entry, if I type limit I still get back zero. Perhaps its a bug in the gui and the daemon really is limited. Anyway to verify?

**Comment by Jaqueeee** [comment]
@gaillard that's because of a bug in the daemon. See #805. You'll have to start the daemon manually too see the output from `limit`

**Comment by Gingeropolous** [comment]
yeah, I guess it can. I introduced another issue about hard data caps, but this is fundamentally different I guess.
