### ISSUE TITLE
Unable to send transactions from Beta2 GUI wallet

### ISSUE THREAD

**Issue by TheRealMadmortigan** [monero-project/monero-gui#659]
So apparently I'm unable to send any transactions from the Beta2 GUI wallet. I just found out when I tried to contribute to a FFS project, otherwise everything seems to be working fine. The Daemon does seem to delay to start but it always starts eventually and syncs up.

I'm running Windows Server 2012 R2 and all outgoing transactions get stuck with a PENDING status. CLI will eventually show the transaction as FAILED. I already re-downloaded the wallet, deleted the cache, restored from seed, and re-synced the entire blockchain. No firewall or other changes to the server. Any ideas?

**Comment by Jaqueeee** [comment]
Hi! Could you check a block explorer after you've sent to see if the tx has been relayed?

**Comment by TheRealMadmortigan** [comment]
Nothing on the block explorers.  I've now deleted the entire blockchain and am almost done re-syncing from scratch.  Once this completes I'll try to send again and let you know.

**Comment by TheRealMadmortigan** [comment]
On another look, it seems it DID eventually broadcast the transaction -- Looking into them to see when they finally sent but this is quite strange behavior.  Let me know if anyone wants to look at logs, etc.

**Comment by TheRealMadmortigan** [comment]
Update: Blockchain is synced and up to date again. Now wallet shows me having MORE XMR than I expected, still shows one PENDING transaction, Unlocked Balance shows (Waiting for Block).
It's entirely possible that balance was incorrect prior to the re-sync and is only NOW displaying the correct balance. I don't keep that close an eye on my holdings but it's over by quite a bit...
Here's some screenshots I've gathered: http://imgur.com/a/hIakD
*The error I receive after starting the GUI
*The daemon log about 5 minutes later (the daemon connects eventually on it's own)
*The log now that the blockchain is fully synced.
Having already deleted the client, blockchain, and wallet files, I'm starting to think there's a local issue with my system. Anything else I can do to help identify the issue?

**Comment by Jaqueeee** [comment]
hi @TheRealMadmortigan 
**1. The balance has increased.** 
It could mean the wallet or daemon wasn't fully synced last time you used it. Did you create a new transaction this time or is the PENDING transaction the same as before? In the latter case, could you provide the tx id or check on a block explorer if it's included in a block.

**2. You get the "daemon failed to start" message, but the daemon starts.** 
Others have reported this error when they had a space in the path where gui was installed. Read in your reddit post that this is not the case. However, i've done some updates in this build that fixed the issue for others. Could you please try it?
https://build.getmonero.org/downloads/monero-core-5d45967-win64.zip

**Comment by TheRealMadmortigan** [comment]
Hi @Jaqueeee 

Thanks for the help!

It's possible it was out of sync but the wallet has been working fine both inbound and out and the balance was at the lower amount for months.  Only since the Beta 2 update did it begin to have issues sending transactions.  There is still one transaction PENDING: 

224ee438e47e16859927f5ee9b5298e0aeb8487485d5df9c0c230564cca4be2a

I'm not seeing it on any block explorers.

The wallet seems stable now but the balance is still higher than expected.  My unlocked balance also reads "waiting for Block" still but does show the same as the balance.  Is that normal, or indicative or something wrong?

The pending transaction is only 3 XMR for a FFS so worst case at this point is that it goes through and Fireice_uk gets funded an hour earlier, lol.  I would like to know that my balance is correct and help others avoid this issue as well.  Let me know if there's anything more can provide to help.  I work in IT at a high level so feel free to get technical.  Am not developer.

**Comment by TheRealMadmortigan** [comment]
@Jaqueeee 

FYI -- I installed the new client you gave me.  Same issue with the delayed daemon start:  Here's the log if interested:

http://imgur.com/unsof0P

**Comment by Jaqueeee** [comment]
@TheRealMadmortigan This would help me debug this:
1. Switch to log level 3 on settings page
2. Close wallet
3. delete/move monero-wallet-gui.log
4. start gui and reproduce error
5. Upload log content to https://paste.fedoraproject.org and paste link here

**Comment by TheRealMadmortigan** [comment]
I'm performing the requested steps now.  FYI -- I'm unable to send any transactions currently with the error "was rejected by daemon with status: Failed. Reason: double spend"

Will upload the log shortly.

**Comment by TheRealMadmortigan** [comment]
@Jaqueeee 

Output below, as requested.

https://paste.fedoraproject.org/paste/lG05hPvd8LYqgsxKcjak515M1UNdIGYhyRLivL9gydE=

**Comment by Jaqueeee** [comment]
Hi @TheRealMadmortigan. Sorry for late reply. Have been busy last week. Are you still experiencing issues with sending?

**Comment by golere** [comment]
Here is a guy with a pretty similar problem: https://www.reddit.com/r/Monero/comments/6ikbof/xmr_in_limbo_after_transaction_behind_firewall/

**Comment by medusadigital** [comment]
allright, seems to me we can close this ? 
the issue was resolved by flushing the mempool. 

doesnt seem to be a bug after all.

please pitch in if you think otherwise.

**Comment by dEBRUYNE-1** [comment]
This issue is resolved as follows:

https://monero.stackexchange.com/questions/6649/transaction-stuck-as-pending-in-the-gui

+resolved
