### ISSUE TITLE
[FEATURE REQUEST] "Show some sort of visual icon/indicator that mining is enabled visible on all the screens"

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#661]
From [Reddit](https://www.reddit.com/r/Monero/comments/62e1mc/mandatory_upgrade_monero_01031_wolfram/dftatcf/?context=3):

>gui suggestion - if mining is enabled in the gui. Show some sort of visual icon/indicator that mining is enabled visible on all the screens. Perhaps down the bottom where Network Status/Lightning Bolt is. Nice work.

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by skftn** [comment]
#1071
