### ISSUE TITLE
[FEATURE REQUEST] User Help via Tiptext

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#684]
Every application needs some help for new users. The idea isnt really to explain to the user how cryptocurrencies work in general, but to shed some additional light in some of the most confusing parts of Monero. This is probabaly the PaymentId, Integrated Address, Unlock Time, Smart Mining and so forth. 

personally i am in favour of using classical Tiptext to display this additional Information. not only its convenient but the implementation of tiptext could help also solve other issues without overloading the layout (for example https://github.com/monero-project/monero-core/issues/142)

This issue should be the placeholder for all this work and related discussion. 

some points worth talking about (and there are sure more) :

- should it be possible to activate/deavtivate the help ?
- is tiptext the right choice to do this ?

+feature

**Comment by xmr-eric** [comment]
Also a fan of tiptext. And I think I've seen some initial implementations of it in the code.

**Comment by jonathancross** [comment]
In some views (like the **Receive** tab) there is an orange "help" link that opens a modal.
This should be factored into the decision... do we want 2 systems for help text?

The current modal works well for larger amounts of text and keeps the UI fairly clean otherwise, but breaks the user out of current activity with this jarring modal which is awkward.

**Comment by fresheneesz** [comment]
Also need a tooltip for "Sign tx file" - what is a "transaction file" ? Is it just signing any file with your wallet or does it have to be some file in a valid "transaction file" format?

**Comment by medusadigital** [comment]
+feature
+in progress

might probably still not make it for next release 

!!

**Comment by erciccione** [comment]
We now have some tiptexts in the new theme, some new shall be added in future. If still valid, please reopen @medusadigital 

+resolved
