### ISSUE TITLE
Add GPU mining to solo mining

### ISSUE THREAD

**Issue by sanecito** [monero-project/monero-gui#689]
CPU solo mining built into the GUI is a great start, but it would be awesome if the GUI could allow for better maximizing the full potential of one's device. 

Not sure if the existing AMD/Nvidia GPU miners out there have licenses that would allow you to add them to the project so a new one doesn't have to be rolled out here, but even if an independent GPU miner has to be created, it could help with miner/miner pool diversity.

In particular it helps by helping people mine more by having a functionally centralized UI to mine (and manage their wallet) rather than having two UI running (GUI/CLI for CPU + wallet, and miner GUI/CLI for GPU).

**Comment by selsta** [comment]
Closing this as it doesn’t make sense for RandomX.

+invalid
