### ISSUE TITLE
Add to github description for this project

### ISSUE THREAD

**Issue by knaccc** [monero-project/monero-gui#727]
At the moment, when someone arrives at https://github.com/monero-project, both the monero and monero-core repositories have the same description: "Monero: the secure, private, untraceable cryptocurrency".

Please could we change one of the descriptions to something like "Monero: the secure, private, untraceable cryptocurrency - GUI wallet", and the other one to something like "Monero: the secure, private, untraceable cryptocurrency - daemon, libs and CLI wallet".

Otherwise it's very confusing for users to know which repository to submit issues to.

Please let's not get bogged down about whether to rename the repository itself. I'm just specifically talking about making the description more informative.

**Comment by jonathancross** [comment]
I agree.  We updated the README header in [#549](https://github.com/monero-project/monero-core/pull/549#discussion_r105540750), but I have no access to the GitHub description unfortunately.

**Comment by skftn** [comment]
Nowadays, the current repository names seem descriptive enough: `monero/monero-gui`.

**Comment by skftn** [comment]
+resolved
