### ISSUE TITLE
Feature Request: optional Night mode for GUI wallet.

### ISSUE THREAD

**Issue by Bits-of-Wisdom** [monero-project/monero-gui#738]
It is quite bright. Night mode will be popular - guaranteed!

**Comment by jonathancross** [comment]
Yes it would be nice to have a "1337 h4x0r" _dark_ mode. Seems like a nice-to-have though (eg low priority for now).  It should be relatively simple to implement once the GUI is more stable and we have colors consolidated into one place.

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by dEBRUYNE-1** [comment]
This is coming with the black theme #952. 

+resolved
