### ISSUE TITLE
Change default transaction priority and privacy

### ISSUE THREAD

**Issue by fresheneesz** [monero-project/monero-gui#742]
I'd like to be able to change the default transaction priority and privacy. Would save me clicks.

**Comment by medusadigital** [comment]
yes but it would also load up the whole user interface.

also it is unclear if in the future, only one certain ring size will be allowed (lets say 10)

therefore i would recmmend doing other thing instead.

however, leaving this open for other comments

**Comment by fresheneesz** [comment]
> therefore i would recmmend doing other thing instead

What is "the other thing"?

And what do you mean it would "load up the whole user interface"? It would just be an option in the settings users would almost never see.

**Comment by medusadigital** [comment]
the "other things" is the 116 other open tickets. 

regarding loading up the user Interface: even if this stuff is small, it takes up place. ofc we still have some space left in the settings page, but we also might need to add more checkboxes (like this one for example https://github.com/monero-project/monero-core/issues/720)


a worthy compromise could maybe be to make the application "remember" the last values of ringsize/fee.

so every time you launch up monero-core, it starts with the last used ringsize/fee settings. 

it would be possible to place this values in the settings file. we also store other stuff there, like last used wallet, etc.

**Comment by fresheneesz** [comment]
Oh i see. Sure of course feel free to prioritize this appropriately. Not urgent. 

>  still have some space left in the settings page

This I don't understand. This is a digital interface. There is literally unlimited space on the settings page. 

> a worthy compromise could maybe be to make the application "remember" the last values of ringsize/fee.

I like that idea. I'd say that might be better/easier/more-intuitive than an option in the settings.

**Comment by erciccione** [comment]
+resolved
