### ISSUE TITLE
GUI Beta 2, Windows, Menu glitch

### ISSUE THREAD

**Issue by wostl** [monero-project/monero-gui#748]
**This issue is only reproducible in low graphics mode.**

When clicking on "Advanced" in the menu, the sub-menu opens correctly:
![guiglitch1](https://cloud.githubusercontent.com/assets/1774712/26471633/b170e134-41a2-11e7-9ba3-1ae648ce0e29.jpg)

When switching to any other menu option afterwards, some small amount of text is glitching just below the letters of "Advanced":
![guiglitch2](https://cloud.githubusercontent.com/assets/1774712/26471632/b16d5046-41a2-11e7-9882-012cbf82bfe6.jpg)
The text fragments look like the lower portions of the sub-menu items.

**Comment by romenoo** [comment]
not the same issue but unless I go full screen, Settings and Network status overlaps when on the Advanced menu

screen size: 1366x768

![monero](https://cloud.githubusercontent.com/assets/29124329/26684021/57fc93c2-46d5-11e7-88ee-a973977466dd.png)

**Comment by romenoo** [comment]
Similarly the buttons under the advanced options when sending monero is not visible and not scrollable unless I maximize the window

![monero](https://cloud.githubusercontent.com/assets/29124329/26692871/c3c713e0-46f1-11e7-8070-e981d3c05140.PNG)

**Comment by medusadigital** [comment]
can confirm on windows.

+enhancement

**Comment by basjoe** [comment]
Issue has overlap with https://github.com/monero-project/monero-core/issues/349

**Comment by skftn** [comment]
+bug

**Comment by erciccione** [comment]
+resolved
