### ISSUE TITLE
GUI 2: On Send Page, the buttons at the bottom are partially hidden.

### ISSUE THREAD

**Issue by dontbuymonero** [monero-project/monero-gui#754]
When you launch the GUI, it opens to its default size (which you can increase with the arrow on the bottom right corner). In this default size, on the send page, the bottom 3 buttons (create tx file, sign tx file, submit tx file), are mostly hidden. These buttons should always be clearly visible to the user when the GUI is in its default size and it should not be necessary to expand in order to fully view/use them.

**Comment by jonathancross** [comment]
Yeah, the UI does not scroll or scale, so if your window is too small, you simply can't reach the items at the bottom ("advanced options" in this case).  We should look into a general pattern for such situations (scrollbars work, but are pretty terrible. Scaling UI elements might help, but can also lead to bad situations).

_Payment ID_ and _Description_ are optional, so there might be a way to collapse those and some surrounding whitespace if screen real estate is needed.

We can also consider establishing a minimum height for the app (based on the left nav probably) and then adjust the UI to always fit inside.
Looks like min is about 700px now.

Any other ideas on how to solve this problem?

**Comment by Jaqueeee** [comment]
Current master supports scrolling (with scroll-wheel or ), but i agree it's a bad solution for the desktop app. I added that for the mobile versions mostly. I think minimum height/width is the best solution, and scrolling for smaller screens. @jonathancross @dontbuymonero

**Comment by jonathancross** [comment]
Thanks for the feedback @Jaqueeee.
Once the UI is a bit more stable, we can tighten things up (there is a lot of misused space).

I played around with the idea of something like an "accordion" pattern where the **Advanced options** and **Payment details** are exclusive -- only one can be open at a time.

Here is a really rough mock just to demonstrate (has too many arrows, etc!).

Payment details editing mode (default):
![2017-06-06_height_editpaymentdetails](https://cloud.githubusercontent.com/assets/5115470/26828597/8abdbc00-4ac2-11e7-9c0a-151526a0298c.png)


Advanced Options mode (when there are no payment details):
![2017-06-06_height_adavanced_ no-pymt-details](https://cloud.githubusercontent.com/assets/5115470/26828602/91dad8ce-4ac2-11e7-91e0-ccfec99ab92c.png)


Advanced Options mode (with payment details):
![2017-06-06_height_adavanced_ with-pymt-details](https://cloud.githubusercontent.com/assets/5115470/26828615/9dcf82ce-4ac2-11e7-9947-28df2b9f0d00.png)


I'm not sure this is a good idea, but it would allow us to avoid scrollbars and make sure all content is accessible in small windows.  There is a little complexity added in keeping track of the various states, but I think it improves usability a lot.

Another option would be to have the _Advanced Options_ always visible, but collapse _Ring Size_ into a button until the user selects it.  Ring Size is not going be be a common adjustment in comparison to adding payment ID / description.

While doing these, I had the thought that for mobile, _Advanced Options_ should probably be a modal window that fills the screen.

**Comment by skftn** [comment]
+resolved
