### ISSUE TITLE
Failed to restore from seed (Japanese characters in username)

### ISSUE THREAD

**Issue by Jaqueeee** [monero-project/monero-gui#758]
<ar4s> When using Monero core (gui) to restore from a moneroaddress seed I'm getting the error "failed to save file 'C:/Users/聖奈/AppData/Local/Temp/monero-core.fl9692.keys'"  I am able to make a wallet from scratch though.
<ar4s> @jaquee windows 10, downloaded yesterday. 0.10.3.1   I didn't get it from github, rather I downloaded it from getmonero.org.  My machine is dead atm, using the girlfriends laptop (note the Japanese characters in the username, which I though was perhaps the problem... But I can create a new wallet from a new seed)

**Comment by Jaqueeee** [comment]
related to https://github.com/monero-project/monero-core/issues/199

**Comment by rbrunner7** [comment]
Just a little note because this issue is still formally open: My [PR #1141](https://github.com/monero-project/monero-gui/pull/1141) will probably fix this.

**Comment by skftn** [comment]
Should be fixed via #1141. Re-open if problem remains.

+resolved
