### ISSUE TITLE
[Feature Request] Auto-populate ideal mining threads in GUI

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-gui#764]
Would it be possible to automatically populate the number of CPU mining threads in the GUI? I was looking around and there seem to be ways in several systems to check the size of the L3 cache. How difficult would this be to implement?

Windows example:

`wmic cpu get L3CacheSize`

I believe this will help new users, who can help the network in an ideal way without needing to look up the specs for their processor.

**Comment by jonathancross** [comment]
I'd recommend against making the default anything more than 1 thread.

My reasoning is:
1. Noobs trying to "help the network" should not have a degraded experience with their computer slowing down, getting hot, etc.
2. If they are curious about mining, they can at least learn a bit about their own system so they are making a _decision_ about the resources being allocated.
3. Users who are really interested in mining should probably be using an optimized miner like 
`xmr-stak-cpu`.

The current input field is not ideal, but unless we can easily and reliably determine how many threads are available, I think this is fine for now.  If we can get CPU info without wasting a lot of dev time or introducing cross-platform bugs / flakey behavior (I'm skeptical) --  a dropdown would be preferable to prevent mistakes and give users a sense for how much of their overall CPU cycles are being allocated.

**Comment by medusadigital** [comment]
i tend to agree with @jonathancross.

however, leaving it open a few more days before closing

**Comment by The13thDoc** [comment]
I believe this is causing the threads to reset back to 1 if the application is restarted. I changed it to 4, but it didn't save that setting. Is this the desired functionality?

**Comment by erciccione** [comment]
Few days has passed

+resolved
