### ISSUE TITLE
GUI says "Synchronizing" when it hasn't connected yet

### ISSUE THREAD

**Issue by fresheneesz** [monero-project/monero-gui#766]
See this issue: https://github.com/monero-project/monero/issues/2083

Basically, the daemon wasn't connected, and yet the GUI said it was synchronizing. Only after going into the status log did I find out it wasn't.

**Comment by medusadigital** [comment]
@Jaqueeee considered adding the status "connecting.." 

not to be mistaken with the status "connected"


will label this as feature for now, because such a new state should be added carefully.

+feature

**Comment by erciccione** [comment]
Resolved with double bar 'syncronizing wallet' and 'syncronizing daemon'

+resolved
