### ISSUE TITLE
Windows x64 Beta 2 GUI missing November 1, 2015

### ISSUE THREAD

**Issue by robricc** [monero-project/monero-gui#789]
The date selector in the History tab for November 2015 starts at November 2nd.

![monero_nov2015](https://user-images.githubusercontent.com/29985373/27969809-6ae82cf6-631a-11e7-9927-753040add784.png)

**Comment by MaxXor** [comment]
For me it's showing the dates correctly on Windows 7 x64. Can you provide more information on how to reproduce this?

![history](https://user-images.githubusercontent.com/7271470/27993952-6de2cd86-64b3-11e7-915c-bee045b7e5f2.png)

**Comment by robricc** [comment]
I am only trying out the GUI because it's easier to pinpoint what transactions happen on what date. So, the wallet I have open is a view-only wallet that has been functioning fine via CLI for years. I'm also connecting to a remote node. I don't think that these factors are likely to contribute to the issue I'm seeing.

I do notice that your week starts on Monday. Since I'm am in the US, my week starts on Sunday. Other than that, I just unzipped the current GUI binary linked from Reddit and restored a wallet from keys (view-only). Once it was done syncing the wallet, I then noticed this issue.

**Comment by jonathancross** [comment]
The date picker is a bit wonky.  Although there is no reason the first of any month should be missing, I did notice that your start date is _after_ your end date (and the end date is December).  Even though it seems as though you can type in dates, I cannot (on a mac).  I had to use the mouse and click back through all months, then select a specific day.  Please try that and see what happens.

**Comment by medusadigital** [comment]
would consider this as a bug, even if exotic. 

+bug

**Comment by Jaqueeee** [comment]
I can't reproduce this. Seems to be related to the locale setting since OP's week starts on a Sunday. Can anyone else confirm this? Haven't found any reported Qt bugs regarding this.

**Comment by jonathancross** [comment]
I changed my "Language & Region" settings here on my mac to make Sunday the first day of the week, but could not reproduce the bug.

Interesting to note that October seems to just be shifted one day forward, deleting Nov 1. (November 2nd, 2015 being Monday is correct).

**Comment by selsta** [comment]
This was most likely a bug in an older Qt version. We require Qt 5.9 now.

+resolved
