### ISSUE TITLE
add support Pt-pt - Portuguese of Portugual

### ISSUE THREAD

**Issue by EvertonMelo** [monero-project/monero-gui#790]
add support Portuguese Portugual. 

Please create to file:

monero-core_pt-pt.ts

**Comment by fabionitto** [comment]
Hello,
I guess it could be copied from pt-br, and them someone could translate it to pt-pt.

**Comment by EvertonMelo** [comment]
@fabionitto 

Great, 

I can translate it

**Comment by erciccione** [comment]
@EvertonMelo Hi! you can find the instructions for trnaslating the GUI here: https://taiga.getmonero.org/project/erciccione-monero-localization/wiki/translating-the-gui
Let me know if you need any help

**Comment by EvertonMelo** [comment]
Hi, 

I started transtlate for Produtino Monero-GUI:
https://github.com/monero-project/monero-gui/tree/master/translations

**Comment by EvertonMelo** [comment]
@erciccione 

thank you. 
Issues closed.
