### ISSUE TITLE
Add notice to clarify status of transaction sent by user (GUI)

### ISSUE THREAD

**Issue by unknownids** [monero-project/monero-gui#798]
Is it possible to add something like this to the GUI http://imgur.com/a/blh3k to indicate the status of a transfer a user has sent? This will help with some of the confusion newbies have I think. Can probably get rid of the word status too now that I think about it..

**Comment by BigslimVdub** [comment]
I agree on this. Litecoin core has this in the transfer tab of the GUI. Shows updated progress of transaction per confirmation.

**Comment by unknownids** [comment]
AFAIK @Jaqueeee has every intention of adding this. He just asked me to create this ticket so he did not forget :)

**Comment by medusadigital** [comment]
+feature

**Comment by rating89us** [comment]
Transaction status has been implemented in History page. @selsta This issue can be closed.
