### ISSUE TITLE
close cmd after start-low-graphics-mode.bat has started the application

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#811]
modify start-low-graphics-mode.bat so the cmd window closes after execution.

at current state, it stays open, confusing the user if he is allowed to close it or not

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by medusadigital** [comment]
closing as dublicate in favour of https://github.com/monero-project/monero-gui/issues/962
