### ISSUE TITLE
[Discussion] make QT quick 2D renderer the default renderer on all platforms. 

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#813]
Right now we offer this option only via environment variable on Linux and OS-X.
On windows there is a .bat script, named _start-low-graphichs-mode.bat._

duscussion needs to happen if this should be made the default setting. this would highly benefit old machines, and depending on settings machines via RDP or VNC, which often support 2D. on future(?) ARM builds it might have an effect too. 

on the other side, we dont know if the 2D renderer really runs everywhere. the current state is kind of ballte proofed allready, therefore the discussion Label (yet to come)

**Comment by danrmiller** [comment]
I can add the "discussion" label but I would think the existing "proposal" label should suffice.

**Comment by medusadigital** [comment]
+proposal

**Comment by selsta** [comment]
Closing as I don’t think this proposal makes sense. The 2D renderer has worse quality, less features and is less supported overall.
