### ISSUE TITLE
Failed on build

### ISSUE THREAD

**Issue by Ernillew** [monero-project/monero-gui#850]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

All packages is up-to-date.

/build.sh release-static

Error:

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:274: recipe for target 'release/bin/monero-wallet-gui' failed
make: *** [release/bin/monero-wallet-gui] Error 1

**Comment by italocoin-project** [comment]
Did you solve this Error?

**Comment by italocoin-project** [comment]
So, apparently you get this error because you need to instal QT from source!

**Comment by skftn** [comment]
Resolving this issue for now. Please create a new one if this happens on current master (and you've verified you have QT +5.7 installed)

**Comment by skftn** [comment]
+resolved

**Comment by reeyon** [comment]
> Resolving this issue for now.
> 
> Please create a new issue if this happens on current master (and verified QT +5.7 is present).

@xmrdsc may I know how did you resolve this error ?
it searched around with no solution.
debian 9.9
compiled everything with static. except for Qt.
