### ISSUE TITLE
[Feature] Add option to choose different date format

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#857]
Data formats aren't uniform across the globe. Therefore, it would make sense to add an option that would allow the user to choose his preferred date format. 

Initially suggested by c-789 [on reddit](https://www.reddit.com/r/Monero/comments/6wlzm1/help_out_with_testing_the_upcoming_gui_release/dm9p0me/):

>On the History tab, the dd.mm.yyyy date format may confuse those who are used to mm.dd.yyyy. An option to pick the date format would be helpful.

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by QuickBASIC** [comment]
Or in the interim standardize on the last confusing date format if choosing a date and displaying a date is problematic. I suggest YYYY-MM-DD as it's used as a secondary format in many countries (including MM-DD countries like the US.)

**Comment by selsta** [comment]
The new History page uses YYYY-MM-DD. Do you consider this resolved @dEBRUYNE-1

**Comment by dEBRUYNE-1** [comment]
Not exactly :-P But I suppose we can close this as there is little net benefit.
