### ISSUE TITLE
Use different color for "Network Status" 

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#858]
Reported by scoobybejesus [on reddit](https://www.reddit.com/r/Monero/comments/6wlzm1/help_out_with_testing_the_upcoming_gui_release/):

>"Network Status" is written in gray, non-bold on a black background. It looks good, except I can't really read it.

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by danrmiller** [comment]
+UI/UX

**Comment by danrmiller** [comment]
+UI/UX

**Comment by danrmiller** [comment]
+UX

**Comment by skftn** [comment]
+resolved
