### ISSUE TITLE
Inconsistent capital letter settings page - styling 

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#861]
Currently, if one presses `Show seed & keys` (on the `Settings` page) the popup window will state `Wallet Mnemonic Seed`. The capital M seems inconsistent here. In addition, there is no colon after `Wallet Mnemonic Seed`, whereas there is one after the keys.

**Comment by dEBRUYNE-1** [comment]
+UI/UX

**Comment by Jaqueeee** [comment]
Most likely also fixed by #826

**Comment by dEBRUYNE-1** [comment]
+UX

**Comment by dEBRUYNE-1** [comment]
Resolved in the new version.
