### ISSUE TITLE
Seed & keys popup window not stylized properly

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#862]
If you press `Show seed & keys` (on the `Settings` page) some of the keys, dependent on their characters, will not be stylized properly, i.e., the output will be on a separate line. Slightly increasing the popup window should fix this.

**Comment by dEBRUYNE-1** [comment]
+UI/UX

**Comment by Jaqueeee** [comment]
#826 adds a separate page for keys and seed

**Comment by dEBRUYNE-1** [comment]
+UX

**Comment by dEBRUYNE-1** [comment]
Resolved by the new dark theme.
