### ISSUE TITLE
Windows GUI ringsize UI glitch

### ISSUE THREAD

**Issue by m2049r** [monero-project/monero-gui#863]
GUI version: v0.10.3.1-151-ge217103 (it would fantastic if the version was copy/pastable)

Clicking slightly to the left of medium privacy level gives a ringsize of 8. Slightly to the right gives 9 and a bit further (but before the next mark) 10. I think this is not the intended behaviour.

**Comment by dEBRUYNE-1** [comment]
+bug
+UX

**Comment by dEBRUYNE-1** [comment]
Can you try v0.11.1.0? If I recall correctly, this is resolved.

**Comment by m2049r** [comment]
sorry, not resolved:

![image](https://user-images.githubusercontent.com/30435443/32292124-610fd306-bf3f-11e7-976e-e88fa1726568.png)

![image](https://user-images.githubusercontent.com/30435443/32292264-d9e6300e-bf3f-11e7-9375-cbc7ed037bb2.png)

**Comment by medusadigital** [comment]
is this the same as this ? https://github.com/monero-project/monero-core/issues/158

**Comment by medusadigital** [comment]
considering the other issues we have, i still consider this good enough at curent stage

**Comment by m2049r** [comment]
definately good enough - no worries!

**Comment by medusadigital** [comment]
+wontfix
