### ISSUE TITLE
[Feature Request] Clear indicator that wallet can't connect to node

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-gui#864]
Recently, the remote node service node.moneroworld.com went dead. A lot of GUI users had trouble using Monero because of this, and there was no clear indicator in the GUI of exactly what went wrong.

Could there be a feature that clearly states that whatever node they are trying to connect to (local or remote) is not functioning properly?

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by erciccione** [comment]
Was this resolved?

**Comment by skftn** [comment]
Not resolved.

**Comment by selsta** [comment]
This should be resolved now.
