### ISSUE TITLE
Password textbox in popup should be cleared if previous attempt was incorrect

### ISSUE THREAD

**Issue by philkode** [monero-project/monero-gui#865]
As per title, if the previous password attempt was incorrect, the textbox in the subsequent password popup should be cleared. Not a serious issue but it's standard practice for password entry and a QoL nice-to-have.

Note: I'm taking a stab at this myself so don't feel you have to fix it. Will update if I fail miserably and give up.

**Comment by dEBRUYNE-1** [comment]
+enhancement
