### ISSUE TITLE
boost library functions undefined reference

### ISSUE THREAD

**Issue by Cherisher** [monero-project/monero-gui#870]
I try to built this project many times on Windows 7,  but it is always failed. The error messages is boost library functions undefined reference.  such as:

C:/msys64/home/admin/monero-core/monero/lib/libwallet_merged.a(wallet_manager.cp                                                                                                    p.obj):wallet_manager.cpp:(.text$_ZN5boost16re_detail_10620012perl_matcherIN9__g                                                                                                    nu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE                                                                                                    EEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_i                                                                                                    mpEv[__ZN5boost16re_detail_10620012perl_matcherIN9__gnu_cxx17__normal_iteratorIP                                                                                                    KcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEEN                                                                                                    S_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x293): undefined ref                                                                                                    erence to `boost::re_detail_106200::put_mem_block(void*)'

**Comment by MaxXor** [comment]
See #828

**Comment by skftn** [comment]
+resolved
