### ISSUE TITLE
Internal Miner Jumping between 100% and 0% load

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#877]
It is reporter that the Hahsrate can oscilate between 0% CPU load and 100% CPu load for some users. 

This seems also to affect the Smart mining feature, where it is less obvious: https://www.reddit.com/r/Monero/comments/6zpves/the_gui_binaries_have_been_finalized/dmz4fcl/

**Comment by medusadigital** [comment]
+Bug

**Comment by medusadigital** [comment]
another report: https://www.reddit.com/r/Monero/comments/7gi4mj/question_monero_wallet_gui_solo_mining_should_the/

**Comment by selsta** [comment]
I wonder if we should close this, a lot has changed. @dEBRUYNE-1 Did you read about this bug recently?

**Comment by dEBRUYNE-1** [comment]
I haven't seen any reports of this recently, though that doesn't rule out the bug not existing anymore :-P

**Comment by erciccione** [comment]
This is related to a very old version and the problem didn't show up with more recent releases. I'm closing this PR. Please open another one if the issue show up again.

+resolved
