### ISSUE TITLE
Passwords with parentheses not working

### ISSUE THREAD

**Issue by MatthijsZw** [monero-project/monero-gui#883]
In the GUI on OSX I can create a wallet with a password containing parentheses (i.e. ‘)’ or ‘(‘ ), but I cannot re-open it (‘password incorrect’)

**Comment by moneromooo-monero** [comment]
Are these actual parentheses, or non ASCII ones ?

**Comment by MatthijsZw** [comment]
Actual, normal parentheses. The ones I get with SHIFT-9 and SHIFT-0

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by skftn** [comment]
Related to #199 #758 #820 and eventually/possibly https://github.com/monero-project/monero/issues/1390

**Comment by medusadigital** [comment]
closing in favour of https://github.com/monero-project/monero/issues/1390

**Comment by medusadigital** [comment]
+duplicate
