### ISSUE TITLE
[FEATURE REQUEST] (send) Warn it's a watch only wallet; can't spend

### ISSUE THREAD

**Issue by zzaappedd** [monero-project/monero-gui#887]
My wallet is watch only and I can't spend. Today I was ready to spend for the 1st time and had forgotten it was watch only. Maybe a flag somewhere can remind users that watch only wallets can't spend. 
1st time posting here and don't know if this is the right place.
Thanks to whomever listens!

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by dEBRUYNE-1** [comment]
+resolved
