### ISSUE TITLE
[Enhancement] Show integrated address as destination on the History page (instead of the current plain address + short, encrypted payment ID)

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-gui#906]
Reported by charutocafe on IRC:

>When looking at the destinations of a transaction sent to an integrated address, instead of seeing the integrated address, we see the normal wallet address along with payment ID. this can cause certain confusions on users that want to confirm that they sent their funds to the correct integrated address (I believe this issue is also present in the CLI).

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by xiphon** [comment]
https://github.com/monero-project/monero/pull/5750
