### ISSUE TITLE
make start-low-graphics-mode.bat part of monero-core repo

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#926]
When doing windows releases, we add .bat script `start-low-graphics-mode.bat` by hand. Script is used to give windows users the option to launch monero GUI in 2D mode (for running it on VPS etc).

Script should be part of monero-core repo and automatically added when building for windows.

**Comment by dEBRUYNE-1** [comment]
#928.

**Comment by selsta** [comment]
I think this is resolved.

+resovled

**Comment by selsta** [comment]
+resolved
