### ISSUE TITLE
GUI 'start daemon' and 'Show status' ignores custom settings

### ISSUE THREAD

**Issue by ronohara** [monero-project/monero-gui#933]
If you set up a remote daemon, in the GUI, under Settings. The Show Status button only checks the localhost daemon (which obviously is not running).

With a remote daemon, you would expect to be able to Show Status, but not 'Start' or 'Stop' the daemon.

**Comment by jnbarlow** [comment]
+1 to this. I had to set up a local apache proxy on 18081 to trick the GUI into grabbing status from my remote server.

**Comment by djfinch** [comment]
Figured out that Monero GUI just ignoring FQDN address... When I put just IP address there - synchronizing works...

**Comment by selsta** [comment]
The settings page changed a lot. Stop/Start only for a local daemon now. Show status got removed.

+resolved
