### ISSUE TITLE
Building release-v0.11.1.0 doesn't produce the correct version

### ISSUE THREAD

**Issue by benma** [monero-project/monero-gui#946]
I checked out `release-v0.11.1.0`, built the code using `build.sh`, and get this:

```sh
$ ./build/release/bin/monerod --version
Monero 'Helium Hydra' (v0.11.0.0-72b5f37f)
```

which is unexpected (.0 instead of .1).

The same from the downloaded binary from the release:

```sh
$ ./monerod --version
Monero 'Helium Hydra' (v0.11.1.0-release)
```

Building on linux 64 bit.

```sh
$ git describe
v0.11.1.0
```
In the monero submodule:

```sh
$ git describe
v0.10.3.1-950-gaf448d38
```

**Comment by dEBRUYNE-1** [comment]
Try deleting `version/version.h` and then rebuild.

**Comment by benma** [comment]
That results in a number of compilation errors:

`fatal error: version.h: No such file or directory`

**Comment by dEBRUYNE-1** [comment]
Have you tried a fresh `git clone`?

**Comment by benma** [comment]
I have. Same result. Does it work for you?

**Comment by Jaqueeee** [comment]
I can't reproduce this either with release-v0.11.1.0 checked out. However, when building master branch I get the same output from `git describe` in monero submodule, which makes sense, since monero master branch still has 0.10.3.1 tag.

**Comment by skftn** [comment]
+resolved
