### ISSUE TITLE
UI Proposal #2 - black theme

### ISSUE THREAD

**Issue by skftn** [monero-project/monero-gui#949]
![](https://i.redd.it/1wcbs2rfk4xz.png)

Author: knueffelbund
Date: 10/11/2017
Reddit thread: [link](https://www.reddit.com/r/Monero/comments/7c0bo7/had_some_fun_yesterday_evening_restyling_the/)
[zpl.io design link](https://zpl.io/2EmDOKD) (ask for invite)

___
Mostly a change of colors, except for:

- Restyled balance information
- Larger titlebar + logo
- Smaller menu buttons
- Change of menu button indicators
- Optional icon placement in buttons

As such, more trivial to implement than [UI Proposal #0](https://github.com/monero-project/monero-core/issues/419), [UI Proposal #1](https://github.com/monero-project/monero-core/issues/869) for the short-term.

___
Benefits from the current design:

- A black look embodies the Monero philosophy; stealth/privacy
- Less clutter in the menu area

An optional color scheme could be made to allow for switching between light/dark mode.

**Comment by Schnoffel** [comment]
Looks very nice, I like it! : )

**Comment by emesik** [comment]
The Monero logo lacks white band, probably due to transparent background.

Otherwise it looks just great!

**Comment by binaryFate** [comment]
Just my personal taste, but it's too all-black-uniform for me. I usually prefer to have very-dark-gray elements here and there too.

**Comment by GBKS** [comment]
Hi everyone. I designed this pretty quickly just for fun and it's by no means meant as final. But it seems like there's a lot of interest having a dark theme like this, so I'd be happy to iterate, implement feedback and lay out more screens, as needed. I haven't designed for an open-source project before, so I'm not totally sure how this process usually works best.

**Comment by skftn** [comment]
Latest WIP image:

![wow](https://i.imgur.com/98YDxcn.png)

**Comment by leonklingele** [comment]
What happened to the Clear button? :o

**Comment by skftn** [comment]
@leonklingele It's a work-in-progress screenshot :-)

**Comment by dontbuymonero** [comment]
For the osx version, would we be able to get the red-orange-green little circles (exit, minimize, full screen) on the top right corner?

**Comment by skftn** [comment]
@dontbuymonero 

That's already possible in the current GUI; settings -> custom decorations (off)

**Comment by skftn** [comment]
+resolved

**Comment by skftn** [comment]
Closing as #952 will be merged eventually.
