### ISSUE TITLE
Small Issues in Debug Info

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#960]
Two small Issues in monero-core Debug Info:

![debuginfo](https://user-images.githubusercontent.com/17108301/32887618-cd832e1c-cac4-11e7-9095-131c32cd3e3a.png)

- text can not be properly selected, because each Line acts as its own field when selecting it.

- Under windows, the displayed path is a lil mixed up. should be `\` everywhere instead of `/`

**Comment by skftn** [comment]
Will be fixed in #952

**Comment by skftn** [comment]
Looks like it's still not fixed.

+enhancement
+easy

**Comment by xmrdsc** [comment]
Fixed in recent builds.

+resolved
