### ISSUE TITLE
'start-low-graphics-mode.bat' leaves command window open.

### ISSUE THREAD

**Issue by QuickBASIC** [monero-project/monero-gui#962]
Referencing #812 #926, it probably should just be in the repo anyway.

Should change to:
```
@echo off

set QMLSCENE_DEVICE=softwarecontext

start /b monero-wallet-gui.exe
```

Which will allow the batch to terminate after launching the GUI.

![moneroguilowgraphics](https://user-images.githubusercontent.com/7226914/32954803-229b8206-cb82-11e7-9094-6e81fceb8d84.png)

**Comment by medusadigital** [comment]
dublicate, but leaving this one open instead of the old one https://github.com/monero-project/monero-gui/issues/811, because this one has the solution inside allready.

**Comment by erciccione** [comment]
+resolved
