### ISSUE TITLE
Can't get Monero GUI wallet to start synchronizing...

### ISSUE THREAD

**Issue by sabiam3** [monero-project/monero-gui#971]
Hi all,

I'm new to Monero, and generally not all that computer-savvy, so I'm at a total loss as to how to solve this issue with getting the GUI wallet to begin synchronizing. I'm working on Mac OS Sierra, and this is version 0.11.1.0 of the wallet.

The wallet's network status says that it is synchronizing, but the status bar is stuck on "establishing connection". The Daemon log reads out a series of messages like this, which indicates that the blockchain height isn't being identified:

Height: 1/1 (100.0%) on mainnet, not mining, net hash 0 H/s, v1, up to date, 0(out)+0(in) connections

I've tried running with monerod and changing the log level as others have suggested to remedy similar problems. I can't even begin to make heads or tails of all of the different errors and warnings that are part of the GUI log, all of which seem to have different sources based on the research I've been able to do myself. Link to the GUI log here: https://paste.fedoraproject.org/paste/IG97qkiCiFZp0UH3r3-7RQ

Thanks for the help.

**Comment by dEBRUYNE-1** [comment]
Are you using an university network or your work network to sync?

**Comment by sabiam3** [comment]
No, but I haven't considered any network solutions to the problem. I couldn't rule that out.

**Comment by dEBRUYNE-1** [comment]
Can you try the following steps:

1. Reboot to ensure no Monero related processes are running anymore. 

2. Delete `~/.bitmonero`.

3. Start `monerod` from the terminal as follows -> `./monerod --log-level 1`

4. Paste the content of `~/.bitmonero/bitmonero.log` to https://paste.fedoraproject.org 

Let me know if you need any assistance.

**Comment by skftn** [comment]
Inactive issue - am closing. Re-open if problems persist.

+resolved
