### ISSUE TITLE
Cannot Connect to Daemon

### ISSUE THREAD

**Issue by alex34qw** [monero-project/monero-gui#978]
Height: 81998/1453682 (5.6%) on mainnet, not mining, net hash 4.88 MH/s, v1, up to date, 6(out)+0(in) connections, uptime 0d 2h 6m 20s

2017-11-29 15:32:31.322	11060	ERROR	net.http	contrib/epee/include/net/http_client.h:444	Unexpected recv fail
Error: Couldn't connect to daemon: 127.0.0.1:18081

**Comment by dEBRUYNE-1** [comment]
Which operating system are you using?

**Comment by alex34qw** [comment]
Windows 10
--
Inviato da Libero Mail per Android Venerdì, 01 Dicembre 2017, 00:48PM +01:00 da dEBRUYNE-1  notifications@github.com :

**Comment by jordangunderson** [comment]
I'm wondering whether this isn't a duplicate issue of #890.

**Comment by dEBRUYNE-1** [comment]
@alex34qw Apologies for the late response. Can you try this guide? https://monero.stackexchange.com/questions/6825/i-am-using-the-gui-and-my-daemon-doesnt-start-anymore

@jordangunderson: Yes. I'll close once alex34qw answers.

**Comment by erciccione** [comment]
duplicate and related to old version

+resolved
