### ISSUE TITLE
Unable to send txn with fastest tx prio - x41.5 fee

### ISSUE THREAD

**Issue by 1337tester** [monero-project/monero-gui#986]
**When choosing fastest transaction priority - x41.5 fee, GUI wallet is unable to send the tx.**

Error message in log - "qrc:///pages/Transfer.qml:338: TypeError: Cannot read property 'priority' of undefined" (after I click "Send")
No warning/error message appears on the GUI level

![cannot_send_41 5x](https://user-images.githubusercontent.com/6553766/33553319-87979e96-d8f8-11e7-9a67-7eb4645f9e4e.jpg)

I was able to send the tx with other parameters (fee, privacy level, payment ID), the x41.5 fee seems to be the cause

**Additional Information:**
I am present on a remote node
Distro - Ubuntu 17.10
GUI version: v0.11.1.0-100-gd9d2050
Embedded Monero version: v0.10.3.1-1136-g9fad4008

**Comment by stoffu** [comment]
#989

**Comment by 1337tester** [comment]
works on 
GUI version: v0.11.1.0-146-gac509ed
Embedded Monero version: v0.10.3.1-1397-ga529f0a6

Close please

**Comment by 1337tester** [comment]
close please;)

**Comment by pazos** [comment]
+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
