### ISSUE TITLE
Problems with  Windows Gui Wallet

### ISSUE THREAD

**Issue by sgf** [monero-project/monero-gui#992]
recently the minerxmr.com transformed 0.5 XMR to me.
but i cant see it on the monero-gui on windows.

its always syn..ing ,has been take lots disk.(the sync takes me several days.)

but when sync completed my XMR also is 0.

im not sure is the monero-gui  works ?

**Comment by 1337tester** [comment]
Wich version you use?

Can be that you have high wallet creation height (the value from which block your wallet scans the blockchain)

**Comment by sgf** [comment]
im using the last version v0.11.1.0
![monerogui](https://user-images.githubusercontent.com/2557696/33611459-6ac21ece-da09-11e7-9839-0a6bafd19f38.PNG)

**Comment by 1337tester** [comment]
change this
![image](https://user-images.githubusercontent.com/6553766/33611620-583dfa3c-d9cf-11e7-8efd-b0cbe6321f2a.png)
set it to 0 as I have

**Comment by sgf** [comment]
![monerogui1](https://user-images.githubusercontent.com/2557696/33612068-72d02ffa-da0b-11e7-95bf-be2ed486e199.PNG)

thank u mate. but it seems not a good idea....😂

it seems im lot the sync history and now i need sync soo much blocks.

**Comment by 1337tester** [comment]
if you know ~~which block it was that you received the monero, you can set it to this value, it will sync from there

**Comment by dEBRUYNE-1** [comment]
>it seems im lost the sync history and now i need sync soo much blocks.

In Monero there's two "syncs". First, the blockchain sync, which is basically downloading the blockchain from other nodes / peers. Second, the wallet sync, which is the wallet "refreshing" / scanning blocks looking for transactions belonging to your address / wallet. The GUI currently uses the status bar for both syncs, which can be a bit confusing to newcomers. Thus, what you are seeing is the wallet refresh.

**Comment by sgf** [comment]
the problems soloved.im keep the client running 3 days.now the  0.5 XMR  got.
thank all,hope the monero Wallet gui  could be release more linght weight version .
