### ISSUE TITLE
Add radio-buttons to sign/verify screen

### ISSUE THREAD

**Issue by 1337tester** [monero-project/monero-gui#994]
**Problem**:
The sign/verify part is either/or in terms message/file -> the Signature generated and shown is either from the message or from the file. The GUI does not really reflect this logic, both options can be filled and the signature is created only from the one
![image](https://user-images.githubusercontent.com/6553766/33619400-72663896-d9e5-11e7-87f6-2d02f2ae125d.png)

**Solution**:
Add radio-buttons which enable to select only one of the candidate for the sign/verify process to make it cleared for which the process is applying

**Comment by skftn** [comment]
+easy

**Comment by erciccione** [comment]
+hacktoberfest
