### ISSUE TITLE
sync issue in gui

### ISSUE THREAD

**Issue by lasergoat** [monero-project/monero-gui#999]
![monero-sync-issue](https://user-images.githubusercontent.com/15964/33734781-07a7fb42-db53-11e7-824b-02638fca11c5.gif)

It just keeps showing a small number like 20, 40 or 60 blocks and then switching to 53,000 or so.

Is this normal?

**Comment by medusadigital** [comment]
this can happen once or twice, but shouldnt be something you can reproduce or see regulary. 

it happens like this afaik: your node doesnt know the top block of the chain, it only knows what other nodes tell it is the top block. So depending on which other nodes your node talks to...that number can eventually change during sync process.

**Comment by dEBRUYNE-1** [comment]
Can you try this guide?

https://monero.stackexchange.com/questions/6651/my-gui-feels-buggy-freezes-all-the-time

**Comment by medusadigital** [comment]
closing here, issue not reproduceable.

**Comment by medusadigital** [comment]
+invalid
